// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "djibouti",
  "name": "Djibouti",
  "country": {
    "idISOlower": "dj",
    "name": "Djibouti"
  },
  "state": {
    "idunique": "dj-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Djibouti",
  "centre": {
    "lon": 43.148002,
    "lat": 11.595014
  },
  "airport": {
    "id": "djibouti-airport",
    "name": "Djibouti-Ambouli Airport",
    "lon": 43.1595,
    "lat": 11.5473,
    "sourceUrl": "https://ourairports.com/airports/HDAM/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=43.145002,11.592014,43.151002,11.598014",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    43.133002,
    11.5353,
    43.1715,
    11.610014
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
