// GENERATED by scripts/body/build-body.ts (npm run body:build). Do not edit by hand.
// What src/scene/body/assets/ holds, and the texture colour references the body material tints from (linear RGB).
export const BODY_MANIFEST = {
  "bodies": {
    "male": {
      "sha": "a375403639",
      "bytes": 159916,
      "brotli": 138098,
      "triangles": 9002,
      "bones": 23,
      "height": 1.81,
      "pelvis": [
        0,
        0.043,
        0.9491
      ],
      "skinRef": [
        0.3865,
        0.1759,
        0.082
      ],
      "skinLum": 0.2139,
      "clothLum": 0.0379,
      "skinUv": [
        0.603515625,
        0.603515625
      ]
    },
    "female": {
      "sha": "ee8b9eb6d7",
      "bytes": 157992,
      "brotli": 137296,
      "triangles": 9002,
      "bones": 23,
      "height": 1.767,
      "pelvis": [
        0,
        0.0457,
        0.9318
      ],
      "skinRef": [
        0.4009,
        0.1848,
        0.0851
      ],
      "skinLum": 0.2235,
      "clothLum": 0.0412,
      "skinUv": [
        0.603515625,
        0.603515625
      ]
    }
  },
  "clips": {
    "sha": "89a2c636d3",
    "bytes": 338060,
    "brotli": 55111,
    "names": [
      "idle",
      "walk",
      "jog",
      "sit-enter",
      "sit",
      "sit-exit",
      "interact",
      "dance",
      "cook",
      "cook-enter",
      "cook-exit",
      "cook-low",
      "cook-low-enter",
      "cook-low-exit",
      "bucket-wash",
      "bucket-wash-enter",
      "bucket-wash-exit",
      "eat",
      "eat-enter",
      "eat-exit",
      "drink",
      "drink-enter",
      "drink-exit",
      "shower-wash",
      "shower-wash-enter",
      "shower-wash-exit",
      "soak-wash",
      "soak-wash-enter",
      "soak-wash-exit",
      "home-door",
      "door",
      "lie-down",
      "get-up",
      "sleep",
      "bathe-sit",
      "bathe-stand",
      "stairs-up",
      "stairs-down",
      "cook-female",
      "cook-enter-female",
      "cook-exit-female",
      "cook-low-female",
      "cook-low-enter-female",
      "cook-low-exit-female",
      "bucket-wash-female",
      "bucket-wash-enter-female",
      "bucket-wash-exit-female",
      "eat-female",
      "eat-enter-female",
      "eat-exit-female",
      "drink-female",
      "drink-enter-female",
      "drink-exit-female",
      "shower-wash-female",
      "shower-wash-enter-female",
      "shower-wash-exit-female",
      "soak-wash-female",
      "soak-wash-enter-female",
      "soak-wash-exit-female",
      "home-door-female"
    ],
    "pelvis": [
      0,
      0.0501,
      0.9167
    ]
  },
  "bones": [
    "root",
    "pelvis",
    "spine_01",
    "spine_02",
    "spine_03",
    "neck_01",
    "Head",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r",
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r"
  ],
  "missing": []
} as const;
export type BodyKey = keyof typeof BODY_MANIFEST.bodies;
