// GENERATED by scripts/body/build-body.ts (npm run body:build). Do not edit by hand.
// What public/body/ holds, and the texture colour references the body material tints from (linear RGB).
export const BODY_MANIFEST = {
  "bodies": {
    "male": {
      "url": "/body/male.glb?v=a375403639",
      "bytes": 159916,
      "brotli": 138098,
      "triangles": 9002,
      "bones": 23,
      "height": 1.81,
      "pelvis": [
        0,
        0.043,
        0.9491
      ],
      "skinRef": [
        0.3865,
        0.1759,
        0.082
      ],
      "skinLum": 0.2139,
      "clothLum": 0.0379,
      "skinUv": [
        0.603515625,
        0.603515625
      ]
    },
    "female": {
      "url": "/body/female.glb?v=ee8b9eb6d7",
      "bytes": 157992,
      "brotli": 137296,
      "triangles": 9002,
      "bones": 23,
      "height": 1.767,
      "pelvis": [
        0,
        0.0457,
        0.9318
      ],
      "skinRef": [
        0.4009,
        0.1848,
        0.0851
      ],
      "skinLum": 0.2235,
      "clothLum": 0.0412,
      "skinUv": [
        0.603515625,
        0.603515625
      ]
    }
  },
  "clips": {
    "url": "/body/clips.glb?v=42fbddbad0",
    "bytes": 53896,
    "brotli": 13984,
    "names": [
      "idle",
      "walk",
      "jog",
      "sit-enter",
      "sit",
      "sit-exit",
      "interact",
      "dance"
    ],
    "pelvis": [
      0,
      0.0501,
      0.9167
    ]
  },
  "bones": [
    "root",
    "pelvis",
    "spine_01",
    "spine_02",
    "spine_03",
    "neck_01",
    "Head",
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "hand_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "hand_r",
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r"
  ],
  "missing": [
    "door (open/close)",
    "bathe",
    "stairs",
    "sleep / lie down"
  ]
} as const;
export type BodyKey = keyof typeof BODY_MANIFEST.bodies;
