// Generated by scripts/world/build-playable-africa.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "nairobi",
  "name": "Nairobi",
  "country": {
    "idISOlower": "ke",
    "name": "Kenya"
  },
  "state": {
    "idunique": "ke-starter",
    "name": "Starter district"
  },
  "timezone": "Africa/Nairobi",
  "centre": {
    "lon": 36.814711,
    "lat": -1.281401
  },
  "airport": {
    "id": "nairobi-airport",
    "name": "Nairobi Jomo Kenyatta Intl",
    "lon": 36.927775,
    "lat": -1.319241667,
    "sourceUrl": "https://eaip.kcaa.or.ke/eAIP_03102024/03-10-2024/eAIP/HK-AD%202%20HKJK-en-GB.html"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and national aeronautical information sources",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=36.811711,-1.284401,36.817711,-1.278401",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; Airport reference points: national aeronautical information sources",
  "bounds": [
    36.799711,
    -1.331242,
    36.939775,
    -1.266401
  ],
  "coverageNote": "Starter visitor area. Real capital and airport points, clipped country land and a bounded central street/building sample. Visitor services and homes are fictional game content. Buildings use approximate box silhouettes; missing heights are estimates. Game prices remain in the shared Allworld economy."
} satisfies DestinationFacts
