// Actual GPU A/B only. Root may bundle this with fixture-hosting-v2/prepare-static-viewer.mjs after source review.
import * as THREE from 'three';
import { createKit } from '/src/scene/kit.ts';
import { normalizeLook } from '/src/scene/avatar-look.ts';
import { BODY_FILES } from '/src/scene/body/files.ts';
import { loadBody } from '/src/scene/body/skinned.ts';
import type { SkinnedBody } from '/src/scene/body/skinned.ts';
import { applyOfficeSourceChart, type FixtureAugmentation } from './fixture.ts';

declare global { interface Window { __OFFICE_CHART_FIXTURE__?: Readonly<Record<string, unknown>> } }
const $ = <T extends HTMLElement = HTMLElement>(id: string) => document.getElementById(id) as T;
const canvas = $<HTMLCanvasElement>('scene'), status = $('status'), stats = $('stats');
const bodySelect = $<HTMLSelectElement>('body'), reachSlider = $<HTMLInputElement>('reach-time'), loadButton = $<HTMLButtonElement>('load');
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: false, preserveDrawingBuffer: true });
renderer.setPixelRatio(1); renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; renderer.debug.checkShaderErrors = true;
const shaderErrors: string[] = [];
renderer.debug.onShaderError = (gl, program, vertexShader, fragmentShader) => {
  const log = (shader: WebGLShader | null) => shader ? gl.getShaderInfoLog(shader) ?? '' : '';
  shaderErrors.push(JSON.stringify({ program: gl.getProgramInfoLog(program) ?? '', vertex: log(vertexShader), fragment: log(fragmentShader) }));
};
const scene = new THREE.Scene(); scene.background = new THREE.Color('#b9d0c5');
scene.add(new THREE.HemisphereLight('#fff8ea', '#65736b', 1.8));
const sun = new THREE.DirectionalLight('#fff1dc', 2.3); sun.position.set(-5, 9, 7); sun.castShadow = true; scene.add(sun);
const fill = new THREE.DirectionalLight('#d6e8ff', 0.8); fill.position.set(7, 5, -5); scene.add(fill);
const camera = new THREE.PerspectiveCamera(36, 1, 0.045, 100);
const floorGeometry = new THREE.PlaneGeometry(30, 30), floorMaterial = new THREE.MeshStandardMaterial({ color: '#c8c5b9', roughness: 0.96 });
const floor = new THREE.Mesh(floorGeometry, floorMaterial); floor.rotation.x = -Math.PI / 2; floor.position.y = -0.015; floor.receiveShadow = true; scene.add(floor);
const PINNED = Object.freeze({
  productionGeometry: '1b2dbfc4dd9557b6216eceb01ddd5f9bcf4119e48788a220589444902d5458ec',
  productionRenderer: '4b053592fdc8efdad0e9cd5071cb853594c2db53829cd74116bf578f439f82da',
  zeroEaseShell: '8512d1ae241ee42e6d22491862df4d3807e408d21fd2497fa4a3f0304a4946b5',
  chartBuilder: '75c04c98071a2df4d90a223e7b0065464a50847370e6d3beeea2e24804f7a04c',
  shaderAdapter: 'bdd57daee82013d0df1f435c947e2b8edd582d4550bc9365b1651dc247c26b02',
  maleGlb: 'b0078206da9f7de0bf346be8133522cf514009f03f262f716613dd196d180686',
  femaleGlb: '977ca5e73ba7b19af2627dab1ba0f0ef3e3d8548bf7b4d54f45faf22cd56001c',
  clipPack: '89a2c636d3a9d1d9eac0e1125c20ca14d030c55ae27561dd8644b30645fd3d47',
  productionAppearance: '8aa5fcbaeb04f8609f8921659444d80aa64295c76c77b9cf813fb947548d8b91',
});
const SEED = 'garment-quality-source-corner-chart-v3';
type Variant = 'source' | 'chart';
type Pose = 'idle' | 'walk' | 'sit' | 'reach';
type Focus = 'full' | 'shoulder';
type Actor = { variant: Variant; body: SkinnedBody; look: ReturnType<typeof normalizeLook>; augmentation: FixtureAugmentation };
let kit: ReturnType<typeof createKit> | null = null, actors: Actor[] = [];
let selected: Variant = 'source', pose: Pose = 'idle', yaw = 0, focus: Focus = 'full', walkPhase = 0.22, reachSeconds = 0.6;
let raf = 0, animation: 'none' | 'walk' | 'reach' = 'none', generation = 0, fullRadius = 6.6, lastChecks: Record<string, unknown> | null = null, loadFailure: string | null = null, loadFailureDetails: unknown = null;
function resize() { const w = Math.max(1, canvas.clientWidth), h = Math.max(1, canvas.clientHeight); renderer.setSize(w, h, false); camera.aspect = w / h; camera.updateProjectionMatrix(); }
function actorFor(variant = selected) { return actors.find(actor => actor.variant === variant); }
function bodyMesh(actor: Actor) { const mesh = actor.body.object.getObjectByName(`body-${actor.body.key}`) as THREE.SkinnedMesh | null; if (!mesh?.isSkinnedMesh) throw new Error('Actual body mesh missing'); return mesh; }
function projectedHeight(object: THREE.Object3D) { scene.updateMatrixWorld(true); object.traverse((node: any) => { if (node.isSkinnedMesh) node.computeBoundingBox(); }); const bounds = new THREE.Box3().setFromObject(object), values: number[] = []; for (const x of [bounds.min.x,bounds.max.x]) for (const y of [bounds.min.y,bounds.max.y]) for (const z of [bounds.min.z,bounds.max.z]) values.push(new THREE.Vector3(x,y,z).project(camera).y); return (Math.max(...values)-Math.min(...values))*canvas.height/2; }
function fitCamera(control: Actor) { resize(); focus='full'; yaw=0; const target=new THREE.Vector3(0,1.03,0); let low=1,high=24; for(let i=0;i<32;i++){const radius=(low+high)/2;camera.position.set(0,target.y+radius*.28,radius);camera.lookAt(target);camera.updateMatrixWorld(true);if(projectedHeight(control.body.object)>300)low=radius;else high=radius;}fullRadius=(low+high)/2; }
function focusPoint(actor: Actor) { if(focus==='full') return new THREE.Vector3(0,1.03,0); scene.updateMatrixWorld(true);const side='l';const bone=bodyMesh(actor).skeleton.bones.find(item=>item.name===`upperarm_${side}`);if(!bone)throw new Error('Missing shoulder anchor');return bone.getWorldPosition(new THREE.Vector3()).add(new THREE.Vector3(0,.04,0)); }
function setCamera(actor=actorFor()) { if(!actor)return;resize();const target=focusPoint(actor),angle=THREE.MathUtils.degToRad(yaw),radius=focus==='full'?fullRadius:.84;camera.position.set(target.x+Math.sin(angle)*radius,target.y+radius*.12,target.z+Math.cos(angle)*radius);camera.lookAt(target);camera.updateMatrixWorld(true); }
function setPose(actor: Actor) { if(pose==='walk')actor.body.stride(walkPhase*Math.PI*2,false);else if(pose==='sit'){actor.body.show('sit');actor.body.sitOn(0,.47,0,0);actor.body.settle();}else if(pose==='reach')actor.body.sampleUse('interact',reachSeconds);else actor.body.show('idle');if(pose!=='sit')actor.body.place(0,0,0,0); }
function bytes(attribute: THREE.BufferAttribute) { return new Uint8Array(attribute.array.buffer,attribute.array.byteOffset,attribute.array.byteLength); }
function fingerprint(geometry: THREE.BufferGeometry) { let h=2166136261>>>0;const update=(arr:Uint8Array)=>{for(const byte of arr){h^=byte;h=Math.imul(h,16777619)>>>0;}};for(const name of Object.keys(geometry.attributes).filter(name=>!name.startsWith('sourceBind')).sort()){const attr=geometry.getAttribute(name) as THREE.BufferAttribute;update(new TextEncoder().encode(name));update(bytes(attr));}if(geometry.index)update(bytes(geometry.index as THREE.BufferAttribute));return h.toString(16).padStart(8,'0'); }
function overlayState(actor: Actor) { const mesh=actor.body.object.getObjectByName('avatar-wardrobe') as THREE.SkinnedMesh;const geometry=mesh.geometry;return {actualFilteredOverlayTriangles:geometry.index!.count/3,baseMaskHiddenTriangles:actor.body.wardrobe.hiddenTriangles,sourceShellTriangles:actor.augmentation.shellTriangles,sourceShellVertices:actor.augmentation.shellVertices,sourceShellBytes:actor.augmentation.shellBytes,sourceShellAttributeCount:actor.augmentation.shellAttributeCount,sourceChartTopologyFingerprint:actor.augmentation.sharedTopologyFingerprint,sourceIndexSha256:actor.augmentation.sourceIndexSha256,appearanceReplayMatchesDisplayed:actor.augmentation.appearanceReplayMatchesDisplayed,rawPositionEncodingBeforeAppearance:actor.augmentation.rawPositionEncodingBeforeAppearance,currentPositionEncodingAfterAppearance:actor.augmentation.currentPositionEncodingAfterAppearance,rawNormalEncodingBeforeAppearance:actor.augmentation.rawNormalEncodingBeforeAppearance,currentNormalEncodingAfterAppearance:actor.augmentation.currentNormalEncodingAfterAppearance,sourceAttributeSha256:actor.augmentation.sourceAttributeSha256,sourceNormalProvenance:actor.augmentation.sourceNormalProvenance,sourceTriangleCount:actor.augmentation.sourceTriangleCount,displayedMaskTriangles:actor.augmentation.displayedMaskTriangles,sourceMaskCoverage:actor.augmentation.sourceMaskCoverage,filteredTopTriangles:actor.augmentation.removedSyntheticTopTriangles,wardrobeDrawCalls:actor.augmentation.drawCallsForWardrobe,sourceFaceBindings:actor.augmentation.shellSourceFaceCount,fingerprintFNV32:fingerprint(geometry),shellShaderKey:actor.augmentation.shaderAdapterKey}; }
function render() { resize();setCamera();const source=actorFor('source'),chart=actorFor('chart');for(const actor of actors)actor.body.object.visible=actor.variant===selected;renderer.info.reset();renderer.render(scene,camera);const active=actorFor();const guard=lastChecks;stats.textContent=JSON.stringify({comparisonValid:!!guard?.valid,comparisonReason:guard?.reason??loadFailure??'Load matched actors first',loadFailure,loadFailureDetails,selected,body:bodySelect.value,requestedOutfit:'office',normalizedLook:active?.look??null,pose,walkPhase:pose==='walk'?walkPhase:null,reachClip:pose==='reach'?'interact':null,reachSeconds:pose==='reach'?reachSeconds:null,yawDegrees:yaw,focus,bodyAssetSha256:guard?.bodyAssetSha256??null,clipPackSha256:guard?.clipPackSha256??null,bodyMaskAndSkeletonEqual:guard?.bodyEqual??false,zeroEaseSourceChartEqual:guard?.chartEqual??false,source:source?overlayState(source):null,chart:chart?overlayState(chart):null,shaderErrors,compiledProgramCount:renderer.info.programs?.length??null,renderCalls:renderer.info.render.calls,renderedTriangles:renderer.info.render.triangles,geometryCount:renderer.info.memory.geometries,actorCount:actors.length,pixelRatio:renderer.getPixelRatio(),pinned:PINNED},null,2);status.dataset.comparisonValid=String(!!guard?.valid);status.textContent=guard?.valid?'Matched actual body, office look, body mask, and zero-ease source chart checks passed. Compare skinning variants at identical controls.':`Comparison blocked: ${guard?.reason??'Load actors.'}`; }
function stopAnimation(){if(raf)cancelAnimationFrame(raf);raf=0;animation='none';}
function play(kind:'walk'|'reach'){stopAnimation();animation=kind;const start=performance.now();const tick=(now:number)=>{if(animation!==kind)return;if(kind==='walk'){pose='walk';walkPhase=((now-start)/1800)%1;}else{pose='reach';reachSeconds=(now-start)/1000;}for(const actor of actors)setPose(actor);render();raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);}
async function sha256(bytes:ArrayBuffer){const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(value=>value.toString(16).padStart(2,'0')).join('');}
async function verify(body:string){const url=body==='man'?BODY_FILES.male:BODY_FILES.female,expected=body==='man'?PINNED.maleGlb:PINNED.femaleGlb;const [a,c]=await Promise.all([fetch(url),fetch(BODY_FILES.clips)]);if(!a.ok||!c.ok)throw new Error('Could not fetch shipped GLBs');const [ab,cb]=await Promise.all([a.arrayBuffer(),c.arrayBuffer()]);const [asset,clip]=await Promise.all([sha256(ab),sha256(cb)]);if(asset!==expected||clip!==PINNED.clipPack)throw new Error('Shipped body or clip SHA differs from frozen source pin');return{bodyAssetSha256:asset,clipPackSha256:clip};}
async function bodyDigest(actor:Actor){
  const mesh=bodyMesh(actor),geo=mesh.geometry;mesh.updateMatrix();
  const attributeLayout:Record<string,unknown>={};
  for(const [name,attribute] of Object.entries(geo.attributes) as [string,any][])attributeLayout[name]={itemSize:attribute.itemSize,normalized:attribute.normalized,count:attribute.count,type:attribute.array.constructor.name};
  const skeleton=mesh.skeleton.bones.map((bone,index)=>({
    name:bone.name,position:bone.position.toArray(),quaternion:bone.quaternion.toArray(),scale:bone.scale.toArray(),
    inverse:mesh.skeleton.boneInverses[index]?.elements,
  }));
  const metadata={drawRange:geo.drawRange,groups:geo.groups,bindMode:mesh.bindMode,matrix:mesh.matrix.elements,
    bindMatrix:mesh.bindMatrix.elements,bindMatrixInverse:mesh.bindMatrixInverse.elements,attributeLayout,skeleton};
  const parts:Uint8Array[]=[new TextEncoder().encode(JSON.stringify(metadata))];
  for(const name of Object.keys(geo.attributes).sort())parts.push(new TextEncoder().encode(name),bytes(geo.getAttribute(name) as THREE.BufferAttribute));
  if(!geo.index)throw new Error('Base mesh index missing');
  parts.push(bytes(geo.index as THREE.BufferAttribute));
  const total=parts.reduce((sum,part)=>sum+part.length,0),merged=new Uint8Array(total);let offset=0;
  for(const part of parts){merged.set(part,offset);offset+=part.length;}
  return sha256(merged.buffer);
}
async function disposeActors(){stopAnimation();for(const actor of actors){actor.augmentation.dispose();actor.body.dispose();}actors=[];lastChecks=null;if(kit){kit.dispose();kit=null;}}
async function loadActors(){stopAnimation();const ticket=++generation;loadFailure=null;loadFailureDetails=null;loadButton.disabled=true;status.textContent='Verifying actual shipped body/clip assets, loading office actors…';try{await disposeActors();const body=bodySelect.value,lookInput={body,outfit:'office',hair:body==='woman'?'braids':'lowcut',outfitColor:'#243a66',bottomsColor:'#d6a83a',fabric:'plain',skin:'#845236',accessories:[]};const look=normalizeLook(lookInput,SEED);if(look.outfit!=='office')throw new Error('Look did not normalize to office');const asset=await verify(body);if(ticket!==generation)return;kit=createKit();const sourceBody=await loadBody(kit,look,SEED,1);if(ticket!==generation){sourceBody.dispose();return;}sourceBody.fit(1);sourceBody.place(0,0,0,0);sourceBody.setPresentation('everyday');const sourceAug=await applyOfficeSourceChart(sourceBody,'source',look);const source:Actor={variant:'source',body:sourceBody,look:normalizeLook(look,SEED),augmentation:sourceAug};actors=[source];scene.add(sourceBody.object);
const chartBody=await loadBody(kit,look,SEED,1);if(ticket!==generation){chartBody.dispose();return;}chartBody.fit(1);chartBody.place(0,0,0,0);chartBody.setPresentation('everyday');const chartAug=await applyOfficeSourceChart(chartBody,'chart',look);const chart:Actor={variant:'chart',body:chartBody,look:normalizeLook(look,SEED),augmentation:chartAug};actors.push(chart);scene.add(chartBody.object);pose='idle';for(const actor of actors)setPose(actor);scene.updateMatrixWorld(true);const sourceDigest=await bodyDigest(source),chartDigest=await bodyDigest(chart);if(sourceDigest!==chartDigest)throw new Error('Source body mesh/mask/skeleton differs across matched variants');const sourceShell=sourceAug,chartShell=chartAug;if(sourceShell.shellTriangles!==chartShell.shellTriangles||sourceShell.shellVertices!==chartShell.shellVertices||sourceShell.sharedTopologyFingerprint!==chartShell.sharedTopologyFingerprint||sourceShell.sourceIndexSha256!==chartShell.sourceIndexSha256||sourceShell.sourceAttributeSha256!==chartShell.sourceAttributeSha256||JSON.stringify(sourceShell.sourceNormalProvenance)!==JSON.stringify(chartShell.sourceNormalProvenance)||!sourceShell.appearanceReplayMatchesDisplayed||!chartShell.appearanceReplayMatchesDisplayed||sourceShell.rawPositionEncodingBeforeAppearance!==chartShell.rawPositionEncodingBeforeAppearance||sourceShell.currentPositionEncodingAfterAppearance!==chartShell.currentPositionEncodingAfterAppearance||sourceShell.rawNormalEncodingBeforeAppearance!==chartShell.rawNormalEncodingBeforeAppearance||sourceShell.currentNormalEncodingAfterAppearance!==chartShell.currentNormalEncodingAfterAppearance||sourceShell.sourceTriangleCount!==9002||chartShell.sourceTriangleCount!==9002||sourceShell.displayedMaskTriangles!==chartShell.displayedMaskTriangles||sourceShell.shellBytes!==chartShell.shellBytes-48*chartShell.shellVertices)throw new Error('Chart differs from zero-ease source topology or expected four added vec3 attributes');if(JSON.stringify(source.look)!==JSON.stringify(chart.look))throw new Error('Normalized looks differ');lastChecks={valid:true,reason:'Both actors share exact current production attributes/mask; private raw GLB appearance replay reproduces the quantized-normal to Float32 morph, and the shell uses a copy of the original full source index.',bodyEqual:true,chartEqual:true,...asset,bodyDigest:sourceDigest,sourceTopologyFingerprint:sourceAug.shellTriangles,chartSourceFaces:chartAug.shellSourceFaceCount,sharedTopologyFingerprint:sourceAug.sharedTopologyFingerprint};fitCamera(source);selected='source';render();
// Compile each program through actual WebGL before snapshot acceptance: render source and chart once, then restore source.
for(const variant of ['source','chart'] as const){selected=variant;render();}selected='source';render();if(shaderErrors.length)throw new Error(`WebGL shader compilation reported ${shaderErrors.length} error(s)`);
}catch(error){loadFailure=error instanceof Error?error.message:String(error);const marker='Raw/displayed source binding witness failed: ';if(loadFailure.startsWith(marker)){try{loadFailureDetails=JSON.parse(loadFailure.slice(marker.length));}catch{loadFailureDetails={parseError:'Could not decode binding witness JSON'};}}render();status.textContent=`Fixture failed closed: ${loadFailure}`;status.dataset.comparisonValid='false';}finally{loadButton.disabled=false;}}
function setPoseName(next:Pose){stopAnimation();pose=next;for(const actor of actors)setPose(actor);render();}
for(const button of document.querySelectorAll<HTMLButtonElement>('[data-version]'))button.addEventListener('click',()=>{selected=button.dataset.version as Variant;render();});
for(const button of document.querySelectorAll<HTMLButtonElement>('[data-yaw]'))button.addEventListener('click',()=>{yaw=Number(button.dataset.yaw);render();});
for(const button of document.querySelectorAll<HTMLButtonElement>('[data-focus]'))button.addEventListener('click',()=>{focus=button.dataset.focus as Focus;render();});
for(const button of document.querySelectorAll<HTMLButtonElement>('[data-pose]'))button.addEventListener('click',()=>setPoseName(button.dataset.pose as Pose));
$('load').addEventListener('click',()=>void loadActors());bodySelect.addEventListener('change',()=>void loadActors());$('play-walk').addEventListener('click',()=>animation==='walk'?stopAnimation():play('walk'));$('play-reach').addEventListener('click',()=>animation==='reach'?stopAnimation():play('reach'));reachSlider.addEventListener('input',()=>{reachSeconds=Number(reachSlider.value);if(pose==='reach')setPoseName('reach');});window.addEventListener('resize',render);
window.__OFFICE_CHART_FIXTURE__=Object.freeze({async load(){await loadActors();},async setBody(value:'man'|'woman'){bodySelect.value=value;await loadActors();},setVariant(value:Variant){selected=value;render();},setPose(value:Pose,seconds=reachSeconds){reachSeconds=seconds;setPoseName(value);},setYaw(value:number){yaw=value;render();},setFocus(value:Focus){focus=value;render();},snapshot(){return JSON.parse(stats.textContent||'{}');},shaderErrors(){return [...shaderErrors];}});
window.addEventListener('pagehide',()=>{++generation;void disposeActors();floorGeometry.dispose();floorMaterial.dispose();renderer.dispose();},{once:true});render();
