// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-1013,"z":3092})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-73.4621167219218,"maxX":80.27638978973835,"minZ":-57.595898775997284,"maxZ":119.48571354339128})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"awka-south":{"lon":7.078709344768183,"lat":6.189824925497666}})
