import { defineCitySpec } from '../spec.ts'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'awka',
  name: 'Awka',
  state: { id: 'anambra', name: 'Anambra', sourceName: 'Anambra', unit: 'local government', sourceIds: ['geography'] },
  country: { id: 'nigeria', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 7.0774372,
    lat: 6.218947,
    teaser: 'The Anambra capital of blacksmiths, with a busy Eke market and the Ora Palace.',
    preview: ['Browse Eke Awka Main Market and see the Ora Palace.', "Visit St Patrick's Cathedral and Ekwueme Square."],
    coordinateSourceId: 'osm-selected',
    coordinateRef: { provider: 'openstreetmap', element: 'node', id: 501540935 },
  },
  population: { tier: 'city', sourceIds: ['awka-wiki'], note: 'The cited article reports 301,657 residents at the 2006 census and an estimated 430,200 for Awka South and Awka North together in 2022.' },
  localUnits: [
    { id: 'awka-south', name: 'Awka South', sourceName: 'Awka South', populationTier: 'city', description: 'The selected local government contains the assembly, market, stadium, Paul University and every mapped venue.', sourceIds: ['geography'] },
  ],
  places: [
    {
      id: 'st-patricks-cathedral-awka', name: 'St Patrick’s Cathedral', kind: 'church', lon: 7.072622, lat: 6.222774, localUnitId: 'awka-south',
      description: "Wikidata records St Patrick's Cathedral as a church in Awka.", sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q114888310' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'lords-chosen-awka', name: "The Lord's Chosen Charismatic Revival Church", kind: 'church', lon: 7.0730346, lat: 6.2258995, localUnitId: 'awka-south',
      description: "A mapped Christian place of worship named The Lord's Chosen Charismatic Revival Church.", sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5199328222 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'ecwa-awka', name: 'Evangelical Church Winning All (ECWA)', kind: 'church', lon: 7.0546024, lat: 6.2040136, localUnitId: 'awka-south',
      description: 'A mapped Christian place of worship named Evangelical Church Winning All (ECWA).', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11950804769 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'awka-central-mosque', name: 'Awka Central Mosque', kind: 'mosque', lon: 7.082093, lat: 6.222111, localUnitId: 'awka-south',
      description: 'Wikidata records the Awka Central Mosque as a mosque in Anambra State.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125422100' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'diamond-pizza-awka', name: 'Diamond Pizza & Restaurant', kind: 'eatery', lon: 7.0744467, lat: 6.2269592, localUnitId: 'awka-south',
      description: 'A mapped restaurant tagged Diamond Pizza & Restaurant Aw, shown here with Abacha.', sourceIds: ['osm-selected', 'abacha'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5199362121 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'abacha',
    },
    {
      id: 'burger-chicken-awka', name: 'Burger Chicken and Co', kind: 'eatery', lon: 7.0822078, lat: 6.2290806, localUnitId: 'awka-south',
      description: 'A mapped fast-food outlet named Burger Chicken and Co, shown here with Ukwa.', sourceIds: ['osm-selected', 'ukwa'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 13012165638 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'ukwa',
    },
    {
      id: 'eke-awka-main-market', name: 'Eke Awka Main Market, Awka', kind: 'market', lon: 7.068651, lat: 6.207937, localUnitId: 'awka-south',
      description: 'Wikipedia calls Eke Awka the largest market in Awka, with an estimated 5,000 lock-up shops and stalls.', sourceIds: ['wikidata-selected', 'awka-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q123345679' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['awka-retail-markets'],
    },
    {
      id: 'old-timber-market-awka', name: 'Old Timber Market Awka', kind: 'market', lon: 7.068109, lat: 6.214308, localUnitId: 'awka-south',
      description: 'Wikidata records the Old Timber Market as a market in Awka.', sourceIds: ['wikidata-selected', 'awka-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q123385761' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['awka-retail-markets'],
    },
    {
      id: 'awka-city-stadium', name: 'Awka City Stadium', kind: 'stadium', lon: 7.0639, lat: 6.2153, localUnitId: 'awka-south',
      description: 'Wikidata records Awka City Stadium as a stadium in Awka South.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q126889235' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'anambra-state-house-of-assembly', name: 'Anambra State House Of Assembly', kind: 'government', lon: 7.079166510660087, lat: 6.234009374645353, localUnitId: 'awka-south',
      description: 'Wikidata records the Anambra State House of Assembly as the legislative arm of the state government.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q28406862' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'anambra-ministry-of-works', name: 'Anambra State Ministry of Works and Infrastructure', kind: 'government', lon: 7.06052, lat: 6.202495, localUnitId: 'awka-south',
      description: 'Wikidata records the Anambra State Ministry of Works and Infrastructure as a state ministry in Awka.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125680357' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'regina-caeli-hospital-awka', name: 'Regina Caeli Hospital', kind: 'hospital', lon: 7.1028834, lat: 6.2231834, localUnitId: 'awka-south',
      description: 'A mapped hospital building named Regina Caeli Hospital.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 557909270 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'christ-the-king-hospital-awka', name: 'Christ The King Hospital, Awka', kind: 'hospital', lon: 7.065078877100833, lat: 6.2180581589739194, localUnitId: 'awka-south',
      description: 'Wikidata records Christ The King Hospital, Awka as a healthcare organisation in Anambra.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q128838539' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'paul-university-awka', name: 'Paul University', kind: 'university', lon: 7.066149276719996, lat: 6.199168536723552, localUnitId: 'awka-south',
      description: 'Wikipedia lists Paul University among the two primary universities of Awka.', sourceIds: ['wikidata-selected', 'awka-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q16966577' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'lamp'] },
    },
    {
      id: 'archbishop-ibezim-college-of-education', name: 'Archbishop Alexander Ibezim COE, Anambra', kind: 'college', lon: 7.064646, lat: 6.197921, localUnitId: 'awka-south',
      description: 'Wikidata records Archbishop Alexander Ibezim College of Education as a college of education in Anambra.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q141150161' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'first-bank-awka', name: 'First Bank Nigeria, Awka', kind: 'savings', lon: 7.065756, lat: 6.197951, localUnitId: 'awka-south',
      description: 'Wikidata records First Bank Nigeria, Awka as a financial institution in Awka.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q113402884' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'mayfresh-savings-loans-awka', name: 'Mayfresh Savings & Loans', kind: 'savings', lon: 7.065482873637312, lat: 6.220533580521804, localUnitId: 'awka-south',
      description: 'Wikidata records Mayfresh Savings & Loans Limited in Awka.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q110984207' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'uzondu-microfinance-bank-awka', name: 'Uzondu Microfinance Bank Limited', kind: 'savings', lon: 7.0687750958092535, lat: 6.209138845035552, localUnitId: 'awka-south',
      description: 'Wikidata records Uzondu Microfinance Bank Limited as a microfinance bank.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q111015665' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'gideons-barber-shop-awka', name: "Gideon's Barber Shop", kind: 'salon', lon: 7.0473132, lat: 6.2015611, localUnitId: 'awka-south',
      description: "A mapped hairdresser named Gideon's Barber Shop.", sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 12988238391 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] },
    },
    {
      id: 'star-sunny-motor-park-awka', name: 'Star Sunny Motor Park', kind: 'road-hub', lon: 7.085041, lat: 6.233808, localUnitId: 'awka-south',
      description: 'Wikidata labels Star sunny motor park at Aroma junction on Ejike Okeke street, Awka.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125604599' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'vcs-gate-awka', name: "VC's Gate", kind: 'heritage', lon: 7.1098235, lat: 6.2426919, localUnitId: 'awka-south',
      description: "A mapped historic city gate named vc's gate.", sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1485745239 }, accuracy: 'feature-centroid',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'ora-palace-okpuno', name: 'Ora Palace Okpuno', kind: 'heritage', lon: 7.06029, lat: 6.235806, localUnitId: 'awka-south',
      description: 'Wikidata records the Ora Palace Okpuno as the palace of the Igwe of Okpuno, Awka.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q126111175' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'ekwueme-square-awka', name: 'Ekwueme Square', kind: 'civic-landmark', lon: 7.080277777777778, lat: 6.235, localUnitId: 'awka-south',
      description: 'Wikidata records Ekwueme Square as the main square in Awka.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q111937959' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
  ],
  identity: {
    foods: [
      { id: 'abacha', name: 'Abacha', description: 'Abacha is a food originating with the Igbo people and made from cassava tubers.', sourceIds: ['abacha'] },
      { id: 'ukwa', name: 'Ukwa', description: 'Ukwa, or African breadfruit, is a traditional food of the Igbo people, most often cooked as a porridge with potash, palm oil and seasonings.', sourceIds: ['ukwa'] },
    ],
    crafts: [
      { id: 'awka-blacksmithing', name: 'Blacksmithing and metalworking', description: 'Wikipedia says Awka became known for metal working, and its blacksmiths were prized for farming implements, dane guns and ceremonial staffs.', sourceIds: ['awka-wiki'] },
    ],
    industries: [
      { id: 'awka-retail-markets', name: 'Traditional retail markets', description: "Wikipedia says Awka's large informal markets sell everything from food produce to clothes, cosmetics and household items.", sourceIds: ['awka-wiki'] },
      { id: 'anambra-farm-crops', name: 'Farm crops', description: 'Wikipedia says agriculture is an important sector in Anambra, with oil palms, maize, rice, yams and cassava among the crops grown.', sourceIds: ['anambra-wiki'] },
    ],
  },
  transport: {
    airports: [],
    rail: [],
    ports: [],
  },
  climate: {
    profile: 'southern-wet-dry', rainyMonths: [4, 5, 6, 7, 8, 9, 10], dryMonths: [12, 1, 2],
    description: 'Awka has heavy rain from April to July, a short dry break in August and rain again in September and October, then a dry season from November to March with a harmattan haze.',
    clearLabel: 'Dry-season sky', sourceIds: ['awka-wiki'], harmattan: { months: [12, 1, 2], label: 'Harmattan haze' },
  },
  homePalette: { back: '#b9915f', left: '#7b5a3a', floor: ['#c8a972', '#617f4f'] },
  geometry: { surface: { path: 'scripts/geo/sources/formula/awka-surface.geojson', bytes: 95282, sha256: '8615057f5d069a7839fb1f2850330629ed0334a82ceff15cd1daa2dd9e6cc97c' } },
  sourceGroups: [
    { id: 'osm-selected', title: 'Selected OpenStreetMap records for Awka', url: 'https://www.openstreetmap.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'ODbL 1.0', cache: { path: 'scripts/city/research/awka/reviewed/osm-selected.json', bytes: 2613, sha256: '75ea37ed873ee634902899fba2ae78aec57c4cdd5b5e3f6d4e76c90322240f26' } },
    { id: 'wikidata-selected', title: 'Selected Wikidata entities for Awka', url: 'https://www.wikidata.org/wiki/Wikidata:Main_Page', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'CC0 1.0', cache: { path: 'scripts/city/research/awka/reviewed/wikidata-selected.json', bytes: 12191, sha256: '11a6cb11cac4477673027f54540abdd57b51af4f7bd01cb390f51821a9cb474f' } },
    { id: 'geography', title: 'Pinned Nigerian administrative geography', url: 'https://www.geoboundaries.org/', checkedOn: '2026-10-06', supports: ['geography'], licence: 'CC BY 4.0', cache: { path: 'scripts/city/research/awka/reviewed/geography.json', bytes: 356, sha256: '80504246d36166e08964b04812eb4800ea445d40e7ad4e1ad6e68fb27ffd3715' } },
    { id: 'awka-wiki', title: 'Wikipedia: Awka', url: 'https://en.wikipedia.org/wiki/Awka', checkedOn: '2026-10-06', supports: ['population', 'climate', 'identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/awka/reviewed/awka-wiki.json', bytes: 1151, sha256: '9bb3b550af707381615db52bb7791cf2279e4defeae6aaff08103db00e1b4bc8' } },
    { id: 'anambra-wiki', title: 'Wikipedia: Anambra State', url: 'https://en.wikipedia.org/wiki/Anambra_State', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/awka/reviewed/anambra-wiki.json', bytes: 267, sha256: 'ca955e585574ec7564487c53a790b4a77cfeb446451685d7f55faa17da7960c0' } },
    { id: 'ukwa', title: 'Wikipedia: Ukwa (food)', url: 'https://en.wikipedia.org/wiki/Ukwa_(food)', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/awka/reviewed/ukwa.json', bytes: 331, sha256: '083866c9d5f4e0f96f06c1f64f5749d66ede001e43173232846c9c0b95566ad3' } },
    { id: 'abacha', title: 'Wikipedia: Abacha (food)', url: 'https://en.wikipedia.org/wiki/Abacha_(food)', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/awka/reviewed/abacha.json', bytes: 252, sha256: 'd049474bd5c4b10408b506333d5916a0d4ee1be45d41090f4eda3d049a23f73d' } },
  ],
  unmapped: [
    { kind: 'garden', note: 'No named garden with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'park', note: 'No named park with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'polling', note: 'No named polling venue with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
  ],
})
