// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Binta Suleiman", role: "Park caretaker", quotes: ["I keep Dutse Emirate Museum tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abdullahi Mohammed", role: "Morning walker", quotes: ["I walk through Dutse Emirate Museum before work.", "Fresh air first, then the day."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Usman Gambo", role: "Church volunteer", quotes: ["Welcome to Christ the King Catholic Church. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Hauwa", role: "Regular worshipper", quotes: ["I have worshipped at Christ the King Catholic Church for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Binta Danladi", role: "Mosque caretaker", quotes: ["Welcome to Central Mosque Galamawa. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abdullahi Umar", role: "Regular worshipper", quotes: ["I have prayed at Central Mosque Galamawa for a long time.", "Come in quietly, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Usman Kabir", role: "Cook", quotes: ["Today the pot at Yahuza Suya Spot Nig Ltd holds Suya.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Idris", role: "Regular diner", quotes: ["I come to Yahuza Suya Spot Nig Ltd for Suya.", "Wikipedia describes suya as a traditional Hausa smoke-grilled spiced meat on skewers, seasoned with the spice mix yaji."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Binta Gwarzo", role: "Cook", quotes: ["Today the pot at Hadiza Nakowa Restaurant holds Kilishi.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Malam Abdullahi", role: "Regular diner", quotes: ["I come to Hadiza Nakowa Restaurant for Kilishi.", "Wikipedia describes kilishi as a Hausaland jerky of dried, spiced meat such as beef or lamb, seasoned, smoked and sun-dried."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Usman Yakubu", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Gambo", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Binta Bala", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abdullahi Danladi", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Usman Bello", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Fatima", role: "Patient's relative", quotes: ["I am waiting with a relative at Rasheed Shekoni Hospital.", "Everyone here is patient, so I must be too."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Binta Tanko", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abdullahi Gwarzo", role: "Patient's relative", quotes: ["I am waiting with a relative at Dutse General Hospital.", "Everyone here is patient, so I must be too."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Usman Abubakar", role: "Market trader", quotes: ["Looking for Farming, livestock and trade? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Yakubu", role: "Shopper", quotes: ["Wikipedia says over 80% of Jigawa residents are engaged in subsistence farming and animal husbandry, with trade especially in agricultural goods and livestock.", "Take your time, and bargain with a smile."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Binta Sadiq", role: "Market trader", quotes: ["Looking for Farming, livestock and trade? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Malam Ibrahim", role: "Shopper", quotes: ["Wikipedia says over 80% of Jigawa residents are engaged in subsistence farming and animal husbandry, with trade especially in agricultural goods and livestock.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Usman Salihu", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Bello", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Binta Mohammed", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abdullahi Tanko", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Usman Magaji", role: "Student", quotes: ["I am on my way to a workshop at Jigawa State Polytechnic, Dutse.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Zainab", role: "Instructor", quotes: ["I teach practical work here.", "Hands first, then the theory."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Binta Umar", role: "Museum guide", quotes: ["Welcome to Dutse Museum. Please take your time.", "Ask me if you want to know what is on display."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abdullahi Sadiq", role: "Visitor", quotes: ["I came to Dutse Museum to learn something new.", "Read the labels slowly. They reward you."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Usman Idris", role: "Site guide", quotes: ["Welcome to Emir of Dutse Palace, Jigawa.. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Salihu", role: "Local resident", quotes: ["I walk past Emir of Dutse Palace, Jigawa. most days.", "Visitors often stop here for photographs."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amina Suleiman", role: "Site guide", quotes: ["Welcome to Dutse Rock Range. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Malam Aliyu", role: "Local resident", quotes: ["I walk past Dutse Rock Range most days.", "Visitors often stop here for photographs."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
