// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":1471,"z":-2992})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-220.18237937316053,"maxX":155.47982859602985,"minZ":-407.1103985902032,"maxZ":147.72491941982662})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"dutse":{"lon":9.310914792790769,"lat":11.796432176646377}})
