// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "brazz",
  "name": "Brazzaville",
  "country": {
    "idISOlower": "cg",
    "name": "Republic of the Congo"
  },
  "state": {
    "idunique": "cg-zone",
    "name": "Starter"
  },
  "timezone": "Africa/Brazzaville",
  "centre": {
    "lon": 15.282744,
    "lat": -4.25724
  },
  "airport": {
    "id": "brazz-airport",
    "name": "Maya-Maya International Airport",
    "lon": 15.253,
    "lat": -4.2517,
    "sourceUrl": "https://ourairports.com/airports/FCBB/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=15.279744,-4.26024,15.285744,-4.25424",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    15.241,
    -4.27224,
    15.297744,
    -4.2397
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
