// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Folake Adeyemi", role: "Park caretaker", quotes: ["I keep Diamond Park tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Adeleke", role: "Morning walker", quotes: ["I walk through Diamond Park before work.", "Fresh air first, then the day."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Bakare", role: "Church volunteer", quotes: ["Welcome to St James' Catholic Church. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Abike", role: "Regular worshipper", quotes: ["I have worshipped at St James' Catholic Church for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Lawal", role: "Mosque caretaker", quotes: ["Welcome to Kankatu Central Mosque. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Ojo", role: "Regular worshipper", quotes: ["I have prayed at Kankatu Central Mosque for a long time.", "Come in quietly, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Afolabi", role: "Garden keeper", quotes: ["I keep Flower Garden tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Ajayi", role: "Evening walker", quotes: ["I come to Flower Garden after work to cool down.", "Fresh air first, then the day."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Ogundele", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Baba Ayodele", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Adeleke", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Olaniyan", role: "Patient's relative", quotes: ["I am waiting with a relative at University of Ilorin Teaching Hospital.", "Everyone here is patient, so I must be too."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Akinola", role: "Market trader", quotes: ["Looking for Aso-oke weaving? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Salami", role: "Shopper", quotes: ["Wikipedia records aso-oke, textiles hand-woven on simple looms, made in large quantities across Ilorin.", "Take your time, and bargain with a smile."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Ojo", role: "Market trader", quotes: ["Looking for Ilorin pottery? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Temitope", role: "Shopper", quotes: ["Wikipedia describes pottery as a major business in Ilorin, with traditional workshops in Okelele, Oju-Ekun, Okekura, Oloje, Abe Emi and Ita Merin.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Ajayi", role: "Market trader", quotes: ["Looking for Ilorin pottery? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Adesina", role: "Shopper", quotes: ["Wikipedia describes pottery as a major business in Ilorin, with traditional workshops in Okelele, Oju-Ekun, Okekura, Oloje, Abe Emi and Ita Merin.", "Take your time, and bargain with a smile."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Akinwale", role: "Stylist", quotes: ["Sit down, I will not keep you long.", "A fresh style changes your whole week."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Balogun", role: "Client", quotes: ["I come to Take Beauty Salon before big days.", "Sit still and it goes faster."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Olaniyan", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Baba Dapo", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Salami", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Adeyemi", role: "Supporter", quotes: ["I come to Kwara State Stadium for the football.", "Sit high up and you see the whole game."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Ogunbanjo", role: "Ticket seller", quotes: ["Check the board for your departure.", "Keep your bags close in a crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Bakare", role: "Traveller", quotes: ["I am waiting at Soludero Bus Terminal for my bus.", "Travelling is half waiting."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Adesina", role: "Student", quotes: ["I am on my way to a lecture at University of Ilorin.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Omolara", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Balogun", role: "Student", quotes: ["I am on my way to a lecture at Al-Hikmah University.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Afolabi", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Oladipo", role: "Museum guide", quotes: ["Welcome to Ilorin National Museum. Please take your time.", "Ask me if you want to know what is on display."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Ogundele", role: "Visitor", quotes: ["I came to Ilorin National Museum to learn something new.", "Read the labels slowly. They reward you."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukola Adeyemi", role: "Site guide", quotes: ["Welcome to Emir's Palace. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Baba Kola", role: "Local resident", quotes: ["I walk past Emir's Palace most days.", "Visitors often stop here for photographs."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
