// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-3789,"z":556})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-120.77839813079026,"maxX":465.79195504282325,"minZ":-275.0833098077364,"maxZ":131.81796226452252})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"ilorin-west":{"lon":4.512553340615662,"lat":8.457569792547567},"ilorin-east":{"lon":4.809080511683334,"lat":8.608770688177785},"ilorin-south":{"lon":4.637087207469649,"lat":8.477842688495343}})
