// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "tripoli",
  "name": "Tripoli",
  "country": {
    "idISOlower": "ly",
    "name": "Libya"
  },
  "state": {
    "idunique": "ly-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Tripoli",
  "centre": {
    "lon": 13.180012,
    "lat": 32.8925
  },
  "airport": {
    "id": "tripoli-airport",
    "name": "Mitiga International Airport",
    "lon": 13.287878,
    "lat": 32.89177,
    "sourceUrl": "https://ourairports.com/airports/HLLM/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=13.177012,32.8895,13.183012,32.8955",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    13.165012,
    32.8775,
    13.299878,
    32.9075
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
