// Generated by scripts/world/build-playable-africa.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "cape-town",
  "name": "Cape Town",
  "country": {
    "idISOlower": "za",
    "name": "South Africa"
  },
  "state": {
    "idunique": "za-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Johannesburg",
  "centre": {
    "lon": 18.433042,
    "lat": -33.918065
  },
  "airport": {
    "id": "cape-town-airport",
    "name": "CAPE TOWN INTERNATIONAL",
    "lon": 18.604291667,
    "lat": -33.971369444,
    "sourceUrl": "https://caasanwebsitestorage.blob.core.windows.net/aeronautical-information-publication/Aerodromes%20%2815_JAN_2026%29.PDF"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and cited aeronautical information sources",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=18.430042,-33.921065,18.436042,-33.915065",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; Airport reference points: cited aeronautical information sources",
  "bounds": [
    18.418042,
    -33.983369,
    18.616292,
    -33.903065
  ],
  "coverageNote": "legislative capital; Pretoria is executive and Bloemfontein judicial capital. Starter visitor area. Real city and airport points, clipped country land and a bounded central street/building sample. Visitor services and homes are fictional game content. Buildings use approximate box silhouettes; missing heights are estimates. Game prices remain in the shared Allworld economy."
} satisfies DestinationFacts
