// Frozen diagnostic-only copy of office-source-shell.ts. Geometry output is
// intentionally unchanged; this adds provenance for vertices merged by the
// existing position+influence cache. It is not a production candidate.
import * as THREE from 'three';
import type { WardrobeRestFrame } from '../../../../../src/scene/wardrobe/geometry.ts';
import { clipSourceTriangle, type ClipCorner, type ClipPlane, type Influence } from '../shoulder-yoke-v1/clip-source-triangle.ts';

export type OfficeShellOptions = Readonly<{ hemY: number; neckTopY: number; clearanceM?: number; supportThreshold?: number }>;
export type OfficeShellResult = Readonly<{ geometry: THREE.BufferGeometry; triangles: number; bytes: number; sourceFaces: number; sourceFaceIds: readonly number[]; sourceBindings: readonly Readonly<{ vertices: readonly [number,number,number]; barycentric: readonly [number,number,number] }>[]; openBoundaryEdges: number; item: 'office-source-shell'; normalCacheWeldCount: number; normalCacheWeldMaxDisplacementM: number; normalCacheWelds: readonly Readonly<Record<string,unknown>>[] }>;
const allowedBones = new Set(['pelvis','spine_01','spine_02','spine_03','neck_01','clavicle_l','clavicle_r','upperarm_l','upperarm_r','lowerarm_l','lowerarm_r','hand_l','hand_r']);
const armBones = new Set(['upperarm_l','upperarm_r','lowerarm_l','lowerarm_r','hand_l','hand_r']);
function edgeKey(a:number,b:number){return a<b?`${a}:${b}`:`${b}:${a}`;}
function cornerKey(corner:ClipCorner){const influence=normalizedInfluences(corner.influences).map(([bone,w])=>`${bone}@${Math.round(w*1e6)}`).join('|');return`${corner.position.map(v=>Math.round(v*1e6)).join(',')}#${influence}`;}
function normalizedInfluences(entries:readonly Influence[]):Influence[]{const combined=new Map<number,number>();for(const [id,w]of entries)if(w>0)combined.set(id,(combined.get(id)??0)+w);const sorted=[...combined].sort((a,b)=>b[1]-a[1]).slice(0,4),total=sorted.reduce((s,e)=>s+e[1],0);if(!(total>0&&Number.isFinite(total)))throw new Error('Source shell vertex has invalid skin weights');return sorted.map(([id,w])=>[id,w/total] as const);}
function mixCorner(a:ClipCorner,b:ClipCorner,t:number):ClipCorner{const influences=normalizedInfluences([...a.influences.map(([i,w])=>[i,w*(1-t)] as const),...b.influences.map(([i,w])=>[i,w*t] as const)]),normal=new THREE.Vector3(...a.normal).lerp(new THREE.Vector3(...b.normal),t).normalize(),position=new THREE.Vector3(...a.position).lerp(new THREE.Vector3(...b.position),t),bary=a.barycentric.map((v,i)=>v+(b.barycentric[i]!-v)*t) as [number,number,number];return{position:position.toArray() as [number,number,number],normal:normal.toArray() as [number,number,number],uv:[a.uv[0]+(b.uv[0]-a.uv[0])*t,a.uv[1]+(b.uv[1]-a.uv[1])*t],influences,barycentric:bary};}
function clipBySupport(face:number,corners:readonly[ClipCorner,ClipCorner,ClipCorner],values:readonly[number,number,number],threshold:number):{sourceFace:number;corners:readonly[ClipCorner,ClipCorner,ClipCorner]}[]{let polygon=corners.map((corner,i)=>({corner,value:values[i]!}));const output=[];for(let i=0;i<polygon.length;i++){const a=polygon[i]!,b=polygon[(i+1)%polygon.length]!,da=a.value-threshold,db=b.value-threshold,ia=da>=-1e-8,ib=db>=-1e-8;if(ia)output.push(a);if(ia!==ib){const t=da/(da-db);output.push({corner:mixCorner(a.corner,b.corner,Math.max(0,Math.min(1,t))),value:threshold});}}if(output.length<3)return[];const result=[];for(let i=1;i+1<output.length;i++)result.push({sourceFace:face,corners:[output[0]!.corner,output[i]!.corner,output[i+1]!.corner] as const});return result;}
/** Diagnostic clone; generated attributes/indices must match the frozen candidate exactly. */
export function buildOfficeSourceShell(base:THREE.SkinnedMesh,rest:WardrobeRestFrame,options:OfficeShellOptions):OfficeShellResult{
  const {hemY,neckTopY}=options,clearance=options.clearanceM??0.009,threshold=options.supportThreshold??0.55;
  if(!(Number.isFinite(hemY)&&Number.isFinite(neckTopY)&&neckTopY>hemY&&clearance>=0&&clearance<=0.025&&threshold>0&&threshold<=1))throw new Error('Invalid source-shell bounds');
  const g=base.geometry,index=g.index,pos=g.getAttribute('position'),norm=g.getAttribute('normal'),si=g.getAttribute('skinIndex'),sw=g.getAttribute('skinWeight'),uv=g.getAttribute('uv');
  if(!index||!pos||!norm||!si||!sw||index.count%3!==0)throw new Error('Source body lacks indexed skinned attributes');
  const names=base.skeleton.bones.map(b=>b.name),allowed=new Set(names.flatMap((n,i)=>allowedBones.has(n)?[i]:[])),arm=new Set(names.flatMap((n,i)=>armBones.has(n)?[i]:[]));
  if(![...allowed].length||!['upperarm_l','upperarm_r','lowerarm_l','lowerarm_r'].every(n=>names.includes(n)))throw new Error('Source rig is missing office-shell influences');
  const transformedNormal=new THREE.Matrix3().setFromMatrix4(rest.meshFromMetres).transpose(),normalAt=(i:number)=>new THREE.Vector3(norm.getX(i),norm.getY(i),norm.getZ(i)).applyMatrix3(transformedNormal).normalize();
  const vertexInfluences=(i:number):Influence[]=>Array.from({length:4},(_,c)=>[si.getComponent(i,c),sw.getComponent(i,c)] as const).filter(([,w])=>w>0);
  const pointAt=(i:number)=>rest.points[i]!.clone();
  const shoulder=new Map<string,THREE.Vector3>();for(const side of ['l','r'] as const){const a=rest.bones.get(`upperarm_${side}`)?.point,b=rest.bones.get(`hand_${side}`)?.point;if(!a||!b)throw new Error(`Missing ${side} arm anchors`);shoulder.set(side,b.clone().sub(a).normalize());}
  const planes:ClipPlane[]=[{normal:[0,1,0],offset:-hemY,keep:'positive'},{normal:[0,1,0],offset:-neckTopY,keep:'negative'}];
  const vertices:number[]=[],colors:number[]=[],uvs:number[]=[],cloth:number[]=[],indices:number[]=[],weights:number[]=[],bones:number[]=[],cache=new Map<string,number>(),sourceFaceIds:number[]=[],sourceBindings:{vertices:readonly[number,number,number];barycentric:readonly[number,number,number]}[]=[],touchedSourceFaces=new Set<number>(),firstCornerByVertex=new Map<number,{position:THREE.Vector3;normal:THREE.Vector3;sourceFace:number}>(),normalCacheWelds:Record<string,unknown>[]=[],normalCacheWeldMaxDisplacementMRef={value:0};let normalCacheWeldCount=0;
  const emit=(sourceIds:readonly number[],corner:ClipCorner,sourceFace:number):number=>{const key=cornerKey(corner);const old=cache.get(key);if(old!==undefined){const first=firstCornerByVertex.get(old)!;const p=new THREE.Vector3(...corner.position),n=new THREE.Vector3(...corner.normal),expected=p.clone().addScaledVector(n,clearance),actual=first.position.clone().addScaledVector(first.normal,clearance),normalDot=first.normal.dot(n),weldDisplacementM=expected.distanceTo(actual);if(weldDisplacementM>1e-7||normalDot<0.999999){normalCacheWeldCount++;normalCacheWeldMaxDisplacementMRef.value=Math.max(normalCacheWeldMaxDisplacementMRef.value,weldDisplacementM);const witness={vertex:old,firstSourceFace:first.sourceFace,firstSourceBinding:sourceBindings[old],aliasSourceFace:sourceFace,aliasSourceBinding:{vertices:sourceIds,barycentric:corner.barycentric},clearanceM:clearance,normalDot,normalDifference:n.clone().sub(first.normal).length(),cacheKeyPositionDeltaM:p.distanceTo(first.position),expectedOffsetPointM:expected.toArray(),cachedOffsetPointM:actual.toArray(),cacheWeldDisplacementM:weldDisplacementM};normalCacheWelds.push(witness);normalCacheWelds.sort((a,b)=>Number(b.cacheWeldDisplacementM)-Number(a.cacheWeldDisplacementM));if(normalCacheWelds.length>64)normalCacheWelds.length=64;}return old;}const id=vertices.length/3,local=new THREE.Vector3(...corner.position).addScaledVector(new THREE.Vector3(...corner.normal),clearance).applyMatrix4(rest.meshFromMetres);vertices.push(local.x,local.y,local.z);colors.push(0.14,0.23,0.40);const p=new THREE.Vector3(...corner.position);uvs.push(p.x*3,p.y*3);cloth.push(1);const influences=normalizedInfluences(corner.influences);for(let c=0;c<4;c++){bones.push(influences[c]?.[0]??0);weights.push(influences[c]?.[1]??0);}sourceBindings.push({vertices:[sourceIds[0]!,sourceIds[1]!,sourceIds[2]!],barycentric:[corner.barycentric[0],corner.barycentric[1],corner.barycentric[2]]});cache.set(key,id);firstCornerByVertex.set(id,{position:new THREE.Vector3(...corner.position),normal:new THREE.Vector3(...corner.normal),sourceFace});return id;};
  for(let off=0;off<index.count;off+=3){const ids=[index.getX(off),index.getX(off+1),index.getX(off+2)],mass=new Map<number,number>();for(const v of ids)for(const [bone,w]of vertexInfluences(v))mass.set(bone,(mass.get(bone)??0)+w/3);const armMass=[...mass].reduce((s,[bone,w])=>s+(arm.has(bone)?w:0),0),centroid=ids.reduce((p,v)=>p.add(pointAt(v)),new THREE.Vector3()).multiplyScalar(1/3);
    const corners=ids.map((v,k)=>({position:pointAt(v).toArray() as [number,number,number],normal:normalAt(v).toArray() as [number,number,number],uv:uv?([uv.getX(v),uv.getY(v)] as [number,number]):([0,0] as [number,number]),influences:vertexInfluences(v),barycentric:([k===0?1:0,k===1?1:0,k===2?1:0] as [number,number,number])})) as [ClipCorner,ClipCorner,ClipCorner];
    const support=ids.map(v=>vertexInfluences(v).reduce((sum,[bone,w])=>sum+(allowed.has(bone)?w:0),0));let fragments=clipBySupport(off/3,corners,support,threshold).flatMap(f=>clipSourceTriangle(f.sourceFace,f.corners,planes));if(armMass>0.08){const side=centroid.x>=0?'l':'r',origin=rest.bones.get(`upperarm_${side}`)!.point,axis=shoulder.get(side)!,hand=rest.bones.get(`hand_${side}`)!.point,limit=hand.clone().sub(origin).dot(axis)+0.012;fragments=fragments.flatMap(f=>clipSourceTriangle(f.sourceFace,f.corners,[{normal:axis.toArray() as [number,number,number],offset:-limit-origin.dot(axis),keep:'negative'}]));}
    for(const fragment of fragments){const out=fragment.corners.map(c=>emit(ids,c,fragment.sourceFace));if(new Set(out).size<3)continue;indices.push(out[0]!,out[1]!,out[2]!);sourceFaceIds.push(fragment.sourceFace);touchedSourceFaces.add(fragment.sourceFace);}
  }
  if(!indices.length)throw new Error('Office source shell selected no faces');
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geometry.setAttribute('wardrobeUv',new THREE.Float32BufferAttribute(uvs,2));geometry.setAttribute('wardrobeCloth',new THREE.Float32BufferAttribute(cloth,1));geometry.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(bones,4));geometry.setAttribute('skinWeight',new THREE.Float32BufferAttribute(weights,4));geometry.setIndex(indices);geometry.computeVertexNormals();geometry.computeBoundingSphere();
  const edgeCount=new Map<string,number>();for(let i=0;i<indices.length;i+=3)for(const [a,b]of [[indices[i]!,indices[i+1]!],[indices[i+1]!,indices[i+2]!],[indices[i+2]!,indices[i]!]]){const k=edgeKey(a,b);edgeCount.set(k,(edgeCount.get(k)??0)+1);}const bytes=Object.values(geometry.attributes).reduce((n,a)=>n+a.array.byteLength,0)+(geometry.index?.array.byteLength??0);
  return{geometry,triangles:indices.length/3,bytes,sourceFaces:touchedSourceFaces.size,sourceFaceIds,sourceBindings,openBoundaryEdges:[...edgeCount.values()].filter(n=>n===1).length,item:'office-source-shell',normalCacheWeldCount,normalCacheWeldMaxDisplacementM:normalCacheWeldMaxDisplacementMRef.value,normalCacheWelds};
}
