// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-1895,"z":4522})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-139.68734924979822,"maxX":320.7925551726869,"minZ":-390.58882566341254,"maxZ":97.00793928020175})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"yenegoa":{"lon":6.394087533691932,"lat":5.067402288709624}})
