import { defineCitySpec } from '../spec.ts'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'yenagoa',
  name: 'Yenagoa',
  state: { id: 'bayelsa', name: 'Bayelsa', sourceName: 'Bayelsa', unit: 'local government', sourceIds: ['geography'] },
  country: { id: 'nigeria', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 6.2747786,
    lat: 4.9334651,
    teaser: 'The Bayelsa capital on the Niger Delta swamps, with Ijaw fish dishes, a castle and a stadium.',
    preview: ['Visit Alamieyesiegha Castle and the National Museum.', 'Catch a bus at Opolo Motor Park and watch a match at Samson Siasia Stadium.'],
    coordinateSourceId: 'osm-selected',
    coordinateRef: { provider: 'openstreetmap', element: 'node', id: 245914677 },
  },
  population: { tier: 'city', sourceIds: ['yenagoa-wiki'], note: 'The cited article reports an estimated 798,466 residents of the Yenagoa local government area in 2024.' },
  localUnits: [
    { id: 'yenegoa', name: 'Yenagoa', sourceName: 'Yenegoa', populationTier: 'city', description: 'The single selected local government contains the state secretariat, stadium, castle, motor parks and every mapped venue.', sourceIds: ['geography'] },
  ],
  places: [
    {
      id: 'st-johns-catholic-yenagoa', name: "St John's Catholic Church", kind: 'church', lon: 6.4029474, lat: 5.034969, localUnitId: 'yenegoa',
      description: "A mapped place of worship named St John's Catholic Church.", sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 632274953 }, accuracy: 'feature-centroid',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'st-lukes-anglican-yenagoa', name: 'St Lukes Anglican Church', kind: 'church', lon: 6.3028337, lat: 4.9270008, localUnitId: 'yenegoa',
      description: 'A mapped Anglican church named St Lukes Anglican Church.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 650036571 }, accuracy: 'feature-centroid',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'st-patrick-catholic-yenagoa', name: 'St. Patrick Catholic Church', kind: 'church', lon: 6.3065703, lat: 4.9260513, localUnitId: 'yenegoa',
      description: 'A mapped place of worship named St. Patrick Catholic Church.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5476317526 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'ekeki-central-mosque', name: 'Ekeki Central Mosque', kind: 'mosque', lon: 6.297072, lat: 4.927757, localUnitId: 'yenegoa',
      description: 'Wikidata records the Ekeki Central Mosque as a mosque in Bayelsa.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125462610' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'opolo-mosque-yenagoa', name: 'Opolo Mosque', kind: 'mosque', lon: 6.3365863, lat: 4.9439049, localUnitId: 'yenegoa',
      description: 'A mapped place of worship named Opolo Mosque on Opolo street.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5512206433 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'crunchies-yenagoa', name: 'Crunchies', kind: 'eatery', lon: 6.3122889, lat: 4.9374678, localUnitId: 'yenegoa',
      description: 'A mapped fast-food outlet named Crunchies, shown here with fried fish and plantain.', sourceIds: ['osm-selected', 'ijaw-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5499882914 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'fried-fish-plantain',
    },
    {
      id: 'pepperoni-yenagoa', name: 'Pepperoni', kind: 'eatery', lon: 6.339907, lat: 4.9503242, localUnitId: 'yenegoa',
      description: 'A mapped fast-food outlet named Pepperoni, shown here with Opuru-fulou prawn soup.', sourceIds: ['osm-selected', 'ijaw-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5509059324 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'opuru-fulou',
    },
    {
      id: 'bayelsa-state-secretariat', name: 'State Secretariat Complex', kind: 'government', lon: 6.2729758, lat: 4.9375265, localUnitId: 'yenegoa',
      description: 'A mapped government office named State Secretariat Complex.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 7956231987 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'bayelsa-state-high-court', name: 'Bayelsa State High Court of Justice', kind: 'government', lon: 6.2723455, lat: 4.9342665, localUnitId: 'yenegoa',
      description: 'A mapped courthouse named Bayelsa State High Court of Justice.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 7956231988 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'bayelsa-state-government-house', name: 'Bayelsa State Government House', kind: 'government', lon: 6.273777777777778, lat: 4.941916666666667, localUnitId: 'yenegoa',
      description: 'Wikidata records the Bayelsa State Government House as a government building in Yenagoa.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q131742900' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'melford-okilo-memorial-hospital', name: 'Melford Okilo Memorial Hospital', kind: 'hospital', lon: 6.279358, lat: 4.9320159, localUnitId: 'yenegoa',
      description: 'A mapped hospital building named Melford Okilo Memorial Hospital.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 705002430 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'diete-koki-memorial-hospital', name: 'Diete-Koki Memorial Hospital', kind: 'hospital', lon: 6.3373897, lat: 4.9448553, localUnitId: 'yenegoa',
      description: 'A mapped hospital named Diete-Koki Memorial Hospital.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 803692595 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'swale-market-yenagoa', name: 'Swale Market', kind: 'market', lon: 6.266774, lat: 4.918839, localUnitId: 'yenegoa',
      description: 'Wikidata records Swale Market as a market in Nigeria; Wikipedia says the Ijaw live by fishing, farming and trading.', sourceIds: ['wikidata-selected', 'ijaw-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136649821' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['ijaw-fishing-farming'],
    },
    {
      id: 'onopa-market-yenagoa', name: 'Onopa Market', kind: 'market', lon: 6.280834, lat: 4.941019, localUnitId: 'yenegoa',
      description: 'Wikidata records Onopa Market as a market in Bayelsa State.', sourceIds: ['wikidata-selected', 'ijaw-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136651733' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['ijaw-fishing-farming'],
    },
    {
      id: 'braids-salon-yenagoa', name: 'Braids', kind: 'salon', lon: 6.332413, lat: 4.9477395, localUnitId: 'yenegoa',
      description: 'A mapped beauty shop named Braids.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5512132503 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] },
    },
    {
      id: 'may-exclusive-paradise-yenagoa', name: 'May Exclusive Paradise', kind: 'salon', lon: 6.3530307, lat: 4.9538716, localUnitId: 'yenegoa',
      description: 'A mapped beauty shop named May Exclusive Paradise.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5506376645 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] },
    },
    {
      id: 'zenith-bank-yenagoa', name: 'Zenith Bank', kind: 'savings', lon: 6.3141554, lat: 4.9383942, localUnitId: 'yenegoa',
      description: 'A mapped bank named Zenith Bank.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5499880729 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'uba-bank-yenagoa', name: 'UBA Bank', kind: 'savings', lon: 6.2897329, lat: 4.9305819, localUnitId: 'yenegoa',
      description: 'A mapped bank named UBA Bank.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 7956225492 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'first-bank-yenagoa', name: 'First Bank', kind: 'savings', lon: 6.2844911, lat: 4.9342131, localUnitId: 'yenegoa',
      description: 'A mapped bank named First Bank.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 7956224797 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'samson-siasia-stadium', name: 'Samson Siasia Stadium', kind: 'stadium', lon: 6.2668956, lat: 4.9327913, localUnitId: 'yenegoa',
      description: 'A mapped stadium named Samson Siasia Stadium.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 667635036 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'igbogene-field', name: 'Igbogene Field', kind: 'park', lon: 6.398331, lat: 5.0351929, localUnitId: 'yenegoa',
      description: 'A mapped park named Igbogene Field.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 908895940 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['tree', 'bench'] },
    },
    {
      id: 'opolo-motor-park', name: 'Opolo Motor Park', kind: 'road-hub', lon: 6.334159, lat: 4.9484499, localUnitId: 'yenegoa',
      description: 'A mapped bus station named Opolo Motor Park on Melford Okilo Road.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 7956224593 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'ekeki-motor-park', name: 'Ekeki Motor Park', kind: 'road-hub', lon: 6.29521, lat: 4.9289213, localUnitId: 'yenegoa',
      description: 'A mapped bus station named Ekeki Motor Park.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 7956225491 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'alamieyesiegha-castle', name: 'Alamieyesiegha Castle', kind: 'heritage', lon: 6.3432974, lat: 4.9488503, localUnitId: 'yenegoa',
      description: 'A mapped historic castle named Alamieyesiegha Castle.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 830731498 }, accuracy: 'feature-centroid',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'gabriel-okara-cultural-centre', name: 'Gabriel Okara Cultural Centre', kind: 'civic-landmark', lon: 6.2690585, lat: 4.9345428, localUnitId: 'yenegoa',
      description: 'A mapped theatre named Gabriel Okara Cultural Centre.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 906784882 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'national-museum-yenagoa', name: 'National Museum, Yenagoa', kind: 'museum', lon: 6.271741727507022, lat: 4.935923817645316, localUnitId: 'yenegoa',
      description: 'Wikidata records the National Museum, Yenagoa as a Nigerian national museum.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q112064213' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'institute-of-science-technology-yenagoa', name: 'Institute of Science and Technology, Yenagoa', kind: 'college', lon: 6.2818633, lat: 4.9317639, localUnitId: 'yenegoa',
      description: 'Wikidata records the Institute of Science and Technology, Yenagoa as a higher institution in Bayelsa State.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q129693122' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'university-of-africa-toru-orua', name: 'University of Africa, Toru-Orua', kind: 'university', lon: 6.2748, lat: 4.9212, localUnitId: 'yenegoa',
      description: 'Wikidata records the University of Africa, Toru-Orua as a public higher education institution in Bayelsa State.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q117836812' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'lamp'] },
    },
  ],
  identity: {
    foods: [
      { id: 'fried-fish-plantain', name: 'Fried fish and plantain', description: 'Wikipedia lists fried or roasted fish and plantain, fish fried in palm oil and served with fried plantains, among Ijaw foods.', sourceIds: ['ijaw-wiki'] },
      { id: 'opuru-fulou', name: 'Opuru-fulou prawn soup', description: 'Wikipedia lists Opuru-fulou, a prawn soup made with ogbono, dried fish, crayfish and red palm oil, among Ijaw foods.', sourceIds: ['ijaw-wiki'] },
    ],
    crafts: [
      { id: 'ijaw-carved-masks', name: 'Carved masquerade masks', description: 'Wikipedia says Ijaw water-spirit festivals centre on masquerades whose dancers wear elaborate outfits and carved masks.', sourceIds: ['ijaw-wiki'] },
    ],
    industries: [
      { id: 'bayelsa-oil-gas', name: 'Oil and gas', description: "Wikipedia says the economy of Bayelsa State is dominated by the petroleum industry and that the state holds Nigeria's largest gas reservoir.", sourceIds: ['bayelsa-wiki'] },
      { id: 'ijaw-fishing-farming', name: 'Fishing, farming and palm products', description: 'Wikipedia says the Ijaw live by fishing supplemented by farming and trading, and process smoke-dried fish, timber, palm oil and palm kernels for export.', sourceIds: ['ijaw-wiki'] },
    ],
  },
  transport: {
    airports: [],
    rail: [],
    ports: [],
  },
  climate: {
    profile: 'southern-wet-dry', rainyMonths: [4, 5, 6, 7, 8, 9, 10], dryMonths: [12, 1, 2],
    description: 'Yenagoa has a wet season from late March to early November and a dry season from early November to late March, in a swamp and mangrove rainforest area.',
    clearLabel: 'Dry-season sky', sourceIds: ['yenagoa-wiki'],
  },
  homePalette: { back: '#a9906a', left: '#6b5a3c', floor: ['#bfa97a', '#4f7a5a'] },
  geometry: { surface: { path: 'scripts/geo/sources/formula/yenagoa-surface.geojson', bytes: 472458, sha256: '55a8ed996e81414031a86f208abb80bd4f2505c7793df007b0c95fa1713b73a6' } },
  sourceGroups: [
    { id: 'osm-selected', title: 'Selected OpenStreetMap records for Yenagoa', url: 'https://www.openstreetmap.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'ODbL 1.0', cache: { path: 'scripts/city/research/yenagoa/reviewed/osm-selected.json', bytes: 5633, sha256: 'c24efe5f0112fc8a013256c059476e7f3a1b00de4bf4bca9c7d877aeba02035d' } },
    { id: 'wikidata-selected', title: 'Selected Wikidata entities for Yenagoa', url: 'https://www.wikidata.org/wiki/Wikidata:Main_Page', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'CC0 1.0', cache: { path: 'scripts/city/research/yenagoa/reviewed/wikidata-selected.json', bytes: 6050, sha256: 'c25ceec655c018d7f413298819a4e464befd4098d5e2843ccb5f5957e56a14cf' } },
    { id: 'geography', title: 'Pinned Nigerian administrative geography', url: 'https://www.geoboundaries.org/', checkedOn: '2026-10-06', supports: ['geography'], licence: 'CC BY 4.0', cache: { path: 'scripts/city/research/yenagoa/reviewed/geography.json', bytes: 350, sha256: '8108e968f344a7f4d95ea1f3ad323b695e040af31386b8148339d92fce280d58' } },
    { id: 'yenagoa-wiki', title: 'Wikipedia: Yenagoa', url: 'https://en.wikipedia.org/wiki/Yenagoa', checkedOn: '2026-10-06', supports: ['population', 'climate', 'identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/yenagoa/reviewed/yenagoa-wiki.json', bytes: 497, sha256: 'a0fd6f65a3c1a84d368b9fc141e228ec93cd1b6ed9dc2bdd6920feca37f7833f' } },
    { id: 'ijaw-wiki', title: 'Wikipedia: Ijaw people', url: 'https://en.wikipedia.org/wiki/Ijaw_people', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/yenagoa/reviewed/ijaw-wiki.json', bytes: 662, sha256: 'ff506bcb55006fd865d99b5cb365c5909366410d2ba51737e62c7ea29e47df87' } },
    { id: 'bayelsa-wiki', title: 'Wikipedia: Bayelsa State', url: 'https://en.wikipedia.org/wiki/Bayelsa_State', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/yenagoa/reviewed/bayelsa-wiki.json', bytes: 330, sha256: '6e03e5762e92430ec8d58bae15ca8dbf9742d0ee8b61c0779d152e9b117b0f49' } },
  ],
  unmapped: [
    { kind: 'garden', note: 'No named garden with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'polling', note: 'No named polling venue with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
  ],
})
