// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-439,"z":-4436})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-48.89040836272295,"maxX":99.37601349977615,"minZ":-107.56708112036176,"maxZ":41.85964757446709})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"katsina":{"lon":7.620474330180409,"lat":13.012698770144421}})
