import { defineCitySpec } from '../spec.ts'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'katsina',
  name: 'Katsina',
  state: { id: 'katsina', name: 'Katsina', sourceName: 'Katsina', unit: 'local government', sourceIds: ['geography'] },
  country: { id: 'nigeria', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 7.6006278,
    lat: 12.9894283,
    teaser: 'The Katsina emirate capital, with the Gobarau Minaret, old city gates and Hausa groundnut and leather trade.',
    preview: ['Visit the Gobarau Minaret and the National Museum.', 'Catch a match at Muhammadu Dikko Stadium and a bus at the Central Motor Park.'],
    coordinateSourceId: 'osm-selected',
    coordinateRef: { provider: 'openstreetmap', element: 'node', id: 501540897 },
  },
  population: { tier: 'city', sourceIds: ['katsina-wiki'], note: 'The cited article gives a 2016 estimate of 429,000 residents for Katsina.' },
  localUnits: [
    { id: 'katsina', name: 'Katsina', sourceName: 'Katsina', populationTier: 'city', description: 'The single selected local government holds the old city gates, the minaret, the stadiums, the markets and every mapped venue.', sourceIds: ['geography'] },
  ],
  places: [
    {
      id: 'st-martin-de-porres-cathedral-katsina', name: 'Cathedral of St. Martin de Porres', kind: 'church', lon: 7.62019, lat: 12.99419, localUnitId: 'katsina',
      description: 'Wikidata records the Cathedral of St. Martin de Porres in Katsina.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q134500966' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'baptist-church-katsina', name: 'Baptist Church katsina', kind: 'church', lon: 7.622488999277737, lat: 13.004060645873208, localUnitId: 'katsina',
      description: 'Wikidata records the Baptist Church in Katsina.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125446416' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'central-mosque-katsina', name: 'Central Mosque', kind: 'mosque', lon: 7.599064, lat: 12.9926255, localUnitId: 'katsina',
      description: 'A mapped mosque building named Central Mosque.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 379658753 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'modoji-central-mosque-katsina', name: 'Modoji Central Mosque', kind: 'mosque', lon: 7.6423433, lat: 13.0100826, localUnitId: 'katsina',
      description: 'A mapped place of worship named Modoji Central Mosque.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 3748972615 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'lady-m-katsina', name: 'Lady m', kind: 'eatery', lon: 7.6216988, lat: 12.9730239, localUnitId: 'katsina',
      description: 'A mapped fast-food outlet named Lady m, shown here with suya.', sourceIds: ['osm-selected', 'suya-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5922051786 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'suya',
    },
    {
      id: 's-cafe-katsina', name: 'S-cafe fast food and restaurant', kind: 'eatery', lon: 7.627551, lat: 12.994566, localUnitId: 'katsina',
      description: 'Wikidata records S-cafe fast food and restaurant in Katsina, shown here with tuwon shinkafa.', sourceIds: ['wikidata-selected', 'tuwon-shinkafa-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136841441' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'tuwon-shinkafa',
    },
    {
      id: 'katsina-state-house-of-assembly', name: 'Katsina State House of Assembly', kind: 'government', lon: 7.6255387, lat: 13.0158413, localUnitId: 'katsina',
      description: 'A mapped administrative office named Katsina State House of Assembly.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2570329819 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'katsina-lga-council', name: 'Katsina Local Government Area Council', kind: 'government', lon: 7.6098811, lat: 12.9953918, localUnitId: 'katsina',
      description: 'A mapped administrative office named Katsina Local Government Area Council.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2570329824 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'katsina-new-government-house', name: 'Katsina State New Government House', kind: 'government', lon: 7.6346626, lat: 13.0128082, localUnitId: 'katsina',
      description: 'A mapped government office named Katsina State New Government House.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5663070993 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'general-hospital-katsina', name: 'General Hospital', kind: 'hospital', lon: 7.6028051, lat: 13.0013745, localUnitId: 'katsina',
      description: 'A mapped hospital building named General Hospital.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 593686043 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'katsina-eye-clinic', name: 'Katsina Eye Clinic', kind: 'hospital', lon: 7.5946175, lat: 12.9954267, localUnitId: 'katsina',
      description: 'A mapped hospital building named Katsina Eye Clinic.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 593734251 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'central-market-katsina', name: 'Central Market, Katsina', kind: 'market', lon: 7.6016692, lat: 12.9712284, localUnitId: 'katsina',
      description: 'A mapped marketplace named Central Market, Katsina; Wikipedia describes the city as a centre for groundnuts, cotton and hides.', sourceIds: ['osm-selected', 'katsina-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 594160275 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['katsina-groundnuts-cotton-hides'],
    },
    {
      id: 'kasuwar-kofar-kaura-katsina', name: 'Kasuwar kofar kaura', kind: 'market', lon: 7.6112401, lat: 12.9764289, localUnitId: 'katsina',
      description: 'Wikidata records Kasuwar Kofar Kaura as a market in Katsina State.', sourceIds: ['wikidata-selected', 'katsina-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136526489' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['katsina-groundnuts-cotton-hides'],
    },
    {
      id: 'maryam-park-katsina', name: 'Maryam Park', kind: 'park', lon: 7.6301656, lat: 12.9988443, localUnitId: 'katsina',
      description: 'A mapped park named Maryam Park.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 593699965 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['tree', 'bench'] },
    },
    {
      id: 'katsina-polo-ground', name: 'Katsina Polo Ground', kind: 'park', lon: 7.5819886, lat: 12.9842337, localUnitId: 'katsina',
      description: 'A mapped park named Katsina Polo Ground.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 250627793 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['tree', 'bench'] },
    },
    {
      id: 'central-motor-park-katsina', name: 'Central Motor Park', kind: 'road-hub', lon: 7.6008343, lat: 12.9698971, localUnitId: 'katsina',
      description: 'A mapped bus station named Central Motor Park.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5656741191 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'kano-motor-park-katsina', name: 'Kano motor park', kind: 'road-hub', lon: 7.5997189, lat: 12.9695418, localUnitId: 'katsina',
      description: 'A mapped bus station named Kano motor park.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5784351153 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'uba-katsina', name: 'United Bank for Africa', kind: 'savings', lon: 7.6145091, lat: 12.9748391, localUnitId: 'katsina',
      description: 'A mapped bank named United Bank for Africa.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5666152458 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'zenith-bank-katsina', name: 'Zenith Bank', kind: 'savings', lon: 7.6034597, lat: 12.9833228, localUnitId: 'katsina',
      description: 'A mapped bank named Zenith Bank.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5666245893 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'muhammadu-dikko-stadium', name: 'Muhammadu Dikko Stadium', kind: 'stadium', lon: 7.6379534, lat: 12.9769254, localUnitId: 'katsina',
      description: 'A mapped stadium named Muhammadu Dikko Stadium.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 213163542 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'katsina-township-stadium', name: 'Katsina Township Stadium', kind: 'stadium', lon: 7.6049264, lat: 12.9962374, localUnitId: 'katsina',
      description: 'A mapped stadium named Katsina Township Stadium.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2570329820 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'yusuf-bala-usman-college-katsina', name: 'Yusuf Bala Usman College of Legal and General Studies', kind: 'college', lon: 7.62227, lat: 12.98156, localUnitId: 'katsina',
      description: 'Wikidata records the Yusuf Bala Usman College of Legal and General Studies as a college of education in Katsina.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q108443815' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'gobarau-minaret', name: 'Gobarau Minaret', kind: 'heritage', lon: 7.595517, lat: 12.997977, localUnitId: 'katsina',
      description: 'Wikidata records the Gobarau Minaret as a tower in Katsina; Wikipedia places it at an 18th-century mosque.', sourceIds: ['wikidata-selected', 'katsina-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q5575409' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'kofar-soro-katsina', name: 'Kofar Soro', kind: 'heritage', lon: 7.5992825, lat: 12.9946706, localUnitId: 'katsina',
      description: 'A mapped historic monument named Kofar Soro, the main gate to the Katsina royal palace according to Wikipedia.', sourceIds: ['osm-selected', 'katsina-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5663434479 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'national-museum-katsina', name: 'National Museum, Katsina', kind: 'museum', lon: 7.604067, lat: 13.005413, localUnitId: 'katsina',
      description: 'Wikidata records the National Museum, Katsina as a national museum in Nigeria.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q111908505' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
  ],
  identity: {
    foods: [
      { id: 'suya', name: 'Suya', description: 'Wikipedia describes suya as a traditional Hausa smoke-grilled spiced meat on skewers, seasoned with the spice mix yaji.', sourceIds: ['suya-wiki'] },
      { id: 'tuwon-shinkafa', name: 'Tuwon shinkafa', description: 'Wikipedia describes tuwon shinkafa as a rice swallow from northern Nigeria, usually served with soups such as miyan kuka and miyan taushe.', sourceIds: ['tuwon-shinkafa-wiki'] },
    ],
    crafts: [
      { id: 'hausa-textiles-leatherwork', name: 'Textiles and leatherwork', description: 'Wikipedia says Hausa states such as Katsina and Kano became trading centres whose merchants specialised in producing textiles and leatherwork.', sourceIds: ['hausa-wiki'] },
    ],
    industries: [
      { id: 'katsina-groundnuts-cotton-hides', name: 'Groundnuts, cotton and hides', description: 'Wikipedia describes Katsina as the centre of an agricultural region noted for groundnuts, cotton, hides, millet and guinea corn, with mills for peanut oil and steel.', sourceIds: ['katsina-wiki'] },
    ],
  },
  transport: {
    airports: [],
    rail: [],
    ports: [],
  },
  climate: {
    profile: 'sahel', rainyMonths: [4, 5, 6, 7, 8, 9, 10], dryMonths: [11, 12, 1, 2, 3],
    description: 'Katsina has a hot semi-arid climate; the cited rainfall record shows no average rain from November to March and rain from April to October.',
    clearLabel: 'Dry-season sky', sourceIds: ['katsina-wiki'],
  },
  homePalette: { back: '#cfa45e', left: '#8c6a34', floor: ['#d8be86', '#7d8a5a'] },
  geometry: { surface: { path: 'scripts/geo/sources/formula/katsina-surface.geojson', bytes: 150457, sha256: 'd45f47a1e5e77e27f999acd3f3e06b5021ee9eeca319e512bced338a7e8fec8d' } },
  sourceGroups: [
    { id: 'osm-selected', title: 'Selected OpenStreetMap records for Katsina', url: 'https://www.openstreetmap.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'ODbL 1.0', cache: { path: 'scripts/city/research/katsina/reviewed/osm-selected.json', bytes: 4720, sha256: '520a81001dfa95b9a241b3c999a468250cfd1c09316b24e739db6f671b9cc49e' } },
    { id: 'wikidata-selected', title: 'Selected Wikidata entities for Katsina', url: 'https://www.wikidata.org/wiki/Wikidata:Main_Page', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'CC0 1.0', cache: { path: 'scripts/city/research/katsina/reviewed/wikidata-selected.json', bytes: 5863, sha256: 'a87cdd52a455d65174cd4f3ef53adfdf406b61c317354d2c8b7e2f4f1c612f33' } },
    { id: 'geography', title: 'Pinned Nigerian administrative geography', url: 'https://www.geoboundaries.org/', checkedOn: '2026-10-06', supports: ['geography'], licence: 'CC BY 4.0', cache: { path: 'scripts/city/research/katsina/reviewed/geography.json', bytes: 350, sha256: 'f8cdf81a1de30582d54dcea00b39bc1dae156d47805ee3b76ca22811b5b06b49' } },
    { id: 'katsina-wiki', title: 'Wikipedia: Katsina (city)', url: 'https://en.wikipedia.org/wiki/Katsina_(city)', checkedOn: '2026-10-06', supports: ['population', 'climate', 'identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/katsina/reviewed/katsina-wiki.json', bytes: 776, sha256: '54636301ae93b2c7b870076e71d6a9e408b726fc167828a8107f201ce63df4e1' } },
    { id: 'hausa-wiki', title: 'Wikipedia: Hausa people', url: 'https://en.wikipedia.org/wiki/Hausa_people', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/katsina/reviewed/hausa-wiki.json', bytes: 482, sha256: '987ce316769189db455036bd5babb2d8753ff2c4b7e1d0c96f83146b539c718f' } },
    { id: 'suya-wiki', title: 'Wikipedia: Suya', url: 'https://en.wikipedia.org/wiki/Suya', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/katsina/reviewed/suya-wiki.json', bytes: 277, sha256: 'ff698f4bff5262056dabb7347be0cb9124e194f9727a2548e7d91028a64643bd' } },
    { id: 'tuwon-shinkafa-wiki', title: 'Wikipedia: Tuwon shinkafa', url: 'https://en.wikipedia.org/wiki/Tuwon_shinkafa', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/katsina/reviewed/tuwon-shinkafa-wiki.json', bytes: 278, sha256: 'd6423e372de83365894902bc6d0f2cf63ba8fe953ec641f4966280a25ac82e84' } },
  ],
  unmapped: [
    { kind: 'garden', note: 'No named garden with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'polling', note: 'No named polling venue with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'salon', note: 'No named salon with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
  ],
})
