import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { mkdirSync, readFileSync, readdirSync, renameSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import type { Plugin } from 'vite';

const wantMaps = process.env.SOURCEMAPS === '1';
const MAPS_DIR = 'dist-maps';

/** With SOURCEMAPS=1: move every .map out of the build output into dist-maps/, keeping its path under dist/ (dist/assets/x.js.map -> dist-maps/assets/x.js.map). */
function moveMaps(): Plugin {
  let outDir = '';
  return {
    name: 'allworld:move-source-maps',
    apply: 'build',
    configResolved(config) { outDir = resolve(config.root, config.build.outDir); },
    writeBundle() {
      const walk = (dir: string): void => {
        for (const entry of readdirSync(dir, { withFileTypes: true })) {
          const from = join(dir, entry.name);
          if (entry.isDirectory()) walk(from);
          else if (entry.name.endsWith('.map')) {
            const to = join(dirname(outDir), MAPS_DIR, from.slice(outDir.length + 1));
            mkdirSync(dirname(to), { recursive: true });
            renameSync(from, to);
          }
        }
      };
      walk(outDir);
    },
  };
}

/**
 * The browser's engine registers the UNILAG campus as stand-ins and fetches its rules on first use (src/game/systems/browser.ts,
 * src/game/campus-gate.ts); the servers, the Worker, the scripts and the tests register everything from systems/index.ts. Only
 * this build swaps one for the other, so the rules themselves exist once.
 */
function browserSystems(): Plugin {
  return {
    name: 'allworld:browser-systems',
    enforce: 'pre',
    // The browser only reads lives (src/game/profile.ts): what only playing one needs is not in the page.
    load(id) { return /\/src\/game\/profile\.ts$/.test(id) ? 'export const PLAYS = false;\nexport const LEFT_OUT = {};\n' : null; },
    async resolveId(source, importer, options) {
      if (!/systems\/index\.ts$/.test(source)) return null;
      const resolved = await this.resolve(source, importer, { ...options, skipSelf: true });
      return resolved && /\/src\/game\/systems\/index\.ts$/.test(resolved.id) ? resolved.id.replace(/index\.ts$/, 'browser.ts') : null;
    },
  };
}

/**
 * Every city spec is checked when it is generated (scripts/city/build-city.ts) and again by the test suite, both through
 * src/game/cities/specValidation.ts. The page runs defineCitySpec on a spec that has already passed, so it gets a validator
 * that finds nothing wrong instead of the several kilobytes of checks.
 */
function skipSpecValidation(): Plugin {
  return {
    name: 'allworld:skip-spec-validation',
    apply: 'build',
    enforce: 'pre',
    load(id) { return /\/src\/game\/cities\/specValidation\.ts$/.test(id) ? 'export const validateCitySpec = (): readonly string[] => [];\n' : null; },
  };
}

/**
 * PROVENANCE MARKS the page never reads. Content entries carry `note` (where a value came from) and `betaFields` (which fields are
 * provisional): src/types/content.ts says they are "never read by the rules", and the view builders leave `note` out of every card
 * (systems/activities.ts). They are for people reading the source; the browser's copy of the default city's content is smaller
 * without them. Only the tables of the default city's engine chunk, the regulars written into a generated city content.ts
 * (scripts/city/build-city.ts) and a formula city's spec.ts are touched, and only the literal forms the tables use. In a spec the
 * page keeps what the content builders read (places, identity, climate, transport); where each value came from (`sourceGroups`
 * with its URLs, licences and file hashes, `geometry` with the surface file's hash, `coordinateRef` and the `note` lines) is read
 * by scripts/city/build-city.ts and the tests, which load the spec in Node, and never by the page.
 */
function leaveOutProvenance(): Plugin {
  const text = String.raw`(?:'(?:[^'\\\n]|\\.)*'|"(?:[^"\\\n]|\\.)*"|`+'`[^`$]*`'+String.raw`|[A-Za-z_$][\w$]*(?=\s*[,}]))`;
  const marks = [new RegExp(String.raw`\bnote:\s*${text}\s*,?\s*`, 'g'), /\bbetaFields:\s*\[[^\]]*\]\s*,?\s*/g];
  const tables = /\/src\/(game\/(cities\/(lagos\/(venues|regulars)|registry)|content\/(food|npcs|furniture|jobs|venues-transport))|campus\/unilag\/content)\.ts$/;
  const generatedContent = /\/src\/game\/cities\/[^/]+\/content\.ts$/, GENERATED_BY = 'Generated by scripts/city/build-city.ts';
  const citySpec = /\/src\/game\/cities\/[^/]+\/spec\.ts$/;
  const coordinateRefs = /\bcoordinateRef:\s*\{[^{}]*\}\s*,?\s*/g;
  /** Removes a property written at the top level of the spec literal (two-space indent) whose value is one array or object. */
  const dropProperty = (code: string, name: string): string => {
    const start = code.search(new RegExp(`^  ${name}: [\\[{]`, 'm'));
    if (start < 0) return code;
    let index = code.indexOf(':', start) + 2, depth = 0, quote = '';
    for (; index < code.length; index += 1) {
      const char = code[index]!;
      if (quote) { if (char === '\\') index += 1; else if (char === quote) quote = ''; continue; }
      if (char === "'" || char === '"' || char === '`') quote = char;
      else if (char === '[' || char === '{') depth += 1;
      else if (char === ']' || char === '}') { depth -= 1; if (depth === 0) break; }
    }
    return code.slice(0, start) + code.slice(index + 1).replace(/^,?[ \t]*\n?/, '');
  };
  return {
    name: 'allworld:leave-out-provenance',
    apply: 'build',
    enforce: 'pre',
    transform(code, id) {
      const spec = citySpec.test(id) && code.includes('defineCitySpec(');
      if (!tables.test(id) && !spec && !(generatedContent.test(id) && code.includes(GENERATED_BY))) return null;
      let out = code;
      if (spec) out = dropProperty(dropProperty(out, 'sourceGroups'), 'geometry').replace(coordinateRefs, '');
      for (const mark of marks) out = out.replace(mark, '');
      return out === code ? null : { code: out, map: null };
    },
  };
}

/**
 * The checked-in loader table uses literal dynamic imports so Node and the Worker bundler can resolve it. In the browser build,
 * emit those same entry modules as Rollup chunks and keep only compact [URL, export] rows plus one shared importer in startup.
 */
function lazyCityLoaders(): Plugin {
  const emitted = new Set<string>();
  return {
    name: 'allworld:lazy-city-loaders',
    apply: 'build',
    enforce: 'pre',
    async transform(code, id) {
      if (!/\/src\/game\/cities\/loaders\.generated\.ts$/.test(id)) return null;
      const declarations = [...code.matchAll(/async\(\)=>\(await import\(("[^"]+")\)\)\.([A-Za-z_$][\w$]*),/g)];
      const declaredCount = [...code.matchAll(/async\(\)=>/g)].length;
      if (!declarations.length || declarations.length !== declaredCount) throw new Error(`Expected ${declaredCount} generated city loaders, parsed ${declarations.length}`);
      const stringLiteral = (literal: string | undefined, label: string): string => { const value: unknown = JSON.parse(literal ?? 'null'); if (typeof value !== 'string') throw new Error(`${label} is not a string`); return value; };
      const catalogueIds = [...readFileSync(id.replace(/loaders\.generated\.ts$/, 'catalogue.generated.ts'), 'utf8').matchAll(/^  \["([^"]+)"/gm)].flatMap((match) => typeof match[1] === 'string' ? [match[1]] : []);
      const loaderIds = declarations.map((match) => stringLiteral(match[1], 'Generated city loader path').replace(/^\.\//, '').replace(/\/index\.ts$/, ''));
      if (JSON.stringify(loaderIds) !== JSON.stringify(catalogueIds)) throw new Error('Generated city catalogue and browser loader rows differ');
      const rows: string[] = [];
      for (let index = 0; index < declarations.length; index += 1) {
        const match = declarations[index]!, specifier = stringLiteral(match[1], 'Generated city loader path'), exportName = match[2]!;
        const resolved = await this.resolve(specifier, id, { skipSelf: true });
        if (!resolved) throw new Error(`Could not resolve generated city loader ${specifier}`);
        const referenceId = this.emitFile({ type: 'chunk', id: resolved.id, name: `city-${catalogueIds[index]}-rules`, preserveSignature: 'strict' });
        emitted.add(referenceId);
        rows.push(`[import.meta.ROLLUP_FILE_URL_${referenceId},${JSON.stringify(exportName)}]`);
      }
      return { code: `import type { CityModule } from '../../types/content.ts'\nimport type { CityModuleLoader } from './catalogue.ts'\nconst rows = [${rows.join(',')}] as const\nconst load = ([path,name]: readonly [string,string]): Promise<CityModule> => import(/* @vite-ignore */ path).then((namespace: Record<string, CityModule>) => { const city = namespace[name]; if (!city) throw new Error('City module export is missing'); return city })\nexport const GENERATED_CITY_LOADERS: readonly CityModuleLoader[] = Object.freeze(rows.map((row) => async() => load(row)))\n`, map: null };
    },
    resolveFileUrl({ referenceId, relativePath }) {
      if (!emitted.has(referenceId)) return null;
      return JSON.stringify(relativePath.startsWith('.') ? relativePath : `./${relativePath}`);
    },
  };
}

export default defineConfig({
  // The page is a Vue 3 + TypeScript application: index.html → src/app/main.ts (docs/MIGRATION-VUE-TS.md).
  plugins: [browserSystems(), skipSpecValidation(), leaveOutProvenance(), lazyCityLoaders(), vue(), ...(wantMaps ? [moveMaps()] : [])],
  // Every shipped component uses Composition API; omit the unused Options API runtime.
  define: { __VUE_OPTIONS_API__: false },
  server: {
    host: '127.0.0.1', port: 5173,
    proxy: {
      '/api': { target: 'http://127.0.0.1:3001' },
      '/socket': { target: 'ws://127.0.0.1:3001', ws: true },
    },
  },
  // voice-test.html is a development fixture (served by `npm run dev` only): it is not a build input.
  // Source maps are opt-in: `SOURCEMAPS=1 npm run build` writes hidden maps (no sourceMappingURL in the served files) to dist-maps/,
  // outside dist/, for `npm run sentry:sourcemaps` to upload. The default build emits none, so nothing under dist/ is a map: the release
  // package admits no .map file, and a bundle never points at a map that is not there.
  // Chunks (caching, and so that the browser fetches the pieces of the first load side by side — Vite adds a modulepreload link
  // for each static import of the entry):
  //   three   Three.js, fetched by the scene (never part of the first load);
  //   vue     the framework: changes with a Vue upgrade only;
  //   engine  the rules (src/game, src/life.ts, the campus rules): the shell builds and reads every life through them, so it is
  //           part of the first load, but it changes far less often than the shell.
  // Three.js is one 700 kB chunk on purpose (fetched by the scene, never part of the first load): the size warning starts above it.
  build: {
    chunkSizeWarningLimit: 800,
    // Terser, two passes: the same program in about 3% fewer gzip bytes than the default esbuild minifier, for every chunk (the startup
    // is the part that has a budget). It only compresses and renames; it does not change what the code does.
    minify: 'terser',
    terserOptions: { compress: { passes: 2 }, format: { comments: false } },
    modulePreload: { polyfill: false },
    sourcemap: wantMaps ? 'hidden' : false,
    rollupOptions: { input: { app: 'index.html', adminshell: 'adminshell.html' }, output: { hashCharacters: 'hex', onlyExplicitManualChunks: true, manualChunks(id) {
    const city = id.match(/\/src\/game\/cities\/([^/]+)\/(content|map)\.ts$/)
    if (city) return `city-${city[1]}-${city[2]}`
    if (/\/src\/game\/cities\/(?:routes\.generated|links)\.ts$/.test(id) || /\/src\/game\/cities\/[^/]+\/links\.ts$/.test(id)) return 'city-routes'
    if (/\/src\/game\/cities\/(spec|specValidation)\.ts$/.test(id)) return 'city-spec'
    if (/\/src\/game\/cities\/contentBuilder\.ts$/.test(id)) return 'city-content-builder'
    if (/\/src\/game\/cities\/ogun\/(contentBuilder)\.ts$/.test(id)) return 'city-ogun-content'
    if (/\/src\/game\/cities\/ogun\/(character|scene)\.ts$/.test(id)) return 'city-ogun-map'
    if (/\/src\/game\/cities\/ogun\/mapOverview\.ts$/.test(id)) return 'city-ogun-map'
    // A city's local-unit wording, and the table of its venues' own scenes, are read by its content only.
    const wording = id.match(/\/src\/game\/cities\/([^/]+)\/(?:descriptions|scenes)\.ts$/)
    if (wording) return `city-${wording[1]}-content`
    // Of a city's folder the engine reads only the rules, the registry entry and the links. Every other file (roads, water, landmarks,
    // rail, the map's character) is fetched with that city's map, so it must never fall through to the `engine` rule below.
    const part = id.match(/\/src\/game\/cities\/([^/]+)\/([\w-]+)\.ts$/)
    if (part) {
      if (/^(rules|index|links|localUnits)$/.test(part[2] as string)) return undefined
      return `city-${part[1]}-${part[2]}`
    }
    // A city's own scenes are fetched when a venue of that city is shown (src/scene/city-scenes.ts): one chunk per city — Ogun's four
    // cities share two, the signature scenes and the everyday ones. What several cities' scenes draw with (venues-common.ts) is left to the bundler: a small chunk of its own.
    const scenes = id.match(/\/src\/scene\/venues-(ibadan|ogun|rivers|fct|kano)(?:-([ab]))?\.ts$/)
    if (scenes) return scenes[1] === 'ogun' ? `city-ogun-scenes-${scenes[2]}` : `city-${{ ibadan: 'ibadan', rivers: 'port-harcourt', fct: 'abuja', kano: 'kano' }[scenes[1] as 'ibadan' | 'rivers' | 'fct' | 'kano']}-scenes`
    // The table of which city needs which: nothing else is in it, so the page can ask for a city's scenes before the host has arrived.
    if (/\/src\/scene\/city-scenes\.ts$/.test(id)) return 'city-scenes'
    // The sound engine (every recipe, the synth, the mixer) is fetched on the first tap; only src/audio/play.ts and settings.ts are in the first download.
    if (/\/src\/audio\/(engine|director|data|synth|scape)\.ts$/.test(id)) return 'audio'
    if (/\/src\/audio\/board\.ts$/.test(id)) return 'audio-board'
    if (/node_modules\/three\//.test(id)) return 'three'
    if (/node_modules\/@?vue\/|node_modules\/vue\//.test(id)) return 'vue'
    // The admin address's page (adminshell.html) is a second entry. The two small account modules both entries use (the state of accounts and the funnel
    // words) ride in the framework chunk both already load, so the game's first download is the same files it was and the admin page carries nothing of the game.
    if (/\/src\/app\/features\/account\/(accountLite|accountTrack)\.ts$/.test(id)) return 'vue'
    // The campus rules are fetched when a life uses the campus (src/game/campus-gate.ts), not with the first page.
    if (/\/src\/campus\/unilag\/(student|games|shuttle|curriculum|walk|layout|register)\.ts$/.test(id)) return 'campus-rules'
    // Plain typed-array code shared by the campus rules and the scenes (never part of the first page): the walk grid included.
    if (/\/src\/scene\/(movement|build|walk-grid)\.ts$/.test(id)) return 'scene-core'
    // The NPC mark's word and spoken text (the scene tags and the badge both read them): the scene is on screen before any panel, so it rides in the chunk the scene already loads instead of adding a file to the first download's list. The badge itself is a panel's, fetched with the first panel that shows a person.
    if (/\/src\/ui\/npc-mark\.ts$/.test(id)) return 'scene-core'
    // Only the share sheet reads this (src/ui/share.ts, fetched on demand).
    if (/\/src\/game\/share-model\.ts$/.test(id)) return undefined
    // The visit rules (door words, how long a visit lasts): read only by the visit screens, which are fetched on demand.
    if (/\/src\/game\/visit\.ts$/.test(id)) return undefined
    // Read only by screens that are fetched on demand: the wording and numbers of Ping, the comeback switches, the sentences of the
    // people screens and of the Map's list, the creative choices of an advert, and the shop line of each piece of furniture.
    // The world clock's bands, day seed and seasons: read only by the moment banks (src/moments, fetched once the game is ready) until a feature of the first page needs them.
    if (/\/src\/game\/(ping|comeback-prefs|social-lines|live-lines|world-time|content\/civic-ads|content\/furniture-blurbs)\.ts$/.test(id)) return undefined
    // The campus discovery trail is read by the campus rules and the Campus app.
    if (/\/src\/campus\/unilag\/trail\.ts$/.test(id)) return 'campus-rules'
    // Short addresses (/games, /abuja, …): the table, what is kept for a visit and the routing are one chunk, fetched only when an address or the landing asks, so the first download lists one file for them.
    if (/\/src\/(paths\.ts$|app\/features\/paths\/[\w-]+\.ts$)/.test(id)) return 'paths'
    // Work dilemmas and place actions (their words and rules, and the kit that installs them) are fetched once the game is ready (src/app/startExtras.ts); the engine never imports them (src/game/features.ts).
    if (/\/src\/game\/(dilemma-pack|dilemmas|place-actions)\.ts$|\/src\/game\/content\/(dilemmas|place-actions)\.ts$/.test(id)) return 'dilemmas'
    // Regulars talking to each other (REALISM R12) are fetched after the game is ready: their words, the picker and the bubbles are one chunk, never part of the first download.
    if (/\/src\/(game|app)\/chatter\//.test(id)) return 'chatter'
    if (/\/src\/(game\/|life\.ts$|campus\/unilag\/(content|spot-names)\.ts$|tables\/places\.ts$)/.test(id)) return 'engine'
    } } },
  },
});
