// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "banjul",
  "name": "Banjul",
  "country": {
    "idISOlower": "gm",
    "name": "Gambia"
  },
  "state": {
    "idunique": "gm-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Banjul",
  "centre": {
    "lon": -16.591701,
    "lat": 13.453876
  },
  "airport": {
    "id": "banjul-airport",
    "name": "Banjul International Airport",
    "lon": -16.652201,
    "lat": 13.338,
    "sourceUrl": "https://ourairports.com/airports/GBYD/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-16.594701,13.450876,-16.588701,13.456876",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -16.664201,
    13.326,
    -16.576701,
    13.468876
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
