// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "dar",
  "name": "Dar es Salaam",
  "country": {
    "idISOlower": "tz",
    "name": "United Republic of Tanzania"
  },
  "state": {
    "idunique": "tz-zone",
    "name": "Starter"
  },
  "timezone": "Africa/Dar_es_Salaam",
  "centre": {
    "lon": 39.266396,
    "lat": -6.798067
  },
  "airport": {
    "id": "dar-airport",
    "name": "Julius Nyerere International Airport",
    "lon": 39.207288,
    "lat": -6.873499,
    "sourceUrl": "https://ourairports.com/airports/HTDA/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=39.263396,-6.801067,39.269396,-6.795067",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    39.195288,
    -6.885499,
    39.281396,
    -6.783067
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
