// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "sao-tome",
  "name": "São Tomé",
  "country": {
    "idISOlower": "st",
    "name": "São Tomé and Principe"
  },
  "state": {
    "idunique": "st-zone",
    "name": "Starter"
  },
  "timezone": "Africa/Sao_Tome",
  "centre": {
    "lon": 6.72965,
    "lat": 0.337466
  },
  "airport": {
    "id": "sao-tome-airport",
    "name": "São Tomé International Airport",
    "lon": 6.71215,
    "lat": 0.378175,
    "sourceUrl": "https://ourairports.com/airports/FPST/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=6.72665,0.334466,6.73265,0.340466",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    6.70015,
    0.3217966,
    6.74465,
    0.390175
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates. Published bounds include complete retained OSM feature coordinates and expand by at most 0.02 degrees beyond the initial settlement/airport bounds."
} satisfies DestinationFacts
