// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "kin",
  "name": "Kinshasa",
  "country": {
    "idISOlower": "cd",
    "name": "Democratic Republic of the Congo"
  },
  "state": {
    "idunique": "cd-zone",
    "name": "Starter"
  },
  "timezone": "Africa/Kinshasa",
  "centre": {
    "lon": 15.313026,
    "lat": -4.327778
  },
  "airport": {
    "id": "kin-airport",
    "name": "Ndjili International Airport",
    "lon": 15.4446,
    "lat": -4.38575,
    "sourceUrl": "https://ourairports.com/airports/FZAA/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=15.310026,-4.330778,15.316026,-4.324778",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    15.298026,
    -4.39775,
    15.4566,
    -4.312778
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
