// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Salamatu Audu", role: "Park caretaker", quotes: ["I keep Children Amusement tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Haruna Garba", role: "Morning walker", quotes: ["I walk through Children Amusement before work.", "Fresh air first, then the day."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Samaila Tanko", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Naomi Adamu", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Salamatu Jatau", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Haruna Musa", role: "Patient's relative", quotes: ["I am waiting with a relative at Federal Medical Centre.", "Everyone here is patient, so I must be too."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Samaila Danjuma", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Naomi Ishaku", role: "Patient's relative", quotes: ["I am waiting with a relative at Kogi State Specialist Hospital, Lokoja.", "Everyone here is patient, so I must be too."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Salamatu Pam", role: "Student", quotes: ["I am on my way to a lecture at Federal University Lokoja.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Haruna Bako", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Samaila Garba", role: "Museum guide", quotes: ["Welcome to Lokoja National Museum. Please take your time.", "Ask me if you want to know what is on display."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Naomi Bulus", role: "Visitor", quotes: ["I came to Lokoja National Museum to learn something new.", "Read the labels slowly. They reward you."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Salamatu Adamu", role: "Site guide", quotes: ["Welcome to Maigari's Palace. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Haruna Gyang", role: "Local resident", quotes: ["I walk past Maigari's Palace most days.", "Visitors often stop here for photographs."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Samaila Musa", role: "Mosque caretaker", quotes: ["Welcome to Lokoja Central Masjid. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Naomi Ibrahim", role: "Regular worshipper", quotes: ["I have prayed at Lokoja Central Masjid for a long time.", "Come in quietly, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Salamatu Ishaku", role: "Mosque caretaker", quotes: ["Welcome to Central Mosque. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Haruna Dung", role: "Regular worshipper", quotes: ["I have prayed at Central Mosque for a long time.", "Come in quietly, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Samaila Bako", role: "Church volunteer", quotes: ["Welcome to Anglican church. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Naomi Yohanna", role: "Regular worshipper", quotes: ["I have worshipped at Anglican church for a long time.", "Sit anywhere there is room, and be welcome."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Salamatu Bulus", role: "Market trader", quotes: ["Looking for Grains and vegetables? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Haruna Gambo", role: "Shopper", quotes: ["Wikipedia says the essential products sold in the three major Lokoja markets are grains, vegetables and general household items.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Samaila Gyang", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Naomi Audu", role: "Supporter", quotes: ["I come to Lokoja International Stadium for the football.", "Sit high up and you see the whole game."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Salamatu Ibrahim", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Haruna Tanko", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
