// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-1379,"z":1332})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-693.2811473764805,"maxX":52.46355435014448,"minZ":-1041.5489988481918,"maxZ":57.48060157875966})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"lokoja":{"lon":6.44850535,"lat":8.25882455}})
