// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildOgunContent } from '../ogun/contentBuilder.ts'
import { SAGAMU_LEGACY_RECIPE } from './recipe.ts'

export const SAGAMU_CONTENT = buildOgunContent(SAGAMU_LEGACY_RECIPE.content)
