// Generated by scripts/city/build-city.ts. Do not edit by hand.
import type { CityModuleRules, LgaDefinition } from '../../../types/content.ts'
import { OGUN_RULES_BASE } from '../ogun/rules.ts'
import { SAGAMU_LEGACY_RECIPE } from './recipe.ts'

export type SagamuLocalGovernmentId = "sagamu" | "ikenne" | "remo-north"
export type SagamuDistrictId = "sagamu-centre" | "ilisan" | "ikenne-town"
export type SagamuHubId = "sagamu-interchange"
type Seed = Omit<LgaDefinition, 'id' | 'districts' | 'beta'> & { id: SagamuLocalGovernmentId; districts?: SagamuDistrictId[] }
const seeds = [{"id":"sagamu","name":"Sagamu","zone":"mainland","land":90000,"districts":["sagamu-centre"]},{"id":"ikenne","name":"Ikenne","zone":"mainland","land":70000,"districts":["ilisan","ikenne-town"]},{"id":"remo-north","name":"Remo North","zone":"mainland","land":55000}] satisfies Seed[]

export const SAGAMU_LGAS = Object.freeze(seeds.map(unit => Object.freeze({ beta: true as const, districts: [], ...unit })))
export const SAGAMU_MAP_ORIGIN = Object.freeze({ ...SAGAMU_LEGACY_RECIPE.rules.mapOrigin })
const legacy = SAGAMU_LEGACY_RECIPE.rules

export const SAGAMU_RULES = Object.freeze({
  ...OGUN_RULES_BASE,
  id: SAGAMU_LEGACY_RECIPE.id, name: legacy.name, units: SAGAMU_LGAS,
  hub: legacy.hub,
  rentedHomeIds: legacy.rentedHomeIds, defaultRentedHome: legacy.defaultRentedHome,
  atlas: legacy.atlas,
  mapOrigin: SAGAMU_MAP_ORIGIN,
  districts: legacy.districts,
  hubs: legacy.hubs,
  links: legacy.links,
} satisfies CityModuleRules<'sagamu', 'ogun', SagamuLocalGovernmentId, SagamuDistrictId, SagamuHubId>)
