import { createHash } from 'node:crypto';
import { lstat, opendir, readFile, realpath } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const PRODUCT = 'natural-earth-admin1-partitions-v1';
const LIMIT = Object.freeze({ source: 64 * 1024 * 1024, parent: 16 * 1024 * 1024, logical: 96 * 1024 * 1024,
  tree: 128 * 1024 * 1024, entries: 2048, depth: 5, manifest: 256 * 1024, report: 2 * 1024 * 1024,
  global: 2 * 1024 * 1024, country: 256 * 1024, partition: 1024 * 1024, positions: 3_000_000,
  featurePositions: 100_000, units: 10_000, countries: 10_000, partitions: 512, duration: 120_000, rss: 512 * 1024 * 1024 });
const HEX64 = /^[a-f0-9]{64}$/;
const SHA = (v: Uint8Array | string): string => createHash('sha256').update(v).digest('hex');
const gitBlob = (v: Uint8Array): string => createHash('sha1').update(`blob ${v.byteLength}\0`).update(v).digest('hex');
const canonical = (v: unknown): string => {
  if (v === null || typeof v === 'string' || typeof v === 'boolean') return JSON.stringify(v);
  if (typeof v === 'number') { if (!Number.isFinite(v)) throw new TypeError('non-finite number'); return JSON.stringify(v); }
  if (Array.isArray(v)) return `[${v.map(canonical).join(',')}]`;
  if (v && typeof v === 'object') { const o = v as Record<string, unknown>; return `{${Object.keys(o).sort().map(k => `${JSON.stringify(k)}:${canonical(o[k])}`).join(',')}}`; }
  throw new TypeError('value is not canonical JSON');
};
function fail(message: string): never { throw new Error(`Admin1 independent verification: ${message}`); }
const obj = (v: unknown, label: string): Record<string, unknown> => { if (!v || typeof v !== 'object' || Array.isArray(v)) fail(`${label} must be an object`); return v as Record<string, unknown>; };
const exact = (o: Record<string, unknown>, keys: string[], label: string): void => { if (Object.keys(o).length !== keys.length || Object.keys(o).some(k => !keys.includes(k))) fail(`${label} field set is invalid`); };
const safeInt = (v: unknown, min: number, max: number, label: string): number => { if (!Number.isSafeInteger(v) || Number(v) < min || Number(v) > max) fail(`${label} is out of bounds`); return Number(v); };
const parse = (bytes: Uint8Array, label: string): unknown => { try { return JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes)) as unknown; } catch { return fail(`${label} is not fatal UTF-8 JSON`); } };
const jsonFile = (bytes: Uint8Array, newline: boolean, label: string): unknown => {
  const text = new TextDecoder('utf-8', { fatal: true }).decode(bytes);
  if (newline ? !text.endsWith('\n') || text.endsWith('\n\n') : text.endsWith('\n')) fail(`${label} newline policy mismatch`);
  const value = parse(bytes, label); const expected = `${canonical(value)}${newline ? '\n' : ''}`;
  if (text !== expected) fail(`${label} is not canonical JSON`); return value;
};
const sourceRecord = (value: unknown, label: string): Record<string, unknown> => {
  const s = obj(value, label); exact(s, ['id','url','release','license','attribution','sha256','bytes'], label);
  if (typeof s.id !== 'string' || !s.id || s.id.length>256 || /[\u0000-\u001f\u007f]/.test(s.id) || typeof s.url !== 'string' || !s.url || s.url.length>2048 || /[\u0000-\u001f\u007f]/.test(s.url) || typeof s.release !== 'string' || !s.release || s.release.length>256 || /[\u0000-\u001f\u007f]/.test(s.release) || typeof s.license !== 'string' || !s.license || s.license.length>512 || /[\u0000-\u001f\u007f]/.test(s.license) || typeof s.attribution !== 'string' || !s.attribution || s.attribution.length>2048 || /[\u0000-\u001f\u007f]/.test(s.attribution) || typeof s.sha256 !== 'string' || !HEX64.test(s.sha256)) fail(`${label} identity is invalid`);
  safeInt(s.bytes, 1, LIMIT.source, `${label}.bytes`); return s;
};
const inside = (root: string, child: string): boolean => { const r = path.relative(root, child); return r === '' || (r !== '..' && !r.startsWith(`..${path.sep}`) && !path.isAbsolute(r)); };
async function assertSafePath(root: string, target: string): Promise<void> {
  const base = path.resolve(root), absolute = path.resolve(target); if (!inside(base, absolute)) fail('path escapes repository root');
  const baseStat = await lstat(base); if (baseStat.isSymbolicLink() || !baseStat.isDirectory()) fail('verification root is not a canonical directory');
  const relative = path.relative(base, absolute); let cursor = base; const parts = relative ? relative.split(path.sep) : [];
  for (let i = 0; i < parts.length; i++) { cursor = path.join(cursor, parts[i]!); let st; try { st = await lstat(cursor); } catch (e) { if ((e as NodeJS.ErrnoException).code === 'ENOENT') fail(`required path is absent: ${path.relative(base, absolute)}`); throw e; }
    if (st.isSymbolicLink() || (i < parts.length - 1 && !st.isDirectory())) fail(`symlink or non-directory ancestor: ${cursor}`);
  }
}
async function readBounded(root: string, filename: string, max: number, total: { n: number } | null, label: string, aggregateLimit = LIMIT.logical): Promise<Uint8Array> {
  await assertSafePath(root, filename); const st = await lstat(filename); if (!st.isFile() || st.size > max) fail(`${label} is not a bounded regular file`);
  if (total && total.n + st.size > aggregateLimit) fail(`${label} aggregate byte ceiling exceeded`);
  const b = new Uint8Array(await readFile(filename)); if (b.byteLength !== st.size || b.byteLength > max) fail(`${label} changed or exceeded its bound during read`); if(total)total.n += b.byteLength; return b;
}
async function treeCheck(root: string): Promise<void> {
  await assertSafePath(path.dirname(root), root); let bytes = 0, entries = 0;
  const walk = async (dir: string, depth: number): Promise<void> => { if (depth > LIMIT.depth) fail('output tree depth exceeded'); const d = await opendir(dir); for await (const ent of d) {
    if (++entries > LIMIT.entries) fail('output tree entry ceiling exceeded'); const p = path.join(dir, ent.name), st = await lstat(p);
    if (st.isSymbolicLink()) fail('output tree contains symlink'); if (st.isDirectory()) await walk(p, depth + 1); else if (st.isFile()) { bytes += st.size; if (bytes > LIMIT.tree) fail('output tree byte ceiling exceeded'); } else fail('output tree contains non-regular entry');
  } }; await walk(root, 0);
}
const same = (a: unknown, b: unknown): boolean => canonical(a) === canonical(b);
function array(v: unknown, label: string): unknown[] { if (!Array.isArray(v)) fail(`${label} must be an array`); return v; }
function text(v: unknown, label: string): string { if (typeof v !== 'string') fail(`${label} must be text`); return v; }
const posCount = (geometry: unknown): { positions: number; polygons: number; holes: number; issue: string | null } => {
  let positions = 0, polygons = 0, holes = 0, issue: string | null = null;
  const g = geometry && typeof geometry === 'object' && !Array.isArray(geometry) ? geometry as Record<string, unknown> : null;
  if (!g) return {positions,polygons,holes,issue:'geometry-is-not-an-object'};
  const countRaw=(value:unknown):number=>{let count=0;const stack:unknown[]=[value];while(stack.length){const item=stack.pop();if(!Array.isArray(item))continue;if(item.length>=2&&typeof item[0]==='number'&&typeof item[1]==='number'&&item.every((v:unknown)=>typeof v==='number'))count++;else for(let i=item.length-1;i>=0;i--)stack.push(item[i]);}return count;};
  if (g.type !== 'Polygon' && g.type !== 'MultiPolygon') return {positions:countRaw(g.coordinates),polygons,holes,issue:'unsupported-geometry-type'};
  if (!Array.isArray(g.coordinates)) return {positions,polygons,holes,issue:'geometry-coordinates-not-array'};
  const polygonRows: unknown[] = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
  polygons = polygonRows.length; if (!polygonRows.length) issue='geometry-has-no-polygons';
  for (const rawPolygon of polygonRows) {
    if (!Array.isArray(rawPolygon) || !rawPolygon.length) { issue ??='polygon-has-no-rings'; continue; }
    for (let ringIndex=0;ringIndex<rawPolygon.length;ringIndex++) {
      const rawRing=rawPolygon[ringIndex]; if(!Array.isArray(rawRing)){issue ??='ring-is-not-array';continue;} if(ringIndex>0)holes++;
      const points:number[][]=[];
      for(const rawPosition of rawRing){positions++;if(!Array.isArray(rawPosition)||rawPosition.length<2||rawPosition.length>4||rawPosition.some((v:unknown)=>typeof v!=='number'||!Number.isFinite(v))){issue ??='position-is-not-finite-wgs84';continue;}const point=rawPosition as number[];if(point[0]! < -180||point[0]! > 180||point[1]! < -90||point[1]! > 90)issue ??='position-outside-wgs84';points.push(point);}
      if(rawRing.length<4)issue ??='ring-has-fewer-than-four-positions';
      const first=rawRing[0],last=rawRing.at(-1);if(!Array.isArray(first)||!Array.isArray(last)||canonical(first)!==canonical(last))issue ??='ring-is-not-closed';
      const unique=new Set(points.slice(0,-1).map(p=>`${p[0]},${p[1]}`));let twiceArea=0;const unwrapped:number[][]=[];
      if(points.length){unwrapped.push([points[0]![0]!,points[0]![1]!]);for(let i=1;i<points.length;i++){const prev=points[i-1]![0]!,raw=points[i]![0]!;let delta=raw-prev;if(delta>180)delta-=360;else if(delta< -180)delta+=360;unwrapped.push([unwrapped[i-1]![0]!+delta,points[i]![1]!]);}for(let i=0;i+1<unwrapped.length;i++)twiceArea+=unwrapped[i]![0]!*unwrapped[i+1]![1]!-unwrapped[i+1]![0]!*unwrapped[i]![1]!;}
      const winding=unwrapped.length?unwrapped.at(-1)![0]!-unwrapped[0]![0]!:0;const polarCap=Math.abs(Math.abs(winding)-360)<1e-6&&(points.slice(0,-1).every(p=>p[1]!>0)&&points.some(p=>p[1]!<90-1e-9)||points.slice(0,-1).every(p=>p[1]!<0)&&points.some(p=>p[1]!> -90+1e-9));
      if(unique.size<3||Math.abs(twiceArea)<1e-12&&!polarCap)issue ??='ring-is-degenerate';
    }
  }
  return {positions,polygons,holes,issue};
};
function sourceKey(feature: Record<string, unknown>): string { const p = obj(feature.properties, 'source properties'); const n=p.ne_id; if(typeof n==='number'){if(!Number.isSafeInteger(n)||n<1)fail('source NE_ID is invalid');}else if(typeof n==='string'){if(!/^[1-9][0-9]*$/.test(n)||!Number.isSafeInteger(Number(n))||String(Number(n))!==n)fail('source NE_ID string is not canonical');}else fail('source NE_ID is missing');return `NE_ID:${String(n)}`; }
function sourceText(v: unknown, label:string): string | null { if(v===null||v===undefined)return null;if(typeof v!=='string'||v.length>2048||/[\u0000-\u001f\u007f]/.test(v))fail(`${label} exceeds published index source-label bounds`);return v; }
function sourceLevel(v: unknown): number | null { if(v===null||v===undefined)return null;if(!Number.isSafeInteger(v)||Number(v)<-1||Number(v)>100)fail('source gadm_level exceeds published index bounds');return Number(v); }
function validateSourcePin(pin: unknown, root: string, capture: Record<string, unknown>): { source: Record<string, unknown>; gitBlobSha1: string; input: string } {
  const p = obj(pin, 'source pin'); exact(p, ['schemaVersion','source','input','gitBlobSha1'], 'source pin'); if (p.schemaVersion !== 1) fail('source pin schema invalid');
  const src = sourceRecord(p.source, 'Admin1 source'); if (typeof p.input !== 'string' || !p.input.startsWith('.cache/world-build/admin1-source-cache/') || !p.input.endsWith('.geojson') || typeof p.gitBlobSha1 !== 'string' || !/^[a-f0-9]{40}$/.test(p.gitBlobSha1)) fail('source pin path/blob invalid');
  const release = text(capture.release,'capture release');if(!/^[a-f0-9]{40}$/.test(release)||capture.metadataPath!=='.cache/world-build/evidence/admin1-resolution-research/source-api.json'||capture.license!=='Public-domain')fail('frozen capture source metadata is invalid');const artifact = 'geojson/ne_10m_admin_1_states_provinces.geojson';
  const expectedUrl = `https://raw.githubusercontent.com/nvkelso/natural-earth-vector/${release}/${artifact}`;
  const requestIdentity = { release, path: artifact, blob: p.gitBlobSha1, expectedBytes: capture.expectedBytes };
  const requestHash = SHA(canonical(requestIdentity));
  exact(capture,['schemaVersion','provider','release','resolution','metadataPath','metadataSha256','metadataBytes','expectedBytes','expectedGitBlobSha1','license','attribution'],'capture pin');
  if(capture.schemaVersion!==1||typeof capture.metadataSha256!=='string'||!HEX64.test(capture.metadataSha256)||typeof capture.expectedGitBlobSha1!=='string'||!/^[a-f0-9]{40}$/.test(capture.expectedGitBlobSha1))fail('capture pin hashes are invalid');
  safeInt(capture.metadataBytes,1,64*1024,'capture metadata bytes');safeInt(capture.expectedBytes,1,LIMIT.source,'captured source bytes');
  if (capture.provider !== 'natural-earth' || capture.resolution !== '10m' || src.id !== `natural-earth-admin1-10m-${release}` || src.release !== release || src.url !== expectedUrl || src.bytes !== capture.expectedBytes || src.license !== capture.license || src.attribution !== capture.attribution || p.gitBlobSha1 !== capture.expectedGitBlobSha1 || p.input !== `.cache/world-build/admin1-source-cache/${requestHash}.geojson`) fail('source pin does not match independently pinned Natural Earth artifact');
  const input = path.resolve(root, String(p.input)); if (!inside(path.join(root,'.cache','world-build'), input)) fail('source pin escapes builder cache');
  return { source: src, gitBlobSha1: String(p.gitBlobSha1), input: String(p.input) };
}

export interface Admin1VerificationRequest { repositoryRoot: string; manifestHash: string; sourcePinPath: string; parentPinPath: string }
export interface Admin1VerificationReceipt {
  schemaVersion: 1; product: typeof PRODUCT; manifestHash: string; sourceSha256: string; parentManifestHash: string;
  sourceUnits: number; sourcePositions: number; sourcePolygons: number; linkedUnits: number; protectedUnits: number;
  unlinkedUnits: number; ambiguousUnits: number; emittedUnits: number; exceptionUnits: number; partitions: number;
  countries: number; missingCountries: number; interiorRings: number; logicalBytesRead: number; assetsVerified: number; maxAssetBytes: number; elapsedMs: number; peakRssBytes: number; sourceLabelAudit:Record<string,{missing:number;blank:number;control:number;maxUtf8Bytes:number}>; sourceLevelDistribution:Array<{level:number|null;units:number}>;
  limitation: 'structural source fidelity only; no topology, official-boundary, currentness, recognition or playability claim';
}

/** Independent raw-source-to-publication verifier. It intentionally imports no project compiler or publisher code. */
export async function verifyAdmin1Product(request: Admin1VerificationRequest): Promise<Admin1VerificationReceipt> {
  const started = performance.now(), deadline = started + LIMIT.duration; let peakRssBytes=0; const check = (): void => { if (performance.now() > deadline) fail('120 second deadline exceeded'); const rss=process.memoryUsage().rss;peakRssBytes=Math.max(peakRssBytes,rss);if(rss>LIMIT.rss)fail('512 MiB RSS ceiling exceeded'); };
  if(!path.isAbsolute(request.repositoryRoot)||path.resolve(request.repositoryRoot)!==request.repositoryRoot)fail('repositoryRoot must be canonical and absolute');const root = await realpath(request.repositoryRoot);if(root!==request.repositoryRoot)fail('repositoryRoot resolves through a symlink or noncanonical path'); const out = path.join(root,'.cache/world-build/output/admin1-foundation');
  if (!HEX64.test(request.manifestHash)) fail('manifest hash must be lowercase SHA-256');
  if (request.sourcePinPath !== 'world/admin1-sources.json' || request.parentPinPath !== 'world/admin1-parent.json') fail('only frozen named source and parent pins are admitted');
  const pinBytes = {n:0}, parentBytes={n:0}, outputBytes={n:0};
  await assertSafePath(root,out);await treeCheck(out);
  const sourcePinBytes = await readBounded(root, path.resolve(root,request.sourcePinPath), 16*1024, pinBytes, 'source pin', 64*1024);
  const parentPinBytes = await readBounded(root, path.resolve(root,request.parentPinPath), 16*1024, pinBytes, 'parent pin', 64*1024);
  const captureBytes = await readBounded(root,path.join(root,'world/admin1-capture.json'),16*1024,pinBytes,'frozen source capture pin',64*1024);
  const capture = obj(parse(captureBytes,'capture pin'),'capture pin');
  const sp = obj(parse(sourcePinBytes,'source pin'),'source pin'); const pin = validateSourcePin(sp,root,capture);
  const src = pin.source; const sourcePath = path.resolve(root,pin.input); const raw = await readBounded(root,sourcePath,LIMIT.source,null,'source bytes');
  if (raw.length !== src.bytes || SHA(raw) !== src.sha256 || gitBlob(raw) !== pin.gitBlobSha1) fail('raw source bytes/SHA/Git blob differ from pinned source');check();
  const sourceDoc = obj(parse(raw,'raw source'),'raw source'); if(sourceDoc.type!=='FeatureCollection'||!Array.isArray(sourceDoc.features)||sourceDoc.features.length<1||sourceDoc.features.length>LIMIT.units) fail('raw source FeatureCollection invalid');
  const features = array(sourceDoc.features,'source features').map((x: unknown,i: number)=>{const f=obj(x,`feature ${i}`); if(f.type!=='Feature'||!f.properties)fail(`source feature ${i} malformed`); return f;});
  const ppin=obj(parse(parentPinBytes,'parent pin'),'parent pin'); exact(ppin,['manifestHash','directoryRoot','source','input'],'parent pin');
  if(typeof ppin.manifestHash!=='string'||!HEX64.test(ppin.manifestHash)||ppin.directoryRoot!=='.cache/world-build/output/country-inventory'||typeof ppin.input!=='string'||!/^\.cache\/world-build\/country-source-cache\/[a-f0-9]{64}\.geojson$/.test(ppin.input)) fail('parent pin invalid');
  const parentSrc=sourceRecord(ppin.source,'parent source');const release=String(src.release);if(parentSrc.license!=='Public-domain')fail('parent source license pin is not Public-domain');if(parentSrc.id!==`natural-earth-admin0-10m-${release}`||parentSrc.release!==release||parentSrc.url!==`https://raw.githubusercontent.com/nvkelso/natural-earth-vector/${release}/geojson/ne_10m_admin_0_countries.geojson`)fail('parent source is not the exact same-release Natural Earth Admin 0 artifact');const parentRaw=await readBounded(root,path.resolve(root,String(ppin.input)),LIMIT.parent,parentBytes,'parent source',16*1024*1024);
  if(parentRaw.length!==parentSrc.bytes||SHA(parentRaw)!==parentSrc.sha256)fail('parent source bytes differ from pin');check();
  const parentDoc=obj(parse(parentRaw,'parent raw source'),'parent source'); if(parentDoc.type!=='FeatureCollection'||!Array.isArray(parentDoc.features))fail('parent source is not FeatureCollection');check();
  const parentRoot=path.join(root,String(ppin.directoryRoot)); const parentManifestPath=path.join(parentRoot,`manifests/${ppin.manifestHash}.json`); const pmBytes=await readBounded(root,parentManifestPath,1_000_000,parentBytes,'parent manifest',16*1024*1024);
  const pm=obj(jsonFile(pmBytes,false,'parent manifest'),'parent manifest'); if(SHA(pmBytes)!==ppin.manifestHash) fail('parent manifest filename hash mismatch');
  exact(pm,['schemaVersion','compiler','source','baselineSource','baselineInventoryHash','sourceUnitCount','nodeCount','outlineCount','partCount','rootNodePath','identityPath','rollups','representation','limits','exceptions'],'parent manifest');sourceRecord(pm.baselineSource,'parent baseline source');if(pm.schemaVersion!==1||pm.compiler!=='country-directory-compiler-v1'||pm.representation!=='whole-polygon-groups'||typeof pm.baselineInventoryHash!=='string'||!HEX64.test(pm.baselineInventoryHash)||!same(pm.source,parentSrc)||pm.sourceUnitCount!== (parentDoc.features as unknown[]).length || typeof pm.rootNodePath!=='string'||typeof pm.identityPath!=='string')fail('parent manifest does not bind exact parent source');
  if(typeof pm.identityPath!=='string'||!/^identity\/[a-f0-9]{64}\.json$/.test(pm.identityPath)||typeof pm.rootNodePath!=='string'||!/^nodes\/[a-f0-9]{64}\.json$/.test(pm.rootNodePath))fail('parent root/identity content paths invalid');
  const parentIdentityPath=path.join(parentRoot,String(pm.identityPath)); const identityBytes=await readBounded(root,parentIdentityPath,256_000,parentBytes,'parent identity',16*1024*1024); if(SHA(identityBytes)!==path.basename(pm.identityPath,'.json'))fail('parent identity content hash mismatch'); const identity=obj(jsonFile(identityBytes,false,'parent identity'),'parent identity');
  exact(identity,['schemaVersion','baselineSourceId','candidateSourceId','baselineUnits','candidateUnits','retained','added','missing','protectedCountryId','exceptions'],'parent identity'); if(identity.schemaVersion!==1||identity.baselineSourceId!==obj(pm.baselineSource,'parent baseline source').id||identity.candidateSourceId!==parentSrc.id||identity.candidateUnits!==pm.sourceUnitCount||identity.baselineUnits!==array(identity.retained,'identity retained').length||Number(identity.candidateUnits)!==array(identity.retained,'identity retained').length+array(identity.added,'identity added').length||!Array.isArray(identity.retained)||!Array.isArray(identity.added)||!Array.isArray(identity.missing)||identity.missing.length!==0||identity.protectedCountryId!=='legacy-ng'||!Array.isArray(identity.exceptions)||identity.exceptions.length!==0)fail('parent identity sidecar is incomplete');
  safeInt(identity.baselineUnits,0,LIMIT.countries,'identity baseline units');safeInt(identity.candidateUnits,1,LIMIT.countries,'identity candidate units');const idmap=new Map<string,string>(); for(const r0 of [...array(identity.retained,'identity retained'),...array(identity.added,'identity added')]){const r=obj(r0,'identity row'); if(typeof r.featureKey!=='string'||typeof r.countryId!=='string'||idmap.has(r.featureKey))fail('parent identity key invalid/duplicated'); idmap.set(r.featureKey,r.countryId);}
  const nodeById=new Map<string,Record<string,unknown>>(),nodeRefs=new Set<string>(),seenPaths=new Set<string>(); const pending=[{rel:String(pm.rootNodePath),id:'world:earth',parent:null as string|null,expectedName:null as string|null}];
  while(pending.length){check();const task=pending.shift()!; if(seenPaths.has(task.rel)||nodeById.has(task.id))fail('parent hierarchy path/ID repeats');seenPaths.add(task.rel);if(!/^nodes\/[a-f0-9]{64}\.json$/.test(task.rel))fail('parent node path invalid');const b=await readBounded(root,path.join(parentRoot,task.rel),128_000,parentBytes,'parent node index',16*1024*1024);if(SHA(b)!==path.basename(task.rel,'.json'))fail('parent node content hash mismatch');const ix=obj(jsonFile(b,false,'parent node index'),'parent node index');exact(ix,['schemaVersion','node','outlineIndexPath','children'],'parent node index');if(ix.schemaVersion!==1)fail('parent node index schema invalid');const node=obj(ix.node,'node');exact(node,['id','parentId','name','kind','countryCode','bounds','sourceFeatureIds','provider','outline','exceptions'],'parent node');if(node.id!==task.id||node.parentId!==task.parent||(task.expectedName!==null&&node.name!==task.expectedName))fail('parent hierarchy mismatch');if(task.parent===null){if(node.kind!=='world')fail('parent root is not world');}else{const parentNode=nodeById.get(task.parent);if(!parentNode||parentNode.kind==='world'&&node.kind!=='continent'||parentNode.kind==='continent'&&node.kind!=='country'||parentNode.kind==='country')fail('parent hierarchy kinds are invalid');}nodeById.set(task.id,node);if(task.id==='world:earth'&&node.kind!=='world'||task.id!=='world:earth'&&node.kind==='world')fail('parent node kinds violate world hierarchy');if(node.kind==='country'){const refs=array(node.sourceFeatureIds,'country source refs');if(refs.length!==1||typeof refs[0]!=='string')fail('country node source reference invalid');nodeRefs.add(refs[0]);}if(!(ix.outlineIndexPath===null||typeof ix.outlineIndexPath==='string'&&/^outline-index\/[a-f0-9]{64}\.json$/.test(ix.outlineIndexPath))||node.kind!=='country'&&ix.outlineIndexPath!==null||node.id==='legacy-ng'&&ix.outlineIndexPath!==null||!Array.isArray(ix.children)||node.kind==='country'&&ix.children.length!==0)fail('node children invalid');for(const child0 of array(ix.children,'node children')){const child=obj(child0,'child');if(typeof child.id!=='string'||typeof child.path!=='string'||!/^nodes\/[a-f0-9]{64}\.json$/.test(child.path))fail('child reference invalid');if(typeof child.name!=='string')fail('parent child name missing');pending.push({rel:child.path,id:child.id,parent:task.id,expectedName:child.name});if(pending.length+nodeById.size>LIMIT.entries)fail('parent node count exceeds bound');}}
  const parentCountries=[...nodeById.values()].filter(n=>n.kind==='country'); if(nodeById.size!==pm.nodeCount||parentCountries.length!==pm.sourceUnitCount||idmap.size!==parentCountries.length||nodeRefs.size!==parentCountries.length)fail('parent country denominator mismatch');
  const parentFeatures=new Map<string,Record<string,unknown>>(), parentCodes=new Map<string,string[]>();
  for(const f0 of array(parentDoc.features,'parent features')){const f=obj(f0,'parent feature'),pr=obj(f.properties,'parent feature properties');const code=text(pr.ADM0_A3,'parent ADM0_A3'),ne=pr.NE_ID;if(!Number.isSafeInteger(ne)||Number(ne)<1)fail('parent source join NE_ID invalid');const key=`NE_ID:${String(ne)}`;if(parentFeatures.has(key))fail('duplicate parent source key');parentFeatures.set(key,f);const ids=parentCodes.get(code)??[];ids.push(key);parentCodes.set(code,ids);}
  if(parentFeatures.size!==parentCountries.length||idmap.size!==parentCountries.length)fail('parent identity/source unit cardinality mismatch');
  const parentCountryByCode=new Map<string,string[]>(); const mappedIdentity=new Set<string>();
  for(const n of parentCountries){let key:string;
    {const refs=array(n.sourceFeatureIds,'country refs');if(refs.length!==1||typeof refs[0]!=='string')fail('parent country must retain exact source reference');const prefix=`${String(parentSrc.id)}:`;if(!refs[0].startsWith(prefix))fail('parent country source reference has wrong provider');key=refs[0].slice(prefix.length);}
    if(!/^NE_ID:[1-9][0-9]*$/.test(key)||idmap.get(key)!==n.id||mappedIdentity.has(key)||(n.id!=='legacy-ng'&&n.id!==`country:natural-earth:${encodeURIComponent(key)}`)||(n.id==='legacy-ng'&&(n.countryCode!=='NG'||n.provider!=='legacy-ng'||n.outline!=='missing')))fail('parent identity map and node source refs disagree');mappedIdentity.add(key);
    const pf=parentFeatures.get(key);if(!pf)fail('parent feature key missing');const code=text(obj(pf.properties,'parent properties').ADM0_A3,'parent ADM0_A3');
    const matches=parentCountryByCode.get(code)??[];matches.push(String(n.id));parentCountryByCode.set(code,matches);
  }
  if(mappedIdentity.size!==idmap.size)fail('parent identity sidecar contains unbound candidate feature keys');
  const manifestPath=path.join(out,`manifests/${request.manifestHash}.json`);const mb=await readBounded(root,manifestPath,LIMIT.manifest,outputBytes,'Admin1 manifest');if(SHA(mb)!==request.manifestHash)fail('Admin1 manifest hash mismatch');
  const m=obj(jsonFile(mb,true,'Admin1 manifest'),'Admin1 manifest'); exact(m,['schemaVersion','product','source','parent','validation','sourceUnits','sourcePositions','sourcePolygons','linked','protected','unlinked','ambiguous','emittedUnits','exceptionUnits','inspection','globalIndex','partitions','countries','limitations'],'Admin1 manifest');
  if(!Array.isArray(m.limitations)||!m.limitations.every((x:unknown)=>typeof x==='string')||!m.limitations.some((x:unknown)=>typeof x==='string'&&/topology/i.test(x))||!m.limitations.some((x:unknown)=>typeof x==='string'&&/playable/i.test(x)))fail('manifest mandatory limitations are absent');if(m.schemaVersion!==1||m.product!==PRODUCT||!same(m.source,src)||!same(m.parent,{manifestHash:ppin.manifestHash,source:parentSrc})||!same(m.validation,{structural:'passed-with-explicit-exceptions',topology:'unverified'}))fail('Admin1 manifest identity/validation mismatch');
  const readAsset=async(ref0:unknown,folder:string,max:number,newline:boolean):Promise<{value:unknown,bytes:Uint8Array,path:string}>=>{const r=obj(ref0,'asset ref');exact(r,['path','sha256','bytes'],'asset ref');if(typeof r.path!=='string'||!new RegExp(`^${folder}/[a-f0-9]{64}\\.json$`).test(r.path)||r.sha256!==path.basename(r.path,'.json'))fail('asset path/hash is invalid');const b=await readBounded(root,path.join(out,r.path),max,outputBytes,r.path);if(b.length!==r.bytes||SHA(b)!==r.sha256)fail(`asset bytes/hash mismatch ${r.path}`);return{value:jsonFile(b,newline,r.path),bytes:b,path:r.path};};
  let maxAssetBytes=0;const report=await readAsset(m.inspection,'reports',LIMIT.report,true),global=await readAsset(m.globalIndex,'indexes',LIMIT.global,false);maxAssetBytes=Math.max(report.bytes.length,global.bytes.length); const reportSha=String(obj(m.inspection,'inspection ref').sha256); const rv=obj(report.value,'inspection report'); exact(rv,['schemaVersion','inspector','source','parent','sourceUnits','sourcePositions','sourcePolygons','linked','protected','unlinked','ambiguous','geometryExceptions','largestFeatureBytes','largestFeaturePositions','countries','missingCountries','rows','limitations'],'inspection report'); if(!Array.isArray(rv.limitations)||!rv.limitations.some((x:unknown)=>typeof x==='string'&&/structural WGS84/i.test(x))||!rv.limitations.some((x:unknown)=>typeof x==='string'&&/legal boundary/i.test(x))||!rv.limitations.some((x:unknown)=>typeof x==='string'&&/not playable content/i.test(x)))fail('inspection mandatory limitations are absent');if(rv.schemaVersion!==1||rv.inspector!=='natural-earth-admin1-structural-v1'||!same(rv.source,src)||!same(rv.parent,m.parent)||rv.sourceUnits!==features.length||!Array.isArray(rv.rows)||rv.rows.length!==features.length)fail('inspection report does not bind source or row count');
  const auditRows=new Map<number,Record<string,unknown>>(); const keyToRow=new Map<string,Record<string,unknown>>(); let previousAuditKey=''; for(const r0 of array(rv.rows,'inspection rows')){const r=obj(r0,'report row');exact(r,['sourceOrdinal','sourceKey','id','featureSha256','adm0Code','countryId','joinStatus','positions','polygons','featureBytes','propertiesBytes','geometryIssue'],'inspection row');safeInt(r.sourceOrdinal,0,features.length-1,'source ordinal');if(auditRows.has(Number(r.sourceOrdinal))||typeof r.sourceKey!=='string'||keyToRow.has(r.sourceKey)||previousAuditKey!==''&&previousAuditKey>=r.sourceKey)fail('duplicate/unsorted inspection row');previousAuditKey=r.sourceKey;auditRows.set(Number(r.sourceOrdinal),r);keyToRow.set(r.sourceKey,r);}
  const sourceUnits=features.length;let sourcePositions=0,sourcePolygons=0,holes=0,largestFeatureBytes=0,largestFeaturePositions=0; const sourceRows:Record<string,unknown>[]=[]; const seenKeys=new Set<string>(); const ordinalByKey=new Map<string,number>();
  for(let i=0;i<features.length;i++){check();const f=features[i]!,key=sourceKey(f),metrics=posCount(f.geometry);if(seenKeys.has(key))fail('source key is duplicated');seenKeys.add(key);ordinalByKey.set(key,i);sourcePositions+=metrics.positions;sourcePolygons+=metrics.polygons;holes+=metrics.holes;largestFeatureBytes=Math.max(largestFeatureBytes,Buffer.byteLength(canonical(f)));largestFeaturePositions=Math.max(largestFeaturePositions,metrics.positions);const row=keyToRow.get(key);const featureBody=canonical(f),properties=obj(f.properties,'source properties'),propertiesBody=canonical(properties),expectedIssue=metrics.issue??(metrics.positions>LIMIT.featurePositions?'feature-position-limit':null);if(!row||row.sourceOrdinal!==i||row.id!==`admin1:natural-earth:${encodeURIComponent(key)}`||row.featureSha256!==SHA(featureBody)||row.positions!==metrics.positions||row.polygons!==metrics.polygons||row.featureBytes!==Buffer.byteLength(featureBody)||row.propertiesBytes!==Buffer.byteLength(propertiesBody)||row.geometryIssue!==expectedIssue)fail(`inspection does not faithfully bind source feature ${i}`);const rawCode=properties.adm0_a3,code=typeof rawCode==='string'&&rawCode.length<=32?rawCode:null,matches=code?parentCountryByCode.get(code)??[]:[];let expectedJoin:string='unlinked',expectedCountry:string|null=null;if(code==='NGA')expectedJoin='protected';else if(code&&/^[A-Z]{3}$/.test(code)){if(matches.length>1)expectedJoin='ambiguous';else if(matches.length===1){if(matches[0]==='legacy-ng')expectedJoin='protected';else{expectedJoin='linked';expectedCountry=matches[0]!;}}}if(row.adm0Code!==code||row.joinStatus!==expectedJoin||row.countryId!==expectedCountry)fail(`inspection parent join is not exact for source feature ${i}`);sourceRows.push(row);}
  check();if(sourcePositions>LIMIT.positions||sourcePositions!==rv.sourcePositions||sourcePolygons!==rv.sourcePolygons||rv.largestFeatureBytes!==largestFeatureBytes||rv.largestFeaturePositions!==largestFeaturePositions)fail('source aggregate geometry counts mismatch');
  const globalRows=parseCanonicalArray(global.value,'global index');if(globalRows.length!==sourceUnits)fail('global index denominator mismatch');const entryByOrdinal=new Map<number,Record<string,unknown>>();let previousGlobalKey='';for(const e0 of globalRows){const e=obj(e0,'global index row');exact(e,['sourceOrdinal','sourceKey','id','featureSha256','countryId','joinStatus','partitionPath','exception'],'global index row');if(typeof e.sourceKey!=='string'||previousGlobalKey!==''&&previousGlobalKey>=e.sourceKey)fail('global index source keys are unsorted');previousGlobalKey=e.sourceKey;const ordinal=safeInt(e.sourceOrdinal,0,sourceUnits-1,'index ordinal');if(entryByOrdinal.has(ordinal))fail('duplicate global index ordinal');if(!(e.partitionPath===null||typeof e.partitionPath==='string'&&/^partitions\/[a-f0-9]{64}\.json$/.test(e.partitionPath))||!(e.exception===null||typeof e.exception==='string'))fail('global index path/exception invalid');if(typeof e.partitionPath==='string'&&e.exception!==null||e.partitionPath===null&&e.exception===null)fail('global index must describe exactly one geometry or exception');const audit=auditRows.get(ordinal)!;for(const k of ['sourceKey','id','featureSha256','countryId','joinStatus'])if(e[k]!==audit[k])fail(`global index and inspection mismatch at ${ordinal}`);entryByOrdinal.set(ordinal,e);}
  if(!Array.isArray(m.partitions)||m.partitions.length>LIMIT.partitions||!Array.isArray(m.countries)||m.countries.length!==parentCountries.length)fail('manifest partition/country denominator invalid');
  const partitionFeatures=new Set<number>();const partitionPaths=new Set<string>();let emitted=0;
  for(const ref of array(m.partitions,'partitions')){const a=await readAsset(ref,'partitions',LIMIT.partition,false),p=obj(a.value,'partition');maxAssetBytes=Math.max(maxAssetBytes,a.bytes.length);exact(p,['schemaVersion','product','parentCountryId','joinStatus','features'],'partition');if(p.schemaVersion!==1||p.product!==PRODUCT||!Array.isArray(p.features)||p.features.length<1||p.features.length>64)fail('partition schema/count invalid');if(partitionPaths.has(a.path))fail('partition ref is duplicated');partitionPaths.add(a.path);let partitionPositions=0,previousPartitionKey='';for(const f0 of array(p.features,'partition features')){const f=obj(f0,'partition feature'),key=sourceKey(f),ord=ordinalByKey.get(key)??-1;if(previousPartitionKey!==''&&previousPartitionKey>=key)fail('partition features are not source-key sorted');previousPartitionKey=key;if(ord<0||partitionFeatures.has(ord)||!same(f,features[ord]))fail('partition feature differs from exact source feature or repeats');const e=entryByOrdinal.get(ord)!;if(e.partitionPath!==a.path)fail('partition path does not match global index');const audit=auditRows.get(ord)!;if(p.parentCountryId!==audit.countryId||p.joinStatus!==audit.joinStatus)fail('partition join differs from inspection');partitionPositions+=posCount(features[ord]!.geometry).positions;if(partitionPositions>150_000)fail('partition positions exceed 150000');partitionFeatures.add(ord);emitted++;}}
  const countriesById=new Map<string,Record<string,unknown>>();let previousCountryId='';for(const c0 of array(m.countries,'country refs')){const c=obj(c0,'country ref');exact(c,['countryId','status','sourceUnits','emittedUnits','index'],'country ref');if(typeof c.countryId!=='string'||countriesById.has(c.countryId)||previousCountryId!==''&&previousCountryId>=c.countryId)fail('duplicate country ref');previousCountryId=c.countryId;countriesById.set(c.countryId,c);}
  const protectedNode=parentCountries.find(n=>n.id==='legacy-ng');if(!protectedNode||protectedNode.provider!=='legacy-ng')fail('parent protected Nigeria identity absent');
  const countryAssets=new Map<string,unknown>();const indexedOrdinals=new Set<number>();const availableCountries=new Set<string>();let missingCountries=0;
  for(const node of parentCountries){const cr=countriesById.get(String(node.id));if(!cr)fail('parent country omitted from manifest');if(node.id==='legacy-ng'){const protectedUnits=sourceRows.filter(r=>r.joinStatus==='protected').length;if(cr.status!=='protected'||cr.index!==null||cr.sourceUnits!==protectedUnits||cr.emittedUnits!==0)fail('Nigeria must remain protected without index');continue;}if(cr.status==='missing'){missingCountries++;if(sourceRows.some(r=>r.countryId===node.id&&r.joinStatus==='linked'))fail('country with linked emitted source rows is marked missing');if(cr.index!==null||cr.sourceUnits!==0||cr.emittedUnits!==0)fail('missing parent source unit has output');continue;}if(cr.status!=='available'||!cr.index)fail('linked parent country has no index');safeInt(cr.sourceUnits,1,sourceUnits,'country ref sourceUnits');const a=await readAsset(cr.index,'countries',LIMIT.country,true),ix=obj(a.value,'country index');maxAssetBytes=Math.max(maxAssetBytes,a.bytes.length);exact(ix,['schemaVersion','product','countryId','sourceSha256','parentManifestHash','inspectionSha256','sourceUnits','emittedUnits','rows'],'country index');availableCountries.add(String(node.id));if(cr.sourceUnits!==ix.sourceUnits||cr.emittedUnits!==ix.emittedUnits||safeInt(ix.sourceUnits,1,sourceUnits,'country index sourceUnits')<1||ix.schemaVersion!==1||ix.product!==PRODUCT||ix.countryId!==node.id||ix.sourceSha256!==src.sha256||ix.parentManifestHash!==ppin.manifestHash||ix.inspectionSha256!==reportSha)fail('country index source/parent/inspection binding mismatch'); countryAssets.set(String(node.id),ix);}
  // Country index entries bind every linked emitted row and copy only bounded source labels.
  for(const [countryId,ix0] of countryAssets){const ix=obj(ix0,'country index');if(!Array.isArray(ix.rows)||ix.sourceUnits!==ix.rows.length||!Number.isSafeInteger(ix.emittedUnits)||Number(ix.emittedUnits)<0||Number(ix.emittedUnits)>ix.sourceUnits)fail('country index row counts invalid');const rows=ix.rows as unknown[];let previousKey='';let emittedIndexRows=0;for(const r0 of rows){const r=obj(r0,'country index row');exact(r,['sourceOrdinal','sourceKey','id','featureSha256','countryId','joinStatus','partitionPath','exception','name','sourceType','sourceTypeEn','gadmLevel','positions','polygons'],'country index row');const ord=safeInt(r.sourceOrdinal,0,sourceUnits-1,'country index ordinal');if(typeof r.sourceKey!=='string'||previousKey!==''&&previousKey>=r.sourceKey)fail('country index source keys unsorted');previousKey=r.sourceKey;const sr=features[ord]!,pr=obj(sr.properties,'source properties'),e=entryByOrdinal.get(ord)!,metric=posCount(sr.geometry);if(indexedOrdinals.has(ord)||e.joinStatus!=='linked'||e.countryId!==countryId||(typeof e.partitionPath==='string'&&!partitionFeatures.has(ord))||r.sourceKey!==sourceKey(sr)||r.featureSha256!==SHA(canonical(sr))||r.id!==e.id||r.partitionPath!==e.partitionPath||r.exception!==e.exception||r.positions!==metric.positions||r.polygons!==metric.polygons||r.name!==sourceText(pr.name,'name')||r.sourceType!==sourceText(pr.type,'type')||r.sourceTypeEn!==sourceText(pr.type_en,'type_en')||r.gadmLevel!==sourceLevel(pr.gadm_level))fail('country index row diverges from exact source feature');indexedOrdinals.add(ord);if(typeof e.partitionPath==='string')emittedIndexRows++;}if(ix.emittedUnits!==emittedIndexRows)fail('country index emitted row count mismatch');}
  const reportCountries=array(rv.countries,'inspection countries').map((x:unknown)=>obj(x,'inspection country'));const linkedCounts=new Map<string,number>(),levelCounts=new Map<number|null,number>();const sourceLabelAudit:Record<string,{missing:number;blank:number;control:number;maxUtf8Bytes:number}>={name:{missing:0,blank:0,control:0,maxUtf8Bytes:0},type:{missing:0,blank:0,control:0,maxUtf8Bytes:0},type_en:{missing:0,blank:0,control:0,maxUtf8Bytes:0}};for(const feature of features){const props=obj(feature.properties,'source properties'),level=sourceLevel(props.gadm_level);levelCounts.set(level,(levelCounts.get(level)??0)+1);for(const field of ['name','type','type_en']){const value=props[field],stat=sourceLabelAudit[field]!;if(value===null||value===undefined)stat.missing++;else if(typeof value==='string'){const bytes=Buffer.byteLength(value);stat.maxUtf8Bytes=Math.max(stat.maxUtf8Bytes,bytes);if(value.length===0)stat.blank++;if(/[\u0000-\u001f\u007f]/.test(value))stat.control++;}else fail(`source label ${field} is not text`);}}for(const row of sourceRows)if(row.joinStatus==='linked'&&typeof row.countryId==='string')linkedCounts.set(row.countryId,(linkedCounts.get(row.countryId)??0)+1);if(reportCountries.length!==linkedCounts.size)fail('inspection country rollup count mismatch');for(let j=0;j<reportCountries.length;j++){const c=reportCountries[j]!;exact(c,['countryId','units'],'inspection country rollup');if(typeof c.countryId!=='string'||c.units!==linkedCounts.get(c.countryId)||j>0&&String(reportCountries[j-1]!.countryId)>=c.countryId)fail('inspection country rollup does not match exact joins');}const expectedMissing=parentCountries.filter(n=>n.id!=='legacy-ng'&&!linkedCounts.has(String(n.id))).map(n=>String(n.id)).sort();const reportMissing=array(rv.missingCountries,'inspection missing countries');if(reportMissing.length!==expectedMissing.length||reportMissing.some((v,i)=>v!==expectedMissing[i]))fail('inspection missing-country denominator mismatch');
  if(array(rv.rows,'inspection rows').filter(x=>obj(x,'inspection row').geometryIssue!==null).length!==rv.geometryExceptions)fail('inspection geometry exception counter mismatch');
  for(const row of sourceRows)if(row.joinStatus==='linked'&&typeof row.countryId==='string'&&!availableCountries.has(row.countryId))fail('linked country source rows lack an available index');
  for(let i=0;i<sourceUnits;i++){const e=entryByOrdinal.get(i)!;if(e.joinStatus==='linked'&&typeof e.countryId==='string'&&!indexedOrdinals.has(i))fail('linked source feature is missing from its country index');}
  for(let i=0;i<sourceUnits;i++){const entry=entryByOrdinal.get(i)!,row=auditRows.get(i)!,feature=features[i]!,properties=obj(feature.properties,'source properties');let expectedException:string|null=null;if(row.joinStatus==='protected')expectedException='protected-nigeria-no-geometry';else if(row.geometryIssue)expectedException=String(row.geometryIssue);else if(Buffer.byteLength(canonical(properties))>16*1024)expectedException='properties-byte-limit';else{const envelope={schemaVersion:1,product:PRODUCT,parentCountryId:row.countryId,joinStatus:row.joinStatus,features:[feature]};if(Buffer.byteLength(canonical(envelope))>LIMIT.partition)expectedException='asset-byte-limit';}if(expectedException){if(entry.partitionPath!==null||entry.exception!==expectedException)fail('source feature exception does not match independently recomputed source limits');}else if(typeof entry.partitionPath!=='string'||entry.exception!==null||!partitionFeatures.has(i))fail('source feature silently omitted or not faithfully partitioned');}
  const count=(k:string):number=>safeInt(m[k],0,k==='sourcePositions'?LIMIT.positions:k==='sourcePolygons'?LIMIT.positions:sourceUnits,k); if(count('sourceUnits')!==sourceUnits||count('sourcePositions')!==sourcePositions||count('sourcePolygons')!==sourcePolygons||count('emittedUnits')!==emitted||count('exceptionUnits')!==sourceUnits-emitted)fail('manifest output counters do not conserve');
  const derived={linked:sourceRows.filter(r=>r.joinStatus==='linked').length,protected:sourceRows.filter(r=>r.joinStatus==='protected').length,unlinked:sourceRows.filter(r=>r.joinStatus==='unlinked').length,ambiguous:sourceRows.filter(r=>r.joinStatus==='ambiguous').length};if(count('linked')!==derived.linked||count('protected')!==derived.protected||count('unlinked')!==derived.unlinked||count('ambiguous')!==derived.ambiguous||rv.linked!==derived.linked||rv.protected!==derived.protected||rv.unlinked!==derived.unlinked||rv.ambiguous!==derived.ambiguous||count('linked')+count('protected')+count('unlinked')+count('ambiguous')!==sourceUnits)fail('manifest join counters do not conserve');
  check();
  return {schemaVersion:1,product:PRODUCT,manifestHash:request.manifestHash,sourceSha256:src.sha256,parentManifestHash:String(ppin.manifestHash),sourceUnits,sourcePositions,sourcePolygons,linkedUnits:count('linked'),protectedUnits:count('protected'),unlinkedUnits:count('unlinked'),ambiguousUnits:count('ambiguous'),emittedUnits:emitted,exceptionUnits:sourceUnits-emitted,partitions:m.partitions.length,countries:parentCountries.length,missingCountries,interiorRings:holes,logicalBytesRead:outputBytes.n,assetsVerified:partitionPaths.size+countryAssets.size+3,maxAssetBytes,elapsedMs:Math.round(performance.now()-started),peakRssBytes,sourceLabelAudit,sourceLevelDistribution:[...levelCounts.entries()].sort((a,b)=>(a[0]??-Infinity)-(b[0]??-Infinity)).map(([level,units])=>({level,units})),limitation:'structural source fidelity only; no topology, official-boundary, currentness, recognition or playability claim'};
}
function parseCanonicalArray(value:unknown,label:string):Record<string,unknown>[] { return array(value,label).map((v:unknown)=>obj(v,label)); }

if (process.argv[1] && fileURLToPath(import.meta.url)===path.resolve(process.argv[1])) {
  const args=process.argv.slice(2); const readArg=(name:string):string=>{const i=args.indexOf(name);if(i<0||!args[i+1])throw new Error(`required named option ${name}`);return args[i+1]!;};
  void verifyAdmin1Product({repositoryRoot:process.cwd(),manifestHash:readArg('--manifest-hash'),sourcePinPath:readArg('--source-pin'),parentPinPath:readArg('--parent-pin')}).then(x=>process.stdout.write(`${JSON.stringify(x)}\n`)).catch(e=>{process.stderr.write(`${e instanceof Error?e.message:String(e)}\n`);process.exitCode=1;});
}
