// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "nouakchott",
  "name": "Nouakchott",
  "country": {
    "idISOlower": "mr",
    "name": "Mauritania"
  },
  "state": {
    "idunique": "mr-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Nouakchott",
  "centre": {
    "lon": -15.97534,
    "lat": 18.086427
  },
  "airport": {
    "id": "nouakchott-airport",
    "name": "Nouakchott–Oumtounsy International Airport",
    "lon": -15.969722,
    "lat": 18.31,
    "sourceUrl": "https://ourairports.com/airports/GQNO/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-15.97834,18.083427,-15.97234,18.089427",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -15.99034,
    18.071427,
    -15.957722,
    18.322
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
