// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "conakry",
  "name": "Conakry",
  "country": {
    "idISOlower": "gn",
    "name": "Guinea"
  },
  "state": {
    "idunique": "gn-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Conakry",
  "centre": {
    "lon": -13.682181,
    "lat": 9.533469
  },
  "airport": {
    "id": "conakry-airport",
    "name": "Ahmed Sékou Touré International Airport",
    "lon": -13.612,
    "lat": 9.57689,
    "sourceUrl": "https://ourairports.com/airports/GUCY/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-13.685181,9.530469,-13.679181,9.536469",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -13.697181,
    9.518469,
    -13.6,
    9.58889
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
