// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "bangui",
  "name": "Bangui",
  "country": {
    "idISOlower": "cf",
    "name": "Central African Republic"
  },
  "state": {
    "idunique": "cf-zone",
    "name": "Starter"
  },
  "timezone": "Africa/Bangui",
  "centre": {
    "lon": 18.558288,
    "lat": 4.366644
  },
  "airport": {
    "id": "bangui-airport",
    "name": "Bangui M'Poko International Airport",
    "lon": 18.518801,
    "lat": 4.39848,
    "sourceUrl": "https://ourairports.com/airports/FEFF/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=18.555288,4.363644,18.561288,4.369644",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    18.506801,
    4.351644,
    18.573288,
    4.41048
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
