// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Rose Ugbe", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Terhemba Idoko", role: "Supporter", quotes: ["I come to Aper Aku Stadium for the football.", "Sit high up and you see the whole game."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aondover Igbe", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Doosuur Shima", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Rose Gbilla", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Terhemba Ode", role: "Patient's relative", quotes: ["I am waiting with a relative at Benue State University Teaching Hospital.", "Everyone here is patient, so I must be too."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aondover Ejeh", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Doosuur Tarkaa", role: "Patient's relative", quotes: ["I am waiting with a relative at Federal Medical Centre Makurdi.", "Everyone here is patient, so I must be too."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Rose Akaahan", role: "Student", quotes: ["I am on my way to a lecture at Benue State University.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Terhemba Ugbe", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aondover Ogbu", role: "Student", quotes: ["I am on my way to a lecture at University of Agriculture, Makurdi.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Doosuur Igbe", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Rose Ayila", role: "Site guide", quotes: ["Welcome to Dajo Pottery. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Terhemba Gbilla", role: "Local resident", quotes: ["I walk past Dajo Pottery most days.", "Visitors often stop here for photographs."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aondover Agbo", role: "Mosque caretaker", quotes: ["Welcome to Makurdi Central Mosque. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Doosuur Ejeh", role: "Regular worshipper", quotes: ["I have prayed at Makurdi Central Mosque for a long time.", "Come in quietly, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Rose Mbaka", role: "Church volunteer", quotes: ["Welcome to First Baptist Church Makurdi. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Terhemba Akaahan", role: "Regular worshipper", quotes: ["I have worshipped at First Baptist Church Makurdi for a long time.", "Sit anywhere there is room, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aondover Ityavyar", role: "Church volunteer", quotes: ["Welcome to Our Lady of Perpetual Help Cathedral. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Doosuur Ogbu", role: "Regular worshipper", quotes: ["I have worshipped at Our Lady of Perpetual Help Cathedral for a long time.", "Sit anywhere there is room, and be welcome."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Rose Ochai", role: "Market trader", quotes: ["Looking for Fresh farm produce? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Terhemba Ayila", role: "Shopper", quotes: ["Nigeria Galleria says farmers bring raw produce to Wurukum market and that North Bank Market sells fresh farm produce and food items.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aondover Tsav", role: "Market trader", quotes: ["Looking for Fresh farm produce? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Doosuur Agbo", role: "Shopper", quotes: ["Nigeria Galleria says farmers bring raw produce to Wurukum market and that North Bank Market sells fresh farm produce and food items.", "Take your time, and bargain with a smile."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Rose Idoko", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Terhemba Mbaka", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aondover Shima", role: "Cook", quotes: ["Today the pot at Golden Plate Restaurant holds Pounded Yam.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Doosuur Ityavyar", role: "Regular diner", quotes: ["I come to Golden Plate Restaurant for Pounded Yam.", "The NICO Benue State cuisine list names Pounded Yam first among Benue dishes."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
