// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":589,"z":1412})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-165.6446068460741,"maxX":196.92666135540549,"minZ":-134.79451646908092,"maxZ":199.29454914005532})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"makurdi":{"lon":8.53845296487209,"lat":7.6622455087624335}})
