// Moments that belong to one city. They fit any place in it unless a line names a place kind too.
// Hausa, Yoruba, Igbo and Efik lines carry `lang`, which marks them beta until a native speaker has reviewed them. Dishes, crafts and
// greetings stay inside what docs/CITIES-*.md and each city's spec already source; anything else is colour, not a fact.
import { AFTERNOON, DAWN, EVENING, LATE, MORNING, NIGHT, bank } from './bank.ts'
import type { Moment } from './types.ts'

const city = (id: string): { weight: number; cityIds: string[] } => ({ weight: 3, cityIds: [id] })

export const CITY_MOMENTS: Moment[] = [
  ...bank('lagos', city('lagos'), [
    'The conductor shouts the last stop twice. The driver, once.',
    'Okada, keke, danfo: all of them with right of way.',
    'Lagoon wind carries fish and engine smell.',
    ['Hawkers weave through the go-slow: gala, water, phone chargers.', { fx: 'crowd' }],
    'Everybody is running to be somewhere.',
    '“E go be!” says a stranger, kindly.',
    ['Generators: the city’s night chorus.', { ...LATE, fx: 'power-on' }],
    'The bridge is crawling. Bring snacks.',
    'Owambe weekend: aso ebi fabric in every colour.',
    'Lagos has two speeds: danfo and park.',
    '“Avoid the bridge,” says the traffic radio. “Which bridge?” says everybody.',
    'Island glass, mainland grit: same city, different weather.',
    ['A vendor crosses a sea of cars with plantain chips.', { fx: 'crowd' }],
    '“How far?” “I dey.” The city moves on.',
    ['The hustle never sleeps. It only changes shifts.', NIGHT],
    ['A rooster, a generator and a horn: Lagos morning, complete.', { ...DAWN, fx: 'horn' }],
    ['Rain and flood arrive together. Expect wet shoes.', { cond: 'rain', fx: 'rain' }],
    'The yellow danfo is painted with black stripes and stuffed with stories.',
    'Someone is sure there is a shortcut. There is not.',
    ['The bus stops fill up as if something is being given away.', EVENING],
  ]),
  ...bank('ibadan', city('ibadan'), [
    'Rusted brown roofs roll down the hills like a sea.',
    'Amala, gbegiri and ewedu: the smell of a good decision.',
    ['“Ẹ káàbọ̀!” A shopkeeper welcomes a stranger.', { lang: 'yo' }],
    ['“Ẹ kú àárọ̀ o!” rolls along the street.', { lang: 'yo', ...MORNING }],
    ['“Ẹ kú ìrọ̀lẹ́,” says an elder, to everyone.', { lang: 'yo', ...EVENING }],
    'Old city, young crowd, loud opinions.',
    'On the hill roads the danfo engines work harder than the passengers.',
    'Market sellers call out like a choir that never rehearsed.',
    'Red-earth dust on every shoe at the end of the day.',
    ['Smoke, chatter and plates: evening in a courtyard.', EVENING],
    'Someone is certain the hill road is faster. It is not.',
    ['A seller tops up a plate of amala and asks, “Is it enough?”', { ...AFTERNOON }],
  ]),
  ...bank('abuja', city('abuja'), [
    'Wide roads, quiet hills, very polite traffic.',
    'Aso Rock sits in the haze, big and unbothered.',
    'A planned city: every road ends in a roundabout.',
    ['Office workers file out towards the suya spots.', EVENING],
    'Drivers wait in the shade, phones in hand.',
    'Greetings fly in a dozen languages across one bus stop.',
    ['The hills keep the cool of the night a little longer.', DAWN],
    'Weekend: the city is half-empty and breathing.',
    ['Suya and kilishi smoke: dinner on a dry evening.', EVENING],
    ['Harmattan haze hides the hills today.', { season: { harmattan: true }, fx: 'dust' }],
    ['A clay pot, a potter and patience: Gbagyi craft at work.', { beta: true }],
    'Tinted cars glide by. A hawker taps on the glass.',
    ['A park bench, a coconut seller, a long exhale.', { placeKinds: ['park'] }],
    ['Rain gives the roads a new shine.', { season: { wet: true }, fx: 'rain' }],
    ['Buses from the satellite towns fill early. The commute is long.', { bands: ['dawn', 'morning'] }],
  ]),
  ...bank('port-harcourt', city('port-harcourt'), [
    ['Bole and fish smoke by the roadside: a good evening.', EVENING],
    'Humid air: your shirt is a second skin.',
    'Boat engines murmur from the creek.',
    'The Garden City has leaves on every street, and mud under them.',
    ['Rain arrives like a drumroll.', { season: { wet: true }, fx: 'rain' }],
    '“Wetin dey?” Pidgin has its own speed here.',
    'Native soup steam rises from a pot by the road.',
    ['Seafood on the grill: the evening smells good.', EVENING],
    ['A boat horn answers the traffic horns.', { fx: 'horn' }],
    ['Evening rain: puddles, laughter and umbrellas.', { ...EVENING, season: { wet: true }, fx: 'rain' }],
    'The waterfront is busy with traders and engines.',
    ['Carnival rehearsals: drums and whistles from the next street.', { beta: true, fx: 'music' }],
    ['Fresh fish, fresh pepper, fresh arguments about the price.', { placeKinds: ['market'] }],
    ['The humidity stays after dark. The fan does its best.', NIGHT],
  ]),
  ...bank('kano', city('kano'), [
    ['The dawn call to prayer: the city rises in one breath.', { ...DAWN, fx: 'prayer' }],
    ['The afternoon call to prayer, and the shops pause.', { ...AFTERNOON, fx: 'prayer' }],
    ['The evening call to prayer, as the light turns gold.', { ...EVENING, fx: 'prayer' }],
    ['The night call to prayer, softer over quiet streets.', { ...NIGHT, fx: 'prayer' }],
    ['“Sannu! Ina kwana?” passes along the wall.', { lang: 'ha', ...MORNING }],
    ['“Barka da zuwa,” says a shopkeeper to a stranger.', { lang: 'ha' }],
    ['“Na gode,” says the buyer, and means it.', { lang: 'ha' }],
    'Indigo hands, indigo cloth: the dye pits are at work.',
    'A leather worker taps and stitches, steady as a clock.',
    'Tuwo shinkafa steam, and a spoon waiting.',
    ['Hot masa on the pan: crisp edges, soft heart.', MORNING],
    ['Suya smoke drifts into the evening.', EVENING],
    'A kilishi seller counts out the strips with great care.',
    ['Fura da nono, cold and sour, in a calabash.', AFTERNOON],
    ['Harmattan dust is on the walls, the roofs and your tea.', { season: { harmattan: true }, fx: 'dust' }],
    ['August rain: the alleys run and the air smells new.', { season: { wet: true }, fx: 'rain' }],
    'Motorcycles weave through the narrow alleys, always just in time.',
    'Old walls, new phones.',
    ['A hot, dry afternoon: everyone in the shade, voices low.', AFTERNOON],
  ]),
  ...bank('calabar', city('calabar'), [
    ['“Sosongo!” says the soup seller, and means it.', { lang: 'efi' }],
    'Afang soup simmers in a big pot, and the leaf smell fills the street.',
    'Edikang ikong: the greens, the pot and the patient cook.',
    'The harbour air is salty and slow.',
    'Somebody is already sketching a carnival costume.',
    ['A long wet season: umbrellas are furniture here.', { season: { wet: true }, fx: 'rain' }],
    ['The short dry season: everybody finally hangs their washing out.', { season: { wet: false } }],
    ['The harmattan is gentle here: a light haze and cooler mornings.', { season: { harmattan: true }, fx: 'dust' }],
    ['Rain on the zinc roof like a drum circle.', { season: { wet: true }, fx: 'rain' }],
    ['A boat horn in the distance, a ship in the haze.', { fx: 'horn' }],
    ['The market smells of fish, leaves and spices all at once.', { placeKinds: ['market'] }],
    ['A slow Calabar evening: people sit outside and watch the day go.', EVENING],
    ['A dance school rehearses in a courtyard: drums, whistles, laughter.', { fx: 'music' }],
    'Greetings first, business second.',
  ]),
  ...bank('benin-city', city('benin-city'), [
    ['Bolts of cloth are unrolled, patterns flashed, prices announced.', { placeKinds: ['market'] }],
    ['Foodstuffs piled high: tomatoes, yams, peppers.', { placeKinds: ['market'] }],
    'A craftsman taps at a piece with all the time in the world.',
    'Old stories on every corner, new motorbikes in between.',
    'The red road dust is the colour of the evening.',
    'A tailor’s machine hums behind a stall of fabric.',
    ['The market opens before the sun and sleeps after the stars.', DAWN],
    'Danfo conductors call out one after another, like a rhythm.',
    ['Afternoon rain: the red earth runs and stalls pull in their canvas.', { ...AFTERNOON, season: { wet: true }, fx: 'rain' }],
    'Craft sellers arrange their pieces in tidy rows.',
  ]),
  ...bank('enugu', city('enugu'), [
    ['“Nnọọ!” A shopkeeper welcomes a customer.', { lang: 'ig' }],
    ['“Kedu?” “Ọ dị mma.” Greetings travel quickly.', { lang: 'ig' }],
    ['“Daalụ!” for the change, the favour and the day.', { lang: 'ig' }],
    'Hills fold around the roads and the traffic goes around the hills.',
    ['African soup simmers in a big pot: pepper and patience.', { beta: true }],
    ['A cool evening breeze drifts down from the hills.', EVENING],
    'Danfo and keke weave through the hill roads.',
    ['Market voices rise at dawn like a choir of roosters.', DAWN],
  ]),
]
