// The main place kinds: about 18 lines each. Pidgin and English; no real business or person is named; nothing here is a claim about a real place.
import { AFTERNOON, DAWN, DAYTIME, EVENING, LATE, MORNING, NIGHT, bank, here } from './bank.ts'
import type { Moment } from './types.ts'

const EARLY = Object.freeze({ bands: ['dawn', 'morning'] } as const)

export const MAIN_KINDS: Moment[] = [
  ...bank('buka', here('buka'), [
    'Mama is stirring a pot the size of a drum.',
    '“You want pepper?” “Small.” She adds plenty anyway.',
    'Rice, beans, plantain. The menu is a mood.',
    'Somebody is asking for extra meat. Again.',
    'The soup is hot. The fan is not helping.',
    'Spoons clink, plates scrape, plastic chairs complain.',
    ['Frying plantain makes the best sound in the world.', { fx: 'hush' }],
    ['Pap and akara steam in the morning air. Breakfast is serious.', EARLY],
    '“Aunty, e don finish?” “E never finish. Sit down.”',
    ['Lunch rush: two people, one seat, a very polite war.', AFTERNOON],
    'Pounded yam arrives. Silence falls.',
    ['The TV in the corner is on, loud, and nobody is watching.', { fx: 'music' }],
    '“Wash your hand first!” says the aunty. She is right.',
    ['The last of the jollof. Somebody is eyeing it.', EVENING],
    ['The beans don finish, the aunty announces. Groans.', LATE],
    'Fresh stew smell. Ten people are suddenly very hungry.',
    'Cold drinks sweat in a bucket of ice by the door.',
  ]),
  ...bank('market', here('market'), [
    ['“Customer, come and see! Last price!”', { fx: 'crowd' }],
    '“Oga, how much?” “For you, special price.”',
    'Bargaining in progress: both sides pretending to leave.',
    'Sacks of rice stacked to the roof of the stall.',
    ['A trolley of tomatoes rolls downhill. Everybody shouts.', { fx: 'crowd' }],
    'Fresh pepper makes the whole row sneeze.',
    ['Traders greet each other across ten stalls.', MORNING],
    ['“Excuse! Excuse!” A porter carries a load with great confidence.', { fx: 'crowd' }],
    '“Madam, I go give you better price.” “I don hear that before.”',
    'Fish smell, onion smell, perfume smell, all negotiating.',
    'A child minds a stall with the calm of a bank manager.',
    'Fabric sellers snap out lengths of colour in the sun.',
    ['Evening: traders count the day’s luck.', EVENING],
    'Somebody weighs tomatoes. Somebody else argues with the scale.',
    'The smell of dried fish and ground crayfish drifts by.',
    'Someone arranges oranges into a perfect pyramid.',
    ['Trucks unload in the half-dark; voices are thick with sleep.', DAWN],
    ['Tarpaulins come down. The stalls turn back into shapes.', NIGHT],
  ]),
  ...bank('hub', here('hub'), [
    ['The conductor slaps the side of the bus: “Enter, enter!”', { fx: 'horn' }],
    '“Change! Who get change?”',
    'A driver argues with a passenger about the exact fare.',
    ['Engines revving, horns arguing, nobody giving way.', { fx: 'horn' }],
    'Hawkers push water and groundnut through the bus windows.',
    '“Driver, I dey come down!” “Which side?”',
    'The bus is full. The conductor says there is still room.',
    'Passengers doze with one hand tight on their bag.',
    'Somebody sprints for a moving bus and makes it.',
    'A boy sells phone chargers like they are fresh bread.',
    'The park queue is a shape only the regulars understand.',
    '“Where you dey go?” “Anywhere that is moving.”',
    'Dust, fumes, shouting: the full travel experience.',
    ['First buses: sleepy faces, strong tea.', DAWN],
    ['Night buses: wrappers for blankets, tired smiles.', NIGHT],
    ['“Full! Full! Go!” The park agent waves it off.', { fx: 'horn' }],
    'A mother counts her children onto the bus, twice.',
    ['Evening rush: every bus is “the last bus.”', EVENING],
  ]),
  ...bank('club', here('club'), [
    ['The bass reaches you before the music does.', { ...LATE, fx: 'music' }],
    ['The DJ drops the song everybody was waiting for.', { ...NIGHT, fx: 'music' }],
    ['Someone dances like nobody is watching. Everybody is watching.', { ...LATE, fx: 'laugh' }],
    ['Bottle service arrives with sparklers. Phones go up.', LATE],
    ['The queue at the door grows. The bouncer is unmoved.', LATE],
    ['The dance floor sweats happily.', NIGHT],
    ['Somebody is on their fifth “last dance.”', { ...NIGHT, fx: 'laugh' }],
    ['A plastic cup walks across the table, shaken by the speaker.', NIGHT],
    ['Neon lights, small talk, big sound.', LATE],
    ['“Wetin dey happen?” “Everything.”', NIGHT],
    ['Afrobeats, amapiano and one stubborn highlife track.', { ...NIGHT, fx: 'music' }],
    ['Phone torches up. Everybody is filming the same chorus.', LATE],
    ['The generator and the DJ fight for the neighbourhood.', { ...NIGHT, fx: 'power-on' }],
    ['“Where did you go?!” Somebody is searching for their friend.', NIGHT],
    ['Outside, suya smoke and loud small talk.', LATE],
    ['The last song plays, and nobody goes home.', { ...NIGHT, fx: 'music' }],
    ['Empty chairs, a mop and a bucket: the quiet before the night.', DAYTIME],
    ['Sound check: “One, two. One, two.” Forever.', AFTERNOON],
  ]),
  ...bank('office', here('office'), [
    'A printer jams. Again.',
    'The ceiling fan wobbles and nobody trusts it.',
    '“Good morning, sir!” echoes down the corridor.',
    'Keyboards, phones and one very quiet sigh.',
    'The AC is on. The boss is cold. Everyone else is not.',
    ['The generator starts: lights flicker, computers hold their breath.', { fx: 'power-on' }],
    'The staff WhatsApp group has 47 unread messages.',
    'Tea break: the real meeting happens at the kettle.',
    'Someone rehearses a speech under their breath.',
    'The line for the one working printer is growing.',
    'The UPS beeps. Everyone stops typing and looks up.',
    '“Please, can I borrow your pen?” The pen will not return.',
    ['Four o’clock: eyes drift to the clock.', AFTERNOON],
    'Month end: everybody is refreshing their bank app.',
    ['Closing time: chairs scrape, bags zip, farewells overlap.', EVENING],
    ['Lunch: sandwiches in the drawer, rice in a flask.', AFTERNOON],
    ['The first one in: lights on, fan off, kettle on.', DAWN],
    ['A cleaner works down the corridor, humming softly.', NIGHT],
  ]),
  ...bank('gym', here('gym'), [
    'Weights clang. Somebody grunts like a hero.',
    'Treadmills hum. Everybody is watching the clock, not the miles.',
    'Mirror selfies: the real workout.',
    '“One more!” says the trainer. It is never one more.',
    ['The speaker plays the same three songs again.', { fx: 'music' }],
    'Someone stretches louder than they lift.',
    'Water bottle empty, resolve full.',
    'A newcomer picks up the smallest dumbbell with total confidence.',
    'Sweat on the floor, mop on the way.',
    'The fan blows warm air, bravely.',
    ['Morning crew: the serious ones, silent and focused.', { ...DAWN, fx: 'hush' }],
    ['Evening rush: a queue for the bench press.', EVENING],
    '“Spot me, please.” “I dey.”',
    'Skipping-rope rhythm. The neighbour downstairs has opinions.',
    'A protein shake is shaken like an argument.',
    'Shoes squeak, towels fly, a plate slams down.',
    'A phone alarm goes: “Time to go.” They do not.',
    ['The gym runs on generator, and everybody pretends it is fine.', { fx: 'power-on' }],
  ]),
  ...bank('mall', here('mall'), [
    'Sale sign: “Up to 50% off.” The small print is very small.',
    'The smell of popcorn and cold air spills from the cinema.',
    'Kids pull their parents towards the toy shop.',
    'The AC is so cold that the sun feels like a rumour.',
    'The security guard waves politely at everyone.',
    'Window shopping, the national sport.',
    '“Lost child at customer service.” Parents sprint.',
    'Food court: a thousand choices and one queue.',
    'A perfume spray ambushes you at the entrance.',
    'A pair of shoppers: one saying “Let’s go” for the third time.',
    'Gift wrap rolls out; someone’s birthday is saved.',
    'Coins glitter at the bottom of the fountain.',
    ['Weekend: families, strollers, slow walkers.', DAYTIME],
    ['Closing: shutters slide down and the lights dim.', NIGHT],
    'Someone guards the one free socket like a treasure.',
    '“Is this the final price?” “Madam, it is fixed price.” “Hmm.”',
    ['Back-to-school rush: uniforms, shoes and sighs.', { ...MORNING, fx: 'crowd' }],
    'The escalator hums its one patient note.',
  ]),
  ...bank('beach', here('beach'), [
    'Waves roll in, patient as ever.',
    ['The sand is hot enough to dance on, so people do.', AFTERNOON],
    '“Fresh coconut!” A hawker taps his cutlass for emphasis.',
    ['Kids build a sandcastle with serious engineering.', DAYTIME],
    ['Wind carries music from the beach bar.', { ...LATE, fx: 'music' }],
    'A family photo shoot: seven tries for one smile.',
    ['Fishermen mend nets in the shade.', DAYTIME],
    'Someone buys sunglasses and loses them within the hour.',
    'Birds wheel over the water, as loud as the music.',
    ['The lifeguard’s whistle: “Not that far!”', DAYTIME],
    ['Sunset: everybody stops to take the same photo.', EVENING],
    ['Dawn joggers on firm wet sand.', DAWN],
    'The tide goes out and takes everyone’s footprints.',
    ['A speaker plays highlife from a plastic chair.', { fx: 'music' }],
    'Salty air: your hair is a lost cause.',
    'Plantain chips in a nylon bag, “fresh from the pot.”',
    ['Night: moonlight on the water, couples whispering.', NIGHT],
    'A hawker sells straw hats and hope.',
  ]),
  ...bank('hospital', here('hospital'), [
    'A nurse calls a name. Three people stand up.',
    ['The waiting room: soft prayers, hard chairs.', { fx: 'hush' }],
    'Antiseptic smell: you know exactly where you are.',
    'The card office queue is a lesson in patience.',
    'A child is crying; a mother hums, steady and low.',
    'A doctor hurries past with a file under one arm.',
    ['The generator kicks in. The ward does not blink.', { fx: 'power-on' }],
    'A visitor holds a flask of pap for a patient.',
    '“Next!” says the receptionist, with the weariness of a hero.',
    'Pharmacy window: “Take it three times a day.”',
    'Relatives pass whispered news along the bench.',
    '“The doctor will see you soon.” Soon is relative.',
    ['Morning rounds: white coats in a line.', MORNING],
    ['Night duty: a long corridor and soft lights.', { ...NIGHT, fx: 'hush' }],
    'Someone hugs a relative, relieved.',
    '“Drink water, rest well, don’t skip your drugs.”',
    'A wheelchair squeaks down the corridor.',
    ['A prayer from one corner, and the whole ward says amen.', { fx: 'prayer' }],
  ]),
  ...bank('salon', here('salon'), [
    'The hair dryer hums. Confession time.',
    'Gist flows faster than the braids.',
    '“Hold your head still!” “I am!”',
    'Attachment hair in every colour of the rainbow.',
    ['A Nollywood film plays; the stylists add their own subtitles.', { fx: 'laugh' }],
    'Hot comb, coconut oil, a hint of burnt hair.',
    'The barber’s clippers buzz. A fade is in progress.',
    'A client checks the mirror and approves. Smiles all round.',
    'Someone fell asleep under the dryer.',
    'The braiding queue: eight hours is “a short one.”',
    '“How much for the braids?” “Madam, depends on the size.”',
    'Scissors snip. Gossip snips louder.',
    'A mirror selfie after the finish. Four of them, in fact.',
    'Nail polish: choose red, change mind, choose red again.',
    'A small boy has his first haircut, crying with dignity.',
    ['Saturday evening: party hair emergencies.', EVENING],
    '“Aunty, I’m coming, I’m coming!” She is not.',
    ['Early customers: wigs on stands, tea on the counter.', MORNING],
  ]),
  ...bank('park', here('park'), [
    'Kids chase a ball. The ball wins.',
    'Tree shade is the best real estate in town.',
    'Joggers pant, bench-sitters judge.',
    'A poet rehearses to nobody on a bench.',
    'Couples share a bag of groundnuts.',
    ['A guitar plays somewhere under a tree.', { fx: 'music' }],
    'A football match where the goalposts are two slippers.',
    'Old men bend over a board game, serious as a court.',
    ['Picnic mats in the sun.', DAYTIME],
    ['Evening: lamps flicker on and families linger.', EVENING],
    'Birds argue in the tree overhead.',
    '“Smile!” says a photographer. Everyone does.',
    ['Dew on the grass; the joggers are already out.', DAWN],
    ['An ice-cream bell rings. Children sprint.', { ...AFTERNOON, fx: 'laugh' }],
    ['A drummer tests a talking drum. The park listens.', { fx: 'music' }],
    'A cold-drink seller does his rounds, hopeful.',
    ['The park is quiet, with one jogger and a lot of birds.', MORNING],
    ['The gate guard locks up and gives the lawn a last look.', NIGHT],
  ]),
  ...bank('worship', here('worship'), [
    ['Quiet inside, loud outside. The doors are doing their job.', { fx: 'hush' }],
    'A small child tries to be silent. Almost.',
    'The floor is cool and the shade is good.',
    ['Morning prayer, before the world wakes up.', { ...DAWN, fx: 'prayer' }],
    ['Evening prayer, voices low.', { ...EVENING, fx: 'prayer' }],
    'Somebody tiptoes in late and finds a seat near the back.',
    ['Choir practice drifts out of a window.', { variants: ['church'], fx: 'music' }],
    ['Ushers fan themselves and smile at the latecomers.', { variants: ['church'] }],
    ['Sunday best: hats, suits, hymn books.', { variants: ['church'], ...MORNING }],
    ['A sermon is building; the “amen” wave rolls back.', { variants: ['church'], fx: 'prayer' }],
    ['The offering basket makes a polite round.', { variants: ['church'] }],
    ['Midweek prayers: quiet and sincere.', { variants: ['church'], ...EVENING }],
    ['Drums and keyboard start; praise begins.', { variants: ['church'], fx: 'music' }],
    ['Mats are laid out in neat rows.', { variants: ['mosque'] }],
    ['Shoes line up by the door, pair after pair.', { variants: ['mosque'] }],
    ['The imam’s voice, calm and steady.', { variants: ['mosque'], fx: 'prayer' }],
    ['Ablution taps run and the courtyard glistens.', { variants: ['mosque'] }],
    ['“As-salamu alaykum” passes down the row.', { variants: ['mosque'], fx: 'prayer' }],
    ['Friday: the crowd spills onto the road.', { variants: ['mosque'], ...AFTERNOON }],
  ]),
  ...bank('police', here('police'), [
    'The radio crackles. Nobody knows what it said.',
    'A report is written, letter by letter.',
    '“I want to report…” The queue at the desk shuffles forward.',
    'An officer sips tea and studies the log.',
    'A man explains a very long story; the officer nods slowly.',
    'A noticeboard of notices and a faded calendar.',
    'A phone rings and nobody picks it up. Again.',
    '“Please, I am looking for my brother.”',
    'A ceiling fan turns, slow as a sigh.',
    'Keys jingle somewhere down the corridor.',
    ['Rain drums on the zinc roof so loud nobody can talk.', { season: { wet: true }, fx: 'rain' }],
    'The patrol van starts. The engine coughs first.',
    ['A whistle from the road; traffic obeys, mostly.', { fx: 'horn' }],
    'Statement forms, three copies each.',
    'Lost and found: umbrellas, one shoe, a phone.',
    ['Night: one bulb, one pen, one steady hand.', NIGHT],
    'A visitor holds a flask and waits for the duty officer.',
    ['Morning handover: tired faces, brisk nods.', DAWN],
  ]),
  ...bank('viewing', here('viewing'), [
    ['Match day: the commentary is louder than the generator.', { fx: 'crowd' }],
    '“Offside!” “No be offside!” The debate goes on.',
    'Plastic chairs packed shoulder to shoulder.',
    ['A goal! The whole room jumps and a cup flies.', { ...LATE, fx: 'crowd' }],
    'Cold drinks and groundnut for the second half.',
    'Half-time: analysis from the experts in row two.',
    'Fans in jerseys. Some jerseys are from the wrong decade.',
    'The referee, every fan’s favourite enemy.',
    ['The signal blinks. A collective groan.', { fx: 'crowd' }],
    'A sleepy fan wakes up for the penalty.',
    'The neighbour’s team lost. Quiet respect.',
    ['The power flickers and the whole room gasps.', { fx: 'power-off' }],
    '“I said it!” “You no say.” Prediction slips are flying.',
    ['Evening: the screen is bright and the room is hot.', EVENING],
    'Kids stand at the door, watching for free.',
    '“Who dey play?” “Doesn’t matter, enter.”',
    ['Full time. The argument continues outside.', { ...LATE, fx: 'laugh' }],
    ['Between matches: a mop, a dark screen, one man asleep.', DAYTIME],
  ]),
  ...bank('home', here('home'), [
    'The neighbour’s voice carries through the wall.',
    'A pot of water sits on the stove, bath soon.',
    ['The compound hums with a generator and a radio.', { fx: 'power-on' }],
    'Your landlord’s keys jingle past the door.',
    'The fan spins. It is your best friend this week.',
    'A kettle clicks off. Peace.',
    'Your phone buzzes. You ignore it for a minute.',
    ['Someone sweeps the compound at dawn, humming.', DAWN],
    'A child’s laughter drifts from next door.',
    'Someone else’s frying smells better than yours.',
    'A mosquito whines. The net is a hero.',
    ['Night: gate locked, bulb glowing, stars outside.', { ...NIGHT, fx: 'hush' }],
    'Clothes dry on the line, flapping.',
    ['Rain on the zinc: sleep arrives early.', { season: { wet: true }, fx: 'rain' }],
    ['The radio next door plays old highlife.', { fx: 'music' }],
    'The water tank gurgles. The tap works today!',
    ['Morning light through the curtain, and a rooster has opinions.', MORNING],
    ['Dinner smells waft from three different windows.', EVENING],
  ]),
]
