// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":3478,"z":-1427})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-51.48833208381984,"maxX":117.6335140526885,"minZ":-63.94344360993364,"maxZ":22.136115046332634})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"gombe":{"lon":11.157967235341278,"lat":10.294180298749763}})
