// Generated by scripts/phone/build-icons.mjs. Original Allworld artwork.
export const PHONE_ART: readonly string[] = ["messages","jobs","bank","ride","missions","groceries","health","houses","land","neighbourhood","goals","boutique","cars","stories","capture","settings","touch","help","business","commerce","statement","richlist","invest","career","contacts","family","invite","refer","people","governor","events","politics","neighbours","tables","games","ads","hunt-sheet","radio","campus","support","community","admin"]
export const PHONE_ART_COLUMNS = 7
export const PHONE_ART_ROWS = 6
