// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "gaborone",
  "name": "Gaborone",
  "country": {
    "idISOlower": "bw",
    "name": "Botswana"
  },
  "state": {
    "idunique": "bw-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Gaborone",
  "centre": {
    "lon": 25.911948,
    "lat": -24.646314
  },
  "airport": {
    "id": "gaborone-airport",
    "name": "Sir Seretse Khama International Airport",
    "lon": 25.9182,
    "lat": -24.555201,
    "sourceUrl": "https://ourairports.com/airports/FBSK/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=25.908948,-24.649314,25.914948,-24.643314",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    25.896948,
    -24.661314,
    25.9302,
    -24.543201
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
