// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Hauwa Bukar", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Umar Lawan", role: "Supporter", quotes: ["I come to August 27 stadium for the football.", "Sit high up and you see the whole game."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukar Abatcha", role: "Mosque caretaker", quotes: ["Welcome to Damaturu Central Mosque. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Waziri", role: "Regular worshipper", quotes: ["I have prayed at Damaturu Central Mosque for a long time.", "Come in quietly, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Mohammed", role: "Mosque caretaker", quotes: ["Welcome to Yobe Islamic Centre. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Umar Zannah", role: "Regular worshipper", quotes: ["I have prayed at Yobe Islamic Centre for a long time.", "Come in quietly, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukar Kyari", role: "Church volunteer", quotes: ["Welcome to St. Mary's Catholic Church. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Bulama", role: "Regular worshipper", quotes: ["I have worshipped at St. Mary's Catholic Church for a long time.", "Sit anywhere there is room, and be welcome."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Ali", role: "Student", quotes: ["I am on my way to a workshop at Federal Polytechnic Damaturu.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Umar Gana", role: "Instructor", quotes: ["I teach practical work here.", "Hands first, then the theory."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukar Lawan", role: "Student", quotes: ["I am on my way to a lecture at Yobe State University.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Mamman", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Waziri", role: "Museum guide", quotes: ["Welcome to National Museum, Damaturu. Please take your time.", "Ask me if you want to know what is on display."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Umar Kolo", role: "Visitor", quotes: ["I came to National Museum, Damaturu to learn something new.", "Read the labels slowly. They reward you."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukar Zannah", role: "Market trader", quotes: ["Looking for Yobe farm produce? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Goni", role: "Shopper", quotes: ["Wikipedia calls Yobe an agricultural state whose produce includes gum arabic, groundnuts, beans and cotton.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Bulama", role: "Market trader", quotes: ["Looking for Yobe farm produce? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Umar Modu", role: "Shopper", quotes: ["Wikipedia calls Yobe an agricultural state whose produce includes gum arabic, groundnuts, beans and cotton.", "Take your time, and bargain with a smile."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukar Gana", role: "Ticket seller", quotes: ["Check the board for your departure.", "Keep your bags close in a crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Mustapha", role: "Traveller", quotes: ["I am waiting at Yobe Line Motor Park for my bus.", "Travelling is half waiting."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Mamman", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Umar Mala", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukar Kolo", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Bukar", role: "Patient's relative", quotes: ["I am waiting with a relative at General Sani Abacha State Specialist Hospital.", "Everyone here is patient, so I must be too."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hauwa Goni", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Umar Abatcha", role: "Patient's relative", quotes: ["I am waiting with a relative at State Teaching Hospital.", "Everyone here is patient, so I must be too."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
