// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":4356,"z":-3058})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-278.0602946657991,"maxX":345.192519787156,"minZ":-438.5112843404445,"maxZ":206.78112024448365})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"damaturu":{"lon":12.033692284437326,"lat":11.853137579865033}})
