// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "kigali",
  "name": "Kigali",
  "country": {
    "idISOlower": "rw",
    "name": "Rwanda"
  },
  "state": {
    "idunique": "rw-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Kigali",
  "centre": {
    "lon": 30.058586,
    "lat": -1.951644
  },
  "airport": {
    "id": "kigali-airport",
    "name": "Kigali International Airport",
    "lon": 30.1395,
    "lat": -1.96863,
    "sourceUrl": "https://ourairports.com/airports/HRYR/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=30.055586,-1.954644,30.061586,-1.948644",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    30.043586,
    -1.98063,
    30.1515,
    -1.936644
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
