// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "kigali",
  "name": "Kigali",
  "country": {
    "idISOlower": "rw",
    "name": "Rwanda"
  },
  "state": {
    "idunique": "rw-starter",
    "name": "Kigali"
  },
  "timezone": "Africa/Kigali",
  "centre": {
    "lon": 30.058586,
    "lat": -1.951644
  },
  "airport": {
    "id": "kigali-airport",
    "name": "Kigali International Airport",
    "lon": 30.1395,
    "lat": -1.96863,
    "sourceUrl": "https://ourairports.com/airports/HRYR/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://www.openstreetmap.org/copyright",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    30.02,
    -2.0,
    30.16,
    -1.9
  ],
  "coverageNote": "Kigali from Nyabugogo to the airport at Kanombe: a sketch of the built-up extent traced from mapped land use (not an administrative boundary), the small lakes and ponds mapped as water, main roads and named places mapped in OpenStreetMap. The airport coordinates are an OurAirports dataset point, not an official reference point or evidence of current operations or schedules. Visitor services and homes are fictional game content set at the real named places.",
  "names": {
    "area": "Kigali",
    "unit": "district",
    "roadHub": "Nyabugogo Bus Station"
  }
} satisfies DestinationFacts
