// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-557,"z":3856})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-142.73613884863164,"maxX":101.91101875039402,"minZ":-190.8568174871134,"maxZ":112.34881534288206})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"umuahia-north":{"lon":7.4902392796481045,"lat":5.584503327125178},"umuahia-south":{"lon":7.444813310823209,"lat":5.487521296490898}})
