import { defineCitySpec } from '../spec.ts'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'umuahia',
  name: 'Umuahia',
  state: { id: 'abia', name: 'Abia', sourceName: 'Abia', unit: 'local government', sourceIds: ['geography'] },
  country: { id: 'nigeria', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 7.4924165,
    lat: 5.5324032,
    teaser: 'The Abia capital, a railway and farm-market town with a war museum and a bunker.',
    preview: ["Visit the National War Museum and Ojukwu's Bunker.", 'Catch the Umuahia-Ibeku station and cross into Umuahia South.'],
    coordinateSourceId: 'osm-selected',
    coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2841325913 },
  },
  population: { tier: 'city', sourceIds: ['umuahia-wiki'], note: 'The cited article reports 359,230 residents at the 2006 census.' },
  localUnits: [
    { id: 'umuahia-north', name: 'Umuahia North', sourceName: 'Umuahia North', populationTier: 'city', description: 'The selected northern local government contains the state secretariat, stadium, hospital, railway station and most mapped venues.', sourceIds: ['geography'] },
    { id: 'umuahia-south', name: 'Umuahia South', sourceName: 'Umuahia South', populationTier: 'town', description: 'The selected southern local government contains the Old Umuahia train station, the Amachara nursing college and the Apumiri council headquarters.', sourceIds: ['geography'] },
  ],
  places: [
    {
      id: 'all-saints-cathedral-umuahia', name: 'All Saints Cathedral', kind: 'church', lon: 7.4619051, lat: 5.5614004, localUnitId: 'umuahia-north',
      description: 'A mapped Methodist religious site named All Saints Cathedral.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 700220997 }, accuracy: 'feature-centroid',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'living-faith-church-umuahia', name: 'Living Faith Church', kind: 'church', lon: 7.5168276, lat: 5.5200208, localUnitId: 'umuahia-north',
      description: 'A mapped Christian place of worship named Living Faith Church.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 6926667891 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'de-native-restaurant-umuahia', name: 'De Native Restaurant Umuahia', kind: 'eatery', lon: 7.4938985, lat: 5.5260901, localUnitId: 'umuahia-north',
      description: 'Wikidata records De Native Restaurant Umuahia as a restaurant, shown here with Ukwa.', sourceIds: ['wikidata-selected', 'ukwa'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136912637' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'ukwa',
    },
    {
      id: 'afrikana-flavors-umuahia', name: 'Afrikana Flavors Umuahia', kind: 'eatery', lon: 7.4916961, lat: 5.5270622, localUnitId: 'umuahia-north',
      description: 'Wikidata records Afrikana Flavors Umuahia as a restaurant, shown here with Abacha.', sourceIds: ['wikidata-selected', 'abacha'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136917502' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'abacha',
    },
    {
      id: 'lux-mundi-university', name: 'Lux Mundi University, Umuahia', kind: 'university', lon: 7.490818, lat: 5.560386, localUnitId: 'umuahia-north',
      description: 'Wikidata records Lux Mundi University as a private Catholic university in Umuahia.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q138455845' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'lamp'] },
    },
    {
      id: 'college-of-nursing-umuahia', name: 'College of Nursing Sciences, Umuahia, Abia State', kind: 'college', lon: 7.4933142, lat: 5.524316499999999, localUnitId: 'umuahia-north',
      description: 'Wikidata records the College of Nursing Sciences, Umuahia as a nursing college.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q137731200' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'college-of-nursing-amachara', name: 'College of Nursing Sciences, Amachara, Abia State', kind: 'college', lon: 7.4516578, lat: 5.5436931, localUnitId: 'umuahia-south',
      description: 'Wikidata records the College of Nursing Sciences, Amachara as a nursing college in Umuahia South.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q137773162' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'national-war-museum-umuahia', name: 'National War Museum, Umuahia', kind: 'museum', lon: 7.486299, lat: 5.54519, localUnitId: 'umuahia-north',
      description: "Wikipedia describes the National War Museum as Nigeria's only war museum, at Ebite Amafor in Umuahia North.", sourceIds: ['wikidata-selected', 'national-war-museum'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q55624815' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'ojukwu-bunker', name: "Ojukwu's Bunker", kind: 'museum', lon: 7.4857481318207455, lat: 5.5192430784843305, localUnitId: 'umuahia-north',
      description: "Wikidata records Ojukwu's Bunker as a museum; Wikipedia places the bunker beside the National War Museum.", sourceIds: ['wikidata-selected', 'national-war-museum'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q111902088' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'national-gallery-art-museum-umuahia', name: 'National Gallery of art museum , Umuahia', kind: 'museum', lon: 7.518826, lat: 5.5292484, localUnitId: 'umuahia-north',
      description: 'Wikidata records the National Gallery of Art museum in Umuahia as a museum.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q111923056' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'fmc-umuahia', name: 'Federal Medical Centre, Umuahia', kind: 'hospital', lon: 7.4965946, lat: 5.5194986, localUnitId: 'umuahia-north',
      description: "A mapped hospital named Federal Medical Centre, Umuahia, which Wikipedia lists among the city's hospitals.", sourceIds: ['osm-selected', 'umuahia-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 804198298 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'abia-state-government-house', name: 'Abia State Government House', kind: 'government', lon: 7.4868289, lat: 5.5253967, localUnitId: 'umuahia-north',
      description: 'A mapped government office named Abia State Government House.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 541014949 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'abia-state-secretariat', name: 'Abia State Secretariat', kind: 'government', lon: 7.5128993, lat: 5.5230726, localUnitId: 'umuahia-north',
      description: 'A mapped government office tagged Abia State Secretarait, with the name spelled correctly here.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 406633775 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'abia-state-house-of-assembly', name: 'Abia State House of Assembly', kind: 'government', lon: 7.5138, lat: 5.5284, localUnitId: 'umuahia-north',
      description: 'Wikidata records the Abia State House of Assembly as the legislative arm of the state government.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q21043169' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'apumiri-council-headquarters', name: 'Apumiri council headquarters', kind: 'government', lon: 7.4496, lat: 5.5117, localUnitId: 'umuahia-south',
      description: 'Wikidata records Apumiri as the council headquarters of Umuahia South Local Government Area.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q60794217' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'township-stadium-umuahia', name: 'Township Stadium, Umuahia', kind: 'stadium', lon: 7.4970665, lat: 5.523916, localUnitId: 'umuahia-north',
      description: 'A mapped stadium named Township Stadium, Umuahia.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 670739208 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'ubani-modern-market', name: 'Ubani Modern Market', kind: 'market', lon: 7.509514, lat: 5.5939927, localUnitId: 'umuahia-north',
      description: 'A mapped marketplace named Ubani Modern Market; Wikipedia calls Umuahia an agricultural market centre.', sourceIds: ['osm-selected', 'umuahia-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 333811770 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['umuahia-farm-produce'],
    },
    {
      id: 'orie-ugba-market', name: 'Orie Ugba Market', kind: 'market', lon: 7.49976103986764, lat: 5.537089247438671, localUnitId: 'umuahia-north',
      description: 'Wikidata records Orie Ugba Market as a market in Abia State.', sourceIds: ['wikidata-selected', 'umuahia-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q123378621' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['umuahia-farm-produce'],
    },
    {
      id: 'uvuoma-microfinance-bank', name: 'Uvuoma Microfinance Bank Limited', kind: 'savings', lon: 7.500921646784333, lat: 5.480907198762799, localUnitId: 'umuahia-south',
      description: 'Wikidata records Uvuoma Microfinance Bank Limited, a microfinance bank in Umuahia South.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q111015699' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'umuchukwu-microfinance-bank', name: 'Umuchukwu Microfinance Bank Limited', kind: 'savings', lon: 7.495725067185217, lat: 5.530225713281917, localUnitId: 'umuahia-north',
      description: 'Wikidata records Umuchukwu Microfinance Bank Limited, a microfinance bank in Umuahia.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q111022143' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'ulo-ama-umuochoko-park', name: 'Ulo ama Umuochoko', kind: 'park', lon: 7.4336329, lat: 5.6322379, localUnitId: 'umuahia-north',
      description: 'A mapped park named Ulo ama Umuochoko.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 8143692581 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['tree', 'bench'] },
    },
    {
      id: 'umuahia-ibeku-station', name: 'Umuahia - Ibeku Station', kind: 'rail-station', lon: 7.4925212, lat: 5.5280677, localUnitId: 'umuahia-north',
      description: 'A mapped railway station named Umuahia - Ibeku Station, the trading post Wikipedia names on the rail route.', sourceIds: ['osm-selected', 'umuahia-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 670739197 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'old-umuahia-train-station', name: 'Old Umuahia Train Station', kind: 'rail-station', lon: 7.4804771, lat: 5.4889117, localUnitId: 'umuahia-south',
      description: 'Wikidata records the Old Umuahia Train Station as a railway station in Umuahia South.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q110570346' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
  ],
  identity: {
    foods: [
      { id: 'ukwa', name: 'Ukwa', description: 'Ukwa, or African breadfruit, is a traditional food of the Igbo people, most often cooked as a porridge with potash, palm oil and seasonings.', sourceIds: ['ukwa'] },
      { id: 'abacha', name: 'Abacha', description: 'Abacha is a food originating with the Igbo people and made from cassava tubers.', sourceIds: ['abacha'] },
    ],
    crafts: [
      { id: 'umuahia-market-crafts', name: 'Market crafts and pottery', description: 'Wikipedia says merchants once travelled to the Umuahia market centre to trade produce, pottery, crafts, textile and tools.', sourceIds: ['umuahia-wiki'] },
    ],
    industries: [
      { id: 'umuahia-farm-produce', name: 'Farm produce market', description: 'Wikipedia calls Umuahia a railway and agricultural market centre where traders and farmers sell yams, cassava, maize, taro, citrus fruits, and palm oil and kernels.', sourceIds: ['umuahia-wiki'] },
      { id: 'umuahia-brewery-palm-oil', name: 'Brewery and palm-oil processing', description: 'Wikipedia lists a brewery and a palm-oil-processing plant among the industries driving the Umuahia economy.', sourceIds: ['umuahia-wiki'] },
    ],
  },
  transport: {
    airports: [],
    rail: [],
    ports: [],
  },
  climate: {
    profile: 'southern-wet-dry', rainyMonths: [4, 5, 6, 7, 8, 9, 10], dryMonths: [12, 1, 2],
    description: 'Umuahia has a tropical Am climate with a wetter season from late March to early November, a short dry season from early November to late March, and about 2,153 mm of rain a year.',
    clearLabel: 'Dry-season sky', sourceIds: ['umuahia-wiki'],
  },
  homePalette: { back: '#b78d5b', left: '#76593a', floor: ['#c7a76f', '#617f4f'] },
  geometry: { surface: { path: 'scripts/geo/sources/formula/umuahia-surface.geojson', bytes: 114389, sha256: 'eab814c1caf4567e5a45fd362dcf4fa811e16b97b14c3448e7a942ce1ad25de2' } },
  sourceGroups: [
    { id: 'osm-selected', title: 'Selected OpenStreetMap records for Umuahia', url: 'https://www.openstreetmap.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'ODbL 1.0', cache: { path: 'scripts/city/research/umuahia/reviewed/osm-selected.json', bytes: 2988, sha256: '42f703d2d2e3e2c894d84bdfbf2866e9459ab4b398671655bbdd235d0b3d846a' } },
    { id: 'wikidata-selected', title: 'Selected Wikidata entities for Umuahia', url: 'https://www.wikidata.org/wiki/Wikidata:Main_Page', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'CC0 1.0', cache: { path: 'scripts/city/research/umuahia/reviewed/wikidata-selected.json', bytes: 11977, sha256: '2d4a89975d6e8aae521615cce15eada7bbdecc1e7e3fbc7ac4ac078e398bc1b1' } },
    { id: 'geography', title: 'Pinned Nigerian administrative geography', url: 'https://www.geoboundaries.org/', checkedOn: '2026-10-06', supports: ['geography'], licence: 'CC BY 4.0', cache: { path: 'scripts/city/research/umuahia/reviewed/geography.json', bytes: 408, sha256: 'f36eba221d45ae8b7f88f55579555853afb8de507a96064c72d4170984dbaea5' } },
    { id: 'umuahia-wiki', title: 'Wikipedia: Umuahia', url: 'https://en.wikipedia.org/wiki/Umuahia', checkedOn: '2026-10-06', supports: ['population', 'climate', 'identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/umuahia/reviewed/umuahia-wiki.json', bytes: 1052, sha256: '1da21ed758e7e2952473772983d53e03212788cf0d925fd329d2a71ad4920dd1' } },
    { id: 'ukwa', title: 'Wikipedia: Ukwa (food)', url: 'https://en.wikipedia.org/wiki/Ukwa_(food)', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/umuahia/reviewed/ukwa.json', bytes: 331, sha256: '083866c9d5f4e0f96f06c1f64f5749d66ede001e43173232846c9c0b95566ad3' } },
    { id: 'abacha', title: 'Wikipedia: Abacha (food)', url: 'https://en.wikipedia.org/wiki/Abacha_(food)', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/umuahia/reviewed/abacha.json', bytes: 252, sha256: 'd049474bd5c4b10408b506333d5916a0d4ee1be45d41090f4eda3d049a23f73d' } },
    { id: 'national-war-museum', title: 'Wikipedia: National War Museum, Umuahia', url: 'https://en.wikipedia.org/wiki/National_War_Museum,_Umuahia', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/umuahia/reviewed/national-war-museum.json', bytes: 375, sha256: '6e99c30d7323d8d9243673839e78cdc8cb9f12ce33f28fd01e8170eb2e5ed993' } },
  ],
  unmapped: [
    { kind: 'garden', note: 'No named garden with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'mosque', note: 'No named mosque with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'polling', note: 'No named polling venue with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'road-hub', note: 'No named bus station, motor park or terminal with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'salon', note: 'No named salon or barber shop with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
  ],
})
