// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Maryam Abubakar", role: "Park caretaker", quotes: ["I keep Gusau Amusement Park tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Garba Umar", role: "Morning walker", quotes: ["I walk through Gusau Amusement Park before work.", "Fresh air first, then the day."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Sani Sadiq", role: "Church volunteer", quotes: ["Welcome to Our Lady of Fatima Catholic Church gusau. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Zulai", role: "Regular worshipper", quotes: ["I have worshipped at Our Lady of Fatima Catholic Church gusau for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Salihu", role: "Church volunteer", quotes: ["Welcome to First Baptist Church Gusau. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Garba Suleiman", role: "Regular worshipper", quotes: ["I have worshipped at First Baptist Church Gusau for a long time.", "Sit anywhere there is room, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Sani Mohammed", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zulai Gambo", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Magaji", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Malam Garba", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Sani Umar", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zulai Kabir", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Idris", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Garba Gwarzo", role: "Patient's relative", quotes: ["I am waiting with a relative at Yariman Bakura Specialist Hospital.", "Everyone here is patient, so I must be too."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Sani Suleiman", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Asmau", role: "Patient's relative", quotes: ["I am waiting with a relative at Federal Medical Centre, Gusau.", "Everyone here is patient, so I must be too."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Gambo", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Garba Bala", role: "Patient's relative", quotes: ["I am waiting with a relative at Daula Hospital Gusau.", "Everyone here is patient, so I must be too."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Sani Danladi", role: "Market trader", quotes: ["Looking for Farming and commerce? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zulai Bello", role: "Shopper", quotes: ["Wikipedia describes Gusau as an important agricultural and commercial centre, and says over 80 percent of Zamfara State is engaged in agriculture, with millet, guinea corn, maize, rice, groundnut, cotton, tobacco and beans.", "Take your time, and bargain with a smile."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Kabir", role: "Market trader", quotes: ["Looking for Farming and commerce? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Malam Mustapha", role: "Shopper", quotes: ["Wikipedia describes Gusau as an important agricultural and commercial centre, and says over 80 percent of Zamfara State is engaged in agriculture, with millet, guinea corn, maize, rice, groundnut, cotton, tobacco and beans.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Sani Gwarzo", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zulai Abubakar", role: "Supporter", quotes: ["I come to Sardauna Memorial Stadium for the football.", "Sit high up and you see the whole game."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Yakubu", role: "Student", quotes: ["I am on my way to a lecture at Federal College of Education (Technical), Gusau.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Garba Sadiq", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Sani Bala", role: "Student", quotes: ["I am on my way to a lecture at Huda University, Gusau.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Jamila", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Bello", role: "Site attendant", quotes: ["Welcome to Zanfara State Library Board, Gusau. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Garba Mohammed", role: "Local resident", quotes: ["I walk past Zanfara State Library Board, Gusau most days.", "Visitors often stop here for photographs."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
