// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-1471,"z":-3520})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-179.56567731299697,"maxX":544.996208582384,"minZ":-297.6130981635456,"maxZ":668.1008287436152})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"gusau":{"lon":6.657035844937807,"lat":11.908114120696723}})
