// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "lusaka",
  "name": "Lusaka",
  "country": {
    "idISOlower": "zm",
    "name": "Zambia"
  },
  "state": {
    "idunique": "zm-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Lusaka",
  "centre": {
    "lon": 28.281382,
    "lat": -15.414698
  },
  "airport": {
    "id": "lusaka-airport",
    "name": "Kenneth Kaunda International Airport",
    "lon": 28.452722,
    "lat": -15.330833,
    "sourceUrl": "https://ourairports.com/airports/FLLS/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=28.278382,-15.417698,28.284382,-15.411698",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    28.266382,
    -15.429698,
    28.464722,
    -15.318833
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
