// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "lusaka",
  "name": "Lusaka",
  "country": {
    "idISOlower": "zm",
    "name": "Zambia"
  },
  "state": {
    "idunique": "zm-starter",
    "name": "Lusaka"
  },
  "timezone": "Africa/Lusaka",
  "centre": {
    "lon": 28.281382,
    "lat": -15.414698
  },
  "airport": {
    "id": "lusaka-airport",
    "name": "Kenneth Kaunda International Airport",
    "lon": 28.452722,
    "lat": -15.330833,
    "sourceUrl": "https://ourairports.com/airports/FLLS/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://www.openstreetmap.org/copyright",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    28.2,
    -15.5,
    28.5,
    -15.3
  ],
  "coverageNote": "Lusaka from Chilenje and Makeni to the way out to the airport: a sketch of the built-up extent traced from mapped land use (not an administrative boundary), the small lakes and dams mapped as water, main roads and named places mapped in OpenStreetMap. The airport coordinates are an OurAirports dataset point, not an official reference point or evidence of current operations or schedules. Visitor services and homes are fictional game content set at the real named places.",
  "names": {
    "area": "Lusaka",
    "unit": "district",
    "roadHub": "Intercity Bus Terminal"
  }
} satisfies DestinationFacts
