import { createHash, randomUUID } from 'node:crypto';
import { lstat, opendir, statfs } from 'node:fs/promises';
import path from 'node:path';
import { Worker } from 'node:worker_threads';
import { withAcquisitionBuildLock } from './acquire.ts';
import { readBoundedLocalFile } from './inventory-reader.ts';
import { readCountryDirectory } from './country-directory-reader.ts';
import { createOutputStore } from './storage.ts';
import { ADMIN1_LIMITS } from './admin1-types.ts';
import { ADMIN1_PRODUCT, ADMIN1_PRODUCT_LIMITS, type Admin1AssetRef, type Admin1CountryIndex, type Admin1CountryRef, type Admin1Partition, type Admin1ProductManifest, type Admin1PublishedResult } from './admin1-product-types.ts';
import type { Admin1ParentPin, Admin1SourcePin, Admin1InspectionReport, Admin1PartitionEntry } from './admin1-types.ts';
import type { InventoryNode } from './production-types.ts';
import type { SourceRecord } from './types.ts';

const HARD=Object.freeze({durationMs:120_000,sourceBytes:64*1024*1024,parentBytes:16*1024*1024,treeBytes:ADMIN1_PRODUCT_LIMITS.treeBytes,treeEntries:ADMIN1_PRODUCT_LIMITS.treeEntries,treeDepth:ADMIN1_PRODUCT_LIMITS.treeDepth,auditBytes:ADMIN1_PRODUCT_LIMITS.auditBytes,auditEntries:ADMIN1_PRODUCT_LIMITS.auditEntries,auditRecordBytes:ADMIN1_PRODUCT_LIMITS.auditRecordBytes,auditReserveBytes:16*1024,freeBytes:ADMIN1_PRODUCT_LIMITS.freeBytes,workerOldMb:256,workerYoungMb:32,rssBytes:ADMIN1_PRODUCT_LIMITS.rssBytes});
const SHA=/^[a-f0-9]{64}$/,HEX40=/^[a-f0-9]{40}$/;
type ByteAsset={path:string;sha256:string;bytes:ArrayBuffer};
interface WorkerOutput { report:ByteAsset;globalIndex:ByteAsset;partitions:ByteAsset[];countries:Array<{countryId:string;asset:ByteAsset;sourceUnits:number;emittedUnits:number}>;entries:Admin1PartitionEntry[];inspection:Admin1InspectionReport;sourceUnits:number;emittedUnits:number;protected:number;unlinked:number;ambiguous:number;exceptionUnits:number;logicalBytes:number }
type WorkerReply={ok:true;output:WorkerOutput}|{ok:false;error:string};
const sha=(bytes:Uint8Array|string):string=>createHash('sha256').update(bytes).digest('hex');
function canonical(value:unknown):string{if(value===null||typeof value==='string'||typeof value==='boolean')return JSON.stringify(value);if(typeof value==='number'){if(!Number.isFinite(value))throw new TypeError('Admin1 publication has a non-finite number');return JSON.stringify(value);}if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object'){const row=value as Record<string,unknown>;return`{${Object.keys(row).sort().map(key=>`${JSON.stringify(key)}:${canonical(row[key])}`).join(',')}}`;}throw new TypeError('Admin1 publication value is not canonical JSON');}
function inside(root:string,child:string):boolean{const relative=path.relative(root,child);return relative!==''&&relative!=='..'&&!relative.startsWith(`..${path.sep}`)&&!path.isAbsolute(relative);}
function errorText(error:unknown):string{return(error instanceof Error?error.message:String(error)).slice(0,2000);}
function check(signal:AbortSignal,deadline:number):void{if(signal.aborted)throw signal.reason??new Error('Admin1 publication aborted');if(performance.now()>=deadline)throw new Error('Admin1 publication exceeded its deadline');if(process.memoryUsage().rss>HARD.rssBytes)throw new RangeError('Admin1 publisher process RSS exceeded 512 MiB');}
async function safePath(target:string):Promise<void>{const absolute=path.resolve(target);let cursor=path.parse(absolute).root;const parts=absolute.slice(cursor.length).split(path.sep).filter(Boolean);for(let i=0;i<parts.length;i++){cursor=path.join(cursor,parts[i]!);try{const info=await lstat(cursor);if(info.isSymbolicLink()||(i<parts.length-1&&!info.isDirectory()))throw new Error(`Admin1 publication path contains unsafe ancestor: ${cursor}`);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return;throw error;}}}
async function treeUsage(root:string,signal:AbortSignal,deadline:number):Promise<{bytes:number;entries:number}>{let bytes=0,entries=0;const walk=async(dir:string,depth:number):Promise<void>=>{check(signal,deadline);if(depth>HARD.treeDepth)throw new RangeError(`Admin1 output tree exceeds depth ${HARD.treeDepth}`);let info;try{info=await lstat(dir);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT'&&dir===root)return;throw error;}if(info.isSymbolicLink()||!info.isDirectory())throw new Error('Admin1 output tree has unsafe directory');const handle=await opendir(dir);for await(const item of handle){check(signal,deadline);if(++entries>HARD.treeEntries)throw new RangeError('Admin1 output tree exceeds entry cap');const filename=path.join(dir,item.name),child=await lstat(filename);if(child.isSymbolicLink())throw new Error('Admin1 output tree contains symlink');if(child.isDirectory())await walk(filename,depth+1);else if(child.isFile())bytes+=child.size;else throw new Error('Admin1 output tree contains non-regular entry');if(bytes>HARD.treeBytes)throw new RangeError('Admin1 output tree exceeds byte cap');}};await walk(root,0);return{bytes,entries};}
async function treeFiles(root:string,signal:AbortSignal,deadline:number):Promise<Array<{path:string;bytes:number}>>{const rows:Array<{path:string;bytes:number}>=[];let entries=0,totalBytes=0;const walk=async(dir:string,depth:number):Promise<void>=>{check(signal,deadline);if(depth>4)throw new RangeError('Admin1 attempt tree exceeds depth 4');let info;try{info=await lstat(dir);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT'&&dir===root)return;throw error;}if(!info.isDirectory()||info.isSymbolicLink())throw new Error('Admin1 attempt tree contains unsafe directory');const handle=await opendir(dir);for await(const item of handle){check(signal,deadline);if(++entries>HARD.auditEntries)throw new RangeError('Admin1 attempt tree exceeds entry cap');const file=path.join(dir,item.name),child=await lstat(file);if(child.isSymbolicLink())throw new Error('Admin1 attempt tree contains symlink');if(child.isDirectory())await walk(file,depth+1);else if(child.isFile()){totalBytes+=child.size;if(totalBytes>HARD.auditBytes)throw new RangeError('Admin1 attempt tree exceeds byte cap');rows.push({path:file,bytes:child.size});}else throw new Error('Admin1 attempt tree contains non-regular file');}};await walk(root,0);return rows;}
function copyBuffer(bytes:Uint8Array):ArrayBuffer{const result=new ArrayBuffer(bytes.byteLength);new Uint8Array(result).set(bytes);return result;}
function transferableBuffer(bytes:Uint8Array):ArrayBuffer{if(bytes.buffer instanceof ArrayBuffer&&bytes.byteOffset===0&&bytes.byteLength===bytes.buffer.byteLength)return bytes.buffer;return copyBuffer(bytes);}
async function runWorker(data:{source:SourceRecord;raw:Uint8Array;parent:{manifestHash:string;source:SourceRecord;raw:Uint8Array;nodes:InventoryNode[]};inspection:Uint8Array;inspectionHash:string},signal:AbortSignal,deadline:number,onWorkerOnline?:()=>void):Promise<WorkerOutput>{
 if(process.memoryUsage().rss>HARD.rssBytes)throw new RangeError('Admin1 publisher process already exceeds 512 MiB RSS');
 const input={source:data.source,raw:transferableBuffer(data.raw),parent:{manifestHash:data.parent.manifestHash,source:data.parent.source,raw:transferableBuffer(data.parent.raw),nodes:data.parent.nodes},inspection:transferableBuffer(data.inspection),inspectionHash:data.inspectionHash};
 const transfer:ArrayBuffer[]=[input.raw,input.parent.raw,input.inspection];const worker=new Worker(new URL('./admin1-publish-worker.ts',import.meta.url),{workerData:input,transferList:transfer,resourceLimits:{maxOldGenerationSizeMb:HARD.workerOldMb,maxYoungGenerationSizeMb:HARD.workerYoungMb}});
 let exited=false,reply:WorkerReply|undefined,workerError:Error|undefined,terminating:Promise<void>|undefined;let resolveExit!:(code:number)=>void;const exit=new Promise<number>(resolve=>{resolveExit=resolve;});
 worker.on('message',(value:unknown)=>{if(!value||typeof value!=='object'||Array.isArray(value)){workerError=new Error('Admin1 publisher worker reply is malformed');return;}const row=value as Record<string,unknown>;if(row.ok===true&&Object.keys(row).length===2&&row.output&&typeof row.output==='object')reply=row as unknown as WorkerReply;else if(row.ok===false&&Object.keys(row).length===2&&typeof row.error==='string'&&row.error.length<=2000)reply=row as unknown as WorkerReply;else workerError=new Error('Admin1 publisher worker reply has invalid fields');});
 worker.on('error',error=>{workerError=error;});worker.on('exit',code=>{exited=true;resolveExit(code);});if(onWorkerOnline)worker.once('online',onWorkerOnline);
 const terminateAndWait=():Promise<void>=>terminating??=(async()=>{if(!exited)await worker.terminate();await exit;})();let rejectControl!:(error:Error)=>void;const control=new Promise<never>((_,reject)=>{rejectControl=reject;});const abort=()=>{rejectControl(signal.reason instanceof Error?signal.reason:new Error('Admin1 publication aborted'));void terminateAndWait();};
 const timer=setInterval(()=>{if(process.memoryUsage().rss>HARD.rssBytes){rejectControl(new RangeError('Admin1 publisher parent RSS exceeded 512 MiB'));void terminateAndWait();}else if(performance.now()>=deadline){rejectControl(new Error('Admin1 publication exceeded its deadline'));void terminateAndWait();}},100);timer.unref();signal.addEventListener('abort',abort,{once:true});if(signal.aborted)abort();
 try{const code=await Promise.race([exit,control]);if(workerError)throw workerError;if(code!==0||!reply)throw new Error(reply&&!reply.ok?reply.error:`Admin1 publisher worker exited without a valid reply (code ${code})`);if(!reply.ok)throw new Error(reply.error);return reply.output;}finally{clearInterval(timer);signal.removeEventListener('abort',abort);if(!exited)await terminateAndWait();}
}
function assetBytes(asset:ByteAsset,label:string,expectedPath:RegExp):Uint8Array{if(!asset||typeof asset!=='object'||Object.keys(asset).length!==3||typeof asset.path!=='string'||!expectedPath.test(asset.path)||!SHA.test(asset.sha256)||!(asset.bytes instanceof ArrayBuffer))throw new TypeError(`${label} asset reference is malformed`);const bytes=new Uint8Array(asset.bytes);if(bytes.length<1||sha(bytes)!==asset.sha256)throw new Error(`${label} asset bytes do not match their hash`);const named=asset.path.split('/').at(-1)?.slice(0,-5);if(named!==asset.sha256)throw new Error(`${label} asset path does not match its content hash`);return bytes;}
function reference(asset:ByteAsset,pattern:RegExp):Admin1AssetRef{const bytes=assetBytes(asset,'published',pattern);return{path:asset.path,sha256:asset.sha256,bytes:bytes.byteLength};}
function featureMetrics(feature:Record<string,unknown>,signal:AbortSignal,deadline:number):{positions:number;polygons:number}{const geometry=feature.geometry;if(!geometry||typeof geometry!=='object'||Array.isArray(geometry))throw new Error('emitted Admin1 feature geometry must be an object');const value=geometry as Record<string,unknown>;if(value.type!=='Polygon'&&value.type!=='MultiPolygon'||!Array.isArray(value.coordinates))throw new Error('emitted Admin1 feature geometry type is invalid');let positions=0;const stack:unknown[]=[value.coordinates];while(stack.length){if(positions%1024===0)check(signal,deadline);const item=stack.pop();if(!Array.isArray(item))continue;if(item.length>=2&&item.length<=4&&item.every(ordinate=>typeof ordinate==='number'&&Number.isFinite(ordinate))){if(++positions>ADMIN1_PRODUCT_LIMITS.partitionPositions)throw new RangeError('Admin1 partition coordinate positions exceed its cap');}else for(let index=item.length-1;index>=0;index--)stack.push(item[index]);}return{positions,polygons:value.type==='Polygon'?1:value.coordinates.length};}
function sourceFeatureKey(value:unknown):string|null{let id:string;if(typeof value==='number'){if(!Number.isSafeInteger(value)||value<=0)return null;id=String(value);}else if(typeof value==='string'&&/^[1-9][0-9]*$/.test(value)){const n=Number(value);if(!Number.isSafeInteger(n)||String(n)!==value)return null;id=value;}else return null;return`NE_ID:${id}`;}
function validateWorkerOutput(output:WorkerOutput,source:SourceRecord,parentManifestHash:string,inspectionHash:string,signal:AbortSignal,deadline:number):void{
 const expectedTop=['report','globalIndex','partitions','countries','entries','inspection','sourceUnits','emittedUnits','protected','unlinked','ambiguous','exceptionUnits','logicalBytes'];if(!output||typeof output!=='object'||Object.keys(output).length!==expectedTop.length||Object.keys(output).some(k=>!expectedTop.includes(k)))throw new TypeError('Admin1 publisher worker output has missing or unknown fields');
 if(!Array.isArray(output.entries)||output.entries.length<1||output.entries.length>ADMIN1_PRODUCT_LIMITS.sourceUnits||output.sourceUnits!==output.entries.length||!Array.isArray(output.partitions)||output.partitions.length>ADMIN1_PRODUCT_LIMITS.partitions||!Array.isArray(output.countries)||output.countries.length>ADMIN1_PRODUCT_LIMITS.countries||output.inspection.source.sha256!==source.sha256||output.inspection.source.bytes!==source.bytes||output.inspection.parent.manifestHash!==parentManifestHash)throw new Error('Admin1 publisher worker counts/source binding invalid');
 const report=assetBytes(output.report,'report',new RegExp(`^reports/${inspectionHash}\\.json$`));if(report.byteLength>ADMIN1_PRODUCT_LIMITS.reportBytes||sha(report)!==inspectionHash)throw new Error('Admin1 publication report asset is not the bounded inspected report');check(signal,deadline);const reportValue=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(report.subarray(0,-1))) as unknown;if(canonical(reportValue)!==canonical(output.inspection))throw new Error('Admin1 worker inspection differs from the pinned report bytes');
 const global=assetBytes(output.globalIndex,'global index',/^indexes\/[a-f0-9]{64}\.json$/);if(global.byteLength>ADMIN1_PRODUCT_LIMITS.globalIndexBytes)throw new RangeError('Admin1 global index exceeds its byte cap');check(signal,deadline);const indexText=new TextDecoder('utf-8',{fatal:true}).decode(global);if(!indexText.startsWith('[')||!indexText.endsWith(']'))throw new Error('Admin1 global index is invalid canonical JSON');
 const entriesByKey=new Map<string,Admin1PartitionEntry>(),ordinals=new Set<number>(),auditRows=new Map(output.inspection.rows.map(row=>[row.sourceKey,row]));let previous='';for(const entry of output.entries){check(signal,deadline);if(!entry||typeof entry.sourceKey!=='string'||entry.sourceKey<=previous||entriesByKey.has(entry.sourceKey)||!SHA.test(entry.featureSha256)||!Number.isSafeInteger(entry.sourceOrdinal)||entry.sourceOrdinal<0||entry.sourceOrdinal>=output.sourceUnits||ordinals.has(entry.sourceOrdinal)||!['linked','protected','unlinked','ambiguous'].includes(entry.joinStatus))throw new Error('Admin1 worker entry identity is invalid');const audit=auditRows.get(entry.sourceKey),expected={...audit,partitionPath:entry.partitionPath,exception:entry.exception};if(!audit||Object.keys(entry).length!==14||canonical(entry)!==canonical(expected)||((entry.partitionPath===null)===(entry.exception===null))||entry.partitionPath!==null&&!/^partitions\/[a-f0-9]{64}\.json$/.test(entry.partitionPath)||entry.exception!==null&&(typeof entry.exception!=='string'||entry.exception.length<1||entry.exception.length>512)||entry.joinStatus==='protected'&&(entry.partitionPath!==null||entry.exception!=='protected-nigeria-no-geometry'))throw new Error('Admin1 partition entry differs from pinned audit, or its path/exception assignment is invalid');previous=entry.sourceKey;entriesByKey.set(entry.sourceKey,entry);ordinals.add(entry.sourceOrdinal);}
 if(ordinals.size!==output.sourceUnits||auditRows.size!==output.sourceUnits)throw new Error('Admin1 source ordinals do not conserve the inspected denominator');
 const globalValue=JSON.parse(indexText) as unknown;if(canonical(globalValue)!==indexText||!Array.isArray(globalValue)||globalValue.length!==output.entries.length)throw new Error('Admin1 global index source denominator or canonical encoding mismatch');for(let i=0;i<globalValue.length;i++){check(signal,deadline);const entry=output.entries[i]!,item=globalValue[i] as Record<string,unknown>,expected={sourceOrdinal:entry.sourceOrdinal,sourceKey:entry.sourceKey,id:entry.id,featureSha256:entry.featureSha256,countryId:entry.countryId,joinStatus:entry.joinStatus,partitionPath:entry.partitionPath,exception:entry.exception};if(Object.keys(item).length!==8||canonical(item)!==canonical(expected))throw new Error('Admin1 global index does not bind the exact audited source entries');}
 const featureMembership=new Map<string,number>();for(const asset of output.partitions){check(signal,deadline);const bytes=assetBytes(asset,'partition',/^partitions\/[a-f0-9]{64}\.json$/);if(bytes.length>ADMIN1_PRODUCT_LIMITS.partitionBytes)throw new RangeError('Admin1 partition exceeds its byte cap');const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes),value=JSON.parse(text) as Record<string,unknown>;if(canonical(value)!==text||!value||Object.keys(value).length!==5||value.schemaVersion!==1||value.product!==ADMIN1_PRODUCT||!Array.isArray(value.features)||value.features.length<1||value.features.length>ADMIN1_PRODUCT_LIMITS.partitionFeatures||!['linked','unlinked','ambiguous'].includes(String(value.joinStatus))||typeof value.parentCountryId!=='string'&&value.parentCountryId!==null)throw new Error('Admin1 partition shape or canonical encoding is invalid');let partitionPositions=0;for(const feature of value.features){check(signal,deadline);if(!feature||typeof feature!=='object'||Array.isArray(feature))throw new Error('Admin1 partition feature is invalid');const row=feature as Record<string,unknown>,props=row.properties as Record<string,unknown>|null;const key=sourceFeatureKey(props?.ne_id);if(!key)throw new Error('Admin1 partition source key is missing or noncanonical');const entry=entriesByKey.get(key),metrics=featureMetrics(row,signal,deadline);partitionPositions+=metrics.positions;if(metrics.positions>ADMIN1_PRODUCT_LIMITS.featurePositions||partitionPositions>ADMIN1_PRODUCT_LIMITS.partitionPositions||!entry||metrics.positions!==entry.positions||metrics.polygons!==entry.polygons||entry.partitionPath!==asset.path||entry.joinStatus!==value.joinStatus||entry.countryId!==value.parentCountryId||sha(canonical(row))!==entry.featureSha256)throw new Error('Admin1 partition feature differs from its exact audited source binding or position limits');featureMembership.set(key,(featureMembership.get(key)??0)+1);}}
 for(const entry of output.entries){if(entry.partitionPath){if(featureMembership.get(entry.sourceKey)!==1)throw new Error('emitted Admin1 feature does not occur exactly once in partition assets');}else if(featureMembership.has(entry.sourceKey))throw new Error('exception Admin1 feature unexpectedly has geometry');}
 const countryIndexMembership=new Map<string,number>();for(const country of output.countries){check(signal,deadline);if(!country||Object.keys(country).length!==4||typeof country.countryId!=='string'||!Number.isSafeInteger(country.sourceUnits)||!Number.isSafeInteger(country.emittedUnits)||country.sourceUnits<1||country.emittedUnits<0||country.emittedUnits>country.sourceUnits)throw new Error('Admin1 country-index worker result is invalid');const bytes=assetBytes(country.asset,'country index',/^countries\/[a-f0-9]{64}\.json$/);if(bytes.length>ADMIN1_PRODUCT_LIMITS.countryIndexBytes)throw new RangeError('Admin1 country index exceeds its byte cap');const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes),index=JSON.parse(text) as Admin1CountryIndex;if(!text.endsWith('\n')||`${canonical(index)}\n`!==text||!index||Object.keys(index).length!==9||index.schemaVersion!==1||index.product!==ADMIN1_PRODUCT||index.countryId!==country.countryId||index.sourceSha256!==source.sha256||index.parentManifestHash!==parentManifestHash||index.inspectionSha256!==inspectionHash||index.sourceUnits!==country.sourceUnits||index.emittedUnits!==country.emittedUnits||!Array.isArray(index.rows)||index.rows.length!==country.sourceUnits||index.emittedUnits!==index.rows.filter(row=>row.partitionPath!==null).length)throw new Error('Admin1 country index binding or canonical encoding is invalid');let previousKey='';for(const row of index.rows){check(signal,deadline);const rowKeys=['sourceOrdinal','sourceKey','id','featureSha256','countryId','joinStatus','partitionPath','exception','name','sourceType','sourceTypeEn','gadmLevel','positions','polygons'];const textFields=[row.name,row.sourceType,row.sourceTypeEn];const entry=entriesByKey.get(row.sourceKey);if(Object.keys(row).length!==rowKeys.length||Object.keys(row).some(key=>!rowKeys.includes(key))||textFields.some(value=>value!==null&&(typeof value!=='string'||value.length>2048||/[\u0000-\u001f\u007f]/.test(value)))||row.gadmLevel!==null&&(!Number.isSafeInteger(row.gadmLevel)||row.gadmLevel< -1||row.gadmLevel>100)||!Number.isSafeInteger(row.positions)||row.positions<0||!Number.isSafeInteger(row.polygons)||row.polygons<0||row.sourceKey<=previousKey||!entry||entry.joinStatus!=='linked'||entry.countryId!==country.countryId||row.featureSha256!==entry.featureSha256||row.sourceOrdinal!==entry.sourceOrdinal||row.id!==entry.id||row.partitionPath!==entry.partitionPath||row.exception!==entry.exception||row.positions!==entry.positions||row.polygons!==entry.polygons)throw new Error('Admin1 country index row differs from global source identity');previousKey=row.sourceKey;countryIndexMembership.set(row.sourceKey,(countryIndexMembership.get(row.sourceKey)??0)+1);}}
 for(const entry of output.entries){if(entry.joinStatus==='linked'&&countryIndexMembership.get(entry.sourceKey)!==1)throw new Error('linked Admin1 source row must occur once in its country index');if(entry.joinStatus!=='linked'&&countryIndexMembership.has(entry.sourceKey))throw new Error('non-linked Admin1 source row must not occur in a country index');}
 const emitted=output.entries.filter(entry=>entry.partitionPath!==null).length,exceptions=output.entries.length-emitted;if(output.emittedUnits!==emitted||output.exceptionUnits!==exceptions||output.protected!==output.entries.filter(e=>e.joinStatus==='protected').length||output.unlinked!==output.entries.filter(e=>e.joinStatus==='unlinked').length||output.ambiguous!==output.entries.filter(e=>e.joinStatus==='ambiguous').length)throw new Error('Admin1 worker output counters do not conserve source rows');
}
async function missingBytes(outputRoot:string,assets:ByteAsset[],signal:AbortSignal,deadline:number):Promise<{bytes:number;newEntries:number;newDirectories:number;scratchBytes:number}>{let bytes=0,newEntries=0,scratchBytes=0;const missingDirectories=new Set<string>();for(const asset of assets){check(signal,deadline);const body=new Uint8Array(asset.bytes);scratchBytes=Math.max(scratchBytes,body.byteLength);const target=path.join(outputRoot,...asset.path.split('/'));await safePath(target);check(signal,deadline);for(const folder of asset.path.split('/').slice(0,-1)){const directory=path.join(outputRoot,...asset.path.split('/').slice(0,asset.path.split('/').indexOf(folder)+1));try{const dirInfo=await lstat(directory);if(dirInfo.isSymbolicLink()||!dirInfo.isDirectory())throw new Error('Admin1 asset ancestor is not a safe directory');}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')missingDirectories.add(directory);else throw error;}}
  try{const info=await lstat(target);if(info.isSymbolicLink()||!info.isFile())throw new Error('Admin1 immutable asset collision is not a regular file');if(info.size!==body.byteLength)throw new Error('Admin1 immutable output collision has a different byte length');const existing=await readBoundedLocalFile(target,body.byteLength);check(signal,deadline);if(existing.byteLength!==body.byteLength||sha(existing)!==asset.sha256)throw new Error('Admin1 immutable output collision has different content');}
  catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT'){bytes+=body.byteLength;newEntries++;}else throw error;}}
 return{bytes,newEntries,newDirectories:missingDirectories.size,scratchBytes};}
function safeRecord(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError('Admin1 attempt record must be an object');return value as Record<string,unknown>;}
function validIso(value:unknown):value is string{if(typeof value!=='string')return false;const time=Date.parse(value);return Number.isFinite(time)&&new Date(time).toISOString()===value;}
function exactFields(value:Record<string,unknown>,fields:readonly string[]):boolean{return Object.keys(value).length===fields.length&&Object.keys(value).every(key=>fields.includes(key));}
function validSourceRecord(value:unknown,maxBytes:number):boolean{if(!value||typeof value!=='object'||Array.isArray(value))return false;const source=value as Record<string,unknown>;return exactFields(source,['id','url','release','license','attribution','sha256','bytes'])&&typeof source.id==='string'&&source.id.length>0&&source.id.length<=200&&typeof source.url==='string'&&source.url.length<=2048&&typeof source.release==='string'&&HEX40.test(source.release)&&typeof source.license==='string'&&source.license.length>0&&source.license.length<=512&&typeof source.attribution==='string'&&source.attribution.length>0&&source.attribution.length<=2048&&typeof source.sha256==='string'&&SHA.test(source.sha256)&&Number.isSafeInteger(source.bytes)&&Number(source.bytes)>0&&Number(source.bytes)<=maxBytes;}
function validateAttemptRecord(record:Record<string,unknown>,filename:string):{requestHash:string;status:string}{
 const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
 if(!filename.endsWith('.json')||!uuid.test(path.basename(filename,'.json'))||record.attemptId!==path.basename(filename,'.json'))throw new Error('Admin1 attempt filename and UUID do not match');
 const base=['schemaVersion','attemptId','requestHash','product','request','status','startedAt','sourceSha256','sourceBytes','parentManifestHash','inspectionHash','networkBytes'];
 const status=record.status;if(!['pending','succeeded','failed','aborted','timed-out'].includes(String(status)))throw new Error('Admin1 attempt history has an invalid status');
 const terminal=status==='pending'?[]:status==='succeeded'?['finishedAt','elapsedMs','manifestHash','bytes','sourceUnits','emittedUnits','partitions']:['finishedAt','elapsedMs','error'];
 if(!exactFields(record,[...base,...terminal])||record.schemaVersion!==1||record.product!==ADMIN1_PRODUCT||!SHA.test(String(record.requestHash))||!SHA.test(String(record.sourceSha256))||!Number.isSafeInteger(record.sourceBytes)||Number(record.sourceBytes)<1||!SHA.test(String(record.parentManifestHash))||!SHA.test(String(record.inspectionHash))||record.networkBytes!==0||!validIso(record.startedAt))throw new Error('Admin1 attempt history record fields or bindings are invalid');
 const request=safeRecord(record.request);if(!exactFields(request,['product','sourcePin','parentPin','inspectionHash'])||request.product!==ADMIN1_PRODUCT||request.inspectionHash!==record.inspectionHash||sha(canonical(request))!==record.requestHash)throw new Error('Admin1 attempt request payload hash is invalid');
 const sourcePin=safeRecord(request.sourcePin),parentPin=safeRecord(request.parentPin);if(!exactFields(sourcePin,['schemaVersion','source','input','gitBlobSha1'])||sourcePin.schemaVersion!==1||typeof sourcePin.input!=='string'||!HEX40.test(String(sourcePin.gitBlobSha1))||!exactFields(parentPin,['manifestHash','directoryRoot','source','input'])||!SHA.test(String(parentPin.manifestHash))||parentPin.directoryRoot!=='.cache/world-build/output/country-inventory'||typeof parentPin.input!=='string'||!validSourceRecord(sourcePin.source,HARD.sourceBytes)||!validSourceRecord(parentPin.source,HARD.parentBytes)||record.sourceSha256!==(sourcePin.source as SourceRecord).sha256||record.sourceBytes!==(sourcePin.source as SourceRecord).bytes||record.parentManifestHash!==parentPin.manifestHash)throw new Error('Admin1 attempt source or parent history binding is invalid');
 if(status!=='pending'){if(!validIso(record.finishedAt)||Date.parse(record.finishedAt as string)<Date.parse(record.startedAt as string)||!Number.isSafeInteger(record.elapsedMs)||Number(record.elapsedMs)<1||Number(record.elapsedMs)>HARD.durationMs+5_000)throw new Error('Admin1 terminal attempt timestamps or elapsed time are invalid');if(status==='succeeded'){if(!SHA.test(String(record.manifestHash))||!Number.isSafeInteger(record.bytes)||Number(record.bytes)<1||Number(record.bytes)>ADMIN1_PRODUCT_LIMITS.logicalBytes||![record.sourceUnits,record.emittedUnits,record.partitions].every(n=>Number.isSafeInteger(n)&&Number(n)>=0)||Number(record.sourceUnits)>ADMIN1_PRODUCT_LIMITS.sourceUnits||Number(record.emittedUnits)>Number(record.sourceUnits)||Number(record.partitions)>ADMIN1_PRODUCT_LIMITS.partitions)throw new Error('Admin1 successful attempt result fields are invalid');}else if(typeof record.error!=='string'||record.error.length<1||record.error.length>2_000)throw new Error('Admin1 failed attempt error is invalid');}
 return{requestHash:record.requestHash as string,status:String(status)};
}
export interface PublishAdmin1SourceOptions {repositoryRoot:string;sourcePin:Admin1SourcePin;parentPin:Admin1ParentPin;inspectionHash:string;inspectionPath:string;signal?:AbortSignal;durationMs?:number;onWorkerOnline?:()=>void;onAssetWritten?:(relativePath:string)=>void;/** Test-only mutation seam, invoked only after the real worker replies. */onWorkerOutputForTest?:(output:unknown)=>void}
/** Publish a verified Natural Earth Admin 1 foundation under its own immutable namespace. */
export async function publishAdmin1Source(options:PublishAdmin1SourceOptions):Promise<Admin1PublishedResult>{
 const start=performance.now(),duration=options.durationMs??HARD.durationMs;if(!Number.isSafeInteger(duration)||duration<1||duration>HARD.durationMs)throw new RangeError('Admin1 publication duration must be 1..120,000 ms');const root=options.repositoryRoot;if(!path.isAbsolute(root)||path.resolve(root)!==root)throw new TypeError('repositoryRoot must be canonical absolute');
 const buildRoot=path.join(root,'.cache','world-build'),outputRoot=path.join(buildRoot,'output','admin1-foundation'),deadline=start+duration,deadlineController=new AbortController(),deadlineTimer=setTimeout(()=>deadlineController.abort(new Error('Admin1 publication exceeded its deadline')),duration);deadlineTimer.unref();const signal=options.signal?AbortSignal.any([options.signal,deadlineController.signal]):deadlineController.signal;
 let attemptStore:Awaited<ReturnType<typeof createOutputStore>>|undefined,attemptId:string|undefined,baseRecord:Record<string,unknown>|undefined;
 try{
  await safePath(root);const rootInfo=await lstat(root);if(!rootInfo.isDirectory()||rootInfo.isSymbolicLink())throw new Error('repositoryRoot must be a real directory');
  const validSource=(value:SourceRecord,maxBytes:number):boolean=>!!value&&Object.keys(value).length===7&&typeof value.id==='string'&&value.id.length>0&&value.id.length<=200&&typeof value.url==='string'&&value.url.length<=2048&&typeof value.release==='string'&&HEX40.test(value.release)&&typeof value.license==='string'&&value.license.length>0&&value.license.length<=512&&typeof value.attribution==='string'&&value.attribution.length>0&&value.attribution.length<=2048&&SHA.test(value.sha256)&&Number.isSafeInteger(value.bytes)&&value.bytes>0&&value.bytes<=maxBytes;
  if(!options.sourcePin||Object.keys(options.sourcePin).length!==4||options.sourcePin.schemaVersion!==1||!HEX40.test(options.sourcePin.gitBlobSha1)||typeof options.sourcePin.input!=='string'||!validSource(options.sourcePin.source,HARD.sourceBytes))throw new TypeError('Admin1 source pin is invalid');
  if(!options.parentPin||Object.keys(options.parentPin).length!==4||!SHA.test(options.parentPin.manifestHash)||options.parentPin.directoryRoot!=='.cache/world-build/output/country-inventory'||!validSource(options.parentPin.source,HARD.parentBytes)||typeof options.parentPin.input!=='string')throw new TypeError('Admin1 parent pin is invalid');
  if(options.sourcePin.source.release!==options.parentPin.source.release||!HEX40.test(options.sourcePin.source.release))throw new Error('Admin1 and parent sources must use the same full release');
  if(!SHA.test(options.inspectionHash)||typeof options.inspectionPath!=='string')throw new TypeError('Admin1 inspection binding is invalid');
  const inspectionMatch=/^\.cache\/world-build\/admin1-inspections\/reports\/([a-f0-9]{64})\/([a-f0-9]{64})\.json$/.exec(options.inspectionPath);if(!inspectionMatch||inspectionMatch[2]!==options.inspectionHash)throw new Error('Admin1 inspection path must be the exact hash-addressed report path');
  const expectedInspectionRequest=sha(canonical({inspector:'natural-earth-admin1-structural-v1',sourcePin:options.sourcePin,parentPin:options.parentPin}));if(inspectionMatch[1]!==expectedInspectionRequest)throw new Error('Admin1 inspection path request identity differs from the exact source and parent pins');
  const sourcePath=path.resolve(root,options.sourcePin.input),parentPath=path.resolve(root,options.parentPin.input),inspectionPath=path.resolve(root,options.inspectionPath);for(const [input,absolute,folder]of [[options.sourcePin.input,sourcePath,'admin1-source-cache'],[options.parentPin.input,parentPath,'country-source-cache']] as const){if(path.isAbsolute(input)||path.normalize(input)!==input||path.relative(root,absolute)!==input||!inside(buildRoot,absolute)||path.dirname(absolute)!==path.join(buildRoot,folder)||!/^[a-f0-9]{64}\.geojson$/.test(path.basename(absolute)))throw new Error('Admin1 pinned source path is not an exact cache-relative source path');await safePath(absolute);}
  if(path.relative(buildRoot,inspectionPath)!==options.inspectionPath.slice('.cache/world-build/'.length))throw new Error('Admin1 inspection path escapes the fixed build cache');await safePath(inspectionPath);check(signal,deadline);
  const result=await withAcquisitionBuildLock(buildRoot,async()=>{
   check(signal,deadline);await safePath(sourcePath);await safePath(parentPath);await safePath(inspectionPath);
   const sourceRaw=await readBoundedLocalFile(sourcePath,HARD.sourceBytes);check(signal,deadline);if(sourceRaw.length!==options.sourcePin.source.bytes||sha(sourceRaw)!==options.sourcePin.source.sha256||createHash('sha1').update(`blob ${sourceRaw.length}\0`).update(sourceRaw).digest('hex')!==options.sourcePin.gitBlobSha1)throw new Error('Admin1 cached source differs from its exact SHA-256/Git blob pin');
   const parentRaw=await readBoundedLocalFile(parentPath,HARD.parentBytes);check(signal,deadline);if(parentRaw.length!==options.parentPin.source.bytes||sha(parentRaw)!==options.parentPin.source.sha256)throw new Error('Admin0 parent source differs from exact pin');
   const inspectionRaw=await readBoundedLocalFile(inspectionPath,ADMIN1_PRODUCT_LIMITS.reportBytes);check(signal,deadline);if(inspectionRaw.length<2||inspectionRaw.length>ADMIN1_PRODUCT_LIMITS.reportBytes||inspectionRaw.at(-1)!==10||sha(inspectionRaw)!==options.inspectionHash)throw new Error('Admin1 inspection report is not exact bounded canonical newline-terminated hash bytes');
   const inspection=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(inspectionRaw.subarray(0,-1))) as Admin1InspectionReport;check(signal,deadline);if(inspection.source.sha256!==options.sourcePin.source.sha256||inspection.source.bytes!==sourceRaw.length||inspection.parent.manifestHash!==options.parentPin.manifestHash||canonical(inspection.source)!==canonical(options.sourcePin.source)||canonical(inspection.parent.source)!==canonical(options.parentPin.source))throw new Error('Admin1 inspection source/parent binding does not match publication pins');
   const directoryRoot=path.resolve(root,options.parentPin.directoryRoot);await safePath(directoryRoot);const directory=await readCountryDirectory(directoryRoot,options.parentPin.manifestHash,signal);check(signal,deadline);if(canonical(directory.manifest.source)!==canonical(options.parentPin.source))throw new Error('Admin1 parent source pin differs from the verified directory manifest');
   // The directory reader validates its manifest and all node/index bindings; the pin separately binds source bytes.
   if(!Array.isArray(directory.nodes)||!directory.nodes.some(node=>node.kind==='country'&&node.id==='legacy-ng'&&node.provider==='legacy-ng'&&node.countryCode==='NG'))throw new Error('Admin1 verified parent lacks protected Nigeria');
   const request={product:ADMIN1_PRODUCT,sourcePin:options.sourcePin,parentPin:options.parentPin,inspectionHash:options.inspectionHash};const requestHash=sha(canonical(request));
   await safePath(outputRoot);const outputUse=await treeUsage(outputRoot,signal,deadline),auditRoot=path.join(buildRoot,'admin1-publish-attempts'),auditFiles=await treeFiles(auditRoot,signal,deadline);
   if(auditFiles.length+2>HARD.auditEntries)throw new RangeError('Admin1 publication audit exceeds 128-entry cap');let auditBytes=0,attemptCount=0;
   for(const file of auditFiles){check(signal,deadline);auditBytes+=file.bytes;if(file.bytes>HARD.auditRecordBytes)throw new RangeError('Admin1 publication audit record exceeds 8 KiB');const bytes=await readBoundedLocalFile(file.path,HARD.auditRecordBytes);check(signal,deadline);const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes),record=safeRecord(JSON.parse(text)),validated=validateAttemptRecord(record,file.path);if(`${canonical(record)}\n`!==text)throw new Error('Admin1 attempt history is not canonical newline-terminated JSON');if(validated.requestHash===requestHash)attemptCount++;}
   if(auditBytes+HARD.auditReserveBytes>HARD.auditBytes)throw new RangeError('Admin1 publication audit exceeds 1 MiB');if(attemptCount>=ADMIN1_PRODUCT_LIMITS.attemptsPerRequest)throw new RangeError('Admin1 publication request exhausted its eight lifetime attempts');
   const disk=await statfs(buildRoot);if(disk.bavail*disk.bsize<HARD.freeBytes+HARD.auditReserveBytes)throw new RangeError('Admin1 publication requires 100 MiB free plus audit reserve');
   if(outputUse.bytes>HARD.treeBytes||outputUse.entries+12>HARD.treeEntries)throw new RangeError('Admin1 output tree has no bounded headroom for this publication');
   attemptId=randomUUID();attemptStore=await createOutputStore(auditRoot,buildRoot);baseRecord={schemaVersion:1,attemptId,requestHash,product:ADMIN1_PRODUCT,request,status:'pending',startedAt:new Date().toISOString(),sourceSha256:options.sourcePin.source.sha256,sourceBytes:sourceRaw.length,parentManifestHash:options.parentPin.manifestHash,inspectionHash:options.inspectionHash,networkBytes:0};
   const pending=Buffer.from(`${canonical(baseRecord)}\n`);if(pending.length>HARD.auditRecordBytes)throw new RangeError('Admin1 pending audit exceeds 8 KiB');await attemptStore.writeImmutable(`${attemptId}.json`,pending);
   let success=false,failure='Admin1 publication did not complete',caughtError:unknown;
   try{
    check(signal,deadline);const output=await runWorker({source:options.sourcePin.source,raw:sourceRaw,parent:{manifestHash:options.parentPin.manifestHash,source:options.parentPin.source,raw:parentRaw,nodes:directory.nodes},inspection:inspectionRaw,inspectionHash:options.inspectionHash},signal,deadline,options.onWorkerOnline);check(signal,deadline);options.onWorkerOutputForTest?.(output);check(signal,deadline);validateWorkerOutput(output,options.sourcePin.source,options.parentPin.manifestHash,options.inspectionHash,signal,deadline);check(signal,deadline);
    const pathRows=new Map(directory.nodes.filter(node=>node.kind==='country').map(node=>[node.id,node]));if(pathRows.size>ADMIN1_PRODUCT_LIMITS.countries||pathRows.size<1)throw new Error('Admin1 parent country denominator is invalid');
    const countryIndexById=new Map(output.countries.map(row=>[row.countryId,row]));if(countryIndexById.size!==output.countries.length)throw new Error('Admin1 country indexes contain duplicate country identities');
    const countries:Admin1CountryRef[]=[...pathRows.values()].sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0).map(node=>{check(signal,deadline);if(node.id==='legacy-ng'||node.provider==='legacy-ng'||node.countryCode==='NG'){if(node.id!=='legacy-ng'||node.countryCode!=='NG'||node.provider!=='legacy-ng')throw new Error('Admin1 protected Nigeria parent identity changed');const sourceUnits=output.entries.filter(entry=>entry.joinStatus==='protected').length;return{countryId:node.id,status:'protected',sourceUnits,emittedUnits:0,index:null};}const country=countryIndexById.get(node.id);if(!country)return{countryId:node.id,status:'missing',sourceUnits:0,emittedUnits:0,index:null};return{countryId:node.id,status:'available',sourceUnits:country.sourceUnits,emittedUnits:country.emittedUnits,index:reference(country.asset,/^countries\/[a-f0-9]{64}\.json$/)};});
    if(countries.filter(item=>item.status==='protected').length!==1||countries.filter(item=>item.status==='available').length!==output.countries.length)throw new Error('Admin1 parent-country indexes do not conserve linked and protected identities');
    const assets:ByteAsset[]=[output.report,output.globalIndex,...output.partitions,...output.countries.map(x=>x.asset)];const refsPartitions:Admin1AssetRef[]=[];for(const asset of output.partitions){check(signal,deadline);refsPartitions.push(reference(asset,/^partitions\/[a-f0-9]{64}\.json$/));}const inspectionRef=reference(output.report,/^reports\/[a-f0-9]{64}\.json$/),globalIndexRef=reference(output.globalIndex,/^indexes\/[a-f0-9]{64}\.json$/);check(signal,deadline);
    const manifest:Admin1ProductManifest={schemaVersion:1,product:ADMIN1_PRODUCT,source:options.sourcePin.source,parent:{manifestHash:options.parentPin.manifestHash,source:options.parentPin.source},validation:{structural:'passed-with-explicit-exceptions',topology:'unverified'},sourceUnits:output.sourceUnits,sourcePositions:inspection.sourcePositions,sourcePolygons:inspection.sourcePolygons,linked:inspection.linked,protected:inspection.protected,unlinked:inspection.unlinked,ambiguous:inspection.ambiguous,emittedUnits:output.emittedUnits,exceptionUnits:output.exceptionUnits,inspection:inspectionRef,globalIndex:globalIndexRef,partitions:refsPartitions,countries,limitations:[...inspection.limitations,'Topology has not been independently verified.','This administrative foundation is not playable content.']};
    const manifestBytes=new TextEncoder().encode(`${canonical(manifest)}\n`);if(manifestBytes.length>ADMIN1_PRODUCT_LIMITS.manifestBytes)throw new RangeError('Admin1 root manifest exceeds its 256 KiB cap');const manifestAsset:ByteAsset={path:`manifests/${sha(manifestBytes)}.json`,sha256:sha(manifestBytes),bytes:manifestBytes.buffer.slice(manifestBytes.byteOffset,manifestBytes.byteOffset+manifestBytes.byteLength) as ArrayBuffer};assets.push(manifestAsset);
    const uniquePaths=new Set<string>();for(const asset of assets){check(signal,deadline);if(uniquePaths.has(asset.path))throw new Error('Admin1 publication has duplicate immutable asset paths');uniquePaths.add(asset.path);if(new Uint8Array(asset.bytes).byteLength<1)throw new Error('Admin1 publication contains an empty output asset');}
    const actualLogical=assets.reduce((sum,asset)=>sum+new Uint8Array(asset.bytes).byteLength,0);if(actualLogical>ADMIN1_PRODUCT_LIMITS.logicalBytes||actualLogical!==output.logicalBytes+manifestBytes.length)throw new RangeError('Admin1 published logical bytes exceed or differ from the planned accounting');
    const currentOutput=await treeUsage(outputRoot,signal,deadline),missing=await missingBytes(outputRoot,assets,signal,deadline);if(currentOutput.bytes+missing.bytes+missing.scratchBytes>HARD.treeBytes||currentOutput.entries+missing.newEntries+missing.newDirectories+1>HARD.treeEntries)throw new RangeError('Admin1 publication exceeds aggregate output tree byte/entry caps including temporary-file headroom');const currentDisk=await statfs(buildRoot);check(signal,deadline);if(currentDisk.bavail*currentDisk.bsize<HARD.freeBytes+missing.bytes+missing.scratchBytes+HARD.auditReserveBytes)throw new RangeError('Admin1 publication lacks 100 MiB free space plus missing assets, scratch file and audit reserve');
    const store=await createOutputStore(outputRoot,buildRoot);for(const asset of assets.filter(value=>value.path!==manifestAsset.path)){check(signal,deadline);const bytes=new Uint8Array(asset.bytes);await store.writeImmutable(asset.path,bytes);check(signal,deadline);options.onAssetWritten?.(asset.path);check(signal,deadline);}
    const afterAssets=await treeUsage(outputRoot,signal,deadline);if(afterAssets.bytes>HARD.treeBytes||afterAssets.entries>HARD.treeEntries)throw new RangeError('Admin1 output tree exceeds aggregate cap before manifest publication');check(signal,deadline);
    const manifestPath=await store.writeImmutable(manifestAsset.path,new Uint8Array(manifestAsset.bytes));check(signal,deadline);const finalUsage=await treeUsage(outputRoot,signal,deadline);if(finalUsage.bytes>HARD.treeBytes||finalUsage.entries>HARD.treeEntries)throw new RangeError('Admin1 output tree exceeds aggregate cap');
    const finalResult:Admin1PublishedResult={manifestHash:manifestAsset.sha256,manifestPath,bytes:actualLogical,sourceUnits:output.sourceUnits,emittedUnits:output.emittedUnits,partitions:output.partitions.length,elapsedMs:Math.max(1,Math.floor(performance.now()-start)),networkBytes:0};
    const terminal=Buffer.from(`${canonical({...baseRecord,status:'succeeded',finishedAt:new Date().toISOString(),elapsedMs:finalResult.elapsedMs,manifestHash:finalResult.manifestHash,bytes:finalResult.bytes,sourceUnits:finalResult.sourceUnits,emittedUnits:finalResult.emittedUnits,partitions:finalResult.partitions,networkBytes:0})}\n`);if(terminal.length>HARD.auditRecordBytes)throw new RangeError('Admin1 terminal audit exceeds 8 KiB');await attemptStore.writeAtomic(`${attemptId}.json`,terminal);success=true;return finalResult;
   }catch(error){caughtError=error;failure=errorText(error);throw error;}
   finally{if(!success){const status=options.signal?.aborted?'aborted':deadlineController.signal.aborted?'timed-out':'failed';const terminal=Buffer.from(`${canonical({...baseRecord,status,finishedAt:new Date().toISOString(),elapsedMs:Math.max(1,Math.floor(performance.now()-start)),error:failure,networkBytes:0})}\n`);if(terminal.length>HARD.auditRecordBytes)throw new AggregateError(caughtError?[caughtError]:[],'Admin1 publication failed and its bounded terminal audit record exceeded 8 KiB');try{await attemptStore.writeAtomic(`${attemptId}.json`,terminal);}catch(auditError){throw new AggregateError(caughtError?[caughtError,auditError]:[auditError],'Admin1 publication failed and its terminal audit could not be persisted');}}}
  },{signal,timeoutMs:Math.max(1,Math.floor(deadline-performance.now()))});return result;
 }finally{clearTimeout(deadlineTimer);}
}
