import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readBoundedLocalFile } from './inventory-reader.ts';
import { publishClimateAttachment } from './climate-attachment-publish.ts';
import { validateClimateAttachmentBinding } from './climate-attachment-compile.ts';
import { CLIMATE_ATTACHMENT_LIMITS, CLIMATE_ATTACHMENT_POLICY } from './climate-attachment-types.ts';

const WORLD=path.dirname(fileURLToPath(import.meta.url));
function parseArgs(values:string[]):{id:string|null;durationMs?:number}{const command=values.shift();if(command!=='build'&&command!=='build-all')throw new Error('usage: climate-attachment-cli.ts build <id> [--duration-ms N] | build-all [--duration-ms N]');const id=command==='build'?values.shift()??null:null;let durationMs:number|undefined;while(values.length){const flag=values.shift();if(flag!=='--duration-ms'||durationMs!==undefined)throw new Error('unknown or duplicate climate attachment option');const value=values.shift();if(!value||!/^[0-9]+$/.test(value))throw new Error('--duration-ms must be an integer from 1 to 60000');durationMs=Number(value);if(!Number.isSafeInteger(durationMs)||durationMs<1||durationMs>CLIMATE_ATTACHMENT_LIMITS.durationMs)throw new Error('--duration-ms must be an integer from 1 to 60000');}if(command==='build'&&(!id||!/^[a-z0-9-]{1,48}$/.test(id)))throw new Error('build requires a known lowercase id');if(command==='build-all'&&id!==null)throw new Error('build-all takes no id');return durationMs===undefined?{id}:{id,durationMs};}
async function main():Promise<void>{const options=parseArgs(process.argv.slice(2));const bytes=await readBoundedLocalFile(path.join(WORLD,'climate-attachment-pins.json'),CLIMATE_ATTACHMENT_LIMITS.pinBytes);const value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes)) as {schemaVersion?:unknown;policy?:unknown;bindings?:unknown};if(Object.keys(value).sort().join(',')!=='bindings,policy,schemaVersion'||value.schemaVersion!==1||value.policy!==CLIMATE_ATTACHMENT_POLICY||!Array.isArray(value.bindings)||value.bindings.length<1||value.bindings.length>CLIMATE_ATTACHMENT_LIMITS.jobs)throw new Error('climate attachment pin registry shape or policy invalid');const bindings=value.bindings.map(validateClimateAttachmentBinding);if(new Set(bindings.map(x=>x.id)).size!==bindings.length)throw new Error('climate attachment registry repeats id');const selected=options.id===null?bindings:bindings.filter(x=>x.id===options.id);if(selected.length===0||options.id!==null&&selected.length!==1)throw new Error('unknown climate attachment id');const controller=new AbortController();const onInt=()=>controller.abort(new Error('climate attachment interrupted by SIGINT')),onTerm=()=>controller.abort(new Error('climate attachment interrupted by SIGTERM'));process.once('SIGINT',onInt);process.once('SIGTERM',onTerm);try{const results=[];for(const binding of selected){if(controller.signal.aborted)throw controller.signal.reason;results.push(await publishClimateAttachment({repositoryRoot:path.resolve(WORLD,'..'),binding,signal:controller.signal,...(options.durationMs===undefined?{}:{durationMs:options.durationMs})}));}process.stdout.write(`${JSON.stringify(results.length===1?results[0]:results)}\n`);}finally{process.removeListener('SIGINT',onInt);process.removeListener('SIGTERM',onTerm);}}
main().catch(error=>{const message=error instanceof Error?error.message:String(error);process.stderr.write(`${Buffer.from(message).subarray(0,2048).toString('utf8')}\n`);process.exitCode=1;});
