import { createHash, randomUUID } from 'node:crypto';
import { lstat, opendir, realpath, statfs } from 'node:fs/promises';
import path from 'node:path';
import { Worker } from 'node:worker_threads';
import { withAcquisitionBuildLock } from './acquire.ts';
import { readBoundedLocalFile } from './inventory-reader.ts';
import { createOutputStore } from './storage.ts';
import { canonicalJson } from './pack.ts';
import { validateManifest } from './validate.ts';
import { buildEnvironmentManifest, validateEnvironmentManifest } from './environment.ts';
import { validateClimateAttachmentBinding } from './climate-attachment-compile.ts';
import { CLIMATE_ATTACHMENT_COMPILER, CLIMATE_ATTACHMENT_LIMITS as L, CLIMATE_ATTACHMENT_POLICY, CLIMATE_ATTACHMENT_PRODUCT, type ClimateAttachmentBinding, type ClimateAttachmentBuildInput, type ClimateAttachmentPublishedResult, type CompiledClimateAttachment, type PublishClimateAttachmentOptions } from './climate-attachment-types.ts';

const HASH = /^[a-f0-9]{64}$/;
const OUTPUT = '.cache/world-build/output/climate-packs';
const AUDIT = '.cache/world-build/climate-attachment-attempts';
const AUDIT_HEADROOM = 16 * 1024;
const SCRATCH = L.tileBytes + L.auditRecordBytes;
type Asset = CompiledClimateAttachment['assets'][number];
function sha(bytes: Uint8Array): string { return createHash('sha256').update(bytes).digest('hex'); }
function canonical(value: unknown): string { return canonicalJson(value); }
function inside(parent: string, child: string): boolean { const rel=path.relative(parent,child); return rel===''||(!rel.startsWith(`..${path.sep}`)&&rel!=='..'&&!path.isAbsolute(rel)); }
function check(signal: AbortSignal, deadline: number): void { if(signal.aborted) throw signal.reason??new Error('climate attachment aborted'); if(performance.now()>=deadline) throw new Error('climate attachment deadline exceeded');if(process.memoryUsage().rss>L.rssBytes)throw new Error('climate attachment exceeded 256 MiB RSS'); }
function errorText(error: unknown): string { return (error instanceof Error?error.message:String(error)).replace(/[\u0000-\u001f\u007f]/g,' ').slice(0,2000)||'climate attachment failed'; }
async function safePath(target:string):Promise<void>{const resolved=path.resolve(target);let cursor=path.parse(resolved).root;for(const part of resolved.slice(cursor.length).split(path.sep).filter(Boolean)){cursor=path.join(cursor,part);try{const st=await lstat(cursor);if(st.isSymbolicLink())throw new Error(`climate attachment path contains symlink: ${cursor}`);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}}}
async function readSafe(file:string,cap:number,signal:AbortSignal,deadline:number):Promise<Buffer>{check(signal,deadline);await safePath(file);const st=await lstat(file);if(!st.isFile()||st.size>cap)throw new RangeError('climate attachment input is oversized or nonregular');const bytes=await readBoundedLocalFile(file,cap);check(signal,deadline);return bytes;}
function pinPath(root:string,relative:string,sha256:string,bytes:number,expectedPrefix:string,cap:number):string{
 if(!HASH.test(sha256)||!Number.isSafeInteger(bytes)||bytes<1||bytes>cap||path.isAbsolute(relative)||relative.includes('\\')||relative.split('/').some(p=>!p||p==='.'||p==='..')||!relative.startsWith(expectedPrefix))throw new Error('climate attachment file pin is invalid');
 const full=path.resolve(root,relative);if(!inside(root,full)||full===root)throw new Error('climate attachment pin escapes repository');return full;
}
async function verifyPin(root:string,relative:string,hash:string,bytes:number,prefix:string,cap:number,signal:AbortSignal,deadline:number):Promise<Buffer>{const full=pinPath(root,relative,hash,bytes,prefix,cap);const body=await readSafe(full,cap,signal,deadline);if(body.length!==bytes||sha(body)!==hash)throw new Error(`climate attachment input pin mismatch: ${relative}`);return body;}
async function usage(root:string,signal:AbortSignal,deadline:number):Promise<{bytes:number;entries:number}>{let bytes=0,entries=0;try{await safePath(root);const rootInfo=await lstat(root);if(rootInfo.isSymbolicLink()||!rootInfo.isDirectory())throw new Error('climate output root is unsafe');}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return{bytes:0,entries:0};throw e;}
 const pending:[string,number][]=[[root,0]];for(let i=0;i<pending.length;i++){check(signal,deadline);if(pending.length>L.treeEntries+1)throw new RangeError('climate output tree exceeds entry cap');const [dir,depth]=pending[i]!;if(depth>L.treeDepth)throw new RangeError('climate output tree exceeds depth cap');const handle=await opendir(dir);try{for await(const ent of handle){check(signal,deadline);if(++entries>L.treeEntries)throw new RangeError('climate output tree exceeds entry cap');const file=path.join(dir,ent.name),st=await lstat(file);if(st.isSymbolicLink())throw new Error('climate output tree contains symlink');if(st.isDirectory())pending.push([file,depth+1]);else if(st.isFile()){bytes+=st.size;if(bytes>L.treeBytes)throw new RangeError('climate output tree exceeds byte cap');}else throw new Error('climate output contains special file');}}finally{await handle.close().catch(()=>{});}}return{bytes,entries};}
interface Attempt {schemaVersion:1;attemptId:string;requestHash:string;compiler:string;policy:string;binding:unknown;status:'pending'|'succeeded'|'failed'|'aborted'|'timed-out';startedAt:string;networkBytes:0;finishedAt?:string;manifestHash?:string;provenanceHash?:string;bytes?:number;tiles?:number;error?:string}
function exactKeys(row:Record<string,unknown>,keys:string[]):boolean{return Object.keys(row).sort().join(',')===keys.slice().sort().join(',');}
function iso(s:unknown):s is string{return typeof s==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString()===s;}
async function verifyAudit(root:string,requestHash:string,binding:ClimateAttachmentBinding,signal:AbortSignal,deadline:number):Promise<{count:number;files:number;bytes:number;succeeded:Array<{manifestHash:string;provenanceHash:string;bytes:number;tiles:number}>}>{let files=0,total=0,count=0;const succeeded:Array<{manifestHash:string;provenanceHash:string;bytes:number;tiles:number}>=[];try{await safePath(root);const st=await lstat(root);if(st.isSymbolicLink()||!st.isDirectory())throw new Error('climate audit root unsafe');}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return{count,files,bytes:total,succeeded};throw e;}
 const dir=await opendir(root);try{for await(const ent of dir){check(signal,deadline);if(++files>L.auditRecords||!/^([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\.json$/.test(ent.name))throw new Error('climate audit entry cap or filename invalid');const file=path.join(root,ent.name),st=await lstat(file);if(st.isSymbolicLink()||!st.isFile()||st.size>L.auditRecordBytes)throw new Error('climate audit record unsafe or oversized');total+=st.size;if(total>L.auditBytes)throw new RangeError('climate audit bytes exceed cap');const body=await readSafe(file,L.auditRecordBytes,signal,deadline),text=new TextDecoder('utf-8',{fatal:true}).decode(body),r=JSON.parse(text) as Record<string,unknown>,status=r.status;const base=['schemaVersion','attemptId','requestHash','compiler','policy','binding','status','startedAt','networkBytes'];const keys=status==='pending'?base:status==='succeeded'?[...base,'finishedAt','manifestHash','provenanceHash','bytes','tiles']:[...base,'finishedAt','error'];const terminal=status!=='pending';if(!exactKeys(r,keys)||text!==`${canonical(r)}\n`||r.schemaVersion!==1||r.attemptId!==path.basename(file,'.json')||!HASH.test(String(r.requestHash))||r.compiler!==CLIMATE_ATTACHMENT_COMPILER||r.policy!==CLIMATE_ATTACHMENT_POLICY||r.networkBytes!==0||!iso(r.startedAt)||!['pending','succeeded','failed','aborted','timed-out'].includes(String(status))||(terminal&&(!iso(r.finishedAt)||Date.parse(r.finishedAt as string)<Date.parse(r.startedAt as string))))throw new Error('climate audit record invalid');const auditBinding=validateClimateAttachmentBinding(r.binding);const computedHash=sha(Buffer.from(canonical({product:CLIMATE_ATTACHMENT_PRODUCT,compiler:CLIMATE_ATTACHMENT_COMPILER,policy:CLIMATE_ATTACHMENT_POLICY,binding:auditBinding})));if(computedHash!==r.requestHash)throw new Error('climate audit request hash is invalid');if(status==='succeeded'&&(!HASH.test(String(r.manifestHash))||!HASH.test(String(r.provenanceHash))||!Number.isSafeInteger(r.bytes)||Number(r.bytes)<1||Number(r.bytes)>L.logicalBytes||!Number.isSafeInteger(r.tiles)||Number(r.tiles)<1||Number(r.tiles)>L.tiles))throw new Error('climate success audit result invalid');if(status!=='pending'&&status!=='succeeded'&&(typeof r.error!=='string'||!r.error||r.error.length>2000||/[\u0000-\u001f\u007f]/.test(r.error)))throw new Error('climate failure audit invalid');if(r.requestHash===requestHash){if(canonical(auditBinding)!==canonical(binding))throw new Error('climate audit binding changed');count++;if(status==='succeeded')succeeded.push({manifestHash:String(r.manifestHash),provenanceHash:String(r.provenanceHash),bytes:Number(r.bytes),tiles:Number(r.tiles)});}}
 }finally{await dir.close().catch(()=>{});}return{count,files,bytes:total,succeeded};}
function validateCompiled(value:unknown,input:ClimateAttachmentBuildInput):CompiledClimateAttachment {
 const binding=input.binding;
 if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("climate worker output malformed");
 const out=value as CompiledClimateAttachment;
 if(!out.manifest||!HASH.test(out.manifestHash)||!HASH.test(out.provenanceHash)||typeof out.manifestPath!=="string"||typeof out.provenancePath!=="string"||!Array.isArray(out.assets)||out.assets.length!==input.tiles.length+2||!Number.isSafeInteger(out.bytes)||out.bytes<1||out.bytes>L.logicalBytes)throw new Error("climate worker output fields invalid");
 const base=JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(input.baseBytes)) as import('./types.ts').WorldManifest;
 const environment=validateEnvironmentManifest(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(input.environmentBytes)) as unknown);
 const reconstructed=buildEnvironmentManifest(binding.environmentRequest,input.rawSourceBytes,binding.rawSource.url);
 if(canonical(environment)!==canonical(reconstructed))throw new Error('climate worker input environment does not reconstruct from its raw pin');
 const normalized=validateManifest(out.manifest);
 if(canonical(normalized)!==canonical(out.manifest))throw new Error('climate worker manifest fails the existing world manifest validator');
 const provenanceRecord=out.provenance as unknown as Record<string,unknown>;
 if(!provenanceRecord||typeof provenanceRecord!=='object'||Object.keys(provenanceRecord).sort().join(',')!=='binding,compiler,environment,limitations,originalTiles,policy,product,schemaVersion'||provenanceRecord.schemaVersion!==1||provenanceRecord.product!==CLIMATE_ATTACHMENT_PRODUCT||provenanceRecord.compiler!==CLIMATE_ATTACHMENT_COMPILER||provenanceRecord.policy!==CLIMATE_ATTACHMENT_POLICY||!Array.isArray(provenanceRecord.limitations))throw new Error('climate worker provenance shape or identity is invalid');
 if(canonical(out.manifest.region)!==canonical(binding.expectedRegion)||out.manifest.schemaVersion!==base.schemaVersion||out.manifest.compilerVersion!==base.compilerVersion||out.manifest.frame!==base.frame||out.manifest.verticalDatum!==base.verticalDatum||out.manifest.coverage!==base.coverage||canonical(out.manifest.tiles)!==canonical(base.tiles)||out.provenance.binding.id!==binding.id||canonical(out.provenance.binding)!==canonical(binding)||canonical(out.provenance.environment)!==canonical(environment)||canonical(out.provenance.originalTiles)!==canonical(base.tiles))throw new Error("climate worker output identity or original geometry mismatch");
 const expectedClimate={sourceId:environment.profile.sourceId,period:environment.profile.period,months:environment.profile.months};
 const expectedClimateSource={id:environment.source.id,url:environment.source.url,release:environment.source.release,license:environment.source.license,attribution:environment.source.attribution,sha256:environment.source.sha256,bytes:environment.source.bytes};
 const retainedExceptions=base.exceptions.filter(item=>item!=='climate unavailable: no monthly regional climate source was provided');
 const association=`Climate association: explicit ${binding.environmentRequest.name} (${binding.id}) native-grid point association; this is not a measurement or spatial average of the pack cell.`;
 const containment=binding.association.sampleInsidePackBounds?'inside':'outside';
 const sample=`Climate sample: requested (${environment.point.requestedLongitude}, ${environment.point.requestedLatitude}); returned (${environment.point.longitude}, ${environment.point.latitude}); sampleInsidePackBounds=${binding.association.sampleInsidePackBounds}; centreOffsetDegrees=(${binding.association.centreOffsetDegrees.longitude}, ${binding.association.centreOffsetDegrees.latitude}); native spacing ${environment.source.spatialResolution.latitudeDegrees}° latitude × ${environment.source.spatialResolution.longitudeDegrees}° longitude.`;
 const baseline='Climate baseline: 1991–2020 monthly normal, LST, not live weather; precipitation is monthly accumulation in millimetres derived from monthly mean mm/day rates, not rain intensity.';
 const provenanceMarker=`Climate attachment provenance sha256:${out.provenanceHash}`;
 const expectedExceptions=[...retainedExceptions,association,sample,baseline,provenanceMarker];
 const expectedLimitations=[`${binding.association.disclosure} The returned point (${environment.point.longitude}, ${environment.point.latitude}) is ${containment} the pack bounds; the requested point was (${environment.point.requestedLongitude}, ${environment.point.requestedLatitude}).`,'The climate profile is a 1991–2020 monthly normal from a single native MERRA-2 grid sample, not current weather or a spatial average of the pack region.','Precipitation is a monthly accumulation derived from the NASA POWER PRECTOTCORR monthly mean rate; it is not rain intensity.','NASA POWER metadata does not provide a separate API product license; source attribution and the provider data-use notice are preserved.'];
 if(canonical(out.provenance.limitations)!==canonical(expectedLimitations)||canonical(out.manifest.exceptions)!==canonical(expectedExceptions)||canonical(out.manifest.climate)!==canonical(expectedClimate)||canonical(out.manifest.sources)!==canonical([...base.sources,expectedClimateSource]))throw new Error('climate worker output changed profile/source or failed the exact disclosure contract');
 const manifestAsset=out.assets.at(-1),provenanceAsset=out.assets.find(a=>a.relative===out.provenancePath);
 if(!manifestAsset||manifestAsset.relative!==out.manifestPath||out.manifestPath!==`manifests/${out.manifestHash}.json`||!provenanceAsset||out.provenancePath!==`provenance/${out.provenanceHash}.json`)throw new Error("climate manifest/provenance path binding mismatch");
 const manifestText=new TextDecoder("utf-8",{fatal:true}).decode(manifestAsset.body),provText=new TextDecoder("utf-8",{fatal:true}).decode(provenanceAsset.body);
 if(manifestAsset.body.byteLength>L.manifestBytes||provenanceAsset.body.byteLength>L.provenanceBytes||manifestText!==`${canonical(out.manifest)}\n`||provText!==`${canonical(out.provenance)}\n`||sha(manifestAsset.body)!==out.manifestHash||sha(provenanceAsset.body)!==out.provenanceHash)throw new Error("climate manifest/provenance bytes are over cap, noncanonical or not hash-bound");
 const refs=new Set<string>();let total=0;
 for(const asset of out.assets){if(!asset||typeof asset.relative!=="string"||!(asset.body instanceof Uint8Array)||asset.body.byteLength<1||path.isAbsolute(asset.relative)||asset.relative.includes("\\")||asset.relative.split("/").some(part=>!part||part==="."||part==="..")||refs.has(asset.relative))throw new Error("climate worker asset invalid");refs.add(asset.relative);total+=asset.body.byteLength;if(asset.relative.startsWith("tiles/")){if(asset.body.byteLength>L.tileBytes)throw new RangeError("climate tile exceeds byte cap");const source=input.tiles.find(t=>t.relative===asset.relative);if(!source||!Buffer.from(asset.body).equals(Buffer.from(source.body)))throw new Error("climate tile differs from original source pack");}else if(asset.relative!==out.manifestPath&&asset.relative!==out.provenancePath)throw new Error("climate worker returned unreferenced asset");}
 if(refs.size!==input.tiles.length+2||input.tiles.some(tile=>!refs.has(tile.relative))||total!==out.bytes||total>L.logicalBytes||out.manifest.tiles.length!==input.tiles.length||out.manifest.tiles.some(ref=>!input.tiles.some(tile=>tile.relative===ref.path&&sha(tile.body)===ref.sha256&&ref.bytes===tile.body.byteLength)))throw new Error("climate worker asset set or byte total mismatch");
 return out;
}
async function runWorker(input:ClimateAttachmentBuildInput,signal:AbortSignal,deadline:number,onOnline?:()=>void):Promise<CompiledClimateAttachment>{check(signal,deadline);const buf=(b:Uint8Array):ArrayBuffer=>{const x=new ArrayBuffer(b.byteLength);new Uint8Array(x).set(b);return x;};const base=buf(input.baseBytes),env=buf(input.environmentBytes),raw=buf(input.rawSourceBytes),tiles=input.tiles.map(t=>({relative:t.relative,body:buf(t.body)}));const transfers=[base,env,raw,...tiles.map(t=>t.body)];const worker=new Worker(new URL('./climate-attachment-worker.ts',import.meta.url),{workerData:{binding:input.binding,base,environment:env,rawSource:raw,tiles},transferList:transfers,resourceLimits:{maxOldGenerationSizeMb:192,maxYoungGenerationSizeMb:32}});let exited=false,reply:unknown,workerError:Error|undefined;let resolveExit!:(code:number)=>void;const exitPromise=new Promise<number>(r=>{resolveExit=r;});worker.once('message',v=>reply=v);worker.once('error',e=>workerError=e);worker.once('exit',code=>{exited=true;resolveExit(code);});worker.once('online',()=>onOnline?.());let rejectAbort!:(e:unknown)=>void;const abortPromise=new Promise<never>((_,r)=>rejectAbort=r);const onAbort=()=>rejectAbort(signal.reason??new Error('climate worker aborted'));signal.addEventListener('abort',onAbort,{once:true});const kill=async()=>{if(!exited)await worker.terminate();await exitPromise;};const poll=setInterval(()=>{if(process.memoryUsage().rss>L.rssBytes){rejectAbort(new Error('climate attachment exceeded 256 MiB RSS'));void kill();}else if(performance.now()>=deadline){rejectAbort(new Error('climate worker deadline exceeded'));void kill();}},50);poll.unref();const timeout=setTimeout(()=>{rejectAbort(new Error('climate worker deadline exceeded'));void kill();},Math.max(1,deadline-performance.now()));timeout.unref();try{const code=await Promise.race([exitPromise,abortPromise]);if(workerError)throw workerError;if(code!==0||!reply||typeof reply!=='object')throw new Error('climate worker exited without output');const r=reply as Record<string,unknown>;if(r.ok!==true){throw new Error(typeof r.error==='string'?r.error.slice(0,2000):'climate worker reply invalid');}if(Object.keys(r).sort().join(',')!=='ok,output')throw new Error('climate worker reply invalid');return validateCompiled(r.output,input);}finally{clearInterval(poll);clearTimeout(timeout);signal.removeEventListener('abort',onAbort);if(!exited)await kill();}}
async function checkAssets(root:string,compiled:CompiledClimateAttachment,signal:AbortSignal,deadline:number):Promise<{state:'complete'|'partial'|'none';expectedManifestPresent:boolean}>{let found=0,expectedManifestPresent=false;for(const a of compiled.assets){check(signal,deadline);const target=path.join(root,a.relative);try{await safePath(target);const st=await lstat(target);if(st.isSymbolicLink()||!st.isFile()||st.size!==a.body.byteLength)throw new Error(`climate immutable collision size/type mismatch: ${a.relative}`);if(a.relative===compiled.manifestPath)expectedManifestPresent=true;const prior=await readSafe(target,a.body.byteLength,signal,deadline);if(!prior.equals(Buffer.from(a.body)))throw new Error(`climate immutable collision content mismatch: ${a.relative}`);found++;}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')continue;throw e;}}if(found===compiled.assets.length)return{state:'complete',expectedManifestPresent};return{state:found?'partial':'none',expectedManifestPresent};}
async function hasBoundCacheCandidate(root:string,binding:ClimateAttachmentBinding,sourceId:string,signal:AbortSignal,deadline:number):Promise<{published:boolean;preManifest:boolean}>{
 const provenanceRoot=path.join(root,'provenance'),provenanceFiles=new Map<string,{binding:unknown;compiler:unknown;policy:unknown}>();
 let provenanceExists=false;try{await safePath(provenanceRoot);const st=await lstat(provenanceRoot);if(st.isSymbolicLink()||!st.isDirectory())throw new Error('climate provenance directory unsafe');provenanceExists=true;}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}
 let scanned=0;
 if(provenanceExists){const dir=await opendir(provenanceRoot);try{for await(const ent of dir){check(signal,deadline);if(!/^[a-f0-9]{64}\.json$/.test(ent.name))throw new Error('climate provenance tree has invalid entry');const file=path.join(provenanceRoot,ent.name),st=await lstat(file);if(st.isSymbolicLink()||!st.isFile()||st.size>L.provenanceBytes)throw new Error('climate provenance cache entry unsafe or oversized');scanned+=st.size;if(scanned>L.treeBytes)throw new RangeError('climate cache candidate scan exceeds tree cap');const body=await readSafe(file,L.provenanceBytes,signal,deadline);const digest=path.basename(ent.name,'.json');if(sha(body)!==digest)throw new Error('climate provenance filename hash mismatch');const text=new TextDecoder('utf-8',{fatal:true}).decode(body),value=JSON.parse(text) as Record<string,unknown>;if(text!==`${canonical(value)}\n`)throw new Error('climate provenance cache is not canonical');provenanceFiles.set(digest,{binding:value.binding,compiler:value.compiler,policy:value.policy});}}finally{await dir.close().catch(()=>{});}}
 const manifestsRoot=path.join(root,'manifests');let manifestsExists=false;try{await safePath(manifestsRoot);const st=await lstat(manifestsRoot);if(st.isSymbolicLink()||!st.isDirectory())throw new Error('climate manifests directory unsafe');manifestsExists=true;}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}
 let published=false;
 if(manifestsExists){const dir=await opendir(manifestsRoot);try{for await(const ent of dir){check(signal,deadline);if(!/^[a-f0-9]{64}\.json$/.test(ent.name))throw new Error('climate manifest tree has invalid entry');const file=path.join(manifestsRoot,ent.name),st=await lstat(file);if(st.isSymbolicLink()||!st.isFile()||st.size>L.manifestBytes)throw new Error('climate manifest cache entry unsafe or oversized');scanned+=st.size;if(scanned>L.treeBytes)throw new RangeError('climate cache candidate scan exceeds tree cap');const body=await readSafe(file,L.manifestBytes,signal,deadline),digest=path.basename(ent.name,'.json');if(sha(body)!==digest)throw new Error('climate manifest filename hash mismatch');const text=new TextDecoder('utf-8',{fatal:true}).decode(body),manifest=JSON.parse(text) as {region?:{id?:unknown};climate?:{sourceId?:unknown};exceptions?:unknown};if(text!==`${canonical(manifest)}\n`)throw new Error('climate manifest cache is not canonical');if(manifest.region?.id!==binding.expectedRegion.id||manifest.climate?.sourceId!==sourceId)continue;const associationPrefix=`Climate association: explicit ${binding.environmentRequest.name} (${binding.id}) native-grid point association;`;const idBound=Array.isArray(manifest.exceptions)&&manifest.exceptions.some(x=>typeof x==='string'&&x.startsWith(associationPrefix));if(!idBound)continue;const marker=Array.isArray(manifest.exceptions)?manifest.exceptions.find(x=>typeof x==='string'&&/^Climate attachment provenance sha256:[a-f0-9]{64}$/.test(x)):undefined;const provHash=typeof marker==='string'?marker.slice('Climate attachment provenance sha256:'.length):'';const matchedProvenance=provenanceFiles.get(provHash);if(!matchedProvenance)continue;if(matchedProvenance.compiler!==CLIMATE_ATTACHMENT_COMPILER||matchedProvenance.policy!==CLIMATE_ATTACHMENT_POLICY)continue;if(canonical(matchedProvenance.binding)!==canonical(binding))continue;if(published)throw new Error('multiple published manifests bind the same climate attachment request');published=true;}}
  finally{await dir.close().catch(()=>{});}}
 const preManifest=[...provenanceFiles.values()].some(x=>x.compiler===CLIMATE_ATTACHMENT_COMPILER&&x.policy===CLIMATE_ATTACHMENT_POLICY);
 return{published,preManifest};
}
async function verifySucceededProducts(root:string,refs:Awaited<ReturnType<typeof verifyAudit>>['succeeded'],binding:ClimateAttachmentBinding,sourceId:string,signal:AbortSignal,deadline:number):Promise<void>{
 const seen=new Set<string>(),readProduct=async(file:string,cap:number)=>{try{return await readSafe(file,cap,signal,deadline);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')throw new Error('previously published climate output is missing or corrupt');throw error;}};for(const ref of refs){check(signal,deadline);if(seen.has(ref.manifestHash))continue;seen.add(ref.manifestHash);const manifestPath=path.join(root,'manifests',`${ref.manifestHash}.json`),provenancePath=path.join(root,'provenance',`${ref.provenanceHash}.json`);const manifestBytes=await readProduct(manifestPath,L.manifestBytes),provenanceBytes=await readProduct(provenancePath,L.provenanceBytes);if(sha(manifestBytes)!==ref.manifestHash||sha(provenanceBytes)!==ref.provenanceHash)throw new Error('previously published climate output is missing or corrupt');const manifestText=new TextDecoder('utf-8',{fatal:true}).decode(manifestBytes),provenanceText=new TextDecoder('utf-8',{fatal:true}).decode(provenanceBytes),manifest=JSON.parse(manifestText) as {region?:{id?:unknown};climate?:{sourceId?:unknown};tiles?:unknown[];exceptions?:unknown},provenance=JSON.parse(provenanceText) as Record<string,unknown>;if(manifestText!==`${canonical(manifest)}\n`||provenanceText!==`${canonical(provenance)}\n`||manifest.region?.id!==binding.expectedRegion.id||manifest.climate?.sourceId!==sourceId||!Array.isArray(manifest.tiles)||manifest.tiles.length!==ref.tiles||manifest.tiles.length<1||manifest.tiles.length>L.tiles||!Array.isArray(manifest.exceptions)||provenance.schemaVersion!==1||provenance.product!==CLIMATE_ATTACHMENT_PRODUCT||provenance.compiler!==CLIMATE_ATTACHMENT_COMPILER||provenance.policy!==CLIMATE_ATTACHMENT_POLICY||canonical(provenance.binding)!==canonical(binding))throw new Error('previously published climate output is missing or corrupt');const marker=`Climate attachment provenance sha256:${ref.provenanceHash}`;if(!manifest.exceptions.includes(marker))throw new Error('previously published climate output provenance binding is corrupt');}
}
async function publishAssets(root:string,buildRoot:string,out:CompiledClimateAttachment,signal:AbortSignal,deadline:number,onWritten?:(p:string)=>void):Promise<string>{const store=await createOutputStore(root,buildRoot);for(let i=0;i<out.assets.length;i++){check(signal,deadline);const asset=out.assets[i]!;if(i===out.assets.length-1&&asset.relative!==out.manifestPath)throw new Error('climate manifest is not last');const target=path.join(root,asset.relative);let exists=false;try{await safePath(target);const st=await lstat(target);if(st.isSymbolicLink()||!st.isFile()||st.size!==asset.body.byteLength)throw new Error(`climate immutable output collision size mismatch: ${asset.relative}`);exists=true;}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}if(exists){const prev=await readSafe(target,asset.body.byteLength,signal,deadline);if(!prev.equals(Buffer.from(asset.body)))throw new Error(`climate immutable output collision content mismatch: ${asset.relative}`);}else await store.writeImmutable(asset.relative,asset.body);onWritten?.(asset.relative);}return path.join(root,out.manifestPath);}

export async function publishClimateAttachment(options:PublishClimateAttachmentOptions):Promise<ClimateAttachmentPublishedResult>{
 if(!path.isAbsolute(options.repositoryRoot)||path.resolve(options.repositoryRoot)!==options.repositoryRoot)throw new TypeError('climate repositoryRoot must be canonical absolute path');const binding=validateClimateAttachmentBinding(structuredClone(options.binding));const duration=options.durationMs??L.durationMs;if(!Number.isSafeInteger(duration)||duration<1||duration>L.durationMs)throw new RangeError('climate duration must be 1..60000ms');const started=performance.now(),deadline=started+duration,controller=new AbortController(),timer=setTimeout(()=>controller.abort(new Error('climate publication deadline exceeded')),duration);timer.unref();const health=setInterval(()=>{if(process.memoryUsage().rss>L.rssBytes)controller.abort(new Error('climate attachment exceeded 256 MiB RSS'));else if(performance.now()>=deadline)controller.abort(new Error('climate attachment deadline exceeded'));},50);health.unref();const signal=options.signal?AbortSignal.any([options.signal,controller.signal]):controller.signal;
 try{const root=options.repositoryRoot;if(await realpath(root)!==root)throw new Error('climate repository root is not canonical');const buildRoot=path.join(root,'.cache/world-build'),outputRoot=path.join(root,OUTPUT),auditRoot=path.join(root,AUDIT);const result=await withAcquisitionBuildLock(buildRoot,async()=>{
  check(signal,deadline);const basePath=pinPath(root,binding.baseManifest.path,binding.baseManifest.sha256,binding.baseManifest.bytes,`.cache/world-build/campaigns/${binding.campaignId}/output/manifests/`,L.baseManifestBytes),envPath=pinPath(root,binding.environmentManifest.path,binding.environmentManifest.sha256,binding.environmentManifest.bytes,'.cache/world-build/output/environment/manifests/',L.environmentManifestBytes),rawPath=pinPath(root,binding.rawSource.path,binding.rawSource.sha256,binding.rawSource.bytes,'.cache/world-build/environment-source-cache/',L.rawSourceBytes);
  const [baseBytes,environmentBytes,rawSourceBytes]=await Promise.all([verifyPin(root,binding.baseManifest.path,binding.baseManifest.sha256,binding.baseManifest.bytes,`.cache/world-build/campaigns/${binding.campaignId}/output/manifests/`,L.baseManifestBytes,signal,deadline),verifyPin(root,binding.environmentManifest.path,binding.environmentManifest.sha256,binding.environmentManifest.bytes,'.cache/world-build/output/environment/manifests/',L.environmentManifestBytes,signal,deadline),verifyPin(root,binding.rawSource.path,binding.rawSource.sha256,binding.rawSource.bytes,'.cache/world-build/environment-source-cache/',L.rawSourceBytes,signal,deadline)]);void basePath;void envPath;void rawPath;
  const base=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(baseBytes)) as {tiles?:Array<{path:string;sha256:string;bytes:number}>};if(!Array.isArray(base.tiles)||base.tiles.length<1||base.tiles.length>L.tiles)throw new RangeError('climate base tile count invalid');let tileBytes=0;for(const ref of base.tiles){check(signal,deadline);if(!ref||!HASH.test(ref.sha256)||ref.path!==`tiles/${ref.sha256}.json`||!Number.isSafeInteger(ref.bytes)||ref.bytes<1||ref.bytes>L.tileBytes)throw new Error('climate base tile reference invalid');tileBytes+=ref.bytes;if(tileBytes>L.logicalBytes)throw new RangeError('climate original tile bytes exceed attachment logical cap');}const tiles:ClimateAttachmentBuildInput['tiles']=[];for(const ref of base.tiles){check(signal,deadline);const rel=`.cache/world-build/campaigns/${binding.campaignId}/output/${ref.path}`;const body=await verifyPin(root,rel,ref.sha256,ref.bytes,`.cache/world-build/campaigns/${binding.campaignId}/output/`,L.tileBytes,signal,deadline);tiles.push({relative:ref.path,body});}
  const environmentValue=validateEnvironmentManifest(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(environmentBytes)) as unknown);
  const request={product:CLIMATE_ATTACHMENT_PRODUCT,compiler:CLIMATE_ATTACHMENT_COMPILER,policy:CLIMATE_ATTACHMENT_POLICY,binding};
  const requestHash=sha(Buffer.from(canonical(request)));
  const audit=await verifyAudit(auditRoot,requestHash,binding,signal,deadline);await verifySucceededProducts(outputRoot,audit.succeeded,binding,environmentValue.source.id,signal,deadline);
  const use=await usage(outputRoot,signal,deadline);
  const disk=await statfs(buildRoot);
  if(disk.bavail*disk.bsize<L.freeBytes+SCRATCH+L.logicalBytes+L.auditRecordBytes*2+AUDIT_HEADROOM)throw new RangeError('climate publication requires 100 MiB free plus bounded output/audit scratch');
  const input:ClimateAttachmentBuildInput={binding,baseBytes,environmentBytes,rawSourceBytes,tiles};
  const cacheState=await hasBoundCacheCandidate(outputRoot,binding,environmentValue.source.id,signal,deadline);
  let record:Attempt|undefined,auditStore:Awaited<ReturnType<typeof createOutputStore>>|undefined,success=false,caught:unknown,error='climate attachment did not complete';
  if(!cacheState.published){
   if(audit.count>=L.attemptsPerRequest)throw new RangeError('climate publication exhausted four lifetime attempts');
   if(audit.files+1>L.auditRecords||audit.bytes+2*L.auditRecordBytes+AUDIT_HEADROOM>L.auditBytes)throw new RangeError('climate audit lacks pending/terminal headroom');
   if(use.bytes+L.logicalBytes+SCRATCH>L.treeBytes||use.entries+L.tiles+6>L.treeEntries)throw new RangeError('climate output tree lacks bounded publication headroom');
   if(disk.bavail*disk.bsize<L.freeBytes+L.logicalBytes+SCRATCH+2*L.auditRecordBytes+AUDIT_HEADROOM)throw new RangeError('climate publication disk lacks full bounded output/audit headroom');
   const attemptId=randomUUID();record={schemaVersion:1,attemptId,requestHash,compiler:CLIMATE_ATTACHMENT_COMPILER,policy:CLIMATE_ATTACHMENT_POLICY,binding,status:'pending',startedAt:new Date().toISOString(),networkBytes:0};
   auditStore=await createOutputStore(auditRoot,buildRoot);const pending=Buffer.from(`${canonical(record)}\n`);if(pending.length>L.auditRecordBytes)throw new RangeError('climate pending audit record exceeds cap');await auditStore.writeImmutable(`${attemptId}.json`,pending);
  }
  try{
   check(signal,deadline);
   const compiled=await runWorker(input,signal,deadline,options.onWorkerOnline);
   const all=await usage(outputRoot,signal,deadline);if(all.bytes>L.treeBytes||all.entries>L.treeEntries)throw new RangeError('climate output tree exceeds cap');
   const state=await checkAssets(outputRoot,compiled,signal,deadline);
   if(state.state==='complete'){
    if(record&&auditStore){const terminal:Attempt={...record,status:'succeeded',finishedAt:new Date().toISOString(),manifestHash:compiled.manifestHash,provenanceHash:compiled.provenanceHash,bytes:compiled.bytes,tiles:compiled.manifest.tiles.length};await auditStore.writeAtomic(`${record.attemptId}.json`,Buffer.from(`${canonical(terminal)}\n`));success=true;}
    return{id:binding.id,regionId:binding.expectedRegion.id,manifestHash:compiled.manifestHash,manifestPath:path.join(outputRoot,compiled.manifestPath),provenanceHash:compiled.provenanceHash,provenancePath:path.join(outputRoot,compiled.provenancePath),bytes:compiled.bytes,tiles:compiled.manifest.tiles.length,cacheHit:true,elapsedMs:0,networkBytes:0} satisfies ClimateAttachmentPublishedResult;
   }
   if(cacheState.published||state.expectedManifestPresent)throw new Error('published climate manifest has missing or corrupt referenced assets');
   if(!record||!auditStore)throw new RangeError('climate publication cannot start after lifetime attempts are exhausted');
   if(use.bytes+compiled.bytes+SCRATCH>L.treeBytes||use.entries+compiled.assets.length*2+4>L.treeEntries)throw new RangeError('climate output tree lacks measured write headroom');
   if(disk.bavail*disk.bsize<L.freeBytes+compiled.bytes+SCRATCH+2*L.auditRecordBytes+AUDIT_HEADROOM)throw new RangeError('climate publication disk lacks measured output/audit headroom');
   const manifestPath=await publishAssets(outputRoot,buildRoot,compiled,signal,deadline,options.onAssetWritten);check(signal,deadline);
   const finalUse=await usage(outputRoot,signal,deadline);if(finalUse.bytes>L.treeBytes||finalUse.entries>L.treeEntries)throw new RangeError('climate output tree exceeded final cap');
   const terminal:Attempt={...record,status:'succeeded',finishedAt:new Date().toISOString(),manifestHash:compiled.manifestHash,provenanceHash:compiled.provenanceHash,bytes:compiled.bytes,tiles:compiled.manifest.tiles.length};const terminalBytes=Buffer.from(`${canonical(terminal)}\n`);if(terminalBytes.length>L.auditRecordBytes)throw new RangeError('climate terminal audit exceeds cap');await auditStore.writeAtomic(`${record.attemptId}.json`,terminalBytes);check(signal,deadline);success=true;
   return{id:binding.id,regionId:binding.expectedRegion.id,manifestHash:compiled.manifestHash,manifestPath,provenanceHash:compiled.provenanceHash,provenancePath:path.join(outputRoot,compiled.provenancePath),bytes:compiled.bytes,tiles:compiled.manifest.tiles.length,cacheHit:false,elapsedMs:0,networkBytes:0} satisfies ClimateAttachmentPublishedResult;
  }catch(e){caught=e;error=errorText(e);throw e;}finally{if(record&&auditStore&&!success){const status=signal.aborted?'aborted':performance.now()>=deadline?'timed-out':'failed';const terminal:Attempt={...record,status,finishedAt:new Date().toISOString(),error};try{await auditStore.writeAtomic(`${record.attemptId}.json`,Buffer.from(`${canonical(terminal)}\n`));}catch(auditError){throw new AggregateError(caught?[caught,auditError]:[auditError],'climate publication and audit failed');}}}
 },{signal,timeoutMs:Math.max(1,Math.floor(deadline-performance.now()))});check(signal,deadline);return{...result,elapsedMs:Math.max(1,Math.floor(performance.now()-started))};}finally{clearInterval(health);clearTimeout(timer);}
}
