import { createHash } from 'node:crypto';
import { lstat, opendir, realpath, statfs } from 'node:fs/promises';
import { Worker } from 'node:worker_threads';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { ALLOWED_ROOT } from './pipeline.ts';
import { readBoundedLocalFile } from './inventory-reader.ts';
import { createOutputStore } from './storage.ts';
import { validateAcquisitionRequest } from './acquire.ts';
import { validateRegionalFanoutRequest } from './regional-fanout.ts';
import type { RegionalFanoutIndex, RegionalFanoutProduct, RegionalFanoutPublished, RegionalFanoutPublishOptions, RegionalFanoutRequest } from './regional-fanout-types.ts';

const SHA=/^[a-f0-9]{64}$/;
const LIMITS=Object.freeze({inputBytes:20_000_000,receiptBytes:1_000_000,children:64,outputBytes:30_000_000,requestBytes:256_000,freeBytes:100_000_000,treeEntries:4096,treeDepth:6,rssBytes:768*1024*1024});
function canonical(value:unknown):string{if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object')return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${canonical((value as Record<string,unknown>)[k])}`).join(',')}}`;return JSON.stringify(value);}
function hash(bytes:Uint8Array):string{return createHash('sha256').update(bytes).digest('hex');}
function inside(parent:string,child:string):boolean{const relative=path.relative(parent,child);return relative===''||(!relative.startsWith(`..${path.sep}`)&&relative!=='..'&&!path.isAbsolute(relative));}
function check(signal:AbortSignal,deadline:number):void{if(signal.aborted)throw signal.reason??new Error('regional fan-out aborted');if(performance.now()>=deadline)throw new Error('regional fan-out deadline exceeded');if(process.memoryUsage().rss>LIMITS.rssBytes)throw new Error('regional fan-out parent RSS exceeded 768 MiB');}
async function ensureNoLinks(target:string,allowMissing:boolean):Promise<void>{const absolute=path.resolve(target);let cursor=path.parse(absolute).root;for(const part of absolute.slice(cursor.length).split(path.sep).filter(Boolean)){cursor=path.join(cursor,part);try{const st=await lstat(cursor);if(st.isSymbolicLink())throw new Error(`regional fan-out path contains a symlink: ${cursor}`);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT'&&allowMissing)continue;throw error;}}}
function resolveInputPath(_allowedRoot:string,value:string):string{if(!path.isAbsolute(value)||path.resolve(value)!==value)throw new Error('regional fan-out input paths must be canonical absolute paths');return value;}
async function validateRoots(allowedRoot:string,outputRoot:string,id:string):Promise<void>{if(!path.isAbsolute(allowedRoot)||path.resolve(allowedRoot)!==allowedRoot||!path.isAbsolute(outputRoot)||path.resolve(outputRoot)!==outputRoot)throw new TypeError('regional fan-out roots must be canonical absolute paths');await ensureNoLinks(allowedRoot,false);if(await realpath(allowedRoot)!==allowedRoot)throw new Error('regional fan-out allowedRoot must be canonical');const production=path.resolve(ALLOWED_ROOT),temp=await realpath(tmpdir());if(allowedRoot!==production&&(!inside(temp,allowedRoot)||allowedRoot===temp))throw new Error('allowedRoot must be the exact production world-build root or an isolated temporary descendant');if(!/^[a-z0-9][a-z0-9._-]{0,47}$/.test(id))throw new Error('regional fan-out id is unsafe for its dedicated output path');if(allowedRoot===production){if(outputRoot!==path.join(production,'regional-fanout',id))throw new Error('production output must be the request-specific regional-fanout directory');}else if(!inside(allowedRoot,outputRoot)||outputRoot===allowedRoot)throw new Error('temporary outputRoot must be a dedicated descendant of allowedRoot');await ensureNoLinks(outputRoot,true);}

async function readPinned(allowedRoot:string,filename:string,bytes:number,digest:string,cap:number,signal:AbortSignal,deadline:number):Promise<Buffer>{check(signal,deadline);if(!Number.isSafeInteger(bytes)||bytes<1||bytes>cap||!SHA.test(digest)||!path.isAbsolute(filename)||path.resolve(filename)!==filename||!inside(allowedRoot,filename)||filename===allowedRoot)throw new Error('regional fan-out input pin is invalid or outside allowedRoot');await ensureNoLinks(filename,false);const body=await readBoundedLocalFile(filename,cap);check(signal,deadline);if(body.length!==bytes||hash(body)!==digest)throw new Error('regional fan-out pinned file SHA-256/length mismatch');return body;}
function exactKeys(value:Record<string,unknown>,keys:string[]):boolean{return Object.keys(value).sort().join(',')===keys.slice().sort().join(',');}
function same(a:unknown,b:unknown):boolean{return canonical(a)===canonical(b);}
async function validateParent(request:RegionalFanoutRequest,allowedRoot:string,signal:AbortSignal,deadline:number):Promise<{bytes:Buffer;receiptBytes?:Buffer}>{
 const plan=request.parentPlan;if(!plan||!plan.region||!plan.source||!plan.input||Object.keys(plan).some(k=>!['region','source','input','rawExtraction'].includes(k)))throw new Error('regional fan-out parent plan is malformed');if(plan.input.sha256!==plan.source.sha256||plan.input.bytes!==plan.source.bytes||!Number.isSafeInteger(plan.input.bytes)||plan.input.bytes<1||plan.input.bytes>LIMITS.inputBytes)throw new Error('parent source and input pins do not match');
 const bytes=await readPinned(allowedRoot,resolveInputPath(allowedRoot,plan.input.path),plan.input.bytes,plan.input.sha256,LIMITS.inputBytes,signal,deadline);
 if(request.parentAcquisition===null)return{bytes};
 const acquisition=request.parentAcquisition,receiptBytes=await readPinned(allowedRoot,resolveInputPath(allowedRoot,acquisition.receipt.path),acquisition.receipt.bytes,acquisition.receipt.sha256,LIMITS.receiptBytes,signal,deadline),receipt=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(receiptBytes)) as Record<string,unknown>;
 if(!exactKeys(receipt,['schemaVersion','requestHash','selection','request','completedAt','inputSha256','inputBytes','metrics','upstream','sources','exceptions'])||receipt.schemaVersion!==1||receipt.requestHash!==acquisition.requestHash||receipt.inputSha256!==plan.input.sha256||receipt.inputBytes!==plan.input.bytes||typeof receipt.completedAt!=='string'||!Number.isFinite(Date.parse(receipt.completedAt)))throw new Error('parent acquisition receipt does not bind the pinned parent extract');
 const req=validateAcquisitionRequest(receipt.request),selection={schemaVersion:req.schemaVersion,id:req.id,inventoryUnitId:req.inventoryUnitId,region:req.region,provider:req.provider,release:req.release,layers:req.layers};if(!same(receipt.selection,selection)||!same(req.region,plan.region)||req.inventoryUnitId!==request.inventoryUnitId)throw new Error('parent acquisition receipt selection or region differs from the fan-out parent');
 if(!Array.isArray(receipt.sources)||receipt.sources.length!==req.layers.length)throw new Error('parent acquisition receipt source set does not match its selected layers');
 const sourceRows=receipt.sources.map((value,index)=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('parent acquisition source record is malformed');const row=value as Record<string,unknown>;if(!exactKeys(row,['id','url','release','license','attribution','sha256','bytes']))throw new Error('parent acquisition source record fields are invalid');const layer=req.layers[index]!,expectedUrl=layer==='buildings'?`https://stac.overturemaps.org/${req.release}/buildings/building/collection.json`:`https://stac.overturemaps.org/${req.release}/transportation/segment/collection.json`;if(row.id!==`overture-${req.release}-${layer}`||row.url!==expectedUrl||row.release!==req.release||row.license!=='ODbL-1.0'||typeof row.attribution!=='string'||!row.attribution.includes('https://docs.overturemaps.org/attribution/')||typeof row.sha256!=='string'||!SHA.test(row.sha256)||!Number.isSafeInteger(row.bytes)||Number(row.bytes)<1||Number(row.bytes)>req.limits.outputBytes)throw new Error('parent acquisition source record is not a verified selected Overture layer');return row;});
 const combined={id:`overture-${req.release}-${req.layers.join('-')}`,url:`https://stac.overturemaps.org/${req.release}/catalog.json`,release:req.release,license:[...new Set(sourceRows.map(row=>row.license as string))].sort().join(' + '),attribution:[...new Set(sourceRows.map(row=>row.attribution as string))].sort().join('; ')};
 if(plan.source.id!==combined.id||plan.source.url!==combined.url||plan.source.release!==combined.release||plan.source.license!==combined.license||plan.source.attribution!==combined.attribution)throw new Error('parent combined source metadata differs from its verified acquisition receipt');
 const raw=plan.rawExtraction;if(!raw||raw.url!==`overture:${req.release}/${acquisition.requestHash}`||raw.sha256!==plan.input.sha256||raw.bytes!==plan.input.bytes||raw.fetched!==receipt.completedAt)throw new Error('parent raw-extraction association differs from its receipt');
 return{bytes,receiptBytes};
}
function validateProduct(value:unknown,request:RegionalFanoutRequest,parentBytes:Uint8Array):RegionalFanoutProduct{
 if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('regional fan-out worker output is malformed');const row=value as Record<string,unknown>;if(!exactKeys(row,['index','indexBytes','indexHash','inputs','logicalBytes'])||!(row.indexBytes instanceof Uint8Array)||!Array.isArray(row.inputs)||!Number.isSafeInteger(row.logicalBytes)||Number(row.logicalBytes)<1||Number(row.logicalBytes)>Math.min(LIMITS.outputBytes,request.limits.outputBytes)||!SHA.test(String(row.indexHash)))throw new Error('regional fan-out worker output fields are invalid');
 const index=row.index as RegionalFanoutIndex;if(!index||typeof index!=='object'||Array.isArray(index)||index.schemaVersion!==1||index.compilerVersion!=='regional-whole-feature-fanout-v1'||index.coverage!=='foundation'||index.ownership!=='lexicographic-source-vertex-closed-cell-id-tie-v1'||index.intersection!=='conservative-feature-bounds'||index.requestHash!==hash(Buffer.from(canonical(request)))||!same(index.request,request)||!Array.isArray(index.features)||index.features.length>Math.min(5000,request.limits.features)||!Array.isArray(index.cells)||index.cells.length!==request.children.length||index.cells.length>Math.min(LIMITS.children,request.limits.children))throw new Error('regional fan-out index request or field binding is invalid');
 const indexBytes=row.indexBytes as Uint8Array,indexText=new TextDecoder('utf-8',{fatal:true}).decode(indexBytes);if(indexBytes.byteLength>LIMITS.outputBytes||indexText!==`${canonical(index)}\n`||hash(indexBytes)!==row.indexHash||!SHA.test(String(index.requestHash)))throw new Error('regional fan-out index bytes are not canonical or hash-bound');
 const counts=index.counts as unknown as Record<string,unknown>;if(!counts||typeof counts!=='object'||Array.isArray(counts)||Object.keys(counts).sort().join(',')!=='coordinates,duplicateRows,emittedParts,outsideDenominator,owned,sourceRows,uniqueFeatures,unsupported'||!Array.isArray(index.limitations)||!Number.isSafeInteger(row.logicalBytes))throw new Error('regional fan-out index summary is malformed');for(const value of Object.values(counts))if(!Number.isSafeInteger(value)||Number(value)<0)throw new Error('regional fan-out count is invalid');if(Number(counts.coordinates)>Math.min(200_000,request.limits.coordinates)||counts.sourceRows!==Number(counts.uniqueFeatures)+Number(counts.duplicateRows)||counts.uniqueFeatures!==Number(counts.owned)+Number(counts.outsideDenominator)+Number(counts.unsupported)||index.features.length!==counts.uniqueFeatures)throw new Error('regional fan-out counts do not conserve source rows');
 const byPath=new Map<string,{ref:RegionalFanoutProduct['inputs'][number]['ref'];bytes:Uint8Array}>();let total=indexBytes.byteLength;for(const itemValue of row.inputs){if(!itemValue||typeof itemValue!=='object'||Array.isArray(itemValue))throw new Error('regional fan-out input asset is malformed');const item=itemValue as Record<string,unknown>,ref=item.ref as RegionalFanoutProduct['inputs'][number]['ref'],body=item.bytes;if(!exactKeys(item,['ref','bytes'])||!ref||typeof ref.path!=='string'||!(body instanceof Uint8Array)||!SHA.test(ref.sha256)||!Number.isSafeInteger(ref.bytes)||ref.bytes!==body.byteLength||ref.bytes<1||ref.bytes>LIMITS.inputBytes||hash(body)!==ref.sha256||ref.path!==`inputs/${ref.sha256}.geojson`||path.isAbsolute(ref.path)||ref.path.includes('\\')||ref.path.split('/').some(part=>!part||part==='.'||part==='..')||byPath.has(ref.path))throw new Error('regional fan-out child input pin or relative path is invalid');const text=new TextDecoder('utf-8',{fatal:true}).decode(body);let geo:unknown;try{geo=JSON.parse(text) as unknown;}catch{throw new Error('regional fan-out child input is not JSON');}if(text!==`${canonical(geo)}\n`||!geo||typeof geo!=='object'||Array.isArray(geo)||(geo as {type?:unknown}).type!=='FeatureCollection'||!Array.isArray((geo as {features?:unknown}).features))throw new Error('regional fan-out child input is not canonical FeatureCollection JSON');byPath.set(ref.path,{ref,bytes:body});total+=body.byteLength;if(total>LIMITS.outputBytes)throw new RangeError('regional fan-out logical output exceeds 30 MB');}
 if(byPath.size!==index.cells.length)throw new Error('regional fan-out child inputs do not match the declared cells');const parentSource={...request.parentPlan.source,sha256:undefined,bytes:undefined};for(const cell of index.cells){const stored=byPath.get(cell.input.path),childRegion=request.children.find(candidate=>candidate.id===cell.region.id),childSource={...cell.plan.source,sha256:undefined,bytes:undefined};if(!stored||!same(stored.ref,cell.input)||!childRegion||!same(childRegion,cell.region)||cell.plan.input.path!==cell.input.path||cell.plan.input.sha256!==cell.input.sha256||cell.plan.input.bytes!==cell.input.bytes||!same({...cell.plan.region,bounds:undefined},{...cell.region,bounds:undefined})||cell.plan.source.sha256!==cell.input.sha256||cell.plan.source.bytes!==cell.input.bytes||!same(parentSource,childSource)||!same(cell.plan.rawExtraction,request.parentPlan.rawExtraction))throw new Error('regional fan-out child plan does not bind its published input and logical cell');const geo=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(stored.bytes)) as {metadata?:{regionalFanout?:Record<string,unknown>};features?:unknown[]};if(!Array.isArray(geo.features)||geo.features.length!==cell.ownedFeatureKeys.length)throw new Error('regional fan-out child feature count differs from its index');const provenance=geo.metadata?.regionalFanout;if(!provenance||provenance.requestHash!==index.requestHash||provenance.parentInputSha256!==request.parentPlan.input.sha256||provenance.logicalCellId!==cell.region.id||provenance.ownership!==index.ownership)throw new Error('regional fan-out child input provenance does not match the index');}
 if(total!==row.logicalBytes)throw new Error('regional fan-out logical byte accounting mismatch');void parentBytes;return value as RegionalFanoutProduct;
}
async function usage(root:string,signal:AbortSignal,deadline:number):Promise<{bytes:number;entries:number}>{let bytes=0,entries=0;try{await ensureNoLinks(root,false);const st=await lstat(root);if(st.isSymbolicLink()||!st.isDirectory())throw new Error('regional fan-out output root is unsafe');}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return{bytes,entries};throw error;}const pending:Array<[string,number]>=[[root,0]];for(let i=0;i<pending.length;i++){check(signal,deadline);if(pending.length>LIMITS.treeEntries+1)throw new RangeError('regional fan-out output tree exceeds entry cap');const [dir,depth]=pending[i]!;if(depth>LIMITS.treeDepth)throw new RangeError('regional fan-out output tree exceeds depth cap');const handle=await opendir(dir);try{for await(const ent of handle){check(signal,deadline);if(++entries>LIMITS.treeEntries)throw new RangeError('regional fan-out output tree exceeds entry cap');const target=path.join(dir,ent.name),st=await lstat(target);if(st.isSymbolicLink())throw new Error('regional fan-out output tree contains symlink');if(st.isDirectory())pending.push([target,depth+1]);else if(st.isFile()){bytes+=st.size;if(bytes>LIMITS.outputBytes)throw new RangeError('regional fan-out output tree exceeds 30 MB');}else throw new Error('regional fan-out output has a special file');}}finally{await handle.close().catch(()=>{});}}return{bytes,entries};}
async function runWorker(request:RegionalFanoutRequest,parentBytes:Buffer,memoryMb:number,signal:AbortSignal,deadline:number):Promise<unknown>{check(signal,deadline);const parent=new ArrayBuffer(parentBytes.byteLength);new Uint8Array(parent).set(parentBytes);const worker=new Worker(new URL('./regional-fanout-worker.ts',import.meta.url),{workerData:{request,parent},transferList:[parent],resourceLimits:{maxOldGenerationSizeMb:Math.floor(memoryMb*0.75),maxYoungGenerationSizeMb:Math.floor(memoryMb*0.25)}});let exited=false,reply:unknown,workerError:Error|undefined,resolveExit!:(code:number)=>void;const exitPromise=new Promise<number>(resolve=>{resolveExit=resolve;});worker.once('message',value=>{reply=value;});worker.once('error',error=>{workerError=error;});worker.once('exit',code=>{exited=true;resolveExit(code);});let rejectAbort!:(reason:unknown)=>void;const abortPromise=new Promise<never>((_,reject)=>{rejectAbort=reject;});const onAbort=()=>rejectAbort(signal.reason??new Error('regional fan-out aborted'));signal.addEventListener('abort',onAbort,{once:true});const stop=async()=>{if(!exited)await worker.terminate();await exitPromise;};const timer=setInterval(()=>{if(process.memoryUsage().rss>LIMITS.rssBytes){rejectAbort(new Error('regional fan-out parent RSS exceeded 768 MiB'));void stop();}else if(performance.now()>=deadline){rejectAbort(new Error('regional fan-out deadline exceeded'));void stop();}},40);timer.unref();const timeout=setTimeout(()=>{rejectAbort(new Error('regional fan-out deadline exceeded'));void stop();},Math.max(1,deadline-performance.now()));timeout.unref();try{const code=await Promise.race([exitPromise,abortPromise]);if(workerError)throw workerError;if(code!==0||!reply||typeof reply!=='object')throw new Error('regional fan-out worker exited without a result');const response=reply as Record<string,unknown>;if(response.ok!==true||!exactKeys(response,['ok','index','indexBytes','indexHash','inputs','logicalBytes']))throw new Error(typeof response.error==='string'?response.error.slice(0,2000):'regional fan-out worker response invalid');return response;}finally{clearInterval(timer);clearTimeout(timeout);signal.removeEventListener('abort',onAbort);if(!exited)await stop();}}
async function publishAsset(store:Awaited<ReturnType<typeof createOutputStore>>,root:string,relative:string,body:Uint8Array,signal:AbortSignal,deadline:number):Promise<string>{check(signal,deadline);const target=path.join(root,...relative.split('/'));try{await ensureNoLinks(target,false);const st=await lstat(target);if(!st.isFile()||st.size!==body.byteLength)throw new Error(`regional fan-out immutable collision size mismatch: ${relative}`);const existing=await readBoundedLocalFile(target,body.byteLength);if(hash(existing)!==hash(body))throw new Error(`regional fan-out immutable collision content mismatch: ${relative}`);return target;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}return store.writeImmutable(relative,body);}

/** Bounded deterministic local publication; this function never performs network I/O. */
export async function publishRegionalFanout(requestValue:unknown,options:RegionalFanoutPublishOptions):Promise<RegionalFanoutPublished>{
 const request=validateRegionalFanoutRequest(structuredClone(requestValue));if(!Number.isSafeInteger(options.durationMs)||options.durationMs<1||options.durationMs>60_000||!Number.isSafeInteger(options.memoryMb)||options.memoryMb<64||options.memoryMb>512)throw new RangeError('regional fan-out duration/memory is outside the frozen limits');const duration=options.durationMs,started=performance.now(),deadline=started+duration,controller=new AbortController(),timeout=setTimeout(()=>controller.abort(new Error('regional fan-out deadline exceeded')),duration);timeout.unref();const signal=options.signal?AbortSignal.any([options.signal,controller.signal]):controller.signal;
 try{const allowedRoot=options.allowedRoot,outputRoot=options.outputRoot;await validateRoots(allowedRoot,outputRoot,request.id);const requestBytes=Buffer.from(canonical(request));if(requestBytes.byteLength>LIMITS.requestBytes)throw new RangeError('regional fan-out request exceeds 256 KB');if(request.parentPlan.input.bytes>request.limits.inputBytes)throw new RangeError('parent source exceeds the request input cap');const {bytes:parentBytes}=await validateParent(request,allowedRoot,signal,deadline);check(signal,deadline);const before=await usage(outputRoot,signal,deadline);if(before.bytes>LIMITS.outputBytes)throw new RangeError('regional fan-out output tree has no remaining logical-byte capacity');
  const raw=await runWorker(request,parentBytes,options.memoryMb,signal,deadline);if(!raw||typeof raw!=='object')throw new Error('regional fan-out worker response is malformed');const response=raw as Record<string,unknown>;if(response.ok!==true||!exactKeys(response,['ok','index','indexBytes','indexHash','inputs','logicalBytes']))throw new Error(typeof response.error==='string'?response.error.slice(0,2000):'regional fan-out worker response invalid');const product=validateProduct(Object.fromEntries(Object.entries(response).filter(([key])=>key!=='ok')),request,parentBytes);check(signal,deadline);const afterCompile=await usage(outputRoot,signal,deadline);
  const requestHash=product.index.requestHash,indexRelative=`indices/${product.indexHash}.json`,indexPath=path.join(outputRoot,indexRelative);
  const publicationRelative=`publications/${requestHash}.json`,publicationPath=path.join(outputRoot,publicationRelative);
  const publicationValue={schemaVersion:1 as const,requestHash,indexHash:product.indexHash,indexPath:indexRelative,logicalBytes:product.logicalBytes,inputs:product.index.cells.map(cell=>cell.input)};
  const publicationBytes=Buffer.from(`${canonical(publicationValue)}\n`);
  if(publicationBytes.byteLength>LIMITS.receiptBytes)throw new RangeError('regional fan-out publication receipt exceeds 1 MB');
  let indexExists=false;try{await ensureNoLinks(indexPath,false);const st=await lstat(indexPath);if(!st.isFile()||st.size!==product.indexBytes.byteLength)throw new Error('published regional fan-out index is corrupt');const existing=await readBoundedLocalFile(indexPath,product.indexBytes.byteLength);if(hash(existing)!==product.indexHash||!existing.equals(Buffer.from(product.indexBytes)))throw new Error('published regional fan-out index collision');indexExists=true;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
  let publicationExists=false;try{await ensureNoLinks(publicationPath,false);const st=await lstat(publicationPath);if(!st.isFile()||st.size!==publicationBytes.byteLength)throw new Error('regional fan-out publication receipt collision size mismatch');const existing=await readBoundedLocalFile(publicationPath,LIMITS.receiptBytes);if(!existing.equals(publicationBytes)||hash(existing)!==hash(publicationBytes))throw new Error('regional fan-out publication receipt collision or corruption');publicationExists=true;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
  if(publicationExists&&!indexExists)throw new Error('completion receipt indicates a completed regional fan-out publication is missing its index; refusing repair');
  const assets=[...product.inputs.map(item=>({path:item.ref.path,body:item.bytes})),{path:indexRelative,body:product.indexBytes},{path:publicationRelative,body:publicationBytes}];let missingBytes=0,maxScratch=0,missingFiles=0;for(const asset of assets){check(signal,deadline);const target=path.join(outputRoot,...asset.path.split('/'));try{await ensureNoLinks(target,false);const st=await lstat(target);if(!st.isFile()||st.size!==asset.body.byteLength)throw new Error(`regional fan-out immutable collision size mismatch: ${asset.path}`);const existing=await readBoundedLocalFile(target,asset.body.byteLength);if(hash(existing)!==hash(asset.body))throw new Error(`regional fan-out immutable collision content mismatch: ${asset.path}`);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;missingBytes+=asset.body.byteLength;missingFiles++;maxScratch=Math.max(maxScratch,asset.body.byteLength);}}
  if(afterCompile.bytes+missingBytes>LIMITS.outputBytes)throw new RangeError('regional fan-out output tree lacks exact publication capacity');if(missingFiles>0&&afterCompile.entries+missingFiles+3>LIMITS.treeEntries)throw new RangeError('regional fan-out output tree lacks entry headroom');const beforeWrite=await statfs(allowedRoot);if(beforeWrite.bavail*beforeWrite.bsize<LIMITS.freeBytes+missingBytes+maxScratch+parentBytes.byteLength)throw new Error('regional fan-out disk lacks free-space publication headroom');
  if(indexExists){for(const item of product.inputs){check(signal,deadline);const file=path.join(outputRoot,...item.ref.path.split('/'));let body:Buffer;try{body=await readBoundedLocalFile(file,item.ref.bytes);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')throw new Error('published regional fan-out index references a missing child input');throw error;}if(hash(body)!==item.ref.sha256||!body.equals(Buffer.from(item.bytes)))throw new Error('published regional fan-out index references a corrupt child input');}}
  else{const store=await createOutputStore(outputRoot,allowedRoot);for(const item of product.inputs){await publishAsset(store,outputRoot,item.ref.path,item.bytes,signal,deadline);}check(signal,deadline);await publishAsset(store,outputRoot,indexRelative,product.indexBytes,signal,deadline);}
  if(!publicationExists){check(signal,deadline);const store=await createOutputStore(outputRoot,allowedRoot);await publishAsset(store,outputRoot,publicationRelative,publicationBytes,signal,deadline);}
  check(signal,deadline);const final=await usage(outputRoot,signal,deadline);if(final.bytes>LIMITS.outputBytes||final.entries>LIMITS.treeEntries)throw new RangeError('regional fan-out output tree exceeds its final cap');const plans=product.index.cells.map(cell=>({...cell.plan,input:{...cell.plan.input,path:path.join(outputRoot,...cell.input.path.split('/'))}}));return{index:product.index,indexHash:product.indexHash,indexPath,logicalBytes:product.logicalBytes,plans,publication:{path:publicationPath,bytes:publicationBytes.byteLength,sha256:hash(publicationBytes)},networkBytes:0};
 }finally{clearTimeout(timeout);}
}
