/**
 * OWNER: home
 * The one-line description of each piece of furniture, shown by Buy mode and by the toast of a piece you touch at home.
 * Only those screens read them, so they are fetched with those screens and not with the first page (the rules read the catalogue
 * in ./furniture.ts, which has everything else about a piece).
 */
import type { FurnitureId } from '../../types/life.ts'

export const FURNITURE_BLURBS: Record<FurnitureId, string> = {
  'sleeping-mat': 'Roll it out, roll it up. Your back keeps the receipts.',
  'spring-bed': 'A real frame and a mattress with opinions.',
  'foam-bed': 'Six inches of foam between you and Monday.',
  'ortho-bed': 'Firm, quiet and doctor-approved.',
  'king-bed': 'Sleep like the landlord.',
  'cooler-box': 'Keeps garri, sugar and zobo cool with no light at all.',
  'kerosene-stove': 'Smoky, patient and never lets jollof down.',
  'gas-cooker': 'Blue flame, no smoke, faster stew.',
  'chef-range': 'Six burners and an oven. The party jollof machine.',
  fridge: 'Cold water on demand, when there is light.',
  'double-fridge': 'A freezer on top and room for a whole pot of soup.',
  'water-drum': 'Fetch once, use all week.',
  'bucket-bowl': 'The shower many of us learned first.',
  'shower-cubicle': 'Water from above. No more scooping.',
  bathtub: 'Bubbles, a long soak and nobody knocking.',
  toilet: 'Your own. No queue in the compound.',
  'wc-suite': 'Quiet lid, strong flush.',
  basin: 'For laundry day and nothing else.',
  'plastic-chair': 'Every party, every compound, every veranda.',
  'velvet-sofa': 'Soft enough to lose the remote in.',
  'family-sofa': 'Room for you, your cousin and their cousin.',
  'leather-sofa': 'Imported leather that squeaks with importance.',
  'gold-sofa': 'For receiving visitors you want to impress.',
  'lounge-armchair': 'One seat, zero sharing.',
  'bean-bag': 'Sink in, struggle to stand up.',
  'corner-lounge': 'Fills a corner and seats the whole match-day crowd.',
  'wall-fan': 'Breeze from a corner nobody was using.',
  'radio-stool': 'Morning news, evening highlife.',
  'sound-system': 'The neighbours will know your playlist.',
  'ludo-board': 'Friendships have ended over this.',
  'small-tv': 'Football, Nollywood and the nine o’clock news.',
  'flat-tv': 'Wide enough to see the offside clearly.',
  'game-console': 'One more match. Just one more.',
  'gym-mat': 'Push-ups before the sun gets serious.',
  'weight-bench': 'A proper bench and a bar that means it.',
  'laptop-desk': 'A desk, a laptop and a side project.',
  bookshelf: 'Novels, textbooks and one borrowed dictionary.',
  keyboard: 'From choir practice to studio dreams.',
  'dance-mirror': 'Check the legwork before the party does.',
  'camera-tripod': 'Golden hour does not wait.',
  'practice-mic': 'Test the jokes on the wall first.',
  'wall-lamp': 'A warm bulb on a bracket.',
  lantern: 'For when the light goes without warning.',
  'standing-lamp': 'Soft light for a soft evening.',
  'led-strip': 'Instant music-video lighting.',
  generator: 'Loud, loyal and never asks the grid for permission.',
  inverter: 'Silent light. The neighbours will ask questions.',
  'wall-calendar': 'A gift from the pharmacy down the road.',
  'jerry-cans': 'Water today, fuel tomorrow.',
  'potted-plant': 'Green, quiet and hard to kill.',
  'wall-art': 'Indigo patterns that make a wall look decided.',
  'centre-rug': 'Shoes off, please.',
  wardrobe: 'The clothes finally leave the chair.',
  aquarium: 'Tiny fish, big calm.',
  'local-dog': 'Barks at strangers, forgives you everything.',
  'house-cat': 'Lives here rent-free and knows it.',
  'grey-parrot': 'Repeats everything. Mind what you say.',
}
