// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-534,"z":2836})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-110.75313749384486,"maxX":158.46617872333195,"minZ":-211.36033296918822,"maxZ":101.14776907806436})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"enugu-north":{"lon":7.4880773871464426,"lat":6.446947918328271},"enugu-south":{"lon":7.52566205444775,"lat":6.40173391825273},"enugu-east":{"lon":7.524443226472161,"lat":6.536295028024751}})
