import { defineCitySpec } from '../spec.ts'

const osmSourceId = 'enugu-osm-selected'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'enugu',
  name: 'Enugu',
  state: {
    id: 'enugu',
    name: 'Enugu',
    sourceName: 'Enugu',
    unit: 'local government area',
    sourceIds: ['enugu-geography'],
  },
  country: { id: 'ng', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 7.5136856,
    lat: 6.4496519,
    teaser: 'The Coal City across Enugu North, Enugu South and Enugu East.',
    preview: ['Coal City history', 'Ogbete Main Market', 'National Museum of Unity'],
    coordinateSourceId: osmSourceId,
    coordinateRef: { provider: 'openstreetmap', element: 'node', id: 27565107 },
  },
  population: { tier: 'city', sourceIds: ['enugu-population'] },
  localUnits: [
    {
      id: 'enugu-north',
      name: 'Enugu North',
      sourceName: 'Enugu North',
      populationTier: 'city',
      description: 'The northern urban local government containing the city centre and Ogbete.',
      sourceIds: ['enugu-geography'],
    },
    {
      id: 'enugu-south',
      name: 'Enugu South',
      sourceName: 'Enugu South',
      populationTier: 'small-city',
      description: 'The southern urban local government containing Awkunanaw and the Aguagwa area.',
      sourceIds: ['enugu-geography'],
    },
    {
      id: 'enugu-east',
      name: 'Enugu East',
      sourceName: 'Enugu East',
      populationTier: 'city',
      description: 'The eastern urban local government extending through Abakpa Nike and Emene.',
      sourceIds: ['enugu-geography'],
    },
  ],
  places: [
    {
      id: 'nnamdi-azikiwe-stadium',
      name: 'Nnamdi Azikiwe Stadium',
      kind: 'stadium',
      lon: 7.4964734,
      lat: 6.4442601,
      localUnitId: 'enugu-north',
      description: 'A mapped stadium in Enugu North.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 617584126 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'flat', sign: 'facade', props: ['lamp', 'tree'] },
    },
    {
      id: 'agofure-park',
      name: 'Agofure park',
      kind: 'park',
      lon: 7.4881237,
      lat: 6.4385958,
      localUnitId: 'enugu-north',
      description: 'A mapped public park in Enugu North.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'node', id: 8753786767 },
      accuracy: 'mapped-feature',
      sourceIds: [osmSourceId],
      scene: { roof: 'hipped', sign: 'roadside', props: ['bench', 'tree'] },
    },
    {
      id: 'ekulu-garden',
      name: 'Ekulu garden',
      kind: 'garden',
      lon: 7.4955845,
      lat: 6.4956334,
      localUnitId: 'enugu-east',
      description: 'A mapped garden in Enugu East.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'node', id: 8753723084 },
      accuracy: 'mapped-feature',
      sourceIds: [osmSourceId],
      scene: { roof: 'hipped', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'jombos-kitchen',
      name: "Jombo's Kitchen",
      kind: 'eatery',
      lon: 7.522927,
      lat: 6.467189,
      localUnitId: 'enugu-east',
      description: 'A mapped restaurant whose cuisine tag includes African soup.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'node', id: 13959213369 },
      accuracy: 'mapped-feature',
      sourceIds: [osmSourceId],
      scene: { roof: 'hipped', sign: 'facade', props: ['planter'] },
      featuredIdentityId: 'african-soup',
    },
    {
      id: 'niger-foundation-hospital',
      name: 'Niger Foundation Hospital & Diagnostic Center',
      kind: 'hospital',
      lon: 7.5135802,
      lat: 6.4430439,
      localUnitId: 'enugu-north',
      description: 'A mapped hospital and diagnostic centre in Enugu North.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 792054615 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'flat', sign: 'facade', props: ['tree'] },
    },
    {
      id: 'national-orthopedic-hospital-enugu',
      name: 'National Orthopedic Hospital Enugu',
      kind: 'hospital',
      lon: 7.5232182,
      lat: 6.4649309,
      localUnitId: 'enugu-east',
      description: 'A mapped hospital complex in Enugu East.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 792054619 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'flat', sign: 'facade', props: ['tree', 'lamp'] },
    },
    {
      id: 'ogbete-main-market',
      name: 'Ogbete main Market',
      kind: 'market',
      lon: 7.4815672,
      lat: 6.4354497,
      localUnitId: 'enugu-north',
      description: 'A mapped marketplace with documented historical produce and artisan trade.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'node', id: 8753676025 },
      accuracy: 'mapped-feature',
      sourceIds: [osmSourceId, 'ogbete-history'],
      scene: { roof: 'gable', sign: 'roadside', props: ['stall', 'lamp'] },
      specialtyIds: ['ogbete-provisions', 'ogbete-artisan-trades'],
    },
    {
      id: 'university-of-nigeria-enugu-campus',
      name: 'University of Nigeria Enugu Campus (UNEC)',
      kind: 'university',
      lon: 7.5045338,
      lat: 6.4232556,
      localUnitId: 'enugu-north',
      description: 'The mapped University of Nigeria campus in Enugu.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1421633156 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'flat', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'institute-of-management-and-technology',
      name: 'Institute of Management and Technology (IMT)',
      kind: 'polytechnic',
      lon: 7.5134,
      lat: 6.4300107,
      localUnitId: 'enugu-north',
      description: 'A mapped tertiary institution in Enugu North.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1421633153 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'flat', sign: 'facade', props: ['tree'] },
    },
    {
      id: 'enugu-state-college-of-education-technical',
      name: 'Enugu State College Of Education (Technical), Enugu',
      kind: 'college',
      lon: 7.498636,
      lat: 6.460075,
      localUnitId: 'enugu-north',
      description: 'A mapped public college in Enugu North.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2460130988 },
      accuracy: 'mapped-feature',
      sourceIds: [osmSourceId],
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'wesley-cathedral',
      name: 'Wesley Cathedral',
      kind: 'church',
      lon: 7.4940956,
      lat: 6.4225293,
      localUnitId: 'enugu-south',
      description: 'A mapped Methodist place of worship in Enugu South.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 630038813 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'gable', sign: 'facade', props: ['tree'] },
    },
    {
      id: 'central-mosque-islamic-centre',
      name: 'Central Mosque, Islamic Centre',
      kind: 'mosque',
      lon: 7.4934845,
      lat: 6.4216448,
      localUnitId: 'enugu-south',
      description: 'A mapped Sunni religious site in Enugu South.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 931313405 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'flat', sign: 'facade', props: ['tree', 'lamp'] },
    },
    {
      id: 'ifenzi-beauty-salon',
      name: 'Ifenzi Beauty Salon',
      kind: 'salon',
      lon: 7.4977946,
      lat: 6.4663188,
      localUnitId: 'enugu-north',
      description: 'A mapped hairdresser in Enugu North.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1135552236 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] },
    },
    {
      id: 'enugu-north-local-government-headquarters',
      name: 'Enugu North Local Government Headquarters',
      kind: 'government',
      lon: 7.486164,
      lat: 6.438371,
      localUnitId: 'enugu-north',
      description: 'The mapped headquarters of Enugu North Local Government.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2455133725 },
      accuracy: 'mapped-feature',
      sourceIds: [osmSourceId],
      scene: { roof: 'flat', sign: 'facade', props: ['lamp', 'tree'] },
    },
    {
      id: 'access-bank-okpara-avenue',
      name: 'Access Bank',
      kind: 'savings',
      lon: 7.494248,
      lat: 6.453484,
      localUnitId: 'enugu-north',
      description: 'A mapped bank on Okpara Avenue.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2455132996 },
      accuracy: 'mapped-feature',
      sourceIds: [osmSourceId],
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'manuwa-bus-sop',
      name: 'manuwa bus sop',
      kind: 'road-hub',
      lon: 7.5076468,
      lat: 6.425058,
      localUnitId: 'enugu-north',
      description: 'A mapped bus station in Enugu North; the source spelling is retained.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 770851671 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'gable', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'enugu-national-museum-of-unity',
      name: "Enugu's National Museum of Unity",
      kind: 'museum',
      lon: 7.5088215,
      lat: 6.461786,
      localUnitId: 'enugu-north',
      description: 'A mapped museum on Abakaliki Road.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1167573499 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'aguagwa',
      name: 'Aguagwa',
      kind: 'civic-landmark',
      lon: 7.4807023,
      lat: 6.415742,
      localUnitId: 'enugu-south',
      description: 'A named site mapped as a tourist attraction on Aguagwa Street.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'node', id: 4592363904 },
      accuracy: 'mapped-feature',
      sourceIds: [osmSourceId],
      scene: { roof: 'hipped', sign: 'roadside', props: ['tree', 'bench'] },
    },
    {
      id: 'akanu-ibiam-international-airport',
      name: 'Akanu Ibiam International Airport',
      kind: 'airport',
      lon: 7.5577709,
      lat: 6.4750846,
      localUnitId: 'enugu-east',
      description: 'The mapped public international aerodrome with IATA code ENU.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 548692606 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'lambi-church-polling',
      name: 'lambi church',
      kind: 'polling',
      lon: 7.4823474,
      lat: 6.4153993,
      localUnitId: 'enugu-south',
      description: 'An OSM-mapped church carrying a polling_station=yes designation; current election service is unverified.',
      coordinateSourceId: osmSourceId,
      coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1135169952 },
      accuracy: 'feature-centroid',
      sourceIds: [osmSourceId],
      scene: { roof: 'gable', sign: 'roadside', props: ['bench'] },
    },
  ],
  identity: {
    foods: [
      {
        id: 'african-soup',
        name: 'African soup',
        description: "Jombo's Kitchen is mapped with African soup in its cuisine tag.",
        localProductId: 'local-plate',
        sourceIds: [osmSourceId],
      },
      {
        id: 'ogbete-provisions',
        name: 'Ogbete provisions',
        description: 'Historical Ogbete trade included yam, rice, pepper, fruit, kola, garri and palm wine.',
        sourceIds: ['ogbete-history'],
      },
    ],
    crafts: [
      {
        id: 'ogbete-artisan-trades',
        name: 'Ogbete artisan trades',
        description: 'A historical account records tailoring, blacksmithing, fashion, hair salons and barbing at Ogbete.',
        sourceIds: ['ogbete-history'],
      },
    ],
    industries: [
      {
        id: 'coal-mining-history',
        name: 'Coal mining history',
        description: 'Coal discovery in 1909 led to mining operations in 1915; the state investment guide also records local coal resources.',
        sourceIds: ['enugu-history', 'enugu-investment'],
      },
    ],
  },
  transport: { airports: [], rail: [], ports: [] },
  climate: {
    profile: 'southern-wet-dry',
    rainyMonths: [4, 5, 6, 7, 8, 9, 10],
    dryMonths: [11, 12, 1, 2, 3],
    description: 'A humid tropical climate with an April-October rainy season and November-March dry season.',
    clearLabel: 'Dry season',
    harmattan: { months: [12, 1], label: 'Harmattan' },
    sourceIds: ['enugu-climate-seasons', 'enugu-climate-report'],
  },
  homePalette: { back: '#d8c7a7', left: '#9b7653', floor: ['#6e8254', '#b28b60'] },
  geometry: {
    surface: {
      path: 'scripts/geo/sources/formula/enugu-surface.geojson',
      bytes: 289833,
      sha256: '211493c7a1c5dde3479f076495b4cf8708bf0e9f65849f10ae2cff33bb49c4b5',
    },
  },
  sourceGroups: [
    {
      id: osmSourceId,
      title: 'Selected OpenStreetMap records for Enugu',
      url: 'https://www.openstreetmap.org/',
      checkedOn: '2026-10-06',
      supports: ['coordinate', 'identity'],
      licence: 'OpenStreetMap contributors, ODbL 1.0',
      cache: {
        path: 'scripts/city/research/enugu/reviewed/osm-selected.json',
        bytes: 4993,
        sha256: '5ffa3212b62f5b1b7bb4d237c741a0a7c0f61ff4edda0ba26039311b31b601c8',
      },
    },
    {
      id: 'enugu-geography',
      title: 'geoBoundaries Enugu administrative boundaries',
      url: 'https://www.geoboundaries.org/countryDownloads.html',
      checkedOn: '2026-10-06',
      supports: ['geography'],
      licence: 'CC BY 4.0',
      cache: {
        path: 'scripts/city/research/enugu/reviewed/geography.json',
        bytes: 554,
        sha256: '43432a425a3094a95eb80224059b66401724367acb79f33a5e1852e8fb4dd69f',
      },
    },
    {
      id: 'enugu-population',
      title: 'National Bureau of Statistics Annual Abstract',
      url: 'https://nigerianstat.gov.ng/pdfuploads/Annual_Abstract_of_Statistics_2011.pdf',
      checkedOn: '2026-10-06',
      supports: ['population'],
      cache: {
        path: 'scripts/city/research/enugu/population-nbs.txt',
        bytes: 471,
        sha256: '32c6d28fb1ba4066d1d436c6075890fc4b779d78225043721784187626921977',
      },
    },
    {
      id: 'enugu-climate-seasons',
      title: 'Climate change and agricultural sustainability in Enugu',
      url: 'https://eajournals.org/wp-content/uploads/Formatted-Climate-Change-Implications-for-Agricultural-Sustainability-in-Enugu-1.pdf',
      checkedOn: '2026-10-06',
      supports: ['climate'],
      cache: {
        path: 'scripts/city/research/enugu/reviewed/climate-seasons.txt',
        bytes: 280,
        sha256: '860287246da625abbcac6c0eeeb3b34575787a5e5aced41c73b2adb2905617cf',
      },
    },
    {
      id: 'enugu-climate-report',
      title: 'Konexa Enugu ESIA climate report',
      url: 'https://www.miga.org/sites/default/files/2025-12/Konexa_Enugu_ESIA_Final_Report_26112025_0.pdf',
      checkedOn: '2026-10-06',
      supports: ['climate'],
      cache: {
        path: 'scripts/city/research/enugu/climate-report.txt',
        bytes: 436,
        sha256: 'c29b2ddd4b62041942a715bd66add5a44544cc551a22e7f812c20ce7d194b5d7',
      },
    },
    {
      id: 'enugu-history',
      title: 'Enugu State Government history',
      url: 'https://enugustate.gov.ng/our-history/',
      checkedOn: '2026-10-06',
      supports: ['identity'],
      cache: {
        path: 'scripts/city/research/enugu/official-history.txt',
        bytes: 322,
        sha256: 'f841272c2acfbe58ec5c3c6488ac9be87713858b528b3c4c3837ec7872a1aa32',
      },
    },
    {
      id: 'enugu-investment',
      title: 'Enugu State Investment Guide',
      url: 'https://enugustate.gov.ng/wp-content/uploads/2024/05/ENUGU-STATE-INVESTMENT-GUIDE-Final-Version-NEW-AJUSTED.pdf',
      checkedOn: '2026-10-06',
      supports: ['identity'],
      cache: {
        path: 'scripts/city/research/enugu/investment-guide.txt',
        bytes: 425,
        sha256: '806e73d2598b36cf68127caa44d81737d325315f2120cf130824a0f035a7cac3',
      },
    },
    {
      id: 'ogbete-history',
      title: 'University journal article on Ogbete Main Market',
      url: 'https://www.nigerianjournalsonline.com/index.php/uj/article/download/3391/3303',
      checkedOn: '2026-10-06',
      supports: ['identity'],
      cache: {
        path: 'scripts/city/research/enugu/ogbete-history.txt',
        bytes: 501,
        sha256: '29eee2e36874d8a8cc5605fdb972a23a604795575e99508fd82825d89ced1910',
      },
    },
  ],
})
