// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "antananarivo",
  "name": "Antananarivo",
  "country": {
    "idISOlower": "mg",
    "name": "Madagascar"
  },
  "state": {
    "idunique": "mg-zone",
    "name": "Starter"
  },
  "timezone": "Indian/Antananarivo",
  "centre": {
    "lon": 47.514678,
    "lat": -18.914691
  },
  "airport": {
    "id": "antananarivo-airport",
    "name": "Ivato International Airport",
    "lon": 47.478802,
    "lat": -18.7969,
    "sourceUrl": "https://ourairports.com/airports/FMMI/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=47.511678,-18.917691,47.517678,-18.911691",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    47.466802,
    -18.929691,
    47.529678,
    -18.7849
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
