// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "bissau",
  "name": "Bissau",
  "country": {
    "idISOlower": "gw",
    "name": "Guinea-Bissau"
  },
  "state": {
    "idunique": "gw-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Bissau",
  "centre": {
    "lon": -15.598361,
    "lat": 11.865024
  },
  "airport": {
    "id": "bissau-airport",
    "name": "Osvaldo Vieira International Airport",
    "lon": -15.653596,
    "lat": 11.894262,
    "sourceUrl": "https://ourairports.com/airports/GGOV/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-15.601361,11.862024,-15.595361,11.868024",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -15.665596,
    11.850024,
    -15.583361,
    11.906262
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
