// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "mogadishu",
  "name": "Mogadishu",
  "country": {
    "idISOlower": "so",
    "name": "Somalia"
  },
  "state": {
    "idunique": "so-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Mogadishu",
  "centre": {
    "lon": 45.364732,
    "lat": 2.068627
  },
  "airport": {
    "id": "mogadishu-airport",
    "name": "Aden Adde International Airport",
    "lon": 45.304699,
    "lat": 2.01444,
    "sourceUrl": "https://ourairports.com/airports/HCMM/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=45.361732,2.065627,45.367732,2.071627",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    45.292699,
    2.00244,
    45.379732,
    2.0867873
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates. Published bounds include complete retained OSM feature coordinates and expand by at most 0.02 degrees beyond the initial settlement/airport bounds."
} satisfies DestinationFacts
