// Generated by scripts/city/build-catalogue.ts. Do not add cities here by hand.
import type { CityCatalogueRow } from './catalogue.ts'

export const GENERATED_CITY_CATALOGUE_ROWS = Object.freeze([
  ["lagos","Lagos","lagos","Lagos State",3.38,6.52,1],
  ["ibadan","Ibadan","oyo","Oyo State",3.95,7.38,1],
  ["abuja","Abuja","fct","Federal Capital Territory",7.49,9.06,1],
  ["port-harcourt","Port Harcourt","rivers","Rivers State",7.03,4.82,1],
  ["abeokuta","Abeokuta","ogun","Ogun State",3.35,7.15,0],
  ["ota","Ota","ogun","Ogun State",3.2,6.68,0],
  ["ijebu-ode","Ijebu-Ode","ogun","Ogun State",3.92,6.82,0],
  ["sagamu","Sagamu","ogun","Ogun State",3.64,6.85,0],
  ["kano","Kano","kano","Kano State",8.52,12,1],
] satisfies readonly CityCatalogueRow[])
