// Generated by scripts/city/build-catalogue.ts. Do not edit by hand.
export const COUNTRY_DIRECTORY_DESCRIPTOR = Object.freeze({
  baseUrl: '/world-country-directory/',
  indexPath: "index-ed4496e128791ba39944343c194fe1fc6a77f044b2e23f0db48a1fe8cf612b93.json",
  indexSha256: "ed4496e128791ba39944343c194fe1fc6a77f044b2e23f0db48a1fe8cf612b93",
  admissionSha256: "764d5c64f075c68361ae6c15fea23a016b6c2b1af9fc15e81cf405ee20ef195b",
  c1Commit: "c1f7c1f7369139ce559292318ba9842c23a28267",
  inventorySha256: "90c931e87b4758544e8de321ecb0bf3b41420cbbf9aeb504b66b93c6938c2e0b",
} as const)
