// Generated by scripts/city/build-catalogue.ts. Do not edit by hand.
export const COUNTRY_DIRECTORY_DESCRIPTOR = Object.freeze({
  baseUrl: '/world-country-directory/',
  indexPath: "index-361f4694e6c02839130544178474249afe02524bd31b0d004cec4f735036f2c0.txt",
  indexSha256: "361f4694e6c02839130544178474249afe02524bd31b0d004cec4f735036f2c0",
  admissionSha256: "c882a0975ab7ec6d5f538c44ccf2447d50d159068f1daab877d026a81b9fbe91",
  c1Commit: "c1f7c1f7369139ce559292318ba9842c23a28267",
  inventorySha256: "90c931e87b4758544e8de321ecb0bf3b41420cbbf9aeb504b66b93c6938c2e0b",
} as const)
