// Generated by scripts/city/build-catalogue.ts. Do not add cities here by hand.
import type { CityModuleLoader } from './catalogue.ts'

export const GENERATED_CITY_LOADERS = Object.freeze([
  async()=>(await import("./lagos/index.ts")).lagosCity,
  async()=>(await import("./ibadan/index.ts")).ibadanCity,
  async()=>(await import("./abuja/index.ts")).abujaCity,
  async()=>(await import("./port-harcourt/index.ts")).portHarcourtCity,
  async()=>(await import("./abeokuta/index.ts")).abeokutaCity,
  async()=>(await import("./ota/index.ts")).otaCity,
  async()=>(await import("./ijebu-ode/index.ts")).ijebuOdeCity,
  async()=>(await import("./sagamu/index.ts")).sagamuCity,
  async()=>(await import("./kano/index.ts")).kanoCity,
] satisfies readonly CityModuleLoader[])
