// Generated by scripts/city/build-catalogue.ts. Do not add routes here by hand.
import type { CityLink } from '../../types/content.ts'

const compactLagosFlights = [
    ["accra","Accra",412,53000,15],
    ["algiers","Algiers",3371,290000,20],
    ["lome","Lomé",243,39000,13],
    ["nairobi","Nairobi",3807,325000,20],
    ["yaounde","Yaoundé",943,95000,20],
    ["abidjan","Abidjan",830,86000,20],
    ["addis-ababa","Addis Ababa",3898,332000,20],
    ["cape-town","Cape Town",4760,401000,20],
    ["cotonou","Cotonou",110,29000,12],
    ["dakar","Dakar",2458,217000,20],
    ["cairo","Cairo",3919,334000,20],
    ["rabat","Rabat",3242,279000,20],
    ["kigali","Kigali",3103,268000,20],
    ["kampala","Kampala",3308,285000,20],
    ["lusaka","Lusaka",3664,313000,20]
  ] as const satisfies readonly (readonly [CityLink['b'], string, number, number, number])[]

const compactLagosFlight = ([b, name, km, fare, seconds]: readonly [CityLink['b'], string, number, number, number]): CityLink => ({
  a: 'lagos', b, mode: 'air', beta: true, label: 'Flight between Lagos and ' + name, icon: '✈️', km, fare, seconds,
})

export const AUTHORED_CITY_LINKS = Object.freeze([
    {
      "a": "lagos",
      "b": "ibadan",
      "mode": "road",
      "beta": true,
      "label": "Bus on the Lagos–Ibadan Expressway",
      "icon": "🚌",
      "fare": 3500,
      "km": 130,
      "seconds": 30
    },
    {
      "a": "lagos",
      "b": "abuja",
      "mode": "road",
      "beta": true,
      "label": "Night bus through Lokoja",
      "icon": "🚌",
      "fare": 14000,
      "km": 760,
      "seconds": 59
    },
    {
      "a": "lagos",
      "b": "abuja",
      "mode": "air",
      "beta": true,
      "label": "Flight between Lagos and Abuja",
      "icon": "✈️",
      "fare": 65000,
      "km": 520,
      "seconds": 16
    },
    {
      "a": "lagos",
      "b": "port-harcourt",
      "mode": "road",
      "beta": true,
      "label": "Bus through Benin and the East–West Road",
      "icon": "🚌",
      "fare": 12000,
      "km": 620,
      "seconds": 53
    },
    {
      "a": "lagos",
      "b": "port-harcourt",
      "mode": "air",
      "beta": true,
      "label": "Flight between Lagos and Port Harcourt",
      "icon": "✈️",
      "fare": 60000,
      "km": 440,
      "seconds": 15
    },
    {
      "a": "lagos",
      "b": "ibadan",
      "mode": "rail",
      "beta": true,
      "label": "Train between Mobolaji Johnson and Obafemi Awolowo stations",
      "icon": "🚆",
      "fare": 9000,
      "km": 157,
      "seconds": 21
    },
    {
      "a": "lagos",
      "b": "ota",
      "mode": "road",
      "label": "Bus on the Lagos–Abeokuta Expressway",
      "icon": "🚌",
      "fare": 2000,
      "km": 40,
      "beta": true,
      "seconds": 26
    },
    {
      "a": "lagos",
      "b": "abeokuta",
      "mode": "road",
      "label": "Bus on the Lagos–Abeokuta Expressway",
      "icon": "🚌",
      "fare": 3500,
      "km": 100,
      "beta": true,
      "seconds": 29
    },
    {
      "a": "lagos",
      "b": "abeokuta",
      "mode": "rail",
      "label": "Train between Mobolaji Johnson and Professor Wole Soyinka stations",
      "icon": "🚆",
      "fare": 7000,
      "km": 110,
      "beta": true,
      "seconds": 19
    },
    {
      "a": "abeokuta",
      "b": "ibadan",
      "mode": "road",
      "label": "Bus on the Abeokuta–Ibadan Road",
      "icon": "🚌",
      "fare": 3000,
      "km": 85,
      "beta": true,
      "seconds": 28
    },
    {
      "a": "abeokuta",
      "b": "ibadan",
      "mode": "rail",
      "label": "Train between Professor Wole Soyinka and Obafemi Awolowo stations",
      "icon": "🚆",
      "fare": 4000,
      "km": 85,
      "beta": true,
      "seconds": 19
    },
    {
      "a": "ibadan",
      "b": "abuja",
      "mode": "road",
      "beta": true,
      "label": "Bus through Ilorin",
      "icon": "🚌",
      "fare": 12000,
      "km": 640,
      "seconds": 54
    },
    {
      "a": "abuja",
      "b": "port-harcourt",
      "mode": "road",
      "beta": true,
      "label": "Bus through Enugu",
      "icon": "🚌",
      "fare": 11000,
      "km": 600,
      "seconds": 52
    },
    {
      "a": "abuja",
      "b": "port-harcourt",
      "mode": "air",
      "beta": true,
      "label": "Flight between Abuja and Port Harcourt",
      "icon": "✈️",
      "fare": 55000,
      "km": 450,
      "seconds": 15
    },
    {
      "a": "abuja",
      "b": "kaduna",
      "mode": "rail",
      "beta": true,
      "label": "Train between Idu and Rigasa",
      "icon": "🚆",
      "fare": 6000,
      "km": 186,
      "seconds": 22
    },
    {
      "a": "ota",
      "b": "abeokuta",
      "mode": "road",
      "label": "Bus through Ifo",
      "icon": "🚌",
      "fare": 2500,
      "km": 70,
      "beta": true,
      "seconds": 27
    },
    {
      "a": "abeokuta",
      "b": "sagamu",
      "mode": "road",
      "label": "Bus on the Sagamu–Abeokuta Road",
      "icon": "🚌",
      "fare": 2500,
      "km": 75,
      "beta": true,
      "seconds": 27
    },
    {
      "a": "ota",
      "b": "sagamu",
      "mode": "road",
      "label": "Bus through the expressway interchange",
      "icon": "🚌",
      "fare": 2500,
      "km": 80,
      "beta": true,
      "seconds": 28
    },
    {
      "a": "sagamu",
      "b": "ijebu-ode",
      "mode": "road",
      "label": "Bus on the Sagamu–Benin Road",
      "icon": "🚌",
      "fare": 1500,
      "km": 55,
      "beta": true,
      "seconds": 27
    },
    {
      "a": "lagos",
      "b": "kano",
      "mode": "air",
      "beta": true,
      "label": "Flight between Lagos and Kano",
      "icon": "✈️",
      "fare": 85000,
      "km": 834,
      "seconds": 20
    },
    {
      "a": "lagos",
      "b": "kano",
      "mode": "road",
      "beta": true,
      "label": "Long-distance bus through Ilorin and Kaduna",
      "icon": "🚌",
      "fare": 20000,
      "km": 1100,
      "seconds": 75
    },
    {
      "a": "lagos",
      "b": "kano",
      "mode": "rail",
      "status": "coming",
      "beta": true,
      "label": "Train on the Lagos–Kano line",
      "icon": "🚆",
      "fare": 16000,
      "km": 1100,
      "seconds": 50
    },
    {
      "a": "abuja",
      "b": "kano",
      "mode": "air",
      "beta": true,
      "label": "Flight between Abuja and Kano",
      "icon": "✈️",
      "fare": 45000,
      "km": 364,
      "seconds": 14
    },
    {
      "a": "abuja",
      "b": "kano",
      "mode": "road",
      "beta": true,
      "label": "Bus through Kaduna and Zaria",
      "icon": "🚌",
      "fare": 9000,
      "km": 450,
      "seconds": 45
    },
    ...compactLagosFlights.map(compactLagosFlight)
  ] satisfies readonly CityLink[])
