// A compact table of common emoji for the picker: text only, no images or fonts. One line per category, entries separated by
// "|", each entry the emoji, then its keywords. The picker searches the keywords.
export interface EmojiCategory { id: string; label: string; icon: string; emoji: readonly { char: string; words: string }[] }
const table: readonly [string, string, string, string][] = [
  ['faces', 'Smileys', '😀', '😀 grin happy smile|😃 smile happy open|😄 laugh happy joy|😁 beam grin teeth|😆 laugh squint lol|😅 sweat nervous relief|🤣 rofl laugh floor lol|😂 joy tears laugh lol|🙂 smile slight|🙃 upside down silly|😉 wink|😊 blush smile shy|😇 angel halo innocent|🥰 love hearts adore|😍 heart eyes love|🤩 star struck wow|😘 kiss blow love|😗 kiss|😚 kiss closed|😋 yum tasty tongue|😛 tongue|😜 wink tongue silly|🤪 zany crazy|😝 tongue squint|🤑 money rich|🤗 hug|🤭 oops giggle|🤫 shush quiet secret|🤔 think hmm|🤐 zip mouth|😐 neutral|😑 expressionless|😶 silent|😏 smirk|😒 unamused|🙄 eyeroll|😬 grimace awkward|😌 relieved calm|😔 sad pensive|😪 sleepy|😴 sleep zzz|😷 mask sick|🤒 fever sick|🤕 hurt bandage|🤢 nausea sick|🤮 vomit|🥵 hot|🥶 cold freezing|🥴 woozy drunk|😵 dizzy|🤯 mind blown|🤠 cowboy|🥳 party celebrate|😎 cool sunglasses|🤓 nerd|🧐 monocle|😕 confused|😟 worried|🙁 frown|😮 wow surprised|😲 astonished|🥺 pleading please|😢 cry sad tear|😭 sob cry loud|😱 scream fear shock|😖 confounded|😞 disappointed|😓 downcast sweat|😩 weary tired|😫 tired|🥱 yawn bored|😤 triumph huff|😡 angry mad|😠 angry|🤬 swearing cursing|😈 devil|💀 skull dead|💩 poop|🤡 clown|👻 ghost|👽 alien|🤖 robot'],
  ['people', 'People', '👋', '👋 wave hello bye|🤚 hand stop|✋ raised hand high five|🖖 vulcan|👌 ok perfect|🤌 pinched italian|✌️ peace victory|🤞 fingers crossed luck|🤟 love you|🤘 rock|🤙 call me shaka|👈 left point|👉 right point|👆 up point|👇 down point|☝️ one up|👍 thumbs up yes good like|👎 thumbs down no bad|✊ fist power|👊 punch fist bump|🤛 fist left|🤜 fist right|👏 clap applause|🙌 hooray raised hands|👐 open hands|🤲 palms|🤝 handshake deal|🙏 pray thanks please|💪 strong muscle flex|🧠 brain|👀 eyes look|👂 ear|👃 nose|👄 mouth|🫶 heart hands love|🫡 salute|🫠 melting|🧍 stand|🚶 walk|🏃 run|💃 dance woman|🕺 dance man|👨‍👩‍👧‍👦 family|👶 baby|👦 boy|👧 girl|👨 man|👩 woman|🧓 elder|👮 police|👷 builder|🧑‍🍳 cook|🧑‍🏫 teacher|🧑‍⚕️ doctor|🧑‍🎤 singer|🧑‍💻 coder'],
  ['hearts', 'Hearts', '❤️', '❤️ red heart love|🧡 orange heart|💛 yellow heart|💚 green heart|💙 blue heart|💜 purple heart|🖤 black heart|🤍 white heart|🤎 brown heart|💔 broken heart sad|❣️ heart exclamation|💕 two hearts|💞 revolving hearts|💓 beating heart|💗 growing heart|💖 sparkling heart|💘 cupid arrow|💝 gift heart|💯 hundred perfect|🔥 fire lit hot|✨ sparkles shine|⭐ star|🌟 glowing star|💫 dizzy star|💥 boom collision|💢 anger|💦 sweat drops water|💤 sleeping zzz|🎉 party popper celebrate|🎊 confetti|🎈 balloon|🎁 gift present|🏆 trophy win|🥇 gold medal first|🥈 silver|🥉 bronze|🎯 target bullseye|🎵 music note|🎶 notes music|🎤 mic sing|🎧 headphones|🥁 drum'],
  ['animals', 'Animals', '🐶', '🐶 dog puppy|🐱 cat kitten|🐭 mouse|🐹 hamster|🐰 rabbit bunny|🦊 fox|🐻 bear|🐼 panda|🐨 koala|🐯 tiger|🦁 lion|🐮 cow|🐷 pig|🐸 frog|🐵 monkey|🙈 see no evil|🙉 hear no evil|🙊 speak no evil|🐔 chicken|🐧 penguin|🐦 bird|🐤 chick|🦅 eagle|🦉 owl|🦇 bat|🐺 wolf|🐴 horse|🦄 unicorn|🐝 bee|🦋 butterfly|🐌 snail|🐛 bug caterpillar|🐜 ant|🕷️ spider|🐢 turtle|🐍 snake|🦎 lizard|🐙 octopus|🦀 crab|🐠 fish|🐬 dolphin|🐳 whale|🦈 shark|🐊 crocodile|🐘 elephant|🦒 giraffe|🦓 zebra|🦍 gorilla|🐪 camel|🐐 goat|🐑 sheep|🐓 rooster|🌸 blossom flower|🌹 rose|🌺 hibiscus|🌻 sunflower|🌴 palm tree|🌳 tree|🌿 herb leaf|🍀 clover luck|🌍 earth africa|🌙 moon|☀️ sun|⛅ cloud sun|🌧️ rain|⚡ lightning|❄️ snow|🌈 rainbow'],
  ['food', 'Food', '🍔', '🍎 apple|🍌 banana|🍊 orange|🍋 lemon|🍉 watermelon|🍇 grapes|🍓 strawberry|🍍 pineapple|🥭 mango|🥥 coconut|🍅 tomato|🥑 avocado|🌽 corn maize|🥕 carrot|🌶️ pepper hot chili|🥔 potato|🍠 yam sweet potato|🍞 bread|🥖 baguette|🧀 cheese|🥚 egg|🍳 fried egg|🥞 pancakes|🍗 chicken drumstick|🍖 meat|🍔 burger|🍟 fries chips|🍕 pizza|🌭 hot dog|🌮 taco|🌯 wrap burrito|🥙 pita|🍝 spaghetti pasta|🍜 noodles ramen|🍲 stew pot soup|🍛 curry rice|🍚 rice jollof|🍣 sushi|🍤 shrimp prawn|🍦 ice cream|🍰 cake|🎂 birthday cake|🍩 doughnut|🍪 cookie|🍫 chocolate|🍬 candy sweet|🥜 peanuts groundnut|☕ coffee tea|🍵 tea|🥛 milk|🍺 beer|🍻 cheers beers|🥂 cheers champagne|🍷 wine|🍹 cocktail|🥤 drink soda|💧 water drop|🧊 ice'],
  ['things', 'Things', '⚽', '⚽ football soccer|🏀 basketball|🏈 american football|🎾 tennis|🏐 volleyball|🏓 table tennis|🎱 pool|🥊 boxing|🎮 game controller|🕹️ joystick|🎲 dice|♟️ chess|🧩 puzzle|📱 phone mobile|💻 laptop computer|⌚ watch|📷 camera|📸 flash photo|📺 tv|📻 radio|🔋 battery|🔌 plug|💡 idea bulb light|🔦 torch flashlight|📚 books|📖 book read|✏️ pencil|📝 memo note write|📌 pin|📎 paperclip|✂️ scissors|🔑 key|🔒 lock|🔓 unlock|🛒 cart shopping|💰 money bag|💵 cash dollar|💳 card|🧾 receipt|📦 package parcel|📧 email|📨 incoming mail|📅 calendar|⏰ alarm clock|⏳ hourglass|⌛ time|🚗 car|🚕 taxi|🚌 bus|🚲 bike bicycle|🏍️ motorbike okada|🚆 train|✈️ plane flight|🚀 rocket|⛵ boat|🏠 house home|🏢 office building|🏥 hospital|🏫 school|⛪ church|🕌 mosque|🏖️ beach|⛰️ mountain|🌆 city|🗺️ map|📍 location pin|🧭 compass'],
  ['symbols', 'Symbols', '✅', '✅ check yes done|❌ cross no wrong|❎ cross box|⭕ circle|❗ exclamation|❓ question|‼️ double exclamation|⁉️ interrobang|⚠️ warning|🚫 prohibited|⛔ no entry|🔞 adults only|♻️ recycle|➕ plus|➖ minus|➗ divide|✖️ multiply|💲 dollar|🔔 bell notification|🔕 bell off mute|📢 loudspeaker|📣 megaphone|💬 speech bubble chat|💭 thought bubble|🗯️ anger bubble|♥️ heart suit|♠️ spade|🔴 red circle|🟠 orange circle|🟡 yellow circle|🟢 green circle|🔵 blue circle|🟣 purple circle|⚫ black circle|⚪ white circle|🔺 red triangle up|🔻 red triangle down|⬆️ up arrow|⬇️ down arrow|⬅️ left arrow|➡️ right arrow|🔁 repeat|🔄 refresh|🆗 ok|🆕 new|🆒 cool|🆓 free|🔝 top|🇳🇬 nigeria flag|🇬🇭 ghana flag|🇿🇦 south africa flag|🇰🇪 kenya flag|🇬🇧 uk flag|🇺🇸 usa flag|🇨🇦 canada flag|🏳️ white flag|🏁 chequered flag finish|🚩 red flag'],
];
export const EMOJI_CATEGORIES: readonly EmojiCategory[] = table.map(([id, label, icon, entries]) => ({ id, label, icon, emoji: entries.split('|').map((entry) => { const cut = entry.indexOf(' '); return { char: entry.slice(0, cut), words: entry.slice(cut + 1) }; }) }));
/** The six quick reactions. */
export const QUICK_REACTIONS: readonly string[] = ['👍', '❤️', '😂', '😮', '😢', '🙏'];
/** `:name:` shortcodes for a keyboard: a small set. */
export const SHORTCODES: Readonly<Record<string, string>> = { smile: '😊', grin: '😀', joy: '😂', lol: '😂', heart: '❤️', love: '😍', thumbsup: '👍', '+1': '👍', pray: '🙏', fire: '🔥', clap: '👏', cry: '😢', sob: '😭', wink: '😉', cool: '😎', party: '🥳', think: '🤔', ok: '👌', wave: '👋', eyes: '👀', '100': '💯', tada: '🎉', sad: '😞', angry: '😠', laugh: '🤣', kiss: '😘', strong: '💪', star: '⭐' };
