// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "n-djamena",
  "name": "N'Djamena",
  "country": {
    "idISOlower": "td",
    "name": "Chad"
  },
  "state": {
    "idunique": "td-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Ndjamena",
  "centre": {
    "lon": 15.047202,
    "lat": 12.115042
  },
  "airport": {
    "id": "n-djamena-airport",
    "name": "N'Djamena International Airport",
    "lon": 15.034,
    "lat": 12.1337,
    "sourceUrl": "https://ourairports.com/airports/FTTJ/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=15.044202,12.112042,15.050202,12.118042",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    15.022,
    12.100042,
    15.062202,
    12.1457
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
