// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Ifiok Akpan", role: "Park caretaker", quotes: ["I keep Unity Park tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ekemini Okon", role: "Morning walker", quotes: ["I walk through Unity Park before work.", "Fresh air first, then the day."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Akpan Essien", role: "Church volunteer", quotes: ["Welcome to Full Life Christian Centre. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mfon Ibanga", role: "Regular worshipper", quotes: ["I have worshipped at Full Life Christian Centre for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifiok Ekpe", role: "Church volunteer", quotes: ["Welcome to RCCG Zion Super Mega Parish Uyo. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ekemini Inyang", role: "Regular worshipper", quotes: ["I have worshipped at RCCG Zion Super Mega Parish Uyo for a long time.", "Sit anywhere there is room, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Akpan Umoh", role: "Cook", quotes: ["Today the pot at Cheeries Fast food holds Afang soup.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mfon Udo", role: "Regular diner", quotes: ["I come to Cheeries Fast food for Afang soup.", "Afang soup is a vegetable soup made by the Ibibio people of Akwa Ibom State."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifiok Usoro", role: "Cook", quotes: ["Today the pot at Night fast food holds Edikang Ikong.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ekemini Akpan", role: "Regular diner", quotes: ["I come to Night fast food for Edikang Ikong.", "Edikang ikong is a vegetable soup that originated among the Efik people and the Ibibio people of Akwa Ibom State."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Akpan Ekong", role: "Student", quotes: ["I am on my way to a lecture at University of Uyo.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mfon Essien", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifiok Effiong", role: "Museum guide", quotes: ["Welcome to National Museum, Uyo. Please take your time.", "Ask me if you want to know what is on display."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ekemini Ekpe", role: "Visitor", quotes: ["I came to National Museum, Uyo to learn something new.", "Read the labels slowly. They reward you."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Akpan Etim", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mfon Umoh", role: "Patient's relative", quotes: ["I am waiting with a relative at University of Uyo Teaching Hospital.", "Everyone here is patient, so I must be too."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifiok Bassey", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ekemini Usoro", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Akpan Udoh", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mfon Ekong", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifiok Ukpong", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ekemini Effiong", role: "Supporter", quotes: ["I come to Godswill Akpabio International Stadium for the football.", "Sit high up and you see the whole game."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Akpan Idiong", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mfon Etim", role: "Supporter", quotes: ["I come to Uyo Township Stadium for the football.", "Sit high up and you see the whole game."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifiok Okon", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ekemini Bassey", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Akpan Ibanga", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mfon Udoh", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifiok Inyang", role: "Market trader", quotes: ["Looking for Akpan Andem yam trade? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ekemini Ukpong", role: "Shopper", quotes: ["BusinessDay quotes a yam seller at the popular Akpan Andem market in Uyo.", "Take your time, and bargain with a smile."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Akpan Udo", role: "Ticket seller", quotes: ["Check the board for your departure.", "Keep your bags close in a crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mfon Idiong", role: "Traveller", quotes: ["I am waiting at AKTC Park for my bus.", "Travelling is half waiting."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
