// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-83,"z":4412})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-108.53262741606451,"maxX":175.18010766505358,"minZ":-238.89411762332475,"maxZ":89.73860539875204})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"uyo":{"lon":7.942422713944772,"lat":5.016101519256394},"itu":{"lon":7.987282246781992,"lat":5.1422168490365605}})
