// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "victoria",
  "name": "Victoria",
  "country": {
    "idISOlower": "sc",
    "name": "Seychelles"
  },
  "state": {
    "idunique": "sc-starter",
    "name": "Starter zone"
  },
  "timezone": "Indian/Mahe",
  "centre": {
    "lon": 55.44999,
    "lat": -4.616632
  },
  "airport": {
    "id": "victoria-airport",
    "name": "Seychelles International Airport",
    "lon": 55.521801,
    "lat": -4.67434,
    "sourceUrl": "https://ourairports.com/airports/FSIA/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=55.44699,-4.619632,55.45299,-4.613632",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    55.43499,
    -4.68634,
    55.533801,
    -4.601632
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
