// Generated by scripts/world/build-playable-africa.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "algiers",
  "name": "Algiers",
  "country": {
    "idISOlower": "dz",
    "name": "Algeria"
  },
  "state": {
    "idunique": "dz-starter",
    "name": "Starter district"
  },
  "timezone": "Africa/Algiers",
  "centre": {
    "lon": 3.048607,
    "lat": 36.765011
  },
  "airport": {
    "id": "algiers-airport",
    "name": "ALGER / Houari Boumediene",
    "lon": 3.216944444,
    "lat": 36.694444444,
    "sourceUrl": "https://di.univ-blida.dz/jspui/bitstream/123456789/10975/1/M%C3%A9moire%20fin%20d%27%C3%A9tude%202020%20copie%20finale%20%20conversion.pdf"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and national aeronautical information sources",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=3.045607,36.762011,3.051607,36.768011",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; Airport reference points: national aeronautical information sources",
  "bounds": [
    3.033607,
    36.682444,
    3.228944,
    36.780011
  ],
  "coverageNote": "Starter visitor area. Real capital and airport points, clipped country land and a bounded central street/building sample. Visitor services and homes are fictional game content. Buildings use approximate box silhouettes; missing heights are estimates. Game prices remain in the shared Allworld economy."
} satisfies DestinationFacts
