// Generated by world/game-map-bundle-cli.ts; do not edit by hand.
export const COUNTRY_DETAIL_CATALOGUE_PATH = "/world-country-detail/catalogue-v1-3ea655c132699dbb81388dc9ed2ad2fc5cfd64127755a54acb64e34f3c6304fd.txt" as const;
export const COUNTRY_DETAIL_CATALOGUE_SHA256 = "3ea655c132699dbb81388dc9ed2ad2fc5cfd64127755a54acb64e34f3c6304fd" as const;
export const COUNTRY_DETAIL_ATLAS_SHA256 = "55f1c27403e3ebc639fd685b911b9e89c6c033f3e8e5202dd043ef7ae0c3b1f2" as const;
export const COUNTRY_DETAIL_DIRECTORY_MANIFEST_SHA256 = "b3fb51b5660ed22b2ee354235c60291d6857b3dd9245afbabec3fc15918c8501" as const;
export const COUNTRY_DETAIL_SOURCE_SHA256 = "239eec57ac17f100a11e2536cffc56752c318b50ae765b0918ff7aab4ce8f255" as const;
export const COUNTRY_DETAIL_SOURCE_BYTES = 13287234 as const;
