// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "niamey",
  "name": "Niamey",
  "country": {
    "idISOlower": "ne",
    "name": "Niger"
  },
  "state": {
    "idunique": "ne-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Niamey",
  "centre": {
    "lon": 2.11471,
    "lat": 13.518652
  },
  "airport": {
    "id": "niamey-airport",
    "name": "Diori Hamani International Airport",
    "lon": 2.18361,
    "lat": 13.4815,
    "sourceUrl": "https://ourairports.com/airports/DRRN/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=2.11171,13.515652,2.11771,13.521652",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    2.09971,
    13.4695,
    2.19561,
    13.533652
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
