// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Laraba Adamu", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Audu Gyang", role: "Supporter", quotes: ["I come to Lafiya City Stadium for the football.", "Sit high up and you see the whole game."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yakubu Musa", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Esther Ibrahim", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Laraba Ishaku", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Audu Dung", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yakubu Bako", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Esther Yohanna", role: "Patient's relative", quotes: ["I am waiting with a relative at Voice of Islam Hospital.", "Everyone here is patient, so I must be too."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Laraba Bulus", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Audu Gambo", role: "Patient's relative", quotes: ["I am waiting with a relative at Sauki Hospital, Lafia.", "Everyone here is patient, so I must be too."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yakubu Gyang", role: "Student", quotes: ["I am on my way to a lecture at Federal University of Lafia.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Esther Audu", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Laraba Ibrahim", role: "Student", quotes: ["I am on my way to a lecture at Nasarawa state poly, Lafia.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Audu Tanko", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yakubu Dung", role: "Church volunteer", quotes: ["Welcome to Evangelical Reformed Church of Christ (ERCC), GraceLand. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Esther Jatau", role: "Regular worshipper", quotes: ["I have worshipped at Evangelical Reformed Church of Christ (ERCC), GraceLand for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Laraba Yohanna", role: "Church volunteer", quotes: ["Welcome to Saint Williams Cathedral, Lafia. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Audu Danjuma", role: "Regular worshipper", quotes: ["I have worshipped at Saint Williams Cathedral, Lafia for a long time.", "Sit anywhere there is room, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yakubu Gambo", role: "Site guide", quotes: ["Welcome to John Castle. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Esther Pam", role: "Local resident", quotes: ["I walk past John Castle most days.", "Visitors often stop here for photographs."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Laraba Audu", role: "Market trader", quotes: ["Looking for Sesame and soybean collecting point and Yams, sorghum and millet? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Audu Garba", role: "Shopper", quotes: ["Wikipedia calls modern Lafia a collecting point for sesame seeds and soybeans.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yakubu Tanko", role: "Market trader", quotes: ["Looking for Yams, sorghum and millet? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Esther Adamu", role: "Shopper", quotes: ["Wikipedia calls modern Lafia a trading centre for yams, sorghum, millet and cotton.", "Take your time, and bargain with a smile."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
