// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":565,"z":560})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-394.58396328635695,"maxX":613.9407316840447,"minZ":-590.1270838433938,"maxZ":110.35755479085026})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"lafia":{"lon":8.71571963084386,"lat":8.635395849944246}})
