// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaScenes } from '../formula/scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_SCENES = buildFormulaScenes(CITY_SPEC)
