// Generated by scripts/world/build-playable-africa.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "abidjan",
  "name": "Abidjan",
  "country": {
    "idISOlower": "ci",
    "name": "Côte d’Ivoire"
  },
  "state": {
    "idunique": "ci-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Abidjan",
  "centre": {
    "lon": -4.020207,
    "lat": 5.323126
  },
  "airport": {
    "id": "abidjan-airport",
    "name": "AEROPORT INTERNATIONAL FELIX HOUPHOUET BOIGNY D'ABIDJAN",
    "lon": -3.928655556,
    "lat": 5.254502778,
    "sourceUrl": "https://aim.asecna.aero/html/eAIP/FR-_06AD-2.DIAP-fr-FR.html"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and cited aeronautical information sources",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-4.023207,5.320126,-4.017207,5.326126",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; Airport reference points: cited aeronautical information sources",
  "bounds": [
    -4.035207,
    5.242503,
    -3.916656,
    5.338126
  ],
  "coverageNote": "commercial city; Yamoussoukro is the political capital. Starter visitor area. Real city and airport points, clipped country land and a bounded central street/building sample. Visitor services and homes are fictional game content. Buildings use approximate box silhouettes; missing heights are estimates. Game prices remain in the shared Allworld economy."
} satisfies DestinationFacts
