// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":371,"z":4470})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-126.71395056608125,"maxX":69.89813324785092,"minZ":-76.94179809529942,"maxZ":150.94340084674786})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"calabar-municipal":{"lon":8.336016994134397,"lat":5.005114009783732},"calabar-south":{"lon":8.329049699396515,"lat":4.925970953246747}})
