// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Yetunde Lawal", role: "Garden keeper", quotes: ["I keep Asha Botanical Garden tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Kola Ojo", role: "Evening walker", quotes: ["I come to Asha Botanical Garden after work to cool down.", "Fresh air first, then the day."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Olumide Afolabi", role: "Church volunteer", quotes: ["Welcome to St Patrick Catholic Church Cathedral. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Omolara", role: "Regular worshipper", quotes: ["I have worshipped at St Patrick Catholic Church Cathedral for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yetunde Ogundele", role: "Mosque caretaker", quotes: ["Welcome to Ansarudeen Mosque. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Kola Akinwale", role: "Regular worshipper", quotes: ["I have prayed at Ansarudeen Mosque for a long time.", "Come in quietly, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Olumide Adeleke", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Omolara Olaniyan", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yetunde Akinola", role: "Market trader", quotes: ["Looking for Yam, cassava and grain? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Baba Kola", role: "Shopper", quotes: ["Wikipedia calls Ado-Ekiti a trade centre for farm produce where yams, cassava, grain and tobacco are grown.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Olumide Ojo", role: "Stylist", quotes: ["Sit down, I will not keep you long.", "A fresh style changes your whole week."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Omolara Ogunbanjo", role: "Client", quotes: ["I come to Diamond Barbing Saloon before big days.", "Sit still and it goes faster."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yetunde Ajayi", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Kola Adesina", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Olumide Akinwale", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Iyabo", role: "Patient's relative", quotes: ["I am waiting with a relative at Afe Babalola University Teaching Hospital.", "Everyone here is patient, so I must be too."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yetunde Olaniyan", role: "Student", quotes: ["I am on my way to a workshop at Federal Polytechnic, Ado-Ekiti.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Kola Oladipo", role: "Instructor", quotes: ["I teach practical work here.", "Hands first, then the theory."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Olumide Salami", role: "Student", quotes: ["I am on my way to a lecture at Afe Babalola University.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Omolara Adeyemi", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yetunde Ogunbanjo", role: "Student", quotes: ["I am on my way to a lecture at Ekiti State University.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Baba Tayo", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Olumide Adesina", role: "Site attendant", quotes: ["Welcome to Ekiti State House of Assembly. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Omolara Lawal", role: "Local resident", quotes: ["I walk past Ekiti State House of Assembly most days.", "Visitors often stop here for photographs."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Yetunde Balogun", role: "Site attendant", quotes: ["Welcome to Ekiti State Library Board. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Kola Afolabi", role: "Local resident", quotes: ["I walk past Ekiti State Library Board most days.", "Visitors often stop here for photographs."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
