// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-3050,"z":1531})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-137.4002940951973,"maxX":238.26575778694223,"minZ":-188.3552109959253,"maxZ":92.23156339328557})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"ado-ekiti":{"lon":5.248794071605711,"lat":7.615925138993501},"irepodun-ifelodun":{"lon":5.240670098210348,"lat":7.708140074950932}})
