// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "port-louis",
  "name": "Port Louis",
  "country": {
    "idISOlower": "mu",
    "name": "Mauritius"
  },
  "state": {
    "idunique": "mu-starter",
    "name": "Starter zone"
  },
  "timezone": "Indian/Mauritius",
  "centre": {
    "lon": 57.499994,
    "lat": -20.166639
  },
  "airport": {
    "id": "port-louis-airport",
    "name": "Sir Seewoosagur Ramgoolam International Airport",
    "lon": 57.683601,
    "lat": -20.430201,
    "sourceUrl": "https://ourairports.com/airports/FIMP/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=57.496994,-20.169639,57.502994,-20.163639",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    57.484994,
    -20.442201,
    57.695601,
    -20.151639
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
