// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "ouagadougou",
  "name": "Ouagadougou",
  "country": {
    "idISOlower": "bf",
    "name": "Burkina Faso"
  },
  "state": {
    "idunique": "bf-zone",
    "name": "Starter"
  },
  "timezone": "Africa/Ouagadougou",
  "centre": {
    "lon": -1.52667,
    "lat": 12.372262
  },
  "airport": {
    "id": "ouagadougou-airport",
    "name": "Ouagadougou Thomas Sankara International Airport",
    "lon": -1.51242,
    "lat": 12.3532,
    "sourceUrl": "https://ourairports.com/airports/DFFD/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-1.52967,12.369262,-1.52367,12.375262",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -1.54167,
    12.3412,
    -1.50042,
    12.387262
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
