// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "libreville",
  "name": "Libreville",
  "country": {
    "idISOlower": "ga",
    "name": "Gabon"
  },
  "state": {
    "idunique": "ga-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Libreville",
  "centre": {
    "lon": 9.457965,
    "lat": 0.385389
  },
  "airport": {
    "id": "libreville-airport",
    "name": "Libreville Leon M'ba International Airport",
    "lon": 9.41214,
    "lat": 0.458951,
    "sourceUrl": "https://ourairports.com/airports/FOOL/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=9.454965,0.382389,9.460965,0.388389",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    9.40014,
    0.370389,
    9.472965,
    0.470951
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
