// Generated by scripts/world/build-playable-africa.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "yaounde",
  "name": "Yaoundé",
  "country": {
    "idISOlower": "cm",
    "name": "Cameroon"
  },
  "state": {
    "idunique": "cm-starter",
    "name": "Starter district"
  },
  "timezone": "Africa/Douala",
  "centre": {
    "lon": 11.514705,
    "lat": 3.868647
  },
  "airport": {
    "id": "yaounde-airport",
    "name": "Yaoundé / Nsimalen",
    "lon": 11.553356528,
    "lat": 3.722563583,
    "sourceUrl": "https://aim.asecna.aero/html/eAIP/FR-_03AD-2.FKYS-fr-FR.html"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and national aeronautical information sources",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=11.511705,3.865647,11.517705,3.871647",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; Airport reference points: national aeronautical information sources",
  "bounds": [
    11.499705,
    3.710564,
    11.565357,
    3.883647
  ],
  "coverageNote": "Starter visitor area. Real capital and airport points, clipped country land and a bounded central street/building sample. Visitor services and homes are fictional game content. Buildings use approximate box silhouettes; missing heights are estimates. Game prices remain in the shared Allworld economy."
} satisfies DestinationFacts
