// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "freetown",
  "name": "Freetown",
  "country": {
    "idISOlower": "sl",
    "name": "Sierra Leone"
  },
  "state": {
    "idunique": "sl-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Freetown",
  "centre": {
    "lon": -13.236162,
    "lat": 8.471957
  },
  "airport": {
    "id": "freetown-airport",
    "name": "Lungi International Airport",
    "lon": -13.1955,
    "lat": 8.61644,
    "sourceUrl": "https://ourairports.com/airports/GFLL/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-13.239162,8.468957,-13.233162,8.474957",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -13.251162,
    8.456957,
    -13.1835,
    8.62844
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
