// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-2612,"z":2966})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-196.49623977028386,"maxX":226.0789488809287,"minZ":-90.66657677947887,"maxZ":386.12958763089273})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"oredo":{"lon":5.5524883152578814,"lat":6.225301485897849},"egor":{"lon":5.581887312495626,"lat":6.3566494117665835},"ikpoba-okha":{"lon":5.654908811220684,"lat":6.1733566272192215}})
