import { defineCitySpec } from '../spec.ts'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'benin-city',
  name: 'Benin City',
  state: { id: 'edo', name: 'Edo', sourceName: 'Edo', unit: 'local government', sourceIds: ['geography'] },
  country: { id: 'nigeria', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 5.6221058,
    lat: 6.3330586,
    teaser: 'Markets, bronze casting and royal heritage at the centre of Edo State.',
    preview: ['Visit Igun Street and the Benin Moat.', 'Cross the city through Oredo, Egor and Ikpoba-Okha.'],
    coordinateSourceId: 'osm-selected',
    coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2149000430 },
  },
  population: { tier: 'major-city', sourceIds: ['climate-population'], note: 'The cited study reports 1.63 million residents in 2018.' },
  localUnits: [
    { id: 'oredo', name: 'Oredo', sourceName: 'Oredo', populationTier: 'city', description: 'The selected central local government contains the airport, Ring Road venues and Igun Street.', sourceIds: ['geography'] },
    { id: 'egor', name: 'Egor', sourceName: 'Egor', populationTier: 'city', description: 'The selected north-western local government contains the sourced church, polling venue and moat point.', sourceIds: ['geography'] },
    { id: 'ikpoba-okha', name: 'Ikpoba-Okha', sourceName: 'Ikpoba-Okha', populationTier: 'city', description: 'The selected eastern local government contains Ramat Park.', sourceIds: ['geography'] },
  ],
  places: [
    {
      id: 'benin-airport', name: 'Benin City Airport', kind: 'airport', lon: 5.599582, lat: 6.3171399, localUnitId: 'oredo',
      description: 'FAAN lists Benin City Airport with IATA code BNI and ICAO code DNBE.', sourceIds: ['osm-selected', 'faan-airport'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 455073363 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'edo-line', name: 'Edo Line', kind: 'road-hub', lon: 5.6282402, lat: 6.3435934, localUnitId: 'oredo',
      description: 'A mapped Edo Line bus station and public-transport station.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 981284618 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'ramat-park', name: 'Ramat Park', kind: 'park', lon: 5.6610878, lat: 6.3505987, localUnitId: 'ikpoba-okha',
      description: 'A mapped public park in Ikpoba-Okha.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 460743740 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'roadside', props: ['tree', 'bench'] },
    },
    {
      id: 'celebrate-garden', name: 'Celebrate Garden', kind: 'garden', lon: 5.6154907, lat: 6.3130294, localUnitId: 'oredo',
      description: 'A mapped garden in Oredo used for the city evening option.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2152958522 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'lamp'] },
    },
    {
      id: 'chicken-republic', name: 'Chicken Republic', kind: 'eatery', lon: 5.6127623, lat: 6.3233504, localUnitId: 'oredo',
      description: 'A mapped Chicken Republic fast-food restaurant; the chain press release documents Smokey Jollof nationwide.', sourceIds: ['osm-selected', 'chicken-republic-jollof'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2161042283 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'smokey-jollof',
    },
    {
      id: 'lily-hospital', name: 'Lily Hospital', kind: 'hospital', lon: 5.6100018, lat: 6.3182295, localUnitId: 'oredo',
      description: 'The selected mapped hospital is near Edo Osagie Street; Lily Hospitals lists a Benin branch at 16A Edo-Osagie Street, GRA.', sourceIds: ['osm-selected', 'lily-hospital'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 84169861 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'oredo-secretariat', name: 'Oredo LGA Secretariat', kind: 'government', lon: 5.6209239, lat: 6.3333173, localUnitId: 'oredo',
      description: 'The mapped public building for Oredo Local Government.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 84169152 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'eweka-primary-polling', name: 'Eweka Primary School', kind: 'polling', lon: 5.583084, lat: 6.3626358, localUnitId: 'egor',
      description: 'INEC names Eweka Primary School as a polling venue for Egor ward OGIDA/USE.', sourceIds: ['osm-selected', 'inec-eweka-polling'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2072662089 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'valkel-salon', name: 'Valkel Unisex Salon & Bar', kind: 'salon', lon: 5.6174435, lat: 6.3093215, localUnitId: 'oredo',
      description: 'A named hairdresser mapped on Ihama Road.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 6793997374 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] },
    },
    {
      id: 'zenith-bank', name: 'Zenith Bank', kind: 'savings', lon: 5.628789, lat: 6.3284183, localUnitId: 'oredo',
      description: 'A mapped Zenith Bank branch in Oredo.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2155738906 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'samuel-ogbemudia-stadium', name: 'Samuel Ogbemudia Stadium', kind: 'stadium', lon: 5.6108963, lat: 6.3319965, localUnitId: 'oredo',
      description: 'A mapped stadium in central Benin City.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 30109996 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'st-monicas-church', name: "St. Monica's Catholic Church", kind: 'church', lon: 5.5868344, lat: 6.3688832, localUnitId: 'egor',
      description: 'A named Catholic place of worship mapped in Egor.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 1995055872 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'central-mosque', name: 'Central Mosque', kind: 'mosque', lon: 5.6226695, lat: 6.3389307, localUnitId: 'oredo',
      description: 'A named Muslim place of worship mapped in Oredo.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2350849570 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'oba-market', name: 'Oba Market', kind: 'market', lon: 5.619749, lat: 6.3347661, localUnitId: 'oredo',
      description: 'Oredo LGA names Oba Market and documents textiles, foodstuffs and crafts in its markets.', sourceIds: ['osm-selected', 'oredo-economy'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 759470271 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['oba-market-textiles', 'oba-market-foodstuffs', 'oba-market-crafts'],
    },
    {
      id: 'baptist-college-theology', name: 'Baptist College Of Theology', kind: 'college', lon: 5.6115163, lat: 6.3488545, localUnitId: 'oredo',
      description: 'A theological college whose official site lists its campus at 5 TV Road, Benin City.', sourceIds: ['osm-selected', 'baptist-college'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 225786231 }, accuracy: 'feature-centroid',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'benin-city-national-museum', name: 'Benin City National Museum', kind: 'museum', lon: 5.6221507, lat: 6.3329164, localUnitId: 'oredo',
      description: 'The National Commission for Museums and Monuments lists National Museum Benin at Ring Road.', sourceIds: ['osm-selected', 'national-museum', 'edo-tourism'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'relation', id: 7326215 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'benin-moat', name: 'Benin Moat', kind: 'heritage', lon: 5.6351724, lat: 6.3669017, localUnitId: 'egor',
      description: 'A mapped monument point on the Great Benin Moat, which Edo State lists as a tourism destination.', sourceIds: ['osm-selected', 'edo-tourism'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 1995051953 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['tree', 'bench'], landmark: 'gate' },
    },
    {
      id: 'oba-palace', name: 'Oba Palace', kind: 'heritage', lon: 5.6200999, lat: 6.3319988, localUnitId: 'oredo',
      description: "Edo State's tourism page identifies the Palace of the Oba of Benin as the Oba's home.", sourceIds: ['osm-selected', 'edo-tourism'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2161071635 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'lamp'], landmark: 'gate' },
    },
    {
      id: 'igun-street', name: 'Igun Street', kind: 'craft-centre', lon: 5.6297054, lat: 6.336412, localUnitId: 'oredo',
      description: 'Edo State identifies Igun Street as a centre for art, craft makers and bronze casting.', sourceIds: ['osm-selected', 'edo-tourism', 'oredo-economy'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 41203715 }, accuracy: 'route-reference',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] },
    },
    {
      id: 'edo-state-sport-council', name: 'Edo State Sport Council', kind: 'sport', lon: 5.6194852, lat: 6.3460276, localUnitId: 'oredo',
      description: 'A mapped public sports centre in Oredo.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2350899857 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
  ],
  identity: {
    foods: [
      { id: 'smokey-jollof', name: 'Smokey Jollof', description: 'Chicken Republic announced its improved Smokey Jollof across restaurants nationwide.', localProductId: 'jollof', sourceIds: ['chicken-republic-jollof'] },
      { id: 'oba-market-foodstuffs', name: 'Oba Market foodstuffs', description: 'Oredo LGA records foodstuffs among the goods traded in its named markets.', sourceIds: ['oredo-economy'] },
    ],
    crafts: [
      { id: 'oba-market-textiles', name: 'Oba Market textiles', description: 'Oredo LGA records textiles among the goods traded in its named markets.', sourceIds: ['oredo-economy'] },
      { id: 'oba-market-crafts', name: 'Oba Market crafts', description: 'Oredo LGA records crafts among the goods traded in its named markets.', sourceIds: ['oredo-economy'] },
      { id: 'benin-bronze-casting', name: 'Benin bronze casting', description: 'Edo State identifies Igun Street with bronze casting and craft makers.', sourceIds: ['edo-tourism', 'oredo-economy'] },
    ],
    industries: [
      { id: 'oredo-commerce', name: 'Oredo commerce', description: 'Oredo LGA describes Benin City as a commercial hub.', sourceIds: ['oredo-economy'] },
    ],
  },
  transport: {
    airports: [{ placeId: 'benin-airport', status: 'operational', sourceIds: ['faan-airport'] }],
    rail: [],
    ports: [],
  },
  climate: {
    profile: 'southern-wet-dry', rainyMonths: [3, 4, 5, 6, 7, 8, 9, 10], dryMonths: [11, 12, 1, 2],
    description: 'Benin City has a humid tropical climate, with rain from March to October and a dry season from November to February.',
    clearLabel: 'Dry-season sky', sourceIds: ['climate-population'],
  },
  homePalette: { back: '#c98b5b', left: '#8a5b3d', floor: ['#c9a46f', '#6f8454'] },
  geometry: { surface: { path: 'scripts/geo/sources/formula/benin-city-surface.geojson', bytes: 291711, sha256: 'ab163b78f1f11078b6e5b48ebe9d3e1950fafef73faeb20e5b7301dcfdb7b36b' } },
  sourceGroups: [
    { id: 'osm-selected', title: 'Selected OpenStreetMap records for Benin City', url: 'https://www.openstreetmap.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'ODbL 1.0', cache: { path: 'scripts/city/research/benin-city/reviewed/osm-selected.json', bytes: 3796, sha256: '5cf4c42fa3cc71edb71ea26ad337f92de9c92e6533df1bc21415706c933d8229' } },
    { id: 'geography', title: 'Pinned Nigerian administrative geography', url: 'https://www.geoboundaries.org/', checkedOn: '2026-10-06', supports: ['geography'], licence: 'CC BY 4.0', cache: { path: 'scripts/city/research/benin-city/reviewed/geography.json', bytes: 420, sha256: 'b35cfb0f751c28a478afcd656193b0f065826202aa5a80b34bbbea9c810b43ad' } },
    { id: 'climate-population', title: 'Peer-reviewed Benin City climate and population study', url: 'https://link.springer.com/article/10.1007/s43621-024-00508-8', checkedOn: '2026-10-06', supports: ['climate', 'population'], cache: { path: 'scripts/city/research/benin-city/reviewed/climate-population.json', bytes: 468, sha256: '81aee4e4a4931dd1aed7a2c620a0f86473b47e34b552644f2b443d7e9ccaff04' } },
    { id: 'faan-airport', title: 'FAAN Benin Airport', url: 'https://faan.gov.ng/benin-airport-2/', checkedOn: '2026-10-06', supports: ['identity', 'transport'], cache: { path: 'scripts/city/research/benin-city/reviewed/faan-airport.json', bytes: 338, sha256: '582036408d08f42ec52025395c13d9bfbc2a1405554571105f6f42e98e503cdc' } },
    { id: 'lily-hospital', title: 'Lily Hospitals locations', url: 'https://lilyhospitals.com/our-locations/', checkedOn: '2026-10-06', supports: ['identity'], cache: { path: 'scripts/city/research/benin-city/reviewed/lily-hospital.json', bytes: 437, sha256: 'e0f505ab73ab4895f87f409fc2067f4720770a38ec3f15a4b9c1ef65927a05d2' } },
    { id: 'baptist-college', title: 'Baptist College of Theology Benin City', url: 'https://www.bctbenin.edu.ng/index.asp', checkedOn: '2026-10-06', supports: ['identity'], cache: { path: 'scripts/city/research/benin-city/reviewed/baptist-college.json', bytes: 332, sha256: '6f4f78d871832da0641a90ecad564f5d7adc38eb3a893f1bdf994581f51a6b40' } },
    { id: 'inec-eweka-polling', title: 'INEC Edo polling-centre list', url: 'https://inecnigeria.org/wp-content/uploads/2024/05/LIST-OF-CVR-REGISTRATION-CENTRES-EDO-ONDO-STATE.pdf', checkedOn: '2026-10-06', supports: ['identity'], cache: { path: 'scripts/city/research/benin-city/reviewed/inec-eweka-polling.json', bytes: 538, sha256: 'a98fe0403ab5f91962641514e8232a89a06fa7d0c465594cd169c19165f5c4d9' } },
    { id: 'edo-tourism', title: 'Edo tourism destinations', url: 'https://edostate.gov.ng/visit-edo-state-to-enjoy-her-unique-hospitality-and-tourism-signature/', checkedOn: '2026-10-06', supports: ['identity'], cache: { path: 'scripts/city/research/benin-city/reviewed/edo-tourism.json', bytes: 525, sha256: 'e85e54d091cde61c0ad7e2518435f395d926285b070ed5498b6e52a5a8d53d8a' } },
    { id: 'national-museum', title: 'National Commission for Museums and Monuments museum list', url: 'https://museum.ng/museums/national-museums/', checkedOn: '2026-10-06', supports: ['identity'], cache: { path: 'scripts/city/research/benin-city/reviewed/national-museum.json', bytes: 251, sha256: 'daa23b77ec98442bbb7b1dd77f601ead02f2c3aa1a4a190d49583d418a2736b6' } },
    { id: 'oredo-economy', title: 'Oredo Local Government economy', url: 'https://www.oredolga.ed.gov.ng/economy.php', checkedOn: '2026-10-06', supports: ['identity'], cache: { path: 'scripts/city/research/benin-city/reviewed/oredo-economy.json', bytes: 454, sha256: 'bf34d2b00ed998ccb34932df331f76c04d8b058f9b8a8ce45069ad3e1849c7e7' } },
    { id: 'chicken-republic-jollof', title: 'Chicken Republic Smokey Jollof press release', url: 'https://www.thecable.ng/chicken-republic-unveils-improved-smokey-jollof/', checkedOn: '2026-10-06', supports: ['identity'], cache: { path: 'scripts/city/research/benin-city/reviewed/chicken-republic-jollof.json', bytes: 435, sha256: '8cdd3022d0adfad7679d483d6162d285de8ec54ab6defcac5c695d013b9e06c2' } },
  ],
})
