// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Ifeoma Mbah", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ugochukwu Chukwu", role: "Supporter", quotes: ["I come to Stephen Keshi Stadium for the football.", "Sit high up and you see the whole game."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Nnamdi Eze", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Ebere", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifeoma Nnadi", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ugochukwu Agu", role: "Patient's relative", quotes: ["I am waiting with a relative at Government Hospital Ibusa.", "Everyone here is patient, so I must be too."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Nnamdi Okafor", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ebere Okeke", role: "Patient's relative", quotes: ["I am waiting with a relative at Federal Medical Centre Asaba.", "Everyone here is patient, so I must be too."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifeoma Anyanwu", role: "Student", quotes: ["I am on my way to a lecture at Federal College of Education (Technical), Asaba.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mazi Ugochukwu", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Nnamdi Chukwu", role: "Museum guide", quotes: ["Welcome to National Museum Asaba. Please take your time.", "Ask me if you want to know what is on display."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ebere Nwosu", role: "Visitor", quotes: ["I came to National Museum Asaba to learn something new.", "Read the labels slowly. They reward you."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifeoma Nwachukwu", role: "Church volunteer", quotes: ["Welcome to Holly Family Catholic Church. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ugochukwu Ugwu", role: "Regular worshipper", quotes: ["I have worshipped at Holly Family Catholic Church for a long time.", "Sit anywhere there is room, and be welcome."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Nnamdi Agu", role: "Market trader", quotes: ["Looking for Yams, spices and smoked fish? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Ogechi", role: "Shopper", quotes: ["Discover Delta says Ogbe-Ogonogo Market sells yams, spices, smoked fish and fabric.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifeoma Okeke", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ugochukwu Okonkwo", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Nnamdi Ibe", role: "Cook", quotes: ["Today the pot at Pokaribs Native Kitchen & Lounge holds Banga Soup.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ebere Onwuka", role: "Regular diner", quotes: ["I come to Pokaribs Native Kitchen & Lounge for Banga Soup.", "The NICO Delta State cuisine list names Banga Soup first among Delta dishes."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ifeoma Nwosu", role: "Check-in agent", quotes: ["Please have your ticket and your ID ready.", "Boarding closes earlier than people think."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mazi Tobenna", role: "Traveller", quotes: ["I am flying out from Asaba International Airport today.", "Travelling is half waiting."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Nnamdi Ugwu", role: "Musician", quotes: ["We play at 1st Empire when the evening comes.", "Stay for the second set."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ebere Mbah", role: "Regular listener", quotes: ["I come to 1st Empire for the music.", "The best seats go early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
