// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-1395,"z":3129})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-181.54256703123656,"maxX":43.48240339414042,"minZ":-350.4952526468387,"maxZ":214.44035928112362})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"oshimili-north":{"lon":6.64310125599664,"lat":6.312327410809746},"oshimili-south":{"lon":6.694866468832527,"lat":6.108226024419377}})
