// The daily answers, hand-written as everyday five-letter words an average adult knows (see
// docs/WORDS.md). The generator keeps only those that are also accepted guesses and clear the
// blocklists; anything it drops is reported when it runs. Order here does not matter.
const WORDS = `
about above abuse actor acute adapt admit adopt adult after again agent agree ahead alarm album alert alike alive allow alone along alter among ample angel anger angle ankle apart apple apply apron arena argue arise armor arrow aside asset atlas attic audio avoid awake award aware awful
bacon badge baker balls bands banjo basic basin basis batch beach beard beast began begin being belly below bench berry bible bikes birth black blade blame blank blast blaze bleak blend bless blind blink block bloom blown blues blunt board boast boats bonus boost booth bound brain brake brand brave bread break breed brick bride brief bring broad broke brook broom brown brush bunch burst buyer
cabin cable cadet camel candy canoe carry carve catch cause cease chain chair chalk champ charm chart chase cheap check cheek cheer chess chest chief child chill china chips choir chord chose civic civil claim clash class clean clear clerk click cliff climb cling clock close cloth cloud clown coach coast coral couch cough count court cover crack craft crane crash crawl crazy cream creek creep crest crisp cross crowd crown crumb crush crust cubic curry curve cycle
daily dairy daisy dance dated dealt dears debut decay delay delta dense depot depth derby desks diary digit diner dirty ditch dizzy dodge doing donor doubt dough dozen draft drain drama drank drawn dream dress dried drift drill drink drive drops drove drums dryer dusty dwarf dwell
eager eagle early earth easel eaten edges eight elbow elder elect elite empty enemy enjoy enter entry equal error essay event every exact exams exist extra
fable faint fairy faith false fancy fares farms fatal fault feast fence ferry fever fewer fiber field fifth fifty fight final finds first fixed flags flame flash flask fleet flesh flies float flock flood floor flour fluid flute focus force forge forms forth forty forum found frame frank fresh fried front frost fruit fully funny
games gauge ghost giant gifts given glass glide globe gloom glory glove going grace grade grain grand grant grape graph grasp grass great greed green greet grill grind groan group grove grown guard guess guest guide guilt
habit handy happy hardy harsh haste hasty hatch haven heads heard heart heavy hedge hello hence herbs hills hinge hobby holds holes holly homes honey honor hoped horse hotel hours house human humor hurry
ideal image imply index inner input irony issue ivory
jeans jelly jewel joint joker jolly judge juice jumbo jumps
karma kayak keeps kicks kinds kings kiosk kites kitty knack knees knelt knife knock knots known
label labor lace lacks ladle lakes lamps lance lands lanes large laser later laugh lawns layer leads leaps learn lease least leave ledge legal lemon level lever light liked likes limit lined linen lines links lions lists liter lives liver llama loads loans lobby local lodge lofty logic loose lorry lover lower loyal lucky lunar lunch lungs lying
magic major maker males mango maple march marks marry masks match maybe mayor meals means meant media melon mercy merge merit merry metal meter midst might mills mince minds miner minor mints minus mirror mixed model moist money month moral motor motto mount mouse mouth moved movie music
naive named names nanny nasal naval needs nerve never newly niece night noble nodes noise north notch noted notes novel nurse nutty
oasis occur ocean offer often olive onion opens opera orbit order organ other otter ought ounce outer owner oxide
paced packs pages pains paint pairs palms panda panel panic pants paper parks party pasta paste patch pause peace peach pearl pedal penny perch peril petal phase phone photo piano picks piece pilot pinch pines pitch pizza place plain plane plank plant plate plays plaza plead pliers plots pluck plumb plume plump plums point poise polar poles polls ponds pools porch ports posed pound pours power prawn press price pride prime print prior prize probe prone proof proud prove pulse punch pupil puppy purse
quack quake queen query quest queue quick quiet quilt quirk quite quota quote
rabbi radar radio raise rally ranch range rapid ratio reach react ready realm rebel refer reign relax relay renew reply rider ridge rifle right rigid ring rings risen risky rival river roads roast robes robin robot rocks rocky roles rolls roman rooms roots ropes roses rough round route royal rugby ruins ruler rules rural
sadly safer sails saint salad sales salon sands sandy sauce saved scale scarf scene scent scone scope score scout screw scrub seals seats seeds seems sells sense serve setup seven shade shake shall shame shape share shark sharp sheep sheet shelf shell shift shine shiny ships shirt shock shoes shone shook shoot shops shore short shout shown shows sides siege sight signs silky silly since sings sixth sixty sized skate skill skirt skull slate sleep slice slide slope small smart smell smile smoke snack snail snake sneak snowy soapy social sofas solar solid solve songs sorry sorts souls sound soups south space spare spark speak speed spell spend spent spice spicy spike spine spoke spoon sport spots spray squad stack staff stage stain stair stake stale stalk stamp stand stare stars start state stays steak steal steam steel steep steer stems steps stick stiff still sting stock stone stood stool stops store storm story stove strap straw strip stuck study stuff style sugar suite sunny super surge swamp swans swear sweat sweep sweet swept swift swing swiss sword
table tacos tails taken takes tales talks tally tamer tanks tapes tasks taste taxes teach teams tears teeth tells tempo tends tenor tense tenth tents terms tests texts thank theft their theme there these thick thief thigh thing think third thorn those three threw throw thumb tidal tides tiger tight tiles timer times tired title toast today token tomato tonic tools tooth topic torch total touch tough tours towel tower towns toxic trace track trade trail train trait trash treat trees trend trial tribe trick tried tries trips troop trout truck truly trump trunk trust truth tubes tulip tumor tuned tunes turns twice twins twist tying
ultra uncle under undue union unite units unity until upper upset urban usage users usual utter
valid value valve vases vault venue verse video views villa vines viola viral virus visit vital vivid vocal vodka voice voter vowel
wages wagon waist walks walls waltz wants warms waste watch water waves weary weave wedge weeds weeks weigh weird wells whale wheat wheel where which while whips white whole whose wider widow width wield wings wiped wired wires witch woman women woods words works world worms worry worth would wound woven wrist write wrote
yacht yards yeast yield young yours youth
zebra zesty
abbey acorn adore agile aisle algae alley amaze amber amuse angry annex anvil aroma arrive ashes atom audit aunts avian axiom
bagel baggy baked balmy bamboo banks barge barns baron basil batty bayou beads beans beers beets belts bends beret bikini birds bison blimp bliss bloke blond bluff blush boxer brace braid brass bravo brawn brine brink brisk broth bulbs bulky bully bumpy bunny burnt bushy butter buzzy
cacao cakes calms campy canal cargo carol carts cases cedar cello chaos chant chefs cheat chewy chick chime chirp choke chore chunk cider cigar cinch cited clamp clang clank clasp claws clays clerk cliff clips cloak clone clots clubs clues clump coats cocoa codes coins colon color comet comic comma conch cones cooks cools cords corns costs cotton cough cozy crabs cramp crates crave crazy creak credo creed crepe crimp croak crook crops cruel cruise crumb cuddle cumin curls curly cuter cyber
dairy dandy dated dates dazed deals dealt decor decoy deeds deity denim dents derby desks deter detox devil dials diets digit dimly dingo dining disco ditto divan diver dives dizzy docks dolls domes donut doors dorks dosed doses dotty dowdy downs dowry drape drawl drawn dread dregs dried drier dries drips droll drone drool droop drops dross drunk ducks duets dully dummy dumps dunes duvet dwelt dying
earns ebony edict eerie eight elfin elude email ember emcee emits ended ender endow enjoy ensue envoy epoch equip erase erect erode error erupt ethic evade evoke exalt exert exile expel extol
fades fails fairs falls famed fangs farce fetch fiery fifth filed files fills films filmy filth finch fines fires firms fishy fists flair flake flank flare flaws fleas flick fling flint flips flirt flora flows fluff flung flunk flush foals foams foamy foggy foils folds folks fonts foods fools foots foray forks forms fouls foxes foyer frail frame fraud freak freed freer fresh friar fried frill frisk frogs frown froze fuels fugue fumes funds fungi funky furry fused fuzzy
gains gamer gamma gassy gaudy gavel gears geese genes genie genre ghoul gipsy girls girth given gizmo glade gland glare glaze gleam glean glens glint glitz gloat globs gloss glows glued glued gnash gnome goals goats godly goers golds golfs goody goose gouge gourd grail grams grave gravy graze greasy greys grids grief grime grimy grins gripe grips groom grope gross grout grows gruel gruff grunt guava guide guilt guise gulch gulls gummy guppy gusts gusty gypsum
`
const REVIEW_REMOVE = new Set(`dirty dumps dregs dross fouls gnash gouge weary worry wound sorry shame upset trash tears knife sword blind swear swiss greys dears goers golds golfs godly ender freer cuter tamer
  dries emits dazed gassy batty buzzy dowdy dowry elfin extol exalt emcee ditto divan doses tying hoped sized wiped caper dated posed deeds dolls yours stars hence`.split(/\s+/))
const REVIEW_ADD = `igloo inbox jumpy kebab koala lilac lotus magma mocha nacho pixel plush quail raven relic rhyme saber scoop shawl sloth snore sonic spade squid swirl tabby tango teddy thump unzip
  vigor vinyl yummy beige bingo gecko hippo lemur parka boots acres amigo bleep bolts bored boxes carat chili cluck cobra comfy corgi craze cynic dimes ditch dwarf elves fjord flora frame fries
  grill hairy hippo jazzy joust juicy kneel lapse latch lemon lilac manor mimic mirth moose nudge oddly olden panel perky piety plaid poems poker pouch prank prism pylon quirk radii rainy raspy reeds
  ripen rouge ruddy salsa satin savvy scrap shrub shrug siren skiff slang sleek slump smirk snuck sooty sparse spawn spurt stern stump sulky swarm tacky taper thumb tithe trove tweed twirl udder umbra
  unfit usher vapor vegan verge vigil vogue wacky waver whisk wimpy wreak yearn yodel zonal`
export const ANSWER_WORDS: readonly string[] = [...new Set((WORDS + ' ' + REVIEW_ADD).split(/\s+/).filter(Boolean))].filter(w => !REVIEW_REMOVE.has(w))

/** Everyday words the source lacks (irregular forms, modern words); accepted as guesses and in the tile dictionary. The Nigerian words below are never answers. */
export const EXTRA_WORDS: readonly string[] = [
  'began', 'begun', 'heard', 'women', 'pasta', 'tacos', 'email', 'sushi', 'pizza', 'proud', 'wider', 'dated', 'posed', 'sadly', 'ought', 'brunch', 'rugby', 'dryer', 'laser', 'curry',
  'wrote', 'written', 'drove', 'driven', 'spoke', 'spoken', 'broke', 'broken', 'chose', 'chosen', 'swam', 'swum', 'sang', 'sung', 'rang', 'rung', 'sank', 'sunk',
  'eaten', 'flew', 'flown', 'knew', 'threw', 'thrown', 'drew', 'taken', 'gave', 'given', 'went', 'gone', 'built', 'kept', 'felt', 'sent', 'spent', 'held', 'taught',
  'donut', 'disco', 'decor', 'inbox', 'nacho', 'pixel', 'teddy', 'unzip', 'amigo', 'bleep', 'boxes', 'fjord', 'salsa', 'vegan', 'gizmo', 'glitz', 'cyber', 'detox', 'famed', 'cited', 'blond', 'credo',
  'caught', 'bought', 'thought', 'fought', 'sought', 'brought',
  // Nigerian food, transport and culture words, accepted as guesses only.
  'akara', 'amala', 'egusi', 'garri', 'danfo', 'okada', 'naija', 'ewedu', 'ofada', 'iroko', 'abula',
]
