// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "cairo",
  "name": "Cairo",
  "country": {
    "idISOlower": "eg",
    "name": "Egypt"
  },
  "state": {
    "idunique": "eg-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Cairo",
  "centre": {
    "lon": 31.248022,
    "lat": 30.051906
  },
  "airport": {
    "id": "cairo-airport",
    "name": "Cairo International Airport",
    "lon": 31.396694,
    "lat": 30.111534,
    "sourceUrl": "https://ourairports.com/airports/HECA/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=31.245022,30.048906,31.251022,30.054906",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    31.233022,
    30.036906,
    31.408694,
    30.123534
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
