// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "cairo",
  "name": "Cairo",
  "country": {
    "idISOlower": "eg",
    "name": "Egypt"
  },
  "state": {
    "idunique": "eg-starter",
    "name": "Greater Cairo"
  },
  "timezone": "Africa/Cairo",
  "centre": {
    "lon": 31.248022,
    "lat": 30.051906
  },
  "airport": {
    "id": "cairo-airport",
    "name": "Cairo International Airport",
    "lon": 31.396694,
    "lat": 30.111534,
    "sourceUrl": "https://ourairports.com/airports/HECA/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://www.openstreetmap.org/copyright",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    31.08,
    29.93,
    31.42,
    30.14
  ],
  "coverageNote": "Greater Cairo from the Giza plateau to the airport: a sketch of the built-up extent traced from mapped land use (not an administrative boundary), the Nile, main roads and named places mapped in OpenStreetMap. The airport coordinates are an OurAirports dataset point, not an official reference point or evidence of current operations or schedules. Visitor services and homes are fictional game content set at the real named places.",
  "names": {
    "area": "Greater Cairo",
    "unit": "district",
    "roadHub": "Ramses Station"
  }
} satisfies DestinationFacts
