// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Hannatu Pam", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Istifanus Audu", role: "Supporter", quotes: ["I come to Jolly Nyame Stadium for the football.", "Sit high up and you see the whole game."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Daniel Garba", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryamu Tanko", role: "Patient's relative", quotes: ["I am waiting with a relative at Specialist Hospital Jalingo.", "Everyone here is patient, so I must be too."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hannatu Adamu", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Istifanus Jatau", role: "Patient's relative", quotes: ["I am waiting with a relative at FEDERAL MEDICAL CENTRE JALINGO.", "Everyone here is patient, so I must be too."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Daniel Musa", role: "Church volunteer", quotes: ["Welcome to Our Lady Queen Of Peace Catholic Cathedral. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryamu Danjuma", role: "Regular worshipper", quotes: ["I have worshipped at Our Lady Queen Of Peace Catholic Cathedral for a long time.", "Sit anywhere there is room, and be welcome."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hannatu Ishaku", role: "Church volunteer", quotes: ["Welcome to St. Peter`s Catholic Church. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Istifanus Pam", role: "Regular worshipper", quotes: ["I have worshipped at St. Peter`s Catholic Church for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Daniel Bako", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryamu Garba", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hannatu Bulus", role: "Mosque caretaker", quotes: ["Welcome to Government House Mosque Jalingo. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Istifanus Adamu", role: "Regular worshipper", quotes: ["I have prayed at Government House Mosque Jalingo for a long time.", "Come in quietly, and be welcome."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Daniel Gyang", role: "Mosque caretaker", quotes: ["Welcome to Central Mosque Sabo Gari Jalingo. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryamu Musa", role: "Regular worshipper", quotes: ["I have prayed at Central Mosque Sabo Gari Jalingo for a long time.", "Come in quietly, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hannatu Ibrahim", role: "Mosque caretaker", quotes: ["Welcome to Nana Aishat Central Mosque Jalingo. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Istifanus Ishaku", role: "Regular worshipper", quotes: ["I have prayed at Nana Aishat Central Mosque Jalingo for a long time.", "Come in quietly, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Daniel Dung", role: "Market trader", quotes: ["Looking for Taraba farming? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryamu Bako", role: "Shopper", quotes: ["Wikipedia says agriculture is the major occupation in Taraba, with cash crops including coffee, tea, groundnuts and cotton.", "Take your time, and bargain with a smile."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hannatu Yohanna", role: "Market trader", quotes: ["Looking for Taraba farming? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Istifanus Bulus", role: "Shopper", quotes: ["Wikipedia says agriculture is the major occupation in Taraba, with cash crops including coffee, tea, groundnuts and cotton.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Daniel Gambo", role: "Student", quotes: ["I am on my way to a lecture at College of Education, Jalingo.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryamu Gyang", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hannatu Audu", role: "Site guide", quotes: ["Welcome to Rafin Sanyi Rock. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Istifanus Ibrahim", role: "Local resident", quotes: ["I walk past Rafin Sanyi Rock most days.", "Visitors often stop here for photographs."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
