// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":3697,"z":111})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-166.3661753186916,"maxX":126.60171371063552,"minZ":-173.72681268593874,"maxZ":101.22314950099303})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"jalingo":{"lon":11.335075568183216,"lat":8.942576134069517}})
