// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "maputo",
  "name": "Maputo",
  "country": {
    "idISOlower": "mz",
    "name": "Mozambique"
  },
  "state": {
    "idunique": "mz-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Maputo",
  "centre": {
    "lon": 32.587217,
    "lat": -25.953332
  },
  "airport": {
    "id": "maputo-airport",
    "name": "Maputo Airport",
    "lon": 32.572601,
    "lat": -25.920799,
    "sourceUrl": "https://ourairports.com/airports/FQMA/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=32.584217,-25.956332,32.590217,-25.950332",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    32.560601,
    -25.968332,
    32.602217,
    -25.908799
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
