import { activity, buildOgunContent, hospitalSpots, OGUN_LOCAL_MODES, peopleFor, spot, work, type OgunVenueSeed } from '../ogun/contentBuilder.ts'
import { OTA_MAP_ORIGIN } from './rules.ts'
const centre={lon:3.2330105,lat:6.6845264},sango={lon:3.2428549,lat:6.7071679},covenant={lon:3.1573472,lat:6.6719407},bells={lon:3.1697985,lat:6.6865088}
const venues:readonly OgunVenueSeed[]=[
  {id:'ota-neighbourhood-park',name:'Ota Neighbourhood Park',district:'Ota Centre, Ado Odo/Ota',kind:'park',variant:'ayo-park',category:'fun',icon:'park',point:{lon:3.2358,lat:6.6882},description:'Meet neighbours, play ayo and take a short walk.',ambient:['The park fills up when the afternoon cools.'],spots:[spot('trees','Under the trees',activity('ota-play-ayo','Play a round of ayo','tables',['fun'],{duration:7})),work()],beta:true,note:'Fictional public park placed at the licensed Ado Odo/Ota footprint centroid.'},
  {id:'covenant-university',name:'Covenant University',district:'Canaanland, Ado Odo/Ota',kind:'office',variant:'campus-dome',category:'work',icon:'school',point:covenant,description:'Join a technology and enterprise workshop on the university campus.',ambient:['Students cross between lectures and project rooms.'],spots:[spot('lab','Enterprise lab',activity('ota-covenant-workshop','Join an enterprise workshop','code',['learn'],{xp:{coding:12}})),work()]},
  {id:'bells-university',name:'Bells University of Technology',district:'Ota, Ado Odo/Ota',kind:'office',variant:'campus-tech',category:'work',icon:'school',point:bells,description:'Visit the technology campus and work on a practical project.',ambient:['Workshop doors stay open through the afternoon.'],spots:[spot('lab','Technology lab',activity('ota-bells-project','Build a practical project','tools',['learn'],{xp:{coding:10}})),work()]},
  {id:'sango-market',name:'Sango-Ota Market',district:'Sango-Ota, Ado Odo/Ota',kind:'market',variant:'market-containers',category:'work',icon:'market',point:{lon:3.2441,lat:6.7088},description:'Price produce and household goods beside the border-city transport routes.',ambient:['Traders and commuters share the same busy streets.'],spots:[spot('aisle','Market aisle',activity('ota-market-price','Price the market','groceries',['market'],{xp:{hustle:8}})),work()],beta:true,note:'Gameplay market at the mapped Sango locality; no private market operator is claimed.'},
  {id:'sango-park',name:'Sango-Ota Motor Park',district:'Sango-Ota, Ado Odo/Ota',kind:'hub',variant:'park-trucks',category:'civic',icon:'bus',point:sango,description:'Catch a bus toward Lagos, Abeokuta or Sagamu.',ambient:['Conductors call out Lagos and Abeokuta routes.'],spots:[spot('platform','Bus platform',activity('ota-bus-wait','Wait for the bus','bus',['travel'],{duration:4}))],beta:true,note:'Gameplay motor park at the mapped Sango locality.'},
  {id:'ota-civic-hall',name:'Ota Civic Hall',district:'Ota Centre, Ado Odo/Ota',kind:'statehouse',variant:'hall-brick',category:'civic',icon:'governor',point:{lon:3.2371,lat:6.6916},description:'Read local notices and attend a community meeting.',ambient:['Residents check notices before the meeting begins.'],spots:[spot('hall','Meeting hall',activity('ota-civic-meeting','Attend a community meeting','people',['civic'],{effects:{social:6}})),work()],beta:true,note:'Fictional civic venue at the licensed LGA centroid.'},
  {id:'ota-polling',name:'Ota Civic Polling Centre',district:'Ota Centre, Ado Odo/Ota',kind:'polling',category:'civic',icon:'poll',point:{lon:3.2342,lat:6.6905},description:'Register, vote and follow the local count.',ambient:['Officials check the register.'],spots:[spot('officials','Election officials',activity('ota-voter-info','Read voter information','poll',['civic']))],beta:true,note:'Fictional election setup at the licensed LGA centroid.'},
  {id:'ota-community-clinic',name:'Ota Community Clinic',district:'Ota, Ado Odo/Ota',kind:'hospital',category:'care',icon:'health',point:{lon:3.2091,lat:6.68273},description:'Get a check-up or use the free clinic.',ambient:['The clinic team calls the next patient.'],spots:hospitalSpots(),beta:true,note:'Fictional gameplay clinic at the mapped Sango locality.'},
  {id:'canaanland-worship',name:'Canaanland Worship Centre',district:'Canaanland, Ado Odo/Ota',kind:'worship',category:'care',icon:'worship',point:{lon:3.167772,lat:6.6774328},description:'Visit the large public worship campus at Canaanland.',ambient:['Visitors move through the broad worship grounds.'],variant:'church',spots:[spot('hall','Worship hall',activity('ota-worship-reflect','Sit quietly in the worship hall','worship',['worship']))]},
  {id:'sango-mosque',name:'Sango Community Mosque',district:'Sango-Ota, Ado Odo/Ota',kind:'worship',category:'care',icon:'worship',point:{lon:3.2364,lat:6.7103},description:'Visit the community mosque around prayer time.',ambient:['People arrive from the market roads.'],variant:'mosque',spots:[spot('hall','Prayer hall',activity('ota-mosque-reflect','Sit quietly in the mosque','worship',['worship']))],beta:true,note:'Fictional worship venue at the mapped Sango locality; no real institution is claimed.'},
  {id:'ota-industry-walk',name:'Ota Industry Walk',district:'Ilupeju-Ota, Ado Odo/Ota',kind:'walk',variant:'factory',category:'fun',icon:'factory',point:{lon:3.2392,lat:6.701},description:'Learn how the Lagos-border industrial corridor grew.',ambient:['Warehouses and workshops line the long road.'],spots:[spot('route','Industry route',activity('ota-industry-learn','Walk the industry route','walk',['history','learn']))],beta:true,note:'Fictional interpretive route at the licensed LGA centroid.'},
  {id:'ota-sports-ground',name:'Ota Sports Ground',district:'Ota Centre, Ado Odo/Ota',kind:'viewing',variant:'ground-clay',category:'fun',icon:'ball',point:{lon:3.2301,lat:6.6868},description:'Train and watch a local football match.',ambient:['Players warm up beside the touchline.'],spots:[spot('stand','Touchline stand',activity('ota-match','Watch the match','ball',['sport'],{effects:{fun:10,social:4}})),work()],beta:true,note:'Fictional sports ground at the licensed LGA centroid.'},
  {id:'ota-border-kitchen',name:'Border Road Kitchen',district:'Sango-Ota, Ado Odo/Ota',kind:'buka',category:'food',icon:'food',point:{lon:3.2415,lat:6.7059},description:'Eat rice, stew and plantain near the commuter routes.',ambient:['The lunch crowd arrives from the market and motor park.'],spots:[spot('counter','Food counter',activity('ota-rice-plate','Eat rice, stew and plantain','food',['food'],{cost:1000,effects:{hunger:32,fun:4}})),work()],beta:true,note:'Fictional food counter at the mapped Sango locality.'},
  {id:'ota-salon',name:'Ota Junction Salon',district:'Sango-Ota, Ado Odo/Ota',kind:'salon',category:'care',icon:'hair',point:{lon:3.2437,lat:6.7059},description:'Get a trim or braid before the next bus.',ambient:['The clippers compete with traffic outside.'],spots:[spot('chair','Styling chair',activity('ota-hair','Get a fresh style','hair',['care'],{cost:1600,effects:{hygiene:8,fun:4}})),work()],beta:true,note:'Fictional salon at the mapped Sango locality.'},
  {id:'ota-evening-garden',name:'Ota Evening Garden',district:'Ota Centre, Ado Odo/Ota',kind:'park',variant:'evening-garden',category:'nightlife',icon:'music',point:{lon:3.2312,lat:6.6842},description:'Listen to an evening live set in a relaxed garden.',ambient:['Friends share tables as the music starts.'],spots:[spot('stage','Garden stage',activity('ota-evening-set','Listen to the evening set','music',['music','nightlife'],{hours:{open:18,close:23},xp:{music:8}})),work()],beta:true,note:'Fictional nightlife garden at the licensed LGA centroid.'},
]
const names=['Aderonke Akinwale','Sola Ogundele','Kemi Alade','Tunde Fashola','Bimpe Olorunfemi','Jide Salami','Yewande Bakare','Lanre Adeoti','Funke Ojo','Wale Adebisi','Rukayat Kareem','Kunle Olatunji','Peju Lawal','Seyi Akinola','Nike Adekunle','Dayo Oyedele','Morenike Balogun','Taiwo Bello','Kehinde Ajayi','Femi Oladele','Dupe Arowolo','Lekan Amoo','Tola Akande','Bayo Ogunleye','Sade Adeniran','Kayode Olaniyan','Ronke Abiodun','Segun Afolabi','Temi Adebayo','Yinka Oyekan']
const careers={'community-helper':'ota-neighbourhood-park',tech:'covenant-university',banking:'ota-civic-hall',music:'ota-evening-garden',trading:'sango-market',nursing:'ota-community-clinic',hair:'ota-salon',chef:'ota-border-kitchen',dj:'ota-evening-garden',fitness:'ota-sports-ground',creator:'ota-industry-walk',teaching:'bells-university',event:'ota-civic-hall',football:'ota-sports-ground',retail:'sango-market'}
export const OTA_CONTENT=buildOgunContent({cityId:'ota',cityName:'Ota',origin:OTA_MAP_ORIGIN,bounds:{minX:-224.6793411898,maxX:218.1394306199,minZ:-169.2422943225,maxZ:144.3278319361},localUnitDescriptions:{'ado-odo-ota':'Ota and Sango-Ota form Ogun’s busy industrial and commuter edge beside Lagos.'},venues,people:peopleFor(venues,names),careerVenues:careers,careerSummaries:{},houses:[{id:'ota-centre-room',label:'Single room',districtId:'ota-centre',district:'Ota Centre',rent:2800,grid:6,point:centre},{id:'ota-sango-flat',label:'Self-contain',districtId:'sango',district:'Sango-Ota',rent:6500,grid:8,point:sango},{id:'ota-ilupeju-house',label:'Two-bedroom house',districtId:'ilupeju-ota',district:'Ilupeju-Ota',rent:24000,grid:11,point:centre}],events:[{id:'ota-border-market',title:'Border-city market evening',blurb:'Traders and commuters stay for music after the market.',venue:'ota-evening-garden',icon:'music',when:{weekday:5,from:18,to:22}},{id:'ota-university-projects',title:'University project showcase',blurb:'Students show practical work from the technology campuses.',venue:'bells-university',icon:'star',when:{weekday:6,from:11,to:16}}],firstFun:{venue:'ota-neighbourhood-park',spot:'trees',activity:'ota-play-ayo',title:'Play ayo in the park',hint:'Neighbourhood Park · takes 7 seconds'},buka:'ota-border-kitchen',thingsToDo:[{venueId:'covenant-university',name:'Covenant University',line:'Join an enterprise workshop.'},{venueId:'bells-university',name:'Bells University',line:'Build a practical technology project.'},{venueId:'sango-market',name:'Sango-Ota Market',line:'Price goods beside the commuter routes.'},{venueId:'ota-industry-walk',name:'Industry Walk',line:'Learn how the border corridor grew.'},{venueId:'ota-evening-garden',name:'Evening Garden',line:'Listen to a relaxed live set.'}],culture:{greeting:'Ẹ káàbọ̀ sí Ọ̀tà',food:['ofada rice and ayamase','rice and plantain','moin-moin'],knownFor:['the Lagos border','universities and industry','daily commuter routes']},localModes:OGUN_LOCAL_MODES,homePalette:{back:'#d6dfc2',left:'#bccfa3',floor:['#cfd6bd','#a9b490']},radioVenueIds:['ota-evening-garden'],billboardRoads:[{id:'ota-bb-sango',near:'sango-park',road:'Lagos–Abeokuta Expressway'},{id:'ota-bb-centre',near:'ota-civic-hall',road:'Idiroko Road'}],tablePlaces:[{id:'ota-garden-whot',venueId:'ota-evening-garden',game:'whot',label:'Garden table',seats:4},{id:'ota-sports-penalty',venueId:'ota-sports-ground',game:'penalty',label:'Sports-ground penalty spot',seats:2}],dreamWording:{'lekki-landlord':{label:'Ota Landlord'},'yaba-unicorn':{label:'Border-City Builder',goal:'Build Coding to level 8 and Hustle to level 5.'}},lotteryWording:{'street-smart':{bullets:['No loan, but very little cash','Raised around busy commuter roads','Hustle starts at level 3 and Fitness at level 2','Choose an affordable local home']}}})
