// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "harare",
  "name": "Harare",
  "country": {
    "idISOlower": "zw",
    "name": "Zimbabwe"
  },
  "state": {
    "idunique": "zw-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Harare",
  "centre": {
    "lon": 31.042764,
    "lat": -17.815844
  },
  "airport": {
    "id": "harare-airport",
    "name": "Robert Gabriel Mugabe International Airport",
    "lon": 31.0928,
    "lat": -17.931801,
    "sourceUrl": "https://ourairports.com/airports/FVHA/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=31.039764,-17.818844,31.045764,-17.812844",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    31.027764,
    -17.943801,
    31.1048,
    -17.800844
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
