// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Amara Mbah", role: "Park caretaker", quotes: ["I keep Fatilami Park tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tobenna Chukwu", role: "Morning walker", quotes: ["I walk through Fatilami Park before work.", "Fresh air first, then the day."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Uchenna Eze", role: "Church volunteer", quotes: ["Welcome to St. Theresa's Cathedral. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Ogechi", role: "Regular worshipper", quotes: ["I have worshipped at St. Theresa's Cathedral for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amara Nnadi", role: "Cook", quotes: ["Today the pot at Crunchies Restaurant holds Abakaliki rice.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tobenna Agu", role: "Regular diner", quotes: ["I come to Crunchies Restaurant for Abakaliki rice.", "Wikipedia describes Abakaliki rice as rice grown predominantly in Ebonyi State and named after the state capital, used in a wide range of dishes."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Uchenna Okafor", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ogechi Okeke", role: "Patient's relative", quotes: ["I am waiting with a relative at Federal Teaching Hospital Abakaliki.", "Everyone here is patient, so I must be too."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amara Anyanwu", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mazi Tobenna", role: "Patient's relative", quotes: ["I am waiting with a relative at Capital Medicare.", "Everyone here is patient, so I must be too."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Uchenna Chukwu", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ogechi Nwosu", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amara Nwachukwu", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tobenna Ugwu", role: "Supporter", quotes: ["I come to Abakaliki Township Stadium for the football.", "Sit high up and you see the whole game."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Uchenna Agu", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Onyinye", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amara Okeke", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tobenna Okonkwo", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Uchenna Ibe", role: "Market trader", quotes: ["Looking for Abakaliki rice? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ogechi Onwuka", role: "Shopper", quotes: ["Wikipedia describes Abakaliki rice as rice grown predominantly in Ebonyi State and named after the state capital, used in a wide range of dishes.", "Take your time, and bargain with a smile."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amara Nwosu", role: "Ticket seller", quotes: ["Check the board for your departure.", "Keep your bags close in a crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mazi Chibueze", role: "Traveller", quotes: ["I am waiting at ITC Motor Park Abakaliki for my bus.", "Travelling is half waiting."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Uchenna Ugwu", role: "Student", quotes: ["I am on my way to a lecture at Blessed Martins College of Nursing Sciences.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ogechi Mbah", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amara Okoro", role: "Museum guide", quotes: ["Welcome to National Museum, Abakaliki. Please take your time.", "Ask me if you want to know what is on display."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tobenna Eze", role: "Visitor", quotes: ["I came to National Museum, Abakaliki to learn something new.", "Read the labels slowly. They reward you."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Uchenna Okonkwo", role: "Site attendant", quotes: ["Welcome to Ebonyi State Library Board. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Chiamaka", role: "Local resident", quotes: ["I walk past Ebonyi State Library Board most days.", "Visitors often stop here for photographs."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
