// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":124,"z":2979})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-88.12421130968193,"maxX":335.0732519350499,"minZ":-503.057510742603,"maxZ":168.54687448290633})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"abakaliki":{"lon":8.214189581946336,"lat":6.256367119415973},"ebonyi":{"lon":8.11874063819648,"lat":6.532930179881126}})
