// Generated by scripts/city/build-city.ts. Do not edit by hand.
import type { CityMapPack } from '../../../types/content.ts'
import { createFormulaCityGeometry } from '../formula/geometry.ts'
import { CITY_MAP_ORIGIN } from './geography.ts'
import { CITY_SPEC } from './spec.ts'
import {
  FORMULA_GEOMETRY_LICENCE,
  FORMULA_GEOMETRY_SOURCE,
  FORMULA_LAND,
  FORMULA_LOCAL_UNITS,
  FORMULA_RAIL,
  FORMULA_ROADS,
  FORMULA_STATE,
  FORMULA_WATER,
} from '../../../map3d/geo/data/abakaliki.formula.ts'

export const CITY_MAP: CityMapPack<typeof CITY_SPEC.id, (typeof CITY_SPEC.localUnits)[number]['id']> = Object.freeze({
  cityId: "abakaliki",
  origin: CITY_MAP_ORIGIN,
  projection: 'nigeria-equirectangular-v1',
  unitsPerKm: 10,
  localUnitIds: Object.freeze(["abakaliki","ebonyi"]),
  stateFeatureId: "ebonyi-state",
  loadScene: async () => {
    const [{ city }, { createModulePack }] = await Promise.all([import('./index.ts'), import('../../../map3d/cities/module.ts')])
    const stations = CITY_SPEC.transport.rail.filter(fact => fact.status !== 'inactive').flatMap(fact => {
      const place = CITY_SPEC.places.find(candidate => candidate.id === fact.placeId)
      return place ? [{ name: place.name, lon: place.lon, lat: place.lat }] : []
    })
    return createModulePack(city, {
      spread: true,
      roads: FORMULA_ROADS,
      landmarks: CITY_SPEC.places.map(place => ({ id: place.id, name: place.name, lon: place.lon, lat: place.lat, kind: place.kind })),
      character: {
        extent: 'city',
        rails: FORMULA_RAIL.map(line => ({ name: line.name, lines: [line.points], stations })),
        notable: CITY_SPEC.places.filter(place => place.scene.landmark).map(place => place.id),
      },
    })
  },
  loadGeometry: async () => createFormulaCityGeometry({
    localUnits: FORMULA_LOCAL_UNITS,
    state: FORMULA_STATE,
    land: FORMULA_LAND,
    water: FORMULA_WATER,
    localUnitIds: ["abakaliki","ebonyi"],
    stateFeatureId: "ebonyi-state",
    source: FORMULA_GEOMETRY_SOURCE,
    licence: FORMULA_GEOMETRY_LICENCE,
  }),
})
