import { createHash } from 'node:crypto';
import { createServer } from 'node:http';
import { spawn, execFileSync } from 'node:child_process';
import { appendFileSync, closeSync, createReadStream, existsSync, mkdirSync, openSync, readSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { mkdtemp, readFile, realpath } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import WebSocket from 'ws';
import { verifySnapshot } from './verify-snapshot.mjs';
import { browserResultPaths } from './browser-result-contract.mjs';

const HERE=path.dirname(fileURLToPath(import.meta.url)),ROOT=path.resolve(HERE,'../../../../../../../..');
const DIST=path.join(HERE,'dist'),RESULT=process.env.RESULT_DIR,RESULT_PATHS=browserResultPaths(RESULT),OUTPUT=RESULT_PATHS.output,expected=process.argv[2];
const stagePath=RESULT_PATHS.stages,stageStart=Date.now();
function stage(name,details={}){if(!stagePath)throw new Error('Missing stage artifact path');appendFileSync(stagePath,`${JSON.stringify({at:new Date().toISOString(),elapsedMs:Date.now()-stageStart,stage:name,...details})}\n`,{flag:'a'});}
if(stagePath&&existsSync(stagePath))throw new Error('Refusing to overwrite browser stage breadcrumbs');
if(process.platform!=='linux')throw new Error('Remote Linux only');
const snapshot=await verifySnapshot(expected);
if(existsSync(OUTPUT)&&readdirSync(OUTPUT).length)throw new Error('Refusing to overwrite browser artifacts');
mkdirSync(OUTPUT,{recursive:true});
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
async function fileSha(file){const h=createHash('sha256');for await(const chunk of createReadStream(file))h.update(chunk);return h.digest('hex');}
function first4(file){const fd=openSync(file,'r'),b=Buffer.alloc(4);try{return readSync(fd,b,0,4,0)===4?b:null;}finally{closeSync(fd);}}
const chromeLauncherPath=await realpath(process.env.CHROME_BIN??''),launcherSha=await fileSha(chromeLauncherPath),sibling=path.join(path.dirname(chromeLauncherPath),'chrome');
const chromePath=existsSync(sibling)&&first4(sibling)?.equals(Buffer.from([0x7f,0x45,0x4c,0x46]))?await realpath(sibling):chromeLauncherPath;
if(!first4(chromePath)?.equals(Buffer.from([0x7f,0x45,0x4c,0x46])))throw new Error('Could not resolve actual Chrome ELF binary');
const chromeVersion=execFileSync(chromeLauncherPath,['--version'],{encoding:'utf8',timeout:3000}).trim(),chromeBinaryVersion=execFileSync(chromePath,['--version'],{encoding:'utf8',timeout:3000}).trim(),chromeSha=await fileSha(chromePath);
const runtime={node:process.version,platform:process.platform,kernel:os.release(),arch:os.arch(),runnerImage:process.env.ImageOS??null,runnerVersion:process.env.ImageVersion??null,chromeLauncherPath,chromeLauncherSha256:launcherSha,chromePath,chromeVersion,chromeBinaryVersion,chromeSha256:chromeSha,manifestSha256:snapshot.manifestSha256,rendererMode:'headless Chrome ANGLE SwiftShader forced single-process diagnostic; not representative Chrome/mobile performance',chromeTopologyFlags:['--single-process','--in-process-gpu','--no-zygote','--renderer-process-limit=1']};
stage('controller-started',{manifestSha256:runtime.manifestSha256,chromePath,chromeSha256:chromeSha,topology:runtime.chromeTopologyFlags});
const mime=new Map([['.html','text/html; charset=utf-8'],['.js','text/javascript; charset=utf-8'],['.glb','model/gltf-binary'],['.json','application/json']]);
const server=createServer(async(req,res)=>{try{if(!['GET','HEAD'].includes(req.method??'')){res.writeHead(405).end();return;}const url=new URL(req.url??'/','http://127.0.0.1');if(url.pathname==='/favicon.ico'){res.writeHead(204).end();return;}const requestPath=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname),file=path.resolve(DIST,`.${requestPath}`),rel=path.relative(DIST,file);if(!rel||rel.startsWith('..')||path.isAbsolute(rel)){res.writeHead(403).end();return;}const data=await readFile(file);res.writeHead(200,{'content-type':mime.get(path.extname(file))??'application/octet-stream','cache-control':'no-store','content-length':data.byteLength});res.end(req.method==='HEAD'?undefined:data);}catch{res.writeHead(404,{'cache-control':'no-store'}).end('not found');}});
let chrome=null,ws=null,serverAddress,profile,chromeLog,serverClosed=false,nextId=0;const pending=new Map(),requestUrls=new Map(),events={runtimeExceptions:[],consoleErrors:[],failedRequests:[],httpErrors:[]};
function cdp(method,params={}){const id=++nextId;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`CDP timeout: ${method}`));},8000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params}));});}
function onMessage(data){const m=JSON.parse(data.toString());if(m.id){const item=pending.get(m.id);if(!item)return;clearTimeout(item.timer);pending.delete(m.id);if(m.error)item.reject(new Error(`${m.error.message}: ${JSON.stringify(m.error.data??null)}`));else item.resolve(m.result);return;}if(m.method==='Runtime.exceptionThrown')events.runtimeExceptions.push(m.params.exceptionDetails);if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')events.consoleErrors.push(m.params.args?.map(a=>a.value??a.description??'').join(' '));if(m.method==='Network.requestWillBeSent')requestUrls.set(m.params.requestId,m.params.request.url);if(m.method==='Network.loadingFailed')events.failedRequests.push({requestId:m.params.requestId,url:requestUrls.get(m.params.requestId)??null,errorText:m.params.errorText,canceled:m.params.canceled});if(m.method==='Network.responseReceived'&&m.params.response.status>=400)events.httpErrors.push({url:m.params.response.url,status:m.params.response.status});}
async function evaluate(expr,awaitPromise=false){const result=await cdp('Runtime.evaluate',{expression:expr,awaitPromise,returnByValue:true,userGesture:true});if(result.exceptionDetails)throw new Error(`Page evaluation failed: ${result.exceptionDetails.text}`);return result.result?.value;}
async function waitFor(predicate,desc,timeout=12000){const end=Date.now()+timeout;while(Date.now()<end){if(await predicate())return;await new Promise(r=>setTimeout(r,100));}throw new Error(`Timed out waiting for ${desc}`);}
async function devtoolsPort(){const p=path.join(profile,'DevToolsActivePort');await waitFor(()=>existsSync(p),'Chrome DevToolsActivePort',8000);const port=Number(readFileSync(p,'utf8').trim().split(/\r?\n/)[0]);if(!Number.isInteger(port)||port<1||port>65535)throw new Error('Invalid DevTools port');return port;}
async function connectPage(port){let targets;await waitFor(async()=>{try{const r=await fetch(`http://127.0.0.1:${port}/json/list`);targets=await r.json();return Array.isArray(targets)&&targets.some(t=>t.type==='page'&&t.webSocketDebuggerUrl);}catch{return false;}},'Chrome page target',8000);const target=targets.find(t=>t.type==='page'&&t.webSocketDebuggerUrl);ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject);});ws.on('message',onMessage);await cdp('Page.enable');await cdp('Runtime.enable');await cdp('Log.enable');await cdp('Network.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});}
async function settle(){await evaluate('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve(true))))',true);}
async function setState(body,variant,pose,yaw,focus,withPositionWitness=false){const api='window.__NECK_COMPLEMENT_FIXTURE__';if(body!==currentBody){await evaluate(`${api}.setBody(${JSON.stringify(body)})`,true);currentBody=body;}await evaluate(`${api}.setPose(${JSON.stringify(pose)})`);await evaluate(`${api}.setYaw(${yaw})`);await evaluate(`${api}.setFocus(${JSON.stringify(focus)})`);await evaluate(`${api}.setVariant(${JSON.stringify(variant)})`);await settle();return evaluate(`${api}.${withPositionWitness?'snapshot':'renderState'}()`);}
let currentBody=null;
const expectedBody={man:{asset:'b0078206da9f7de0bf346be8133522cf514009f03f262f716613dd196d180686',triangles:3266,vertices:1778},woman:{asset:'977ca5e73ba7b19af2627dab1ba0f0ef3e3d8548bf7b4d54f45faf22cd56001c',triangles:3541,vertices:1893}},poses=['idle','walk','jog','sit','reach','dance','lie','soak'];
function validateSnapshot(s,body,variant){const e=expectedBody[body],record=s?.[variant==='source'?'source':'chart'];if(!s?.comparisonValid||s.body!==body||s.requestedOutfit!=='office'||s.selected!==variant)throw new Error(`Invalid matched state ${body}/${variant}: ${JSON.stringify({valid:s?.comparisonValid,body:s?.body,outfit:s?.requestedOutfit,selected:s?.selected})}`);if(record?.sourceTriangleCount!==9002||record?.sourceShellTriangles!==e.triangles||record?.sourceShellVertices!==e.vertices||record?.appearanceReplayMatchesDisplayed!==true||record?.displayedMaskTriangles<=0)throw new Error(`Actual source/chart record mismatch ${body}/${variant}: ${JSON.stringify(record)}`);if(variant==='chart'&&(!record.neckDomainAuditSummary?.domainMatchesActualCandidate||!s.independentNeckDomain?.domainMatchesActualCandidate||record.neckDomainAuditSummary.excludedResidualFaces!==s.independentNeckDomain.excludedFullNeckResidualFaceIds?.length))throw new Error(`Independent neck-domain proof missing or inconsistent for ${body}: ${JSON.stringify({summary:record.neckDomainAuditSummary,domain:s.independentNeckDomain})}`);if(!Array.isArray(s.shaderErrors)||s.shaderErrors.length)throw new Error(`Shader errors for ${body}/${variant}: ${JSON.stringify(s.shaderErrors)}`);if(!(s.renderCalls>0)||!(s.renderedTriangles>0))throw new Error('No actual WebGL draw reported');return record;}
async function capture(body,variant,pose,yaw,focus){const s=await setState(body,variant,pose,yaw,focus),record=validateSnapshot(s,body,variant);const file=`${body}-${variant}-${pose}-yaw${String(yaw).padStart(3,'0')}-${focus}.png`;stage('screenshot-before',{file,body,variant,pose,yaw,focus});const shot=await cdp('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});const data=Buffer.from(shot.data,'base64');if(data.subarray(1,4).toString()!=='PNG')throw new Error(`Invalid screenshot payload ${file}`);writeFileSync(path.join(OUTPUT,file),data,{flag:'wx'});const result={file,body,variant,pose,yaw,focus,bytes:data.length,sha256:sha(data),renderCalls:s.renderCalls,renderedTriangles:s.renderedTriangles,sourceTriangles:record.sourceShellTriangles,sourceBytes:record.sourceShellBytes,complement:s.neckClosure};stage('screenshot-after',result);return result;}
let finalStatus='failed',failure=null,chromeEvents=null,serverClosedFlag=false,screenshots=[],poseWitnesses=[],webgl=null;
let cleanupPromise=null;async function cleanup(){if(cleanupPromise)return cleanupPromise;cleanupPromise=(async()=>{if(ws&&ws.readyState===WebSocket.OPEN){try{ws.close();}catch{}}if(chrome&&chrome.exitCode===null){chrome.kill('SIGTERM');await Promise.race([new Promise(resolve=>chrome.once('exit',resolve)),new Promise(r=>setTimeout(r,1200))]);if(chrome.exitCode===null)chrome.kill('SIGKILL');}if(!serverClosedFlag){serverClosedFlag=true;await new Promise(resolve=>server.close(()=>resolve()));}if(chromeLog!==undefined)closeSync(chromeLog);if(profile)rmSync(profile,{recursive:true,force:true});})();return cleanupPromise;}
let terminating=false;process.on('SIGTERM',()=>{if(terminating)return;terminating=true;try{stage('controller-sigterm',{screenshots:screenshots.length});}catch{}void cleanup().finally(()=>process.exit(143));});
try{
 if(!existsSync(path.join(DIST,'index.html'))||!existsSync(path.join(DIST,'build-manifest.json')))throw new Error('Static bundle is missing');
 serverAddress=await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>resolve(server.address()));});stage('loopback-server-listening',{port:serverAddress?.port??null,address:serverAddress?.address??null});if(!serverAddress||typeof serverAddress==='string'||serverAddress.address!=='127.0.0.1')throw new Error('Fixture server is not loopback-only');
 profile=await mkdtemp(path.join(os.tmpdir(),'neck-complement-chrome-'));chromeLog=openSync(path.join(OUTPUT,'chrome.log'),'wx');const args=['--single-process','--in-process-gpu','--no-zygote','--renderer-process-limit=1','--headless=new','--no-sandbox','--disable-dev-shm-usage','--disable-gpu-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader','--disable-extensions','--disable-background-networking','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'];
 stage('chrome-launch-before',{chromePath,flags:args.filter(a=>a.startsWith('--'))});chrome=spawn(chromePath,args,{stdio:['ignore','ignore',chromeLog],env:{...process.env}});stage('chrome-launch-after',{pid:chrome.pid??null});chrome.once('error',e=>{failure=String(e);});
 stage('devtools-port-wait-before');const port=await devtoolsPort();stage('devtools-port-ready',{port});await connectPage(port);stage('cdp-connected',{port});const url=`http://127.0.0.1:${serverAddress.port}/`;stage('navigation-before',{url});await cdp('Page.navigate',{url});stage('navigation-after',{url});await waitFor(async()=>await evaluate('Boolean(window.__NECK_COMPLEMENT_FIXTURE__)').catch(()=>false),'neck-complement fixture API');stage('fixture-api-ready');
 await evaluate('window.__NECK_COMPLEMENT_FIXTURE__.load()',true);let status=await evaluate("document.getElementById('status')?.textContent??null");let first=await evaluate('window.__NECK_COMPLEMENT_FIXTURE__.snapshot()');stage('fixture-load-after',{status,first});if(typeof status==='string'&&status.startsWith('Fixture failed closed:'))throw new Error(`Fixture failed closed: ${status}`);if(first?.comparisonValid!==true)throw new Error('Fixture API loaded without a valid matched chart');currentBody='man';
 webgl=await evaluate(`(()=>{const c=document.getElementById('scene'),g=c.getContext('webgl2')||c.getContext('webgl'),e=g?.getExtension('WEBGL_debug_renderer_info');return g?{version:g.getParameter(g.VERSION),vendor:g.getParameter(e?e.UNMASKED_VENDOR_WEBGL:g.VENDOR),renderer:g.getParameter(e?e.UNMASKED_RENDERER_WEBGL:g.RENDERER),shadingLanguage:g.getParameter(g.SHADING_LANGUAGE_VERSION)}:null})()`);if(!webgl?.renderer||!String(webgl.renderer).toLowerCase().includes('swiftshader'))throw new Error(`Expected SwiftShader but got ${JSON.stringify(webgl)}`);
 for(const body of ['man','woman']){
  if(body==='woman'){await evaluate("window.__NECK_COMPLEMENT_FIXTURE__.setBody('woman')",true);currentBody='woman';await settle();}
  for(const pose of poses){const s=await setState(body,'chart',pose,0,'shoulder',true),record=validateSnapshot(s,body,'chart'),w=s.exactComplementPositionWitness;if(!w||w.allFinite!==true||w.vertices!==s.chart?.neckComplement?.vertices||w.vertices<=0||w.maxErrorMetres>2e-5||w.maxBindInverseDelta>1e-9)throw new Error(`Eight-pose exact position guard failed ${body}/${pose}: ${JSON.stringify(w)}`);poseWitnesses.push({body,pose,exactComplementPositionWitness:w,sourceTriangles:record.sourceShellTriangles,complement:s.neckClosure,shaderErrors:s.shaderErrors});stage('pose-witness',{body,pose,witness:w});}
  const frames=[...Array(8)].map((_,i)=>({pose:'idle',yaw:i*45,focus:'shoulder'})).concat([{pose:'idle',yaw:0,focus:'full'},{pose:'reach',yaw:45,focus:'shoulder'},{pose:'reach',yaw:90,focus:'shoulder'},{pose:'reach',yaw:315,focus:'shoulder'},{pose:'walk',yaw:45,focus:'shoulder'},{pose:'walk',yaw:90,focus:'shoulder'},{pose:'sit',yaw:90,focus:'shoulder'}]);
  for(const frame of frames){const pair=[];for(const variant of ['source','chart'])pair.push(await capture(body,variant,frame.pose,frame.yaw,frame.focus));const [baseline,candidate]=pair;if(candidate.complement.extraDrawCalls!==1||candidate.complement.candidateTriangles<=0||candidate.complement.candidateBytes<=0||baseline.complement.extraDrawCalls!==1||baseline.complement.candidateTriangles!==candidate.complement.candidateTriangles||baseline.complement.candidateBytes!==candidate.complement.candidateBytes||candidate.renderCalls!==baseline.renderCalls+1||candidate.renderedTriangles!==baseline.renderedTriangles+candidate.complement.candidateTriangles)throw new Error(`Render-cost delta does not equal the isolated complement for ${body}/${frame.pose}/${frame.yaw}: ${JSON.stringify({baseline,candidate})}`);screenshots.push(...pair);}
 }
 if(events.runtimeExceptions.length||events.consoleErrors.length||events.httpErrors.length||events.failedRequests.length>0)throw new Error(`Browser errors or uncanceled requests: ${JSON.stringify(events)}`);
 if(screenshots.length!==60||poseWitnesses.length!==16)throw new Error(`Incomplete capture set: ${screenshots.length} images, ${poseWitnesses.length} pose witnesses`);
 finalStatus='measured';
}catch(error){failure=error instanceof Error?error.stack??error.message:String(error);try{stage('controller-error',{error:failure});}catch{}}
finally{try{stage('cleanup-before',{finalStatus,screenshots:screenshots.length,poseWitnesses:poseWitnesses.length});}catch{}await cleanup();try{stage('cleanup-after',{finalStatus,screenshots:screenshots.length,poseWitnesses:poseWitnesses.length});}catch{}}
const after=await verifySnapshot(expected).catch(e=>({error:String(e)})),sourceUnchanged=!after.error&&JSON.stringify(snapshot.sourceHashes)===JSON.stringify(after.sourceHashes);chromeEvents=events;
const breadcrumbs=existsSync(stagePath)?readFileSync(stagePath,'utf8').split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line)):[];
const report={status:finalStatus,success:finalStatus==='measured'&&sourceUnchanged&&screenshots.length===60&&poseWitnesses.length===16,failure,runtime,sourceUnchanged,stageBreadcrumbCount:breadcrumbs.length,browser:{webgl,events:chromeEvents,screenshotCount:screenshots.length,screenshots,poseWitnesses},limitations:['Remote Linux headless Chrome ANGLE SwiftShader only; forced single-process topology is diagnostic and not representative of ordinary browser or phone cost.','The exact-position witness checks the custom complement skinning against barycentric interpolation of actual skinned source corners at eight sampled poses; it does not prove material continuity, absence of z-fighting, or acceptable appearance.','Captured images require independent visual review; no production acceptance is claimed.']};
writeFileSync(path.join(OUTPUT,'review-results.json'),`${JSON.stringify(report,null,2)}\n`,{flag:'wx'});console.log(JSON.stringify({status:report.status,success:report.success,failure:report.failure,screenshotCount:screenshots.length,poseWitnessCount:poseWitnesses.length,webgl,sourceUnchanged},null,2));if(!report.success)process.exitCode=1;
