// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-3034,"z":-4516})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-50.76265651125641,"maxX":67.9269418986164,"minZ":-31.404534534300183,"maxZ":62.04503403984381})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"sokoto-north":{"lon":5.229444737102703,"lat":13.06985692836212},"sokoto-south":{"lon":5.2596273376613585,"lat":13.040038867746455}})
