import { defineCitySpec } from '../spec.ts'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'sokoto',
  name: 'Sokoto',
  state: { id: 'sokoto', name: 'Sokoto', sourceName: 'Sokoto', unit: 'local government', sourceIds: ['geography'] },
  country: { id: 'nigeria', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 5.2373194,
    lat: 13.0610588,
    teaser: "The Sultanate capital on the Sokoto-Rima plains, known for leather, hides, the Sultan's palace and a Hausa food tradition.",
    preview: ["Visit the Sultan's palace and the tomb of Uthman dan Fodio.", 'Browse Central Market and try kilishi at a roadside restaurant.'],
    coordinateSourceId: 'osm-selected',
    coordinateRef: { provider: 'openstreetmap', element: 'node', id: 501540904 },
  },
  population: { tier: 'city', sourceIds: ['sokoto-wiki'], note: 'The cited article reports a population of over 427,760 for Sokoto in 2006.' },
  localUnits: [
    { id: 'sokoto-north', name: 'Sokoto North', sourceName: 'Sokoto North', populationTier: 'city', description: "The northern local government holds Central Market, the Sultan's palace, the Uthman dan Fodio tomb, the main motor parks and the cattle market.", sourceIds: ['geography'] },
    { id: 'sokoto-south', name: 'Sokoto South', sourceName: 'Sokoto South', populationTier: 'city', description: 'The southern local government holds the Shehu Mosque, the cathedral, the Specialist Hospital, the museum, Marna market and the main banks.', sourceIds: ['geography'] },
  ],
  places: [
    {
      id: 'shehu-mosque-sokoto', name: 'Shehu Mosque', kind: 'mosque', lon: 5.2382853, lat: 13.0636629, localUnitId: 'sokoto-south',
      description: 'A mapped mosque building recorded as Shehsu Mosque, shown here under its usual name Shehu Mosque.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1523859177 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'masallacin-nana-aisha-sokoto', name: 'Masallacin Nana Aisha', kind: 'mosque', lon: 5.2004793, lat: 13.0702894, localUnitId: 'sokoto-north',
      description: 'A mapped place of worship named Masallacin Nana Aisha.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 4701329422 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'holy-family-cathedral-sokoto', name: 'Cathedral of the Holy Family of Sokoto', kind: 'church', lon: 5.232137, lat: 13.053325, localUnitId: 'sokoto-south',
      description: 'Wikidata records the Cathedral of the Holy Family of Sokoto as a building in Sokoto.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q25938086' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'mountain-of-fire-sokoto', name: 'Mountain of Fire & Miracles church', kind: 'church', lon: 5.2381424, lat: 13.0424532, localUnitId: 'sokoto-south',
      description: 'A mapped place of worship named Mountain of Fire & Miracles church.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5836592708 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'sokoto-clinic-restaurant', name: 'Sokoto Clinic Restaurant', kind: 'eatery', lon: 5.2177782, lat: 13.0598774, localUnitId: 'sokoto-north',
      description: 'A mapped restaurant building named Sokoto Clinic Restaurant serving regional cuisine, shown here with suya.', sourceIds: ['osm-selected', 'suya-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 318493293 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'suya',
    },
    {
      id: 'shanghai-bakers-sokoto', name: 'Shanghai Bakers', kind: 'eatery', lon: 5.2311436, lat: 13.0416151, localUnitId: 'sokoto-south',
      description: 'A mapped restaurant building named Shanghai Bakers serving regional cuisine, shown here with kilishi.', sourceIds: ['osm-selected', 'kilishi-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 318385589 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'kilishi',
    },
    {
      id: 'sokoto-sultanate-council', name: 'Sokoto Sultanate Council', kind: 'government', lon: 5.23333333, lat: 13.06666667, localUnitId: 'sokoto-north',
      description: 'Wikidata records the Sokoto Sultanate Council as the northern Nigerian emirate council of the Sultanate of Sokoto.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q25044572' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'specialist-hospital-sokoto', name: 'Specialist Hospital', kind: 'hospital', lon: 5.2459372, lat: 13.0517874, localUnitId: 'sokoto-south',
      description: 'A mapped hospital building named Specialist Hospital.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 311526964 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'noma-children-hospital-sokoto', name: 'Noma Children Hospital Sokoto', kind: 'hospital', lon: 5.2155432, lat: 13.0674774, localUnitId: 'sokoto-north',
      description: 'A mapped hospital named Noma Children Hospital Sokoto.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 804232867 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'central-market-sokoto', name: 'Central Market', kind: 'market', lon: 5.2233104, lat: 13.0606685, localUnitId: 'sokoto-north',
      description: 'A mapped marketplace named Central Market; Wikipedia says Sokoto trades sheepskins, hides, leather crafts, kola nuts and goatskins.', sourceIds: ['osm-selected', 'sokoto-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 282586704 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['sokoto-hides-skins-trade'],
    },
    {
      id: 'marna-market-sokoto', name: 'Marna market', kind: 'market', lon: 5.246654, lat: 13.057159, localUnitId: 'sokoto-south',
      description: 'Wikidata records Marna market as a market in Nigeria, located in Sokoto South.', sourceIds: ['wikidata-selected', 'sokoto-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q108619547' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['sokoto-hides-skins-trade'],
    },
    {
      id: 'karra-cattle-market-sokoto', name: 'Sokoto karra cattle market', kind: 'market', lon: 5.2257062, lat: 13.0704306, localUnitId: 'sokoto-north',
      description: 'Wikidata records the Sokoto karra cattle market as a market in Sokoto State; Wikipedia says Sokoto residents largely practise agriculture.', sourceIds: ['wikidata-selected', 'sokoto-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136512703' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['sokoto-farming'],
    },
    {
      id: 'cross-country-motor-park-sokoto', name: 'Cross Country Motor Park', kind: 'road-hub', lon: 5.2153834, lat: 13.055914, localUnitId: 'sokoto-north',
      description: 'A mapped bus station named Cross Country Motor Park.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 3249091263 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'sokoto-main-garage', name: 'Sokoto Main Garage', kind: 'road-hub', lon: 5.226043, lat: 13.0587608, localUnitId: 'sokoto-north',
      description: 'A mapped bus station named Sokoto Main Garage.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 318507720 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'first-bank-sokoto', name: 'First Bank', kind: 'savings', lon: 5.2452739, lat: 13.0448526, localUnitId: 'sokoto-south',
      description: 'A mapped bank building named First Bank.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 318532522 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'gt-bank-sokoto', name: 'GT Bank', kind: 'savings', lon: 5.2324342, lat: 13.05889, localUnitId: 'sokoto-south',
      description: 'A mapped bank building named GT Bank.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 318532524 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'gamji-college-of-nursing-sokoto', name: 'Gamji College of Nursing Sciences, Sokoto, Sokoto State', kind: 'college', lon: 5.2573621, lat: 13.0818197, localUnitId: 'sokoto-north',
      description: 'Wikidata records Gamji College of Nursing Sciences as a college of nursing in Sokoto.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q137712129' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'sultans-palace-sokoto', name: 'The sultan of sokoto palace', kind: 'heritage', lon: 5.247323, lat: 13.067056, localUnitId: 'sokoto-north',
      description: 'Wikidata records the Sultan of Sokoto palace as a tourist attraction in Sokoto North.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q108933898' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'uthman-dan-fodio-tomb-sokoto', name: 'uthman Dan fodio tomb', kind: 'heritage', lon: 5.241215, lat: 13.064464, localUnitId: 'sokoto-north',
      description: 'Wikidata records the tomb of the Islamic scholar Uthman dan Fodio, acknowledged founder of Sokoto, in Sokoto North.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q108908560' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'waziri-junaidu-museum-sokoto', name: 'Waziri Junaidu History & Culture Bureau Sokoto', kind: 'museum', lon: 5.2495893, lat: 13.0435103, localUnitId: 'sokoto-south',
      description: 'Wikidata records the Waziri Junaidu History and Culture Bureau as a museum in Sokoto State.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q112107280' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
  ],
  identity: {
    foods: [
      { id: 'suya', name: 'Suya', description: 'Wikipedia describes suya as a traditional Hausa smoke-grilled spiced meat on skewers, seasoned with the spice mix yaji.', sourceIds: ['suya-wiki'] },
      { id: 'kilishi', name: 'Kilishi', description: 'Wikipedia describes kilishi as a Hausaland jerky of dried, spiced meat such as beef or lamb, seasoned, smoked and sun-dried.', sourceIds: ['kilishi-wiki'] },
    ],
    crafts: [
      { id: 'sokoto-local-crafts', name: 'Blacksmithing, weaving, dyeing, carving and leatherwork', description: 'Wikipedia lists blacksmithing, weaving, dyeing, carving and leather works among the local crafts that matter to the economic life of Sokoto.', sourceIds: ['sokoto-wiki'] },
    ],
    industries: [
      { id: 'sokoto-hides-skins-trade', name: 'Hides, skins and leather trade', description: 'Wikipedia says modern Sokoto is known for trading sheepskins, cattle hides, leather crafts, kola nuts and goatskins.', sourceIds: ['sokoto-wiki'] },
      { id: 'sokoto-farming', name: 'Farming and fishing', description: 'Wikipedia says over eighty percent of Sokoto inhabitants practise agriculture, growing millet, guinea corn, maize, rice and groundnuts, and that many people on the river basin fish.', sourceIds: ['sokoto-wiki'] },
    ],
  },
  transport: {
    airports: [],
    rail: [],
    ports: [],
  },
  climate: {
    profile: 'sahel', rainyMonths: [6, 7, 8, 9, 10], dryMonths: [11, 12, 1, 2, 3, 4, 5],
    description: 'Sokoto has a hot semi-arid climate in the dry Sahel, with a rainy season from June to October and a harmattan dust season from late October to February.',
    clearLabel: 'Dry-season sky', sourceIds: ['sokoto-wiki'], harmattan: { months: [11, 12, 1, 2], label: 'Harmattan dust' },
  },
  homePalette: { back: '#b5703f', left: '#7a4a2a', floor: ['#d3a374', '#8a5a3a'] },
  geometry: { surface: { path: 'scripts/geo/sources/formula/sokoto-surface.geojson', bytes: 111051, sha256: 'e2e1a69b4d65cd5ea28b497bac742c8c2715fb2796d03b2ce551a3481302eef0' } },
  sourceGroups: [
    { id: 'osm-selected', title: 'Selected OpenStreetMap records for Sokoto', url: 'https://www.openstreetmap.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'ODbL 1.0', cache: { path: 'scripts/city/research/sokoto/reviewed/osm-selected.json', bytes: 3891, sha256: '0c7d0fa56d52fe405435ea115d8df5f11ff5ec1e073edac368523d5e94cd4eac' } },
    { id: 'wikidata-selected', title: 'Selected Wikidata entities for Sokoto', url: 'https://www.wikidata.org/wiki/Wikidata:Main_Page', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'CC0 1.0', cache: { path: 'scripts/city/research/sokoto/reviewed/wikidata-selected.json', bytes: 6669, sha256: 'e4288ce16990d009b706c8d4db8d8644655700abc4d2ab87b155a3a03fc0b9f8' } },
    { id: 'geography', title: 'Pinned Nigerian administrative geography', url: 'https://www.geoboundaries.org/', checkedOn: '2026-10-06', supports: ['geography'], licence: 'CC BY 4.0', cache: { path: 'scripts/city/research/sokoto/reviewed/geography.json', bytes: 408, sha256: '39d450dc437307ac3459f9a85ec804ee6b63d57c1df74d51b4f2be675087308f' } },
    { id: 'sokoto-wiki', title: 'Wikipedia: Sokoto (city)', url: 'https://en.wikipedia.org/wiki/Sokoto_(city)', checkedOn: '2026-10-06', supports: ['population', 'climate', 'identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/sokoto/reviewed/sokoto-wiki.json', bytes: 1116, sha256: '5c2d51ebfbceaac37ad48a8c3cc35fc18dd734e9d1f70e7a0048d028e6f55a1c' } },
    { id: 'suya-wiki', title: 'Wikipedia: Suya', url: 'https://en.wikipedia.org/wiki/Suya', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/sokoto/reviewed/suya-wiki.json', bytes: 277, sha256: 'ff698f4bff5262056dabb7347be0cb9124e194f9727a2548e7d91028a64643bd' } },
    { id: 'kilishi-wiki', title: 'Wikipedia: Kilishi', url: 'https://en.wikipedia.org/wiki/Kilishi', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/sokoto/reviewed/kilishi-wiki.json', bytes: 320, sha256: 'dea34f670c3f12b5527a66d5099665c517538f678af58e93b3cc43ef4d2e1b72' } },
  ],
  unmapped: [
    { kind: 'garden', note: 'No named garden with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'park', note: 'No named park with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'polling', note: 'No named polling venue with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'salon', note: 'No named salon with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'stadium', note: 'No named stadium with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
  ],
})
