// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "juba",
  "name": "Juba",
  "country": {
    "idISOlower": "ss",
    "name": "South Sudan"
  },
  "state": {
    "idunique": "ss-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Juba",
  "centre": {
    "lon": 31.580026,
    "lat": 4.829975
  },
  "airport": {
    "id": "juba-airport",
    "name": "Juba International Airport",
    "lon": 31.601101,
    "lat": 4.87201,
    "sourceUrl": "https://ourairports.com/airports/HJJJ/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=31.577026,4.826975,31.583026,4.832975",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    31.565026,
    4.814975,
    31.613101,
    4.88401
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
