// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Zainab Suleiman", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Lawal Yakubu", role: "Supporter", quotes: ["I come to Haliru Abdu Stadium. for the football.", "Sit high up and you see the whole game."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aliyu Gambo", role: "Church volunteer", quotes: ["Welcome to St. Dominic's Catholic Church Bernin Kebbi. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Halima", role: "Regular worshipper", quotes: ["I have worshipped at St. Dominic's Catholic Church Bernin Kebbi for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zainab Danladi", role: "Church volunteer", quotes: ["Welcome to 1st ecwa Bishara church. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Lawal Bello", role: "Regular worshipper", quotes: ["I have worshipped at 1st ecwa Bishara church for a long time.", "Sit anywhere there is room, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aliyu Kabir", role: "Mosque caretaker", quotes: ["Welcome to Birnin kebbi central mosque, Kebbi State.. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Halima Tanko", role: "Regular worshipper", quotes: ["I have prayed at Birnin kebbi central mosque, Kebbi State. for a long time.", "Come in quietly, and be welcome."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zainab Gwarzo", role: "Cook", quotes: ["Today the pot at DEELAD PLACE holds Suya.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Malam Lawal", role: "Regular diner", quotes: ["I come to DEELAD PLACE for Suya.", "Wikipedia describes suya as a traditional Hausa smoke-grilled spiced meat on skewers, seasoned with the spice mix yaji."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aliyu Yakubu", role: "Cook", quotes: ["Today the pot at Daula Restaurant holds Dambu nama.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Halima Sadiq", role: "Regular diner", quotes: ["I come to Daula Restaurant for Dambu nama.", "Wikipedia describes dambu nama as a West African dish of dried, shredded meat, popular in northern Nigeria and among Hausa speakers, with a candy-floss texture."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zainab Bala", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Lawal Salihu", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aliyu Bello", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Zulai", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zainab Tanko", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Lawal Magaji", role: "Patient's relative", quotes: ["I am waiting with a relative at Sir Yahaya Memorial Hospital.", "Everyone here is patient, so I must be too."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aliyu Abubakar", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Halima Umar", role: "Patient's relative", quotes: ["I am waiting with a relative at Federal Medical Centre, Birnin Kebbi.", "Everyone here is patient, so I must be too."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zainab Sadiq", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Malam Garba", role: "Patient's relative", quotes: ["I am waiting with a relative at Zauro Ambrusa General Hospital.", "Everyone here is patient, so I must be too."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aliyu Salihu", role: "Market trader", quotes: ["Looking for Rice, grain, fish and livestock trade? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Halima Suleiman", role: "Shopper", quotes: ["Wikipedia says Birnin Kebbi is a collecting point for groundnuts and rice and a local market centre for millet, sorghum, rice, fish, goats and cattle.", "Take your time, and bargain with a smile."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zainab Mohammed", role: "Market trader", quotes: ["Looking for Rice, grain, fish and livestock trade? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Lawal Gambo", role: "Shopper", quotes: ["Wikipedia says Birnin Kebbi is a collecting point for groundnuts and rice and a local market centre for millet, sorghum, rice, fish, goats and cattle.", "Take your time, and bargain with a smile."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aliyu Magaji", role: "Student", quotes: ["I am on my way to a lecture at Federal University, Birnin Kebbi.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Asmau", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Zainab Umar", role: "Student", quotes: ["I am on my way to a workshop at Waziri Umaru Federal Polytechnic, Birnin Kebbi.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Lawal Kabir", role: "Instructor", quotes: ["I teach practical work here.", "Hands first, then the theory."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Aliyu Idris", role: "Site attendant", quotes: ["Welcome to Dr. Yusuf Bala Usman LIbrary Complex, Birnin Kebbi, Kebbi State. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Halima Gwarzo", role: "Local resident", quotes: ["I walk past Dr. Yusuf Bala Usman LIbrary Complex, Birnin Kebbi, Kebbi State most days.", "Visitors often stop here for photographs."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Maryam Suleiman", role: "Check-in agent", quotes: ["Please have your ticket and your ID ready.", "Boarding closes earlier than people think."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Malam Mustapha", role: "Traveller", quotes: ["I am flying out from Sir Ahmadu Bello International Airport today.", "Travelling is half waiting."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
