// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-4173,"z":-3844})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-172.85582523533412,"maxX":315.1316693858912,"minZ":-221.03582867802515,"maxZ":146.60657478174153})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"birnin-kebbi":{"lon":4.2557146572529385,"lat":12.476687344990035}})
