import { defineCitySpec } from '../spec.ts'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'birnin-kebbi',
  name: 'Birnin Kebbi',
  state: { id: 'kebbi', name: 'Kebbi', sourceName: 'Kebbi', unit: 'local government', sourceIds: ['geography'] },
  country: { id: 'nigeria', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 4.2006114,
    lat: 12.4573462,
    teaser: 'The Kebbi State capital on the Sokoto River, home of the Gwandu Emirate headquarters and a market centre for rice, millet, fish and livestock.',
    preview: ['Walk to the Central Mosque and the Haliru Abdu Stadium.', 'Visit a market and try suya or dambu nama at a local restaurant.'],
    coordinateSourceId: 'osm-selected',
    coordinateRef: { provider: 'openstreetmap', element: 'node', id: 501540938 },
  },
  population: { tier: 'city', sourceIds: ['birnin-kebbi-wiki'], note: 'The cited article gives an estimated 2007 population of 125,594 for Birnin Kebbi.' },
  localUnits: [
    { id: 'birnin-kebbi', name: 'Birnin Kebbi', sourceName: 'Birnin Kebbi', populationTier: 'city', description: 'The single selected local government holds the state capital, the federal university and polytechnic, the hospitals, the markets and every mapped venue.', sourceIds: ['geography'] },
  ],
  places: [
    {
      id: 'st-dominics-catholic-church-birnin-kebbi', name: "St. Dominic's Catholic Church Bernin Kebbi", kind: 'church', lon: 4.194948, lat: 12.451274, localUnitId: 'birnin-kebbi',
      description: "Wikidata records St. Dominic's Catholic Church in Birnin Kebbi.", sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125455571' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'first-ecwa-bishara-church-birnin-kebbi', name: '1st ecwa Bishara church', kind: 'church', lon: 4.192324, lat: 12.453793, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records the 1st ECWA Bishara Church, an evangelical church in Birnin Kebbi.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125471895' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'central-mosque-birnin-kebbi', name: 'Birnin kebbi central mosque, Kebbi State.', kind: 'mosque', lon: 4.202529, lat: 12.461817, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records the Birnin Kebbi Central Mosque in Kebbi State.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125446845' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'deelad-place-birnin-kebbi', name: 'DEELAD PLACE', kind: 'eatery', lon: 4.2087388, lat: 12.4379996, localUnitId: 'birnin-kebbi',
      description: 'A mapped fast-food outlet named DEELAD PLACE, open around the clock, shown here with suya.', sourceIds: ['osm-selected', 'suya-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11780081758 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'suya',
    },
    {
      id: 'daula-restaurant-birnin-kebbi', name: 'Daula Restaurant', kind: 'eatery', lon: 4.20606, lat: 12.449137, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records Daula Restaurant in Kebbi, shown here with dambu nama.', sourceIds: ['wikidata-selected', 'dambu-nama-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136892475' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'dambu-nama',
    },
    {
      id: 'kebbi-ministry-of-information-culture', name: 'Kebbi State Ministry of Information and Culture', kind: 'government', lon: 4.2003, lat: 12.4536, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records the Kebbi State Ministry of Information and Culture as a government agency in Birnin Kebbi.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q140379340' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'kebbi-ministry-of-environment-solid-minerals', name: 'Ministry of Environment & Solid Minerals Kebbi State', kind: 'government', lon: 4.207965, lat: 12.464976, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records the Kebbi State Ministry of Environment and Solid Minerals in Birnin Kebbi.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q122643299' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'sir-yahaya-memorial-hospital-birnin-kebbi', name: 'Sir Yahaya Memorial Hospital', kind: 'hospital', lon: 4.199941668960727, lat: 12.456327680230672, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records Sir Yahaya Memorial Hospital; Wikipedia calls it the oldest hospital in Birnin Kebbi.', sourceIds: ['wikidata-selected', 'birnin-kebbi-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q7529870' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'federal-medical-centre-birnin-kebbi', name: 'Federal Medical Centre, Birnin Kebbi', kind: 'hospital', lon: 4.188951, lat: 12.433839, localUnitId: 'birnin-kebbi',
      description: "Wikidata records the Federal Medical Centre, Birnin Kebbi, which Wikipedia lists among the city's hospitals.", sourceIds: ['wikidata-selected', 'birnin-kebbi-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q109713073' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'zauro-ambrusa-general-hospital-birnin-kebbi', name: 'Zauro Ambrusa General Hospital', kind: 'hospital', lon: 4.3127453, lat: 12.4970301, localUnitId: 'birnin-kebbi',
      description: 'A mapped hospital named Zauro Ambrusa General Hospital.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 7909118759 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'yaryara-mini-market-birnin-kebbi', name: 'Yaryara mini market', kind: 'market', lon: 4.1940351, lat: 12.4640814, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records Yaryara mini market in Kebbi State; Wikipedia describes the city as a local market centre for millet, sorghum, rice, fish, goats and cattle.', sourceIds: ['wikidata-selected', 'birnin-kebbi-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136562542' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['kebbi-grain-fish-livestock-trade'],
    },
    {
      id: 'zaget-mini-market-birnin-kebbi', name: 'zaget mini market', kind: 'market', lon: 4.2201964, lat: 12.4558419, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records zaget mini market in Kebbi State; Wikipedia describes the city as a local market centre for millet, sorghum, rice, fish, goats and cattle.', sourceIds: ['wikidata-selected', 'birnin-kebbi-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136562577' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['kebbi-grain-fish-livestock-trade'],
    },
    {
      id: 'haliru-abdu-stadium-birnin-kebbi', name: 'Haliru Abdu Stadium.', kind: 'stadium', lon: 4.1939215, lat: 12.4410712, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records Haliru Abdu Stadium as a stadium in Kebbi State.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q126199094' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'federal-university-birnin-kebbi', name: 'Federal University, Birnin Kebbi', kind: 'university', lon: 4.19524, lat: 12.434517, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records the Federal University, Birnin Kebbi as a federal university in Kebbi.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q18354916' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'lamp'] },
    },
    {
      id: 'waziri-umaru-federal-polytechnic-birnin-kebbi', name: 'Waziri Umaru Federal Polytechnic, Birnin Kebbi', kind: 'polytechnic', lon: 4.231068871130262, lat: 12.465326616020077, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records the Waziri Umaru Federal Polytechnic; Wikipedia notes a polytechnic college in the city.', sourceIds: ['wikidata-selected', 'birnin-kebbi-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q107476839' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'yusuf-bala-usman-library-birnin-kebbi', name: 'Dr. Yusuf Bala Usman LIbrary Complex, Birnin Kebbi, Kebbi State', kind: 'civic-landmark', lon: 4.221578, lat: 12.463214, localUnitId: 'birnin-kebbi',
      description: 'Wikidata records the Dr. Yusuf Bala Usman Library Complex in Birnin Kebbi.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q68653115' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'sir-ahmadu-bello-airport-birnin-kebbi', name: 'Sir Ahmadu Bello International Airport', kind: 'airport', lon: 4.3696699, lat: 12.4795261, localUnitId: 'birnin-kebbi',
      description: 'A mapped aerodrome named Sir Ahmadu Bello International Airport, which Wikipedia says serves the city.', sourceIds: ['osm-selected', 'birnin-kebbi-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 771842984 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
  ],
  identity: {
    foods: [
      { id: 'suya', name: 'Suya', description: 'Wikipedia describes suya as a traditional Hausa smoke-grilled spiced meat on skewers, seasoned with the spice mix yaji.', sourceIds: ['suya-wiki'] },
      { id: 'dambu-nama', name: 'Dambu nama', description: 'Wikipedia describes dambu nama as a West African dish of dried, shredded meat, popular in northern Nigeria and among Hausa speakers, with a candy-floss texture.', sourceIds: ['dambu-nama-wiki'] },
    ],
    crafts: [
      { id: 'hausa-weaving-dyeing-leatherwork', name: 'Weaving, dyeing and leatherwork', description: 'Wikipedia says the Hausa were famous for cloth weaving and dyeing, leather sandals and leather-working; Birnin Kebbi lies in a mostly Hausa and Fulani state.', sourceIds: ['hausa-wiki', 'kebbi-state-wiki'] },
    ],
    industries: [
      { id: 'kebbi-grain-fish-livestock-trade', name: 'Rice, grain, fish and livestock trade', description: 'Wikipedia says Birnin Kebbi is a collecting point for groundnuts and rice and a local market centre for millet, sorghum, rice, fish, goats and cattle.', sourceIds: ['birnin-kebbi-wiki'] },
      { id: 'kebbi-fishing-farming', name: 'Fishing and farming', description: 'Wikipedia says the Kebbi State economy is largely based on fishing and agriculture, mainly sorghum, groundnuts, millet, onions and rice.', sourceIds: ['kebbi-state-wiki'] },
    ],
  },
  transport: {
    airports: [{ placeId: 'sir-ahmadu-bello-airport-birnin-kebbi', status: 'operational', sourceIds: ['birnin-kebbi-wiki'] }],
    rail: [],
    ports: [],
  },
  climate: {
    profile: 'northern-savanna', rainyMonths: [5, 6, 7, 8, 9], dryMonths: [10, 11, 12, 1, 2, 3, 4],
    description: 'Kebbi State has tropical weather with a rainy season from mid-May to mid-September and a dry season of about seven months, with the harmattan wind.',
    clearLabel: 'Dry-season sky', sourceIds: ['kebbi-state-wiki'],
  },
  homePalette: { back: '#8fb0a8', left: '#4f7370', floor: ['#c9d2c3', '#7d8a6a'] },
  geometry: { surface: { path: 'scripts/geo/sources/formula/birnin-kebbi-surface.geojson', bytes: 115136, sha256: '2628a5eaeb04cfd2b68943eddf241a3e56d5dc89404bd65d86004a2c4b351dc5' } },
  sourceGroups: [
    { id: 'osm-selected', title: 'Selected OpenStreetMap records for Birnin Kebbi', url: 'https://www.openstreetmap.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'ODbL 1.0', cache: { path: 'scripts/city/research/birnin-kebbi/reviewed/osm-selected.json', bytes: 1472, sha256: '3b6195b314d6b6534871089e8662c369ac86913eb3463a605c5a531595957e3c' } },
    { id: 'wikidata-selected', title: 'Selected Wikidata entities for Birnin Kebbi', url: 'https://www.wikidata.org/wiki/Wikidata:Main_Page', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'CC0 1.0', cache: { path: 'scripts/city/research/birnin-kebbi/reviewed/wikidata-selected.json', bytes: 11015, sha256: 'bfae90ede23ae72b5395671a12234dfbc3e4ec34602d653e0f907e924eb3cdb8' } },
    { id: 'geography', title: 'Pinned Nigerian administrative geography', url: 'https://www.geoboundaries.org/', checkedOn: '2026-10-06', supports: ['geography'], licence: 'CC BY 4.0', cache: { path: 'scripts/city/research/birnin-kebbi/reviewed/geography.json', bytes: 356, sha256: 'd6d4550cd4f27fadd11423420d6da8537755b38e1097bfd28f45fa64b3862910' } },
    { id: 'birnin-kebbi-wiki', title: 'Wikipedia: Birnin Kebbi', url: 'https://en.wikipedia.org/wiki/Birnin_Kebbi', checkedOn: '2026-10-06', supports: ['population', 'identity', 'transport'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/birnin-kebbi/reviewed/birnin-kebbi-wiki.json', bytes: 706, sha256: '1df79e532b2e179bc42c611aecb9bb2526d0c40b7a67aaba346c6763e878bdd1' } },
    { id: 'kebbi-state-wiki', title: 'Wikipedia: Kebbi State', url: 'https://en.wikipedia.org/wiki/Kebbi_State', checkedOn: '2026-10-06', supports: ['climate', 'identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/birnin-kebbi/reviewed/kebbi-state-wiki.json', bytes: 610, sha256: 'e472aa409c7813101e77da541e99fac22b7093a3b209fcd3143f8b5116e4a217' } },
    { id: 'hausa-wiki', title: 'Wikipedia: Hausa people', url: 'https://en.wikipedia.org/wiki/Hausa_people', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/birnin-kebbi/reviewed/hausa-wiki.json', bytes: 306, sha256: 'f479ca3cf8c805717bc1f703d90ee7da1dcab24fc5c698022765b6976d035a43' } },
    { id: 'suya-wiki', title: 'Wikipedia: Suya', url: 'https://en.wikipedia.org/wiki/Suya', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/birnin-kebbi/reviewed/suya-wiki.json', bytes: 277, sha256: 'ff698f4bff5262056dabb7347be0cb9124e194f9727a2548e7d91028a64643bd' } },
    { id: 'dambu-nama-wiki', title: 'Wikipedia: Dambu nama', url: 'https://en.wikipedia.org/wiki/Dambu_nama', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/birnin-kebbi/reviewed/dambu-nama-wiki.json', bytes: 356, sha256: '47383619ec419af0fd0a1d0e4b43b85311e327b1292643b28c9bb2fcc5d5ff14' } },
  ],
  unmapped: [
    { kind: 'garden', note: 'No named garden with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'park', note: 'No named park with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'polling', note: 'No named polling venue with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'road-hub', note: 'No named road hub with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'salon', note: 'No named salon with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'savings', note: 'No named bank or savings venue with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
  ],
})
