// Generated by scripts/world/build-playable-africa.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "accra",
  "name": "Accra",
  "country": {
    "idISOlower": "gh",
    "name": "Ghana"
  },
  "state": {
    "idunique": "gh-starter",
    "name": "Starter district"
  },
  "timezone": "Africa/Accra",
  "centre": {
    "lon": -0.218662,
    "lat": 5.55198
  },
  "airport": {
    "id": "accra-airport",
    "name": "Accra International Airport",
    "lon": -0.17,
    "lat": 5.596388889,
    "sourceUrl": "https://www.gacl.com.gh/accra-international-airport/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and national aeronautical information sources",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-0.221662,5.54898,-0.215662,5.55498",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; Airport reference points: national aeronautical information sources",
  "bounds": [
    -0.233662,
    5.53698,
    -0.158,
    5.608389
  ],
  "coverageNote": "Starter visitor area. Real capital and airport points, clipped country land and a bounded central street/building sample. Visitor services and homes are fictional game content. Buildings use approximate box silhouettes; missing heights are estimates. Game prices remain in the shared Allworld economy."
} satisfies DestinationFacts
