// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Fatima Yakubu", role: "Park caretaker", quotes: ["I keep Veez Garden tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Kabiru Sadiq", role: "Morning walker", quotes: ["I walk through Veez Garden before work.", "Fresh air first, then the day."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ibrahim Bala", role: "Church volunteer", quotes: ["Welcome to St. Michael's Catholic Cathedral. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Amina", role: "Regular worshipper", quotes: ["I have worshipped at St. Michael's Catholic Cathedral for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Fatima Bello", role: "Mosque caretaker", quotes: ["Welcome to Niger State Secretariat Juma'at Mosque. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Kabiru Mohammed", role: "Regular worshipper", quotes: ["I have prayed at Niger State Secretariat Juma'at Mosque for a long time.", "Come in quietly, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ibrahim Tanko", role: "Cook", quotes: ["Today the pot at King's Corner holds Moi-moi.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amina Magaji", role: "Regular diner", quotes: ["I come to King's Corner for Moi-moi.", "The mapped cuisine tag for King's Corner lists moi-moi, rice, indomie, bread, eggs and tea."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Fatima Abubakar", role: "Garden keeper", quotes: ["I keep Yemisi Suswam Garden tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Malam Kabiru", role: "Evening walker", quotes: ["I come to Yemisi Suswam Garden after work to cool down.", "Fresh air first, then the day."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ibrahim Sadiq", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amina Idris", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Fatima Salihu", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Kabiru Suleiman", role: "Patient's relative", quotes: ["I am waiting with a relative at General Hospital Minna.", "Everyone here is patient, so I must be too."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ibrahim Mohammed", role: "Market trader", quotes: ["Looking for Farm produce and soap manufacturing? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Halima", role: "Shopper", quotes: ["Wikipedia lists cotton, guinea corn, maize, ginger and yam as main farm products, and names PZ Cussons for toilet soaps.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Fatima Magaji", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Kabiru Danladi", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ibrahim Umar", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amina Kabir", role: "Supporter", quotes: ["I come to Minna stadium for the football.", "Sit high up and you see the whole game."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Fatima Idris", role: "Ticket seller", quotes: ["Check the board for your departure.", "Keep your bags close in a crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Malam Lawal", role: "Traveller", quotes: ["I am waiting at Bus Park for my bus.", "Travelling is half waiting."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ibrahim Suleiman", role: "Student", quotes: ["I am on my way to a lecture at Federal University of Technology, Minna.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Amina Yakubu", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Fatima Gambo", role: "Student", quotes: ["I am on my way to a lecture at Federal University of Technology Minna, Bosso Campus.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Kabiru Bala", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ibrahim Danladi", role: "Site attendant", quotes: ["Welcome to Federal Library Minna. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Hajiya Zulai", role: "Local resident", quotes: ["I walk past Federal Library Minna most days.", "Visitors often stop here for photographs."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
