// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-1585,"z":-683})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-413.99024759860254,"maxX":107.38448646928055,"minZ":-336.6871292918762,"maxZ":274.5853628857636})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"chanchaga":{"lon":6.5395760175203685,"lat":9.606252252527375},"bosso":{"lon":6.410937536124223,"lat":9.630056028094646}})
