// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Temitope Adeyemi", role: "Park caretaker", quotes: ["I keep Nelson Mandela Freedom Park tidy, so please mind the grass.", "Evenings are the best time here."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tunde Ogunbanjo", role: "Morning walker", quotes: ["I walk through Nelson Mandela Freedom Park before work.", "Fresh air first, then the day."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Dapo Bakare", role: "Church volunteer", quotes: ["Welcome to Union Baptist Church. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Bukola", role: "Regular worshipper", quotes: ["I have worshipped at Union Baptist Church for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Temitope Lawal", role: "Church volunteer", quotes: ["Welcome to Calvary Baptist Church. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tunde Balogun", role: "Regular worshipper", quotes: ["I have worshipped at Calvary Baptist Church for a long time.", "Sit anywhere there is room, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Dapo Afolabi", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukola Oladipo", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Temitope Ogundele", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Baba Tunde", role: "Patient's relative", quotes: ["I am waiting with a relative at LAUTECH Teaching Hospital.", "Everyone here is patient, so I must be too."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Dapo Adeleke", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukola Bakare", role: "Patient's relative", quotes: ["I am waiting with a relative at Our Lady of Fatima Hospital.", "Everyone here is patient, so I must be too."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Temitope Akinola", role: "Market trader", quotes: ["Looking for Yam? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tunde Lawal", role: "Shopper", quotes: ["Wikipedia lists yams, cassava, grain and tobacco among the farm produce of the region around Osogbo.", "Take your time, and bargain with a smile."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Dapo Ojo", role: "Market trader", quotes: ["Looking for Adire tie-and-dye? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Yetunde", role: "Shopper", quotes: ["Wikipedia calls Osogbo \"Ilu Aro\", a major dyeing centre whose traditional adire industry includes raffia, stitch, starch and wax-batik resist types.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Temitope Ajayi", role: "Market trader", quotes: ["Looking for Yam? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tunde Ogundele", role: "Shopper", quotes: ["Wikipedia lists yams, cassava, grain and tobacco among the farm produce of the region around Osogbo.", "Take your time, and bargain with a smile."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Dapo Akinwale", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukola Adeleke", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Temitope Olaniyan", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Baba Olumide", role: "Supporter", quotes: ["I come to Osogbo Township Stadium for the football.", "Sit high up and you see the whole game."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Dapo Salami", role: "Student", quotes: ["I am on my way to a lecture at Fountain University.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukola Ojo", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Temitope Ogunbanjo", role: "Student", quotes: ["I am on my way to a lecture at National Open University of Nigeria.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tunde Ajayi", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Dapo Adesina", role: "Site guide", quotes: ["Welcome to Osun-Osogbo Sacred Grove. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Funmilayo", role: "Local resident", quotes: ["I walk past Osun-Osogbo Sacred Grove most days.", "Visitors often stop here for photographs."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Temitope Balogun", role: "Museum guide", quotes: ["Welcome to Susanne Wenger House. Please take your time.", "Ask me if you want to know what is on display."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Tunde Olaniyan", role: "Visitor", quotes: ["I came to Susanne Wenger House to learn something new.", "Read the labels slowly. They reward you."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Dapo Oladipo", role: "Musician", quotes: ["We play at ABEGI ANU when the evening comes.", "Stay for the second set."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Bukola Salami", role: "Regular listener", quotes: ["I come to ABEGI ANU for the music.", "The best seats go early."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
