// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-3771,"z":1371})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-93.6436115793158,"maxX":111.19938812084638,"minZ":-189.85650225823156,"maxZ":65.29639903900261})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"osogbo":{"lon":4.551837345592004,"lat":7.75429811744755},"olorunda":{"lon":4.593766346660332,"lat":7.848936084021634}})
