// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "luanda",
  "name": "Luanda",
  "country": {
    "idISOlower": "ao",
    "name": "Angola"
  },
  "state": {
    "idunique": "ao-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Luanda",
  "centre": {
    "lon": 13.232481,
    "lat": -8.83634
  },
  "airport": {
    "id": "luanda-airport",
    "name": "Quatro de Fevereiro International Airport",
    "lon": 13.2312,
    "lat": -8.85837,
    "sourceUrl": "https://ourairports.com/airports/FNLU/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=13.229481,-8.83934,13.235481,-8.83334",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    13.217481,
    -8.87037,
    13.247481,
    -8.82134
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
