// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "kampala",
  "name": "Kampala",
  "country": {
    "idISOlower": "ug",
    "name": "Uganda"
  },
  "state": {
    "idunique": "ug-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Kampala",
  "centre": {
    "lon": 32.581378,
    "lat": 0.318605
  },
  "airport": {
    "id": "kampala-airport",
    "name": "Entebbe International Airport",
    "lon": 32.443501,
    "lat": 0.042386,
    "sourceUrl": "https://ourairports.com/airports/HUEN/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=32.578378,0.315605,32.584378,0.321605",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    32.431501,
    0.030386,
    32.596378,
    0.333605
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
