// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "kampala",
  "name": "Kampala",
  "country": {
    "idISOlower": "ug",
    "name": "Uganda"
  },
  "state": {
    "idunique": "ug-starter",
    "name": "Kampala"
  },
  "timezone": "Africa/Kampala",
  "centre": {
    "lon": 32.581378,
    "lat": 0.318605
  },
  "airport": {
    "id": "kampala-airport",
    "name": "Entebbe International Airport",
    "lon": 32.443501,
    "lat": 0.042386,
    "sourceUrl": "https://ourairports.com/airports/HUEN/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://www.openstreetmap.org/copyright",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    32.42,
    0.02,
    32.66,
    0.4
  ],
  "coverageNote": "Kampala and the way south to the airport at Entebbe: a sketch of the built-up extent traced from mapped land use (not an administrative boundary), Lake Victoria as a band along its shore with the other water mapped nearby, main roads and named places mapped in OpenStreetMap. The airport coordinates are an OurAirports dataset point, not an official reference point or evidence of current operations or schedules. Visitor services and homes are fictional game content set at the real named places.",
  "names": {
    "area": "Kampala",
    "unit": "district",
    "roadHub": "Buganda Bus Park"
  }
} satisfies DestinationFacts
