// Generated by scripts/world/build-playable-africa.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "lome",
  "name": "Lomé",
  "country": {
    "idISOlower": "tg",
    "name": "Togo"
  },
  "state": {
    "idunique": "tg-starter",
    "name": "Starter district"
  },
  "timezone": "Africa/Lome",
  "centre": {
    "lon": 1.220811,
    "lat": 6.133883
  },
  "airport": {
    "id": "lome-airport",
    "name": "Aéroport International Gnassingbé Eyadema (AIGE)",
    "lon": 1.254166667,
    "lat": 6.165833333,
    "sourceUrl": "https://aim.asecna.aero/html/eAIP/FR-_15AD-2.DXXX-fr-FR.html"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and national aeronautical information sources",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=1.217811,6.130883,1.223811,6.136883",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; Airport reference points: national aeronautical information sources",
  "bounds": [
    1.205811,
    6.118883,
    1.266167,
    6.177833
  ],
  "coverageNote": "Starter visitor area. Real capital and airport points, clipped country land and a bounded central street/building sample. Visitor services and homes are fictional game content. Buildings use approximate box silhouettes; missing heights are estimates. Game prices remain in the shared Allworld economy."
} satisfies DestinationFacts
