// Generated by scripts/words/build-lists.ts from the public-domain Webster's Second International
// word list (see docs/WORDS.md). Do not edit by hand.
// Letter counts over the dictionary words of length 2..8 plus the answers.
const letters: Readonly<Record<string, number>> = {"a":74638,"b":20079,"c":31345,"d":32627,"e":97933,"f":12819,"g":23801,"h":21498,"i":63594,"j":2153,"k":12602,"l":49365,"m":25063,"n":52363,"o":53705,"p":25088,"q":1447,"r":60433,"s":86771,"t":50650,"u":34706,"v":7955,"w":11061,"x":2772,"y":16348,"z":3327}
export default letters
