// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "rabat",
  "name": "Rabat",
  "country": {
    "idISOlower": "ma",
    "name": "Morocco"
  },
  "state": {
    "idunique": "ma-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Casablanca",
  "centre": {
    "lon": -6.836408,
    "lat": 34.025307
  },
  "airport": {
    "id": "rabat-airport",
    "name": "Rabat-Salé Airport",
    "lon": -6.75152,
    "lat": 34.051498,
    "sourceUrl": "https://ourairports.com/airports/GMME/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-6.839408,34.022307,-6.833408,34.028307",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -6.851408,
    34.010307,
    -6.73952,
    34.063498
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
