// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "rabat",
  "name": "Rabat",
  "country": {
    "idISOlower": "ma",
    "name": "Morocco"
  },
  "state": {
    "idunique": "ma-starter",
    "name": "Rabat"
  },
  "timezone": "Africa/Casablanca",
  "centre": {
    "lon": -6.836408,
    "lat": 34.025307
  },
  "airport": {
    "id": "rabat-airport",
    "name": "Rabat-Salé Airport",
    "lon": -6.75152,
    "lat": 34.051498,
    "sourceUrl": "https://ourairports.com/airports/GMME/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://www.openstreetmap.org/copyright",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -6.95,
    33.93,
    -6.72,
    34.1
  ],
  "coverageNote": "Rabat and Salé from Temara to the airport: a sketch of the built-up extent traced from mapped land use (not an administrative boundary), the Atlantic as a band along the coast, the Bou Regreg and the other water mapped nearby, main roads and named places mapped in OpenStreetMap. The airport coordinates are an OurAirports dataset point, not an official reference point or evidence of current operations or schedules. Visitor services and homes are fictional game content set at the real named places.",
  "names": {
    "area": "Rabat",
    "unit": "district",
    "roadHub": "Rabat City Station"
  }
} satisfies DestinationFacts
