// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "lilongwe",
  "name": "Lilongwe",
  "country": {
    "idISOlower": "mw",
    "name": "Malawi"
  },
  "state": {
    "idunique": "mw-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Blantyre",
  "centre": {
    "lon": 33.783302,
    "lat": -13.983295
  },
  "airport": {
    "id": "lilongwe-airport",
    "name": "Kamuzu International Airport",
    "lon": 33.780998,
    "lat": -13.7894,
    "sourceUrl": "https://ourairports.com/airports/FWKI/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=33.780302,-13.986295,33.786302,-13.980295",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    33.768302,
    -13.998295,
    33.798302,
    -13.7774
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
