// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "asmara",
  "name": "Asmara",
  "country": {
    "idISOlower": "er",
    "name": "Eritrea"
  },
  "state": {
    "idunique": "er-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Asmara",
  "centre": {
    "lon": 38.933324,
    "lat": 15.333339
  },
  "airport": {
    "id": "asmara-airport",
    "name": "Asmara International Airport",
    "lon": 38.910702,
    "lat": 15.2919,
    "sourceUrl": "https://ourairports.com/airports/HHAS/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=38.930324,15.330339,38.936324,15.336339",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    38.898702,
    15.2799,
    38.948324,
    15.348339
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
