// Generated by scripts/world/build-playable-africa.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "dakar",
  "name": "Dakar",
  "country": {
    "idISOlower": "sn",
    "name": "Senegal"
  },
  "state": {
    "idunique": "sn-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Dakar",
  "centre": {
    "lon": -17.475076,
    "lat": 14.717778
  },
  "airport": {
    "id": "dakar-airport",
    "name": "AEROPORT INTL BLAISE DIAGNE - DAKAR - DIASS",
    "lon": -17.072777778,
    "lat": 14.670833333,
    "sourceUrl": "https://aim.asecna.aero/html/eAIP/FR-_13AD-2.GOBD-fr-FR.html"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and cited aeronautical information sources",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-17.478076,14.714778,-17.472076,14.720778",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; Airport reference points: cited aeronautical information sources",
  "bounds": [
    -17.490076,
    14.658833,
    -17.060778,
    14.732778
  ],
  "coverageNote": "national capital. Starter visitor area. Real city and airport points, clipped country land and a bounded central street/building sample. Visitor services and homes are fictional game content. Buildings use approximate box silhouettes; missing heights are estimates. Game prices remain in the shared Allworld economy."
} satisfies DestinationFacts
