// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":2022,"z":-1464})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-258.51399831034837,"maxX":481.9815657181998,"minZ":-327.93996378092766,"maxZ":466.9656436483788})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"bauchi":{"lon":9.904970336786223,"lat":10.239566054976436}})
