import { defineCitySpec } from '../spec.ts'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'bauchi',
  name: 'Bauchi',
  state: { id: 'bauchi', name: 'Bauchi', sourceName: 'Bauchi', unit: 'local government', sourceIds: ['geography'] },
  country: { id: 'nigeria', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 9.8410189,
    lat: 10.3168749,
    teaser: 'The Bauchi State capital on the northern edge of the Jos Plateau, seat of the Bauchi Emirate and resting place of Abubakar Tafawa Balewa.',
    preview: ["Visit the Emir's Palace and the Tafawa Balewa Mausoleum.", 'Catch a match at the Abubakar Tafawa Balewa Stadium and try suya at a local restaurant.'],
    coordinateSourceId: 'osm-selected',
    coordinateRef: { provider: 'openstreetmap', element: 'node', id: 501540900 },
  },
  population: { tier: 'city', sourceIds: ['bauchi-wiki'], note: 'The cited article gives a 2006 population of 493,810 for the Bauchi local government area.' },
  localUnits: [
    { id: 'bauchi', name: 'Bauchi', sourceName: 'Bauchi', populationTier: 'city', description: "The single selected local government holds the state capital, the emir's palace, the stadium, the universities, the markets, the hospitals and every mapped venue.", sourceIds: ['geography'] },
  ],
  places: [
    {
      id: 'st-john-catholic-church-bauchi', name: 'St. John Catholic Church', kind: 'church', lon: 9.8337778, lat: 10.318549, localUnitId: 'bauchi',
      description: 'A mapped place of worship named St. John Catholic Church.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11011672101 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'methodist-church-bauchi', name: 'Methodist Church', kind: 'church', lon: 9.8324701, lat: 10.3200621, localUnitId: 'bauchi',
      description: 'A mapped place of worship named Methodist Church.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11011672210 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'masallacin-rimi-bauchi', name: 'Masallacin Rimi', kind: 'mosque', lon: 9.7884471, lat: 10.2915048, localUnitId: 'bauchi',
      description: 'A mapped place of worship named Masallacin Rimi.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 9972498079 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'bauchi-central-mosque', name: 'Bauchi Central Mosque', kind: 'mosque', lon: 9.845391, lat: 10.310204, localUnitId: 'bauchi',
      description: "Wikidata records the Bauchi Central Mosque beside the Emir of Bauchi's palace.", sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125749403' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'alhamus-restaurant-bauchi', name: 'Alhamus', kind: 'eatery', lon: 9.7924401, lat: 10.2788724, localUnitId: 'bauchi',
      description: 'A mapped restaurant named Alhamus serving local cuisine, shown here with suya.', sourceIds: ['osm-selected', 'suya-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11016292502 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'suya',
    },
    {
      id: 'shukurah-restaurant-bauchi', name: 'SHUKURAH RESTAURANT BAUCHI', kind: 'eatery', lon: 9.831275, lat: 10.316589, localUnitId: 'bauchi',
      description: 'Wikidata records Shukurah Restaurant in Bauchi, shown here with kilishi.', sourceIds: ['wikidata-selected', 'kilishi-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136812451' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'kilishi',
    },
    {
      id: 'bauchi-state-secretariat', name: 'State Secretariat', kind: 'government', lon: 9.8263423, lat: 10.3046297, localUnitId: 'bauchi',
      description: 'A mapped government office recorded as State Secreteriate, shown here as the State Secretariat.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 10003376704 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'bauchi-government-house', name: 'Government House', kind: 'government', lon: 9.8114124, lat: 10.3069641, localUnitId: 'bauchi',
      description: 'A mapped government office named Government House.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11011049109 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'bauchi-local-government-secretariat', name: 'Local Government Secretariat', kind: 'government', lon: 9.8459799, lat: 10.3121305, localUnitId: 'bauchi',
      description: 'A mapped government office named Local Government Secretariat.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11013682839 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'general-hospital-specialist-bauchi', name: 'General Hospital (Specialist)', kind: 'hospital', lon: 9.8413021, lat: 10.3336375, localUnitId: 'bauchi',
      description: 'A mapped hospital named General Hospital (Specialist), open around the clock.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11013629235 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'atbu-teaching-hospital-bauchi', name: 'Abubakar Tafawa Balewa University Teaching Hospital', kind: 'hospital', lon: 9.83088, lat: 10.32429, localUnitId: 'bauchi',
      description: 'Wikidata records the Abubakar Tafawa Balewa University Teaching Hospital in Bauchi.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q105485721' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'muda-lawal-market-bauchi', name: 'Muda lawal market', kind: 'market', lon: 9.841, lat: 10.3307, localUnitId: 'bauchi',
      description: 'Wikidata records Muda Lawal market in Bauchi; Wikipedia describes the city as a trade centre for groundnuts, cotton, grains and livestock.', sourceIds: ['wikidata-selected', 'bauchi-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q108546626' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['bauchi-groundnut-cotton-trade'],
    },
    {
      id: 'yelwa-market-bauchi', name: 'Yelwa market', kind: 'market', lon: 9.795404, lat: 10.272967, localUnitId: 'bauchi',
      description: 'Wikidata records Yelwa market in Bauchi; Wikipedia describes the city as a trade centre for groundnuts, cotton, grains and livestock.', sourceIds: ['wikidata-selected', 'bauchi-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q108547230' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['bauchi-groundnut-cotton-trade'],
    },
    {
      id: 'unity-park-bauchi', name: 'Unity Park', kind: 'park', lon: 9.8308821, lat: 10.3162139, localUnitId: 'bauchi',
      description: 'A mapped park named Unity Park.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11011672585 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['tree', 'bench'] },
    },
    {
      id: 'yankari-motor-park-bauchi', name: 'Yankari Motor park', kind: 'road-hub', lon: 9.8441618, lat: 10.3079133, localUnitId: 'bauchi',
      description: 'A mapped bus station named Yankari Motor park.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11013682842 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'mobil-car-station-bauchi', name: 'Mobil Car station', kind: 'road-hub', lon: 9.8215429, lat: 10.3209257, localUnitId: 'bauchi',
      description: 'A mapped bus station named Mobil Car station.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 7260806785 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'gtb-bauchi', name: 'GTB', kind: 'savings', lon: 9.8327957, lat: 10.3138448, localUnitId: 'bauchi',
      description: 'A mapped bank named GTB.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 10003376693 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'first-bank-bauchi', name: 'First Bank', kind: 'savings', lon: 9.8225201, lat: 10.3061497, localUnitId: 'bauchi',
      description: 'A mapped bank named First Bank.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 10003376701 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'atbu-stadium-bauchi', name: 'Abubakar Tafawa Balewa Stadium', kind: 'stadium', lon: 9.83527778, lat: 10.31944444, localUnitId: 'bauchi',
      description: 'Wikidata records the football stadium in Bauchi named for Abubakar Tafawa Balewa.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q335700' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'atbu-yelwa-campus-bauchi', name: 'ATBU Yelwa Campus', kind: 'university', lon: 9.7948111, lat: 10.2783566, localUnitId: 'bauchi',
      description: 'A mapped university named A.T.B.U Yelwa Campus; Wikipedia says Abubakar Tafawa Balewa University is in the town.', sourceIds: ['osm-selected', 'bauchi-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11010221446 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'lamp'] },
    },
    {
      id: 'bauchi-state-university-bauchi', name: 'Bauchi State University, Bauchi Campus', kind: 'university', lon: 9.8256244, lat: 10.313457, localUnitId: 'bauchi',
      description: 'A mapped university named Bauchi State University, Bauchi Campus.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11011106708 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'lamp'] },
    },
    {
      id: 'federal-polytechnic-bauchi', name: 'Federal Polytechnic, Bauchi', kind: 'polytechnic', lon: 9.768, lat: 10.257, localUnitId: 'bauchi',
      description: 'Wikidata records the Federal Polytechnic, Bauchi; Wikipedia says a Federal Polytechnic is in the town.', sourceIds: ['wikidata-selected', 'bauchi-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q18207057' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'emirs-palace-bauchi', name: "Emir's Palace", kind: 'heritage', lon: 9.8464981, lat: 10.3099226, localUnitId: 'bauchi',
      description: "A mapped historic castle named Emir's Palace; Wikipedia describes Bauchi as the seat of the traditional Bauchi Emirate.", sourceIds: ['osm-selected', 'bauchi-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11013682840 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'tafawa-balewa-mausoleum-bauchi', name: 'Abubakar Tafawa Balewa Mausoleum, Bauchi', kind: 'heritage', lon: 9.846187, lat: 10.318725, localUnitId: 'bauchi',
      description: 'Wikidata records the Abubakar Tafawa Balewa Mausoleum; Wikipedia says Tafawa Balewa is buried in the city.', sourceIds: ['wikidata-selected', 'bauchi-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q109476806' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'shadawanka-rock-painting-bauchi', name: 'Shadawanka Rock Painting', kind: 'heritage', lon: 9.8238333333333, lat: 10.300805555556, localUnitId: 'bauchi',
      description: 'Wikidata records the Shadawanka Rock Painting as a national monument of Nigeria in Bauchi.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q26235318' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
  ],
  identity: {
    foods: [
      { id: 'suya', name: 'Suya', description: 'Wikipedia describes suya as a traditional Hausa smoke-grilled spiced meat on skewers, seasoned with the spice mix yaji.', sourceIds: ['suya-wiki'] },
      { id: 'kilishi', name: 'Kilishi', description: 'Wikipedia describes kilishi as a Hausaland jerky of dried, spiced meat such as beef or lamb, seasoned, smoked and sun-dried.', sourceIds: ['kilishi-wiki'] },
    ],
    crafts: [
      { id: 'bauchi-weaving-dyeing-tanning-blacksmithing', name: 'Cotton weaving, dyeing, tanning and blacksmithing', description: 'Wikipedia lists cotton weaving and dyeing, tanning and blacksmithing as traditional activities in Bauchi.', sourceIds: ['bauchi-wiki'] },
    ],
    industries: [
      { id: 'bauchi-groundnut-cotton-trade', name: 'Groundnut, cotton, grain and livestock trade', description: 'Wikipedia says that after the railway arrived in 1961 Bauchi grew as a collecting point for groundnuts and cotton and as a trade centre in sorghum, millet, cowpeas, maize, cassava, vegetables and livestock.', sourceIds: ['bauchi-wiki'] },
    ],
  },
  transport: {
    airports: [],
    rail: [],
    ports: [],
  },
  climate: {
    profile: 'northern-savanna', rainyMonths: [5, 6, 7, 8, 9], dryMonths: [11, 12, 1, 2, 3],
    description: 'Bauchi has a tropical savanna climate (Aw) with a hot dry season and an overcast wet season; the harmattan usually appears in December and January.',
    clearLabel: 'Dry-season sky', sourceIds: ['bauchi-wiki', 'climate-nigeria-wiki'], harmattan: { months: [12, 1], label: 'Harmattan haze' },
  },
  homePalette: { back: '#a89a4e', left: '#6a6030', floor: ['#d8cf9a', '#7a7a52'] },
  geometry: { surface: { path: 'scripts/geo/sources/formula/bauchi-surface.geojson', bytes: 317427, sha256: '3142bf1863f8872031b6e1db292419b02a1d066fbb9f3416e1e6131e47ee7580' } },
  sourceGroups: [
    { id: 'osm-selected', title: 'Selected OpenStreetMap records for Bauchi', url: 'https://www.openstreetmap.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'ODbL 1.0', cache: { path: 'scripts/city/research/bauchi/reviewed/osm-selected.json', bytes: 3879, sha256: '6f3c049af5a40f24215dbce244de6ebece193cac4e34263a445297ac77c612b7' } },
    { id: 'wikidata-selected', title: 'Selected Wikidata entities for Bauchi', url: 'https://www.wikidata.org/wiki/Wikidata:Main_Page', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'CC0 1.0', cache: { path: 'scripts/city/research/bauchi/reviewed/wikidata-selected.json', bytes: 7375, sha256: '84afaf802b805705c34c7cd43bb80e867efcd4dfd1bfea8bd7089c02f61a99d5' } },
    { id: 'geography', title: 'Pinned Nigerian administrative geography', url: 'https://www.geoboundaries.org/', checkedOn: '2026-10-06', supports: ['geography'], licence: 'CC BY 4.0', cache: { path: 'scripts/city/research/bauchi/reviewed/geography.json', bytes: 346, sha256: 'b5bd1fe218d219c00a87db2988faecc69d30c9a73ffec1fd4872f0f1c6b788ae' } },
    { id: 'bauchi-wiki', title: 'Wikipedia: Bauchi (city)', url: 'https://en.wikipedia.org/wiki/Bauchi_(city)', checkedOn: '2026-10-06', supports: ['population', 'climate', 'identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/bauchi/reviewed/bauchi-wiki.json', bytes: 1084, sha256: '9608840f77dac2e60a9b1b8d215be9b1d342c4d6071d600438d42236e6ff5f37' } },
    { id: 'climate-nigeria-wiki', title: 'Wikipedia: Climate of Nigeria', url: 'https://en.wikipedia.org/wiki/Climate_of_Nigeria', checkedOn: '2026-10-06', supports: ['climate'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/bauchi/reviewed/climate-nigeria-wiki.json', bytes: 277, sha256: '09369377504d8b707c5a71181917109995704e17e0238006f5307b3d6253bba4' } },
    { id: 'suya-wiki', title: 'Wikipedia: Suya', url: 'https://en.wikipedia.org/wiki/Suya', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/bauchi/reviewed/suya-wiki.json', bytes: 277, sha256: 'ff698f4bff5262056dabb7347be0cb9124e194f9727a2548e7d91028a64643bd' } },
    { id: 'kilishi-wiki', title: 'Wikipedia: Kilishi', url: 'https://en.wikipedia.org/wiki/Kilishi', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/bauchi/reviewed/kilishi-wiki.json', bytes: 320, sha256: 'dea34f670c3f12b5527a66d5099665c517538f678af58e93b3cc43ef4d2e1b72' } },
  ],
  unmapped: [
    { kind: 'garden', note: 'No named garden with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'polling', note: 'No named polling venue with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'salon', note: 'No named salon with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
  ],
})
