// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaContent } from '../formula/content.ts'
import { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'
import { CITY_SCENES } from './scenes.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_CONTENT = buildFormulaContent({
  spec: CITY_SPEC,
  origin: CITY_MAP_ORIGIN,
  bounds: CITY_PLAY_BOUNDS,
  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,
  scenes: CITY_SCENES,
  people: [
    { name: "Abike Salami", role: "Groundsman", quotes: ["I mark the lines before every match.", "A good pitch is quiet work."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Ojo", role: "Supporter", quotes: ["I come to Akure Sports Stadium for the football.", "Sit high up and you see the whole game."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Ogunbanjo", role: "Church volunteer", quotes: ["Welcome to St. David's Cathedral. Please come in quietly.", "I help to keep the place ready for each service."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Folake", role: "Regular worshipper", quotes: ["I have worshipped at St. David's Cathedral for a long time.", "Sit anywhere there is room, and be welcome."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Adesina", role: "Mosque caretaker", quotes: ["Welcome to Akure Central Mosque. Please take off your shoes at the door.", "I keep the place clean for prayer."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Akinwale", role: "Regular worshipper", quotes: ["I have prayed at Akure Central Mosque for a long time.", "Come in quietly, and be welcome."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Balogun", role: "Cook", quotes: ["Today the pot at Chicken Republic holds Grilled pepper chicken.", "Sit down and eat first. Questions can wait."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Olaniyan", role: "Regular diner", quotes: ["I come to Chicken Republic for Grilled pepper chicken.", "Wikivoyage names grilled pepper chicken among the dishes served by Akure restaurants and eateries."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Oladipo", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Baba Adebayo", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Adeyemi", role: "Clerk", quotes: ["Notices go on the board by the door.", "Bring your papers in order and everything is easier."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Ogunbanjo", role: "Visitor", quotes: ["I am here about some paperwork.", "The queue moves faster if you stay calm."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Bakare", role: "Nurse", quotes: ["Please take a seat and we will call you.", "Drink water, and ask if you are unsure where to go."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Adesina", role: "Patient's relative", quotes: ["I am waiting with a relative at First Mercy Specialist Hospital.", "Everyone here is patient, so I must be too."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Lawal", role: "Market trader", quotes: ["Looking for Cocoa, yam and cassava? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Bukola", role: "Shopper", quotes: ["Wikipedia calls Akure the trading avenue of a farming region growing cocoa, yam, cassava, maize and tobacco.", "Take your time, and bargain with a smile."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Afolabi", role: "Market trader", quotes: ["Looking for Cocoa, yam and cassava? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Oladipo", role: "Shopper", quotes: ["Wikipedia calls Akure the trading avenue of a farming region growing cocoa, yam, cassava, maize and tobacco.", "Take your time, and bargain with a smile."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Ogundele", role: "Market trader", quotes: ["Looking for Cocoa, yam and cassava? You are in the right place.", "Come early. Bargaining is easier before the crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Adeyemi", role: "Shopper", quotes: ["Wikipedia calls Akure the trading avenue of a farming region growing cocoa, yam, cassava, maize and tobacco.", "Take your time, and bargain with a smile."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Adeleke", role: "Bank teller", quotes: ["Please fill the form in block letters.", "Count your money before you leave the counter."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Baba Tunde", role: "Customer", quotes: ["I am here to save a little this week.", "Small savings add up."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Akinola", role: "Ticket seller", quotes: ["Check the board for your departure.", "Keep your bags close in a crowd."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Folake Lawal", role: "Traveller", quotes: ["I am waiting at Ondo State Bus Terminal for my bus.", "Travelling is half waiting."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Ojo", role: "Site guide", quotes: ["Welcome to Holy Mary Statue. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Afolabi", role: "Local resident", quotes: ["I walk past Holy Mary Statue most days.", "Visitors often stop here for photographs."], age: "young", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Ayodele Ajayi", role: "Site attendant", quotes: ["Welcome to Ondo State Library. Please take your time.", "Ask me if you want to know about this place."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Mama Yetunde", role: "Local resident", quotes: ["I walk past Ondo State Library most days.", "Visitors often stop here for photographs."], age: "elder", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Abike Akinwale", role: "Student", quotes: ["I am on my way to a lecture at Federal University of Technology Akure.", "If you are lost, ask at the gate."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
    { name: "Adebayo Adeleke", role: "Lecturer", quotes: ["I teach here, and I still enjoy a good question.", "Read slowly and ask early."], age: "adult", note: "Generated regular. The name is drawn from a reviewed regional pool." },
  ],
})
