// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-3083,"z":1943})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-207.23693654384897,"maxX":327.44125076481987,"minZ":-230.84717648000083,"maxZ":208.83952021879304})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"akure-south":{"lon":5.213933164032578,"lat":7.187464160942549},"akure-north":{"lon":5.317884816766807,"lat":7.265133061410427},"ifedore":{"lon":5.114156879631629,"lat":7.357340423679186}})
