// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-1061,"z":3903})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-180.31689555418575,"maxX":152.75914997528798,"minZ":-88.36403891462669,"maxZ":255.64485099722333})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"owerri-municipal":{"lon":7.006132867418689,"lat":5.474479104727021},"owerri-north":{"lon":7.095212019074777,"lat":5.448112935976343},"owerri-west":{"lon":6.94955153487438,"lat":5.466438397268389}})
