// Generated by scripts/city/build-city.ts. Do not edit by hand.
import type { CityModule } from '../../../types/content.ts'
import { CITY_RULES } from './rules.ts'
import { CITY_SPEC } from './spec.ts'

export const city = Object.freeze({
  id: CITY_SPEC.id,
  rules: CITY_RULES,
  loadContent: async () => (await import('./content.ts')).CITY_CONTENT,
  loadMap: async () => (await import('#city-map/owerri')).CITY_MAP,
} satisfies CityModule<typeof CITY_SPEC.id>)
