import { defineCitySpec } from '../spec.ts'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'owerri',
  name: 'Owerri',
  state: { id: 'imo', name: 'Imo', sourceName: 'Imo', unit: 'local government', sourceIds: ['geography'] },
  country: { id: 'nigeria', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 7.0341973,
    lat: 5.489736,
    teaser: 'The Imo capital of Ofe Owerri soup, Mbari art and a stadium in the Igbo heartland.',
    preview: ['Try Ofe Owerri and visit the National Museum.', 'Cross Owerri Municipal, North and West by road.'],
    coordinateSourceId: 'osm-selected',
    coordinateRef: { provider: 'openstreetmap', element: 'node', id: 2469246094 },
  },
  population: { tier: 'major-city', sourceIds: ['owerri-wiki'], note: 'The cited article reports an estimated 1,401,873 residents in 2016 across the three Owerri local governments.' },
  localUnits: [
    { id: 'owerri-municipal', name: 'Owerri Municipal', sourceName: 'Owerri Municipal', populationTier: 'city', description: 'The selected central local government contains the cathedral, stadium, assembly, museum and most mapped venues.', sourceIds: ['geography'] },
    { id: 'owerri-north', name: 'Owerri North', sourceName: 'Owerri North', populationTier: 'city', description: 'The selected northern local government contains Imo State University, Emekuku and the Nkwo Emeke market.', sourceIds: ['geography'] },
    { id: 'owerri-west', name: 'Owerri West', sourceName: 'Owerri West', populationTier: 'city', description: "The selected western local government contains the Federal University of Technology, the polytechnic at Nekede and St John's Anglican Church.", sourceIds: ['geography'] },
  ],
  places: [
    {
      id: 'assumpta-maria-cathedral', name: 'Assumpta Maria Cathedral', kind: 'church', lon: 7.021, lat: 5.4885691, localUnitId: 'owerri-municipal',
      description: 'A mapped cathedral named Assumpta Maria Cathedral.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 406231918 }, accuracy: 'feature-centroid',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'holy-trinity-world-bank-owerri', name: 'Holy Trinity World Bank, Owerri', kind: 'church', lon: 7.0003363, lat: 5.4855463, localUnitId: 'owerri-municipal',
      description: 'A mapped Catholic place of worship named Holy Trinity World Bank, Owerri.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 7340335729 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'st-johns-anglican-owerri', name: "Saint John's Anglican Church", kind: 'church', lon: 7.0119983, lat: 5.4030248, localUnitId: 'owerri-west',
      description: "A mapped Anglican church named saint John's Anglican Church in Owerri West.", sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1557632349 }, accuracy: 'feature-centroid',
      scene: { roof: 'gable', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'imo-state-central-mosque', name: 'imo State Central Mosque', kind: 'mosque', lon: 7.030246, lat: 5.496231, localUnitId: 'owerri-municipal',
      description: 'Wikidata records the Imo State Central Mosque as a mosque in the Shell Camp area.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125458579' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'owerri-central-mosque', name: 'owerri Central Mosque', kind: 'mosque', lon: 7.027273, lat: 5.498808, localUnitId: 'owerri-municipal',
      description: 'Wikidata records the Owerri Central Mosque as a central mosque in Owerri.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q125458708' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'mr-biggs-owerri', name: 'Mr.Biggs', kind: 'eatery', lon: 7.0169546, lat: 5.4847702, localUnitId: 'owerri-municipal',
      description: 'A mapped fast-food outlet named Mr.Biggs, shown here with Ofe Owerri.', sourceIds: ['osm-selected', 'ofe-owerri'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 4029444747 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'ofe-owerri',
    },
    {
      id: 'josephs-pot-owerri', name: "Joseph's pot owerri", kind: 'eatery', lon: 7.039885, lat: 5.494852, localUnitId: 'owerri-municipal',
      description: "Wikidata records Joseph's pot owerri as a restaurant and eatery in Owerri, shown here with Ofe Owerri.", sourceIds: ['wikidata-selected', 'ofe-owerri'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q136813520' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'ofe-owerri',
    },
    {
      id: 'imo-state-university', name: 'Imo State University', kind: 'university', lon: 7.0444515, lat: 5.505306, localUnitId: 'owerri-north',
      description: 'A mapped university named Imo State University, which Wikipedia lists among Owerri tertiary institutions.', sourceIds: ['osm-selected', 'owerri-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 797998350 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'lamp'] },
    },
    {
      id: 'futo-owerri', name: 'Federal University of Technology Owerri', kind: 'university', lon: 6.985959853968703, lat: 5.3938730846074545, localUnitId: 'owerri-west',
      description: 'Wikipedia lists the Federal University of Technology Owerri among Owerri tertiary institutions.', sourceIds: ['wikidata-selected', 'owerri-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q5440485' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'lamp'] },
    },
    {
      id: 'federal-polytechnic-nekede', name: 'Federal Polytechnic, Nekede', kind: 'polytechnic', lon: 7.029125681391086, lat: 5.431931910880564, localUnitId: 'owerri-west',
      description: 'Wikipedia lists the Federal Polytechnic, Nekede among Owerri tertiary institutions.', sourceIds: ['wikidata-selected', 'owerri-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q24590304' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'national-museum-owerri', name: 'National Museum Owerri', kind: 'museum', lon: 7.0251503, lat: 5.5032967, localUnitId: 'owerri-municipal',
      description: 'Wikidata records the National Museum Owerri as a museum in Imo State.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q111983775' }, accuracy: 'published-point',
      scene: { roof: 'gable', sign: 'facade', props: ['tree'], landmark: 'tower' },
    },
    {
      id: 'akachi-monument', name: 'Akachi Monument', kind: 'civic-landmark', lon: 7.0413991, lat: 5.4685807, localUnitId: 'owerri-municipal',
      description: 'A mapped monument named Akachi Monument.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 626684268 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'statue-of-freed-slave-owerri', name: 'Statue of a freed slave in Owerri', kind: 'civic-landmark', lon: 7.026181, lat: 5.490956, localUnitId: 'owerri-municipal',
      description: 'Wikidata records the Statue of a freed slave in Owerri as a statue.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q110826353' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'ikenegbu-hospital', name: 'IKenegbu HOSPITAL', kind: 'hospital', lon: 7.037526, lat: 5.5021654, localUnitId: 'owerri-municipal',
      description: 'A mapped hospital named IKenegbu HOSPITAL.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1334821796 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'holy-rosary-hospital-emekuku', name: 'Holy Rosary Hospital, Emekuku', kind: 'hospital', lon: 7.110741, lat: 5.4703928, localUnitId: 'owerri-north',
      description: 'A mapped hospital named Holy Rosary Hospital, Emekuku.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1027211373 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'imo-state-house-of-assembly', name: 'Imo State House of Assembly', kind: 'government', lon: 7.0142069, lat: 5.4749875, localUnitId: 'owerri-municipal',
      description: 'A mapped government office named Imo State House of Assembly.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 406582225 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'imo-trade-investment-centre', name: 'Imo Trade & Investment Centre', kind: 'government', lon: 7.0082391, lat: 5.4655574, localUnitId: 'owerri-municipal',
      description: 'A mapped government office named Imo Trade & Investment Centre.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 626506388 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'], landmark: 'gate' },
    },
    {
      id: 'world-bank-market-owerri', name: 'World Bank Market', kind: 'market', lon: 7.0015138, lat: 5.4821288, localUnitId: 'owerri-municipal',
      description: "A mapped marketplace named World Bank Market; Wikipedia lists yams, cassava, taro and corn among Owerri's produce.", sourceIds: ['osm-selected', 'owerri-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 7340335730 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['owerri-farm-produce'],
    },
    {
      id: 'nkwo-emeke-market', name: 'Nkwo Emeke', kind: 'market', lon: 7.123771, lat: 5.4763066, localUnitId: 'owerri-north',
      description: 'A mapped marketplace named Nkwo Emeke in Owerri North.', sourceIds: ['osm-selected', 'owerri-wiki'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1027214141 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['owerri-farm-produce'],
    },
    {
      id: 'uloma-food-market', name: 'Uloma Food Market', kind: 'market', lon: 7.044781979133888, lat: 5.491574276102519, localUnitId: 'owerri-municipal',
      description: 'Wikidata records Uloma Food Market as a market in Imo State.', sourceIds: ['wikidata-selected', 'owerri-wiki'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q123384843' }, accuracy: 'published-point',
      scene: { roof: 'hipped', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['owerri-farm-produce'],
    },
    {
      id: 'zenith-bank-owerri', name: 'Zenith', kind: 'savings', lon: 7.032301, lat: 5.492387, localUnitId: 'owerri-municipal',
      description: 'A mapped bank building named Zenith.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 459242483 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'fcmb-owerri', name: 'FCMB', kind: 'savings', lon: 7.0391915, lat: 5.4869205, localUnitId: 'owerri-municipal',
      description: 'A mapped bank branch named FCMB.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 13442626445 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'duke-and-duchess-owerri', name: 'Duke and Duchess', kind: 'salon', lon: 7.0548831, lat: 5.490811, localUnitId: 'owerri-municipal',
      description: 'A mapped hairdresser named Duke and Duchess.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 12469070062 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] },
    },
    {
      id: 'dan-anyiam-stadium', name: 'Dan Anyiam Stadium', kind: 'stadium', lon: 7.0438158, lat: 5.4837162, localUnitId: 'owerri-municipal',
      description: 'A mapped stadium named Dan Anyiam Stadium.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 970190637 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'], landmark: 'tower' },
    },
    {
      id: 'love-garden-imsu', name: 'Love Garden, IMSU', kind: 'garden', lon: 7.0439286, lat: 5.505973, localUnitId: 'owerri-north',
      description: 'A mapped park named Love Garden, IMSU.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 791153418 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['tree', 'bench'] },
    },
    {
      id: 'imo-golf-amusement-center', name: 'Imo Golf and Amusement Center', kind: 'park', lon: 7.046749, lat: 5.515623, localUnitId: 'owerri-north',
      description: 'Wikidata records the Imo Golf and Amusement Center as a park in Owerri.', sourceIds: ['wikidata-selected'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q126164925' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'roadside', props: ['tree', 'bench'] },
    },
  ],
  identity: {
    foods: [
      { id: 'ofe-owerri', name: 'Ofe Owerri', description: 'Ofe Owerri is an Igbo soup popular in Owerri, made with snails, meat and fish, and nicknamed the Jewel of the South East.', sourceIds: ['ofe-owerri', 'owerri-wiki'] },
    ],
    crafts: [
      { id: 'mbari-clay-art', name: 'Mbari clay sculpture', description: 'Mbari houses are an Owerri-Igbo art form holding life-sized painted figures sculpted in anthill clay.', sourceIds: ['mbari'] },
    ],
    industries: [
      { id: 'owerri-farm-produce', name: 'Rain-forest farm produce', description: 'Wikipedia says Owerri sits in the rain forest and produces yams, cassava, taro, corn, rubber and palm products.', sourceIds: ['owerri-wiki'] },
      { id: 'owerri-oil-gas', name: 'Oil and gas reserves', description: 'Wikipedia says Owerri sits on large crude oil and natural gas reserves.', sourceIds: ['owerri-wiki'] },
    ],
  },
  transport: {
    airports: [],
    rail: [],
    ports: [],
  },
  climate: {
    profile: 'southern-wet-dry', rainyMonths: [4, 5, 6, 7, 8, 9, 10], dryMonths: [12, 1, 2],
    description: 'Owerri has a tropical wet climate with rain for most of the year, a rainy season from April to October and a brief dry season with a harmattan that is less pronounced than elsewhere in Nigeria.',
    clearLabel: 'Dry-season sky', sourceIds: ['owerri-wiki', 'imo-wiki'], harmattan: { months: [12, 1, 2], label: 'Harmattan haze' },
  },
  homePalette: { back: '#b98d5a', left: '#7a5a3a', floor: ['#c9aa72', '#5f804f'] },
  geometry: { surface: { path: 'scripts/geo/sources/formula/owerri-surface.geojson', bytes: 323069, sha256: 'd124ac10fcabaf5409e4314810bb7b39592959d99521c29a21445d458e76bccb' } },
  sourceGroups: [
    { id: 'osm-selected', title: 'Selected OpenStreetMap records for Owerri', url: 'https://www.openstreetmap.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'ODbL 1.0', cache: { path: 'scripts/city/research/owerri/reviewed/osm-selected.json', bytes: 5069, sha256: 'dfa819cc48497d1403aeb993f268a90407537e514a530bb32d53c75653e89974' } },
    { id: 'wikidata-selected', title: 'Selected Wikidata entities for Owerri', url: 'https://www.wikidata.org/wiki/Wikidata:Main_Page', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'CC0 1.0', cache: { path: 'scripts/city/research/owerri/reviewed/wikidata-selected.json', bytes: 5925, sha256: 'e439a14790722b5667d07caff7cd417ffff97b2f763c5bf02b2962486b6137d2' } },
    { id: 'geography', title: 'Pinned Nigerian administrative geography', url: 'https://www.geoboundaries.org/', checkedOn: '2026-10-06', supports: ['geography'], licence: 'CC BY 4.0', cache: { path: 'scripts/city/research/owerri/reviewed/geography.json', bytes: 458, sha256: '4a53817e12dcf5b6632da7faae921f7845ce77c237331bd2e3038a4cdc2cc1aa' } },
    { id: 'owerri-wiki', title: 'Wikipedia: Owerri', url: 'https://en.wikipedia.org/wiki/Owerri', checkedOn: '2026-10-06', supports: ['population', 'climate', 'identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/owerri/reviewed/owerri-wiki.json', bytes: 874, sha256: '3b780e83fd0ab62bfc0ffc17cd2c14f23e2b18d559a15751d1acb2d1da9ead60' } },
    { id: 'imo-wiki', title: 'Wikipedia: Imo State', url: 'https://en.wikipedia.org/wiki/Imo_State', checkedOn: '2026-10-06', supports: ['climate'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/owerri/reviewed/imo-wiki.json', bytes: 286, sha256: '6c8a24eb25a0347262bc4a19e180fdec01b2de3aa62fd8f1fc94b8ad2edb617f' } },
    { id: 'ofe-owerri', title: 'Wikipedia: Ofe Owerri', url: 'https://en.wikipedia.org/wiki/Ofe_Owerri', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/owerri/reviewed/ofe-owerri.json', bytes: 307, sha256: 'fa3229534e5c7ea81a236f82882e862cf0c5a013e7f7b4ac930b32cf55633731' } },
    { id: 'mbari', title: 'Wikipedia: Mbari (art)', url: 'https://en.wikipedia.org/wiki/Mbari_(art)', checkedOn: '2026-10-06', supports: ['identity'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/owerri/reviewed/mbari.json', bytes: 271, sha256: '8ff3b0e610a98a94dce1ec351d1b446ba5b0afcbdff51dd5273d0670238d5868' } },
  ],
  unmapped: [
    { kind: 'polling', note: 'No named polling venue with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
    { kind: 'road-hub', note: 'No named bus station, motor park or terminal with an exact OSM element or Wikidata P625 record was found in the selected LGAs on 2026-10-06.' },
  ],
})
