import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { GLYPHS } from '../src/ui/phone/icons-source.ts';
import { glyphJson, packGlyphText } from './glyph-packing.ts';

const args = process.argv.slice(2);
if (args.some(arg => arg !== '--check')) throw new Error('Usage: npm run icons:build -- [--check]');
if (!Object.values(GLYPHS).every(value => typeof value === 'string')) throw new Error('Glyph artwork must contain SVG strings');
const packed = packGlyphText(glyphJson(GLYPHS));
const output = '/** Generated by npm run icons:build. Edit icons-source.ts, not this file. */\n'
  + 'export const GLYPH_CODES = ' + packed.count + ';\n'
  + 'export const GLYPH_DATA = ' + JSON.stringify(packed.data) + ';\n';
const path = fileURLToPath(new URL('../src/ui/phone/icons-packed.ts', import.meta.url));
if (args.includes('--check')) {
  if (readFileSync(path, 'utf8') !== output) throw new Error('Glyph data is stale: run npm run icons:build');
} else writeFileSync(path, output);
console.log(Object.keys(GLYPHS).length + ' exact glyphs, ' + Buffer.byteLength(output) + ' generated bytes' + (args.includes('--check') ? '; regeneration matches' : ''));
