import { PORT_HARCOURT_SCENES } from './scenes.ts'
import {
  activity, buildCityContent, hospitalSpots, PORT_HARCOURT_LOCAL_MODES, PORT_HARCOURT_LOCAL_UNIT_DESCRIPTIONS,
  riversPeople, spot, work, type CityVenueSeed,
} from './descriptions.ts'
import { PORT_HARCOURT_MAP_ORIGIN, PORT_HARCOURT_PLAY_BOUNDS } from './rules.ts'

const points = {
  park:{lon:7.0115139,lat:4.8375095}, boro:{lon:7.0054726,lat:4.788293}, mile1:{lon:6.9979166,lat:4.7925234},
  mile3:{lon:6.992341,lat:4.804663}, oilmill:{lon:7.0653907,lat:4.8577216}, station:{lon:7.0164659,lat:4.7650949},
  wharf:{lon:7.0077827,lat:4.7693656}, rsu:{lon:6.9807492,lat:4.7969856}, uniport:{lon:6.9158749,lat:4.8940715},
  iaue:{lon:6.9309744,lat:4.8041686}, gowon:{lon:7.0219237,lat:4.8249177}, adokiye:{lon:6.9714235,lat:4.9675311},
  amusement:{lon:6.9981336,lat:4.8281193}, beach:{lon:7.0122039,lat:4.759365}, bonny:{lon:7.0247212,lat:4.7576372},
  okrika:{lon:7.0823282,lat:4.7471189}, okrikaTown:{lon:7.0848772,lat:4.7415886}, transAmadi:{lon:7.0412027,lat:4.8201471}, refinery:{lon:7.107784,lat:4.7605332}, alesa:{lon:7.1171908,lat:4.7855961},
  airport:{lon:6.9518013,lat:5.0165409}, government:{lon:7.0167428,lat:4.7765377}, rumuola:{lon:6.9982413,lat:4.8340294},
}

const venues: readonly CityVenueSeed[] = [
  {id:'pleasure-park',name:'Port Harcourt Pleasure Park',district:'Rumuomasi, Obio/Akpor',kind:'park',category:'fun',icon:'park',point:points.park,description:'Walk, relax and play ayo in the public park.',ambient:['Families spread out beside the water and lawns.'],spots:[spot('lawn','Park lawn',activity('ph-play-ayo','Play a round of ayo','tables',['fun'],{duration:7})),work()]},
  {id:'rumuola-hub',name:'Rumuola Interchange',district:'Rumuola, Obio/Akpor',kind:'hub',category:'civic',icon:'bus',point:points.rumuola,description:'Catch road transport from the Rumuola interchange area.',ambient:['Buses turn between Aba Road and neighbourhood routes.'],spots:[spot('platform','Road platform',activity('ph-rumuola-wait','Wait for road transport','bus',['travel'],{duration:4}))],beta:true,note:'Fictional boarding platform at an OSM road reference; no private motor-park identity is claimed.'},
  {id:'rumuola-savings',name:'Rumuola Savings Hall',district:'Rumuola, Obio/Akpor',kind:'office',category:'work',icon:'office',point:points.rumuola,description:'Learn everyday banking and work a finance shift.',ambient:['Neighbours ask about deposits and account records.'],spots:[spot('counter','Service counter',activity('ph-banking-learn','Learn about banking','book',['learn'],{xp:{hustle:7}})),work()],beta:true,note:'Fictional banking workplace at the mapped Rumuola road area.'},
  {id:'isaac-boro-park',name:'Isaac Boro Park',district:'Old GRA, Port Harcourt',kind:'park',category:'fun',icon:'park',point:points.boro,description:'Walk through the civic park and learn its place in the city.',ambient:['Office workers cross the park between appointments.'],spots:[spot('walk','Park walk',activity('ph-boro-walk','Walk through Isaac Boro Park','walk',['walk','history'],{xp:{fitness:8}})),work()]},
  {id:'mile-one-market',name:'New Mile One Market',district:'Diobu, Port Harcourt',kind:'market',category:'work',icon:'market',point:points.mile1,description:'Price produce, cloth and household goods in Diobu.',ambient:['Market calls carry into the surrounding streets.'],spots:[spot('aisle','Market aisle',activity('ph-mile-one-price','Price the market','groceries',['market'],{xp:{hustle:8}})),work()]},
  {id:'mile-three-market',name:'Mile Three Market',district:'Nkpolu-Oroworukwo, Port Harcourt',kind:'market',category:'work',icon:'market',point:points.mile3,description:'Browse food, timber and spare-parts rows at Mile Three.',ambient:['Porters and traders move quickly between the rows.'],spots:[spot('aisle','Market aisle',activity('ph-mile-three-price','Compare market prices','groceries',['market'],{xp:{hustle:8}})),work()],note:'Published Nkpolu-Oroworukwo locality reference; not a surveyed market gate.'},
  {id:'oil-mill-market',name:'Oil Mill Market',district:'Eleme Junction, Obio/Akpor',kind:'market',category:'food',icon:'market',point:points.oilmill,description:'Visit the busy market at Eleme Junction.',ambient:['The market expands around the junction.'],spots:[spot('aisle','Market aisle',activity('ph-oil-mill-price','Price the market','groceries',['market'],{xp:{hustle:8}})),work()]},
  {id:'railway-township',name:'Old Township and Railway Station',district:'Old Township, Port Harcourt',kind:'walk',category:'fun',icon:'train',point:points.station,description:'Walk the old township route and visit the railway terminus.',ambient:['Station Road points back to the city’s early transport history.'],spots:[spot('station','Station frontage',activity('ph-rail-history','Learn the railway story','book',['history','learn']))],},
  {id:'wharf',name:'Old Wharf Road Walk',district:'Old Township, Port Harcourt',kind:'walk',category:'fun',icon:'water',point:points.wharf,description:'Walk the historic wharf road and learn about the port.',ambient:['The waterfront opens beyond the old township streets.'],spots:[spot('view','Wharf Road view',activity('ph-wharf-learn','Learn about the port','book',['history','learn']))],note:'Road reference near the historic wharf, not a surveyed berth entrance.'},
  {id:'rsu',name:'Rivers State University',district:'Nkpolu-Oroworukwo, Port Harcourt',kind:'office',category:'work',icon:'school',point:points.rsu,description:'Join a university project workshop.',ambient:['Students compare notes outside the project rooms.'],spots:[spot('lab','Project lab',activity('ph-rsu-project','Join a project workshop','code',['learn'],{xp:{coding:10}})),work()]},
  {id:'uniport',name:'University of Port Harcourt',district:'Choba, Obio/Akpor',kind:'office',category:'work',icon:'school',point:points.uniport,description:'Visit the Choba campus and join a research session.',ambient:['Campus buses and students fill the East–West Road approach.'],spots:[spot('lab','Research room',activity('ph-uniport-research','Join a research session','book',['learn'],{xp:{coding:8}})),work()]},
  {id:'iaue',name:'Ignatius Ajuru University of Education',district:'Rumuolumeni, Obio/Akpor',kind:'office',category:'work',icon:'school',point:points.iaue,description:'Join a teaching and media workshop.',ambient:['Teacher training and student productions share the campus day.'],spots:[spot('class','Teaching studio',activity('ph-iaue-teach','Join a teaching workshop','book',['learn'],{xp:{charisma:10}})),work()]},
  {id:'yakubu-gowon-stadium',name:'Yakubu Gowon Stadium',district:'Elekahia, Port Harcourt',kind:'viewing',category:'fun',icon:'ball',point:points.gowon,description:'Train and watch a match at the former Liberation Stadium.',ambient:['Supporters gather beside the main stand.'],spots:[spot('stand','Main stand',activity('ph-gowon-match','Watch the match','ball',['sport'],{effects:{fun:12,social:5}})),work()]},
  {id:'adokiye-stadium',name:'Adokiye Amiesimaka Stadium',district:'Igwuruta, Ikwerre',kind:'viewing',category:'fun',icon:'ball',point:points.adokiye,description:'Visit the large stadium on the airport approach.',ambient:['The broad stadium complex sits beyond the dense urban core.'],spots:[spot('stand','Main stand',activity('ph-adokiye-match','Watch a stadium event','ball',['sport'],{effects:{fun:10,social:4}})),work()]},
  {id:'garden-city-amusement',name:'Garden City Amusement Park',district:'Birabi Street, Port Harcourt metropolis',kind:'park',category:'fun',icon:'park',point:points.amusement,description:'Visit the family amusement park on Birabi Street.',ambient:['Rides and children’s games fill the compact park.'],spots:[spot('rides','Ride area',activity('ph-amusement-rides','Try the amusement rides','star',['fun'],{cost:1000,effects:{fun:14}}))],note:'Official Birabi Street identity; map point is the OSM road reference, not a surveyed gate.'},
  {id:'tourist-beach',name:'Port Harcourt Tourist Beach',district:'Old Township, Port Harcourt',kind:'beach',category:'fun',icon:'water',point:points.beach,description:'Walk the waterfront and learn about its boat-regatta history.',ambient:['The creek edge sits beside the old township.'],spots:[spot('shore','Waterfront',activity('ph-beach-walk','Walk by the water','walk',['nature','walk'],{effects:{fun:9}}))]},
  {id:'bonny-jetty',name:'Bonny/Nembe Waterside Terminal',district:'Creek Road, Port Harcourt',kind:'hub',category:'civic',icon:'boat',point:points.bonny,description:'Take the beta boat trip to Okrika.',ambient:['Passengers wait beside working waterfront traffic.'],spots:[spot('landing','Ferry landing',activity('ph-jetty-wait','Wait at the landing','boat',['travel'],{duration:4}))]},
  {id:'okrika-jetty',name:'Okrika Town Landing',district:'Okrika, Okrika',kind:'hub',category:'civic',icon:'boat',point:points.okrika,description:'Take the beta boat trip to Port Harcourt’s waterside.',ambient:['Small craft move between Okrika and the city waterfront.'],spots:[spot('landing','Town landing',activity('ph-okrika-wait','Wait at the landing','boat',['travel'],{duration:4}))]},
  {id:'trans-amadi',name:'Trans-Amadi Industrial Walk',district:'Trans-Amadi, Obio/Akpor',kind:'office',category:'work',icon:'factory',point:points.transAmadi,description:'Learn how the industrial layout fits into the working city.',ambient:['Workshops, warehouses and offices line the layout roads.'],spots:[spot('route','Industry route',activity('ph-industry-learn','Walk the industry route','walk',['learn'])),work()]},
  {id:'refinery',name:'Port Harcourt Refinery Viewpoint',district:'Eleme–Okrika refinery corridor',kind:'refinery',category:'civic',icon:'factory',point:points.refinery,description:'Explore a game interpretation of the industrial landmark.',ambient:['The complex marks the eastern industrial corridor.'],spots:[spot('view','Civic viewpoint',activity('ph-refinery-learn','Learn about the industrial corridor','book',['learn']))],beta:true,note:'Mapped complex spans the Eleme–Okrika boundary; its address is Alesa-Eleme. No operational access or real public viewpoint is implied.'},
  {id:'airport',name:'Port Harcourt International Airport',district:'Omagwa, Ikwerre',kind:'airport',category:'civic',icon:'plane',point:points.airport,description:'Use the airport terminal at Omagwa.',ambient:['Announcements carry across the terminal.'],spots:[spot('terminal','Terminal',activity('ph-airport-wait','Wait in the terminal','plane',['travel'],{duration:4}))]},
  {id:'government-house',name:'Rivers State Government House Area',district:'Old GRA, Port Harcourt',kind:'statehouse',category:'civic',icon:'governor',point:points.government,description:'Read civic notices and attend a public information session.',ambient:['Visitors approach through the Old GRA streets.'],spots:[spot('office','Public information',activity('ph-civic-session','Attend a civic information session','people',['civic'])),work()]},
  {id:'ph-clinic',name:'Garden City Community Clinic',district:'Rumuomasi, Obio/Akpor',kind:'hospital',category:'care',icon:'health',point:points.park,description:'Get a check-up or use the free clinic.',ambient:['The clinic team calls the next patient.'],spots:hospitalSpots(),beta:true,note:'Fictional gameplay clinic at the verified Pleasure Park locality.'},
  {id:'diobu-church',name:'Diobu Community Church',district:'Diobu, Port Harcourt',kind:'worship',category:'care',icon:'worship',point:points.mile1,description:'Visit a community church respectfully.',ambient:['People arrive from the market streets.'],variant:'church',spots:[spot('hall','Church hall',activity('ph-church-reflect','Sit quietly in the church','worship',['worship']))],beta:true,note:'Fictional worship venue at the verified Mile One locality.'},
  {id:'diobu-mosque',name:'Diobu Community Mosque',district:'Diobu, Port Harcourt',kind:'worship',category:'care',icon:'worship',point:points.mile3,description:'Visit a community mosque respectfully around prayer time.',ambient:['People arrive from nearby streets.'],variant:'mosque',spots:[spot('hall','Prayer hall',activity('ph-mosque-reflect','Sit quietly in the mosque','worship',['worship']))],beta:true,note:'Fictional worship venue at the verified Mile Three locality.'},
  {id:'ph-polling',name:'Garden City Civic Polling Centre',district:'Old GRA, Port Harcourt',kind:'polling',category:'civic',icon:'poll',point:points.government,description:'Register, vote and follow the local count.',ambient:['Officials check the register.'],spots:[spot('officials','Election officials',activity('ph-voter-info','Read voter information','poll',['civic']))],beta:true,note:'Fictional election setup at the mapped Government House locality.'},
  {id:'bole-kitchen',name:'Waterfront Bole Kitchen',district:'Old Township, Port Harcourt',kind:'buka',category:'food',icon:'food',point:points.beach,description:'Eat roasted plantain with fish and pepper sauce.',ambient:['Plantain roasts while pepper sauce is spooned over fish.'],spots:[spot('counter','Food counter',activity('ph-bole-fish','Eat bole and fish','food',['food'],{cost:1400,effects:{hunger:36,fun:6}})),work()],beta:true,note:'Fictional food counter at the verified tourist-beach point.'},
  {id:'garden-city-salon',name:'Garden City Salon',district:'Diobu, Port Harcourt',kind:'salon',category:'care',icon:'hair',point:points.mile1,description:'Get a trim or braid and catch up on neighbourhood news.',ambient:['The clippers and radio share the room.'],spots:[spot('chair','Styling chair',activity('ph-hair','Get a fresh style','hair',['care'],{cost:1800,effects:{hygiene:8,fun:4}})),work()],beta:true,note:'Fictional salon at the verified Mile One market point.'},
  {id:'garden-city-evening',name:'Garden City Evening Garden',district:'Old GRA, Port Harcourt',kind:'park',category:'nightlife',icon:'music',point:points.boro,description:'Listen to an evening live set in a relaxed garden.',ambient:['Friends gather as the live set begins.'],spots:[spot('stage','Garden stage',activity('ph-evening-set','Listen to the evening set','music',['music','nightlife'],{hours:{open:18,close:23},xp:{music:8}})),work()],beta:true,note:'Fictional nightlife garden at the verified Isaac Boro Park locality.'},
]

const names=['Tamuno Briggs','Ibiwari George','Tamunomiebi Kalio','Kio Tamuno','Nengi Amachree','Tonye Douglas','Sotonye Cookey','Ibiso Jack','Barineka Nwinee','Ledum Kpaka','Ebiere Asawo','Dumo Bob','Chisom Nwankwo','Adaeze Okafor','Preye Diri','Ebitimi Alaowei','Tammy Fiberesima','Fubara Georgewill','Kurotimi Abam','Nimi Brown','Seinye Amakiri','Tekena Wariboko','Mfon Akpan','Iniobong Etim','Amina Bello','Sani Musa','Boma Horsfall','Ipalibo Wokoma','Kelechi Amadi','Ngozi Eze','Simi Adeyemi','Kunle Balogun','Sokari Davies','Tamunotonye Alabo','Deinma Kalio','Ibiye Aguma','Nneka Worlu','Chinedu Opara','Eno Essien','Uduak James','Yemi Ogunleye','Tola Akinyemi','Omasirichi Nwogu','Kio Briggs','Fyneface Gogo','Legborsi Saro','Tamunoemiari Green','Bariyaa Kpea','Blessing Iwowari','Perekiye Fubara','Atonye Lawson','Erefa Dokubo','Sira George','Obum Nwafor','Tamunokuro Abbey','Bariere Nwinee','Miebaka Inko','Nkechi Ogbonda']
const voices: Readonly<Record<string, readonly [string, string, string, string]>> = {
  'pleasure-park':['park volunteer','There is room to slow down here. Come see the lawn.','ayo player','One more round? I can teach you the opening move.'],
  'rumuola-hub':['route helper','The Aba Road turn is busy. Tell me which direction you need.','commuter','I pass through Rumuola on my way across town.'],
  'rumuola-savings':['banking trainee','I am learning how to keep careful account records.','savings customer','I stopped in to ask how to plan for a bigger goal.'],
  'isaac-boro-park':['park walker','This park is a good pause between Old GRA streets.','local history reader','I come here to read about the city and its people.'],
  'mile-one-market':['produce trader','Look around first; the food rows change through the day.','market porter','I know the quickest way through these Diobu aisles.'],
  'mile-three-market':['household trader','You can compare prices across more than one row.','market shopper','I always bring a list and still find something extra.'],
  'oil-mill-market':['market trader','The junction brings customers from every direction.','food shopper','Come early if you want to take your time here.'],
  'railway-township':['township walker','Station Road tells a piece of Port Harcourt history.','rail enthusiast','I like seeing where the old railway meets the city.'],
  wharf:['waterfront walker','Wharf Road leads toward the old port story.','local history reader','The township grew around work on land and water.'],
  rsu:['student mentor','Our project group meets after class. Join us.','campus learner','I am trying out an idea in the lab today.'],
  uniport:['research student','Choba keeps us busy with questions worth asking.','campus visitor','The East–West Road approach is easy to remember.'],
  iaue:['teaching student','Come see how we practise a lesson together.','media learner','We are recording another short campus project.'],
  'yakubu-gowon-stadium':['training partner','There is always space for another training partner.','match supporter','I still call this place Liberation Stadium sometimes.'],
  'adokiye-stadium':['stadium runner','The long walk around this complex is a workout.','football supporter','I came out from Igwuruta to watch the match.'],
  'garden-city-amusement':['family visitor','The little ones picked the first ride already.','games fan','I would start with the games before the rides.'],
  'tourist-beach':['waterfront walker','Take a moment by the creek and look toward the boats.','regatta storyteller','I enjoy hearing stories of boats on this waterfront.'],
  'bonny-jetty':['landing helper','This mainland terminal has a route toward Okrika.','boat passenger','I wait here when I need to cross toward Okrika.'],
  'okrika-jetty':['landing helper','This pier is the Okrika end of the boat trip.','boat passenger','I like seeing the city shoreline from the water.'],
  'trans-amadi':['workshop apprentice','The layout has room for many kinds of work.','industrial planner','I study how these streets connect workshops and offices.'],
  refinery:['corridor guide','We can learn about the complex from this public viewpoint.','engineering student','I am mapping the eastern industrial corridor.'],
  airport:['terminal traveller','Omagwa is my starting point when I fly to Lagos.','travel helper','I can point you toward the terminal information.'],
  'government-house':['civic visitor','The public information desk has today’s notices.','community organiser','I follow the decisions that affect our neighbourhood.'],
  'ph-clinic':['clinic volunteer','The free clinic queue is open when you need it.','neighbour','I came for a check-up and stayed to help someone find the ward.'],
  'diobu-church':['church volunteer','You are welcome to sit quietly in the hall.','neighbour','The market is close, so I stop here on my way home.'],
  'diobu-mosque':['mosque volunteer','You are welcome to ask about visiting respectfully.','neighbour','I come in from the nearby Diobu streets.'],
  'ph-polling':['voter information helper','I can show you where to read the voter information.','local voter','It helps to know the process before polling day.'],
  'bole-kitchen':['bole cook','The plantain is roasting; fish and pepper sauce come next.','food regular','Bole and fish always brings me back to the waterfront.'],
  'garden-city-salon':['stylist','Take a seat and tell me how you want your hair.','salon regular','I came for a trim and stayed for the radio.'],
  'garden-city-evening':['music host','The live set starts when the garden lights come on.','music regular','I like hearing new songs here after a long day.'],
}
const careers={'community-helper':'pleasure-park',tech:'rsu',banking:'rumuola-savings',music:'garden-city-evening',trading:'mile-one-market',nursing:'ph-clinic',hair:'garden-city-salon',chef:'bole-kitchen',dj:'garden-city-evening',fitness:'yakubu-gowon-stadium',creator:'tourist-beach',teaching:'iaue',event:'isaac-boro-park',football:'adokiye-stadium',retail:'oil-mill-market'}

const base=buildCityContent({scenes:PORT_HARCOURT_SCENES,cityId:'port-harcourt',cityName:'Port Harcourt',origin:PORT_HARCOURT_MAP_ORIGIN,bounds:PORT_HARCOURT_PLAY_BOUNDS,localUnitDescriptions:PORT_HARCOURT_LOCAL_UNIT_DESCRIPTIONS,venues,people:riversPeople(venues,names,voices),careerVenues:careers,careerSummaries:{'community-helper':'Help visitors and residents at the Pleasure Park community desk.'},houses:[
  {id:'ph-diobu-room',label:'Single room',districtId:'diobu',district:'Diobu',rent:3200,grid:6,point:points.mile1},
  {id:'ph-rumuola-flat',label:'Self-contain',districtId:'rumuola',district:'Rumuola',rent:7500,grid:8,point:points.park},
  {id:'ph-eleme-flat',label:'One-bedroom flat',districtId:'eleme',district:'Alesa-Eleme',rent:12000,grid:9,point:points.alesa},
  {id:'ph-okrika-room',label:'Town room',districtId:'okrika',district:'Okrika',rent:4000,grid:7,point:points.okrikaTown},
  {id:'ph-omagwa-flat',label:'Airport-road flat',districtId:'omagwa',district:'Omagwa',rent:9500,grid:9,point:points.airport},
  {id:'ph-oyigbo-house',label:'Two-bedroom house',districtId:'oyigbo',district:'Oyigbo',rent:20000,grid:10,point:{lon:7.1334475,lat:4.8814078}},
  {id:'ph-etche-house',label:'Two-bedroom house',districtId:'etche',district:'Etche',rent:17000,grid:10,point:{lon:7.0926388,lat:5.0765321}},
],events:[
  {id:'ph-carniriv',title:'Carniriv — beta game edition',blurb:'A simulated carnival programme of music, costume and city performance; it is not an official future schedule.',venue:'isaac-boro-park',icon:'star',when:{start:'2027-12-14',end:'2027-12-18',from:14,to:22},spray:true},
  {id:'ph-boat-regatta',title:'Boat regatta — beta game edition',blurb:'A simulated waterfront regatta programme at the tourist beach.',venue:'tourist-beach',icon:'star',when:{weekday:6,from:13,to:18},spray:true},
],firstFun:{venue:'pleasure-park',spot:'lawn',activity:'ph-play-ayo',title:'Play ayo in the park',hint:'Pleasure Park · takes 7 seconds'},buka:'bole-kitchen',thingsToDo:[
  {venueId:'pleasure-park',name:'Pleasure Park',line:'Walk, relax and play ayo.'},{venueId:'tourist-beach',name:'Tourist Beach',line:'Walk the waterfront and learn its regatta history.'},{venueId:'bonny-jetty',name:'Bonny/Nembe Waterside',line:'Take the beta boat trip to Okrika.'},{venueId:'mile-one-market',name:'Mile One Market',line:'Price produce, cloth and household goods.'},{venueId:'yakubu-gowon-stadium',name:'Yakubu Gowon Stadium',line:'Watch a match at the former Liberation Stadium.'},{venueId:'trans-amadi',name:'Trans-Amadi',line:'Learn how the industrial layout fits the city.'},
],culture:{greeting:'How far?',food:['bole and fish','native soup','roasted plantain with pepper sauce'],knownFor:['the Garden City','Pidgin heard around waterfronts and markets','Ikwerre, Okrika, Kalabari, Ogoni and many other communities']},localModes:PORT_HARCOURT_LOCAL_MODES,radioVenueIds:['garden-city-evening'],billboardRoads:[{id:'ph-bb-aba',near:'pleasure-park',road:'Aba Road'},{id:'ph-bb-ikwerre',near:'airport',road:'Ikwerre Road'},{id:'ph-bb-east-west',near:'uniport',road:'East–West Road'}],tablePlaces:[{id:'ph-garden-whot',venueId:'garden-city-evening',game:'whot',label:'Garden table',seats:4},{id:'ph-stadium-penalty',venueId:'yakubu-gowon-stadium',game:'penalty',label:'Stadium penalty spot',seats:2}],dreamWording:{'lekki-landlord':{label:'Garden City Landlord',goal:'Build a net worth of ₦1,000,000.',measure:'Your cash plus what you have bought, minus loan debt, counts toward ₦1,000,000.'},'afrobeats-star':{label:'Carnival Headliner',goal:'Reach Music level 10.',measure:'Your Music level, including partial levels, counts toward level 10.'},'yaba-unicorn':{label:'Waterfront Builder'}},lotteryWording:{}})

export const PORT_HARCOURT_CONTENT = Object.freeze({
  ...base,
  localRoutes: Object.freeze([{a:'bonny-jetty',b:'okrika-jetty',mode:'boat' as const,fare:800,seconds:40,beta:true as const}]),
})
