// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "monrovia",
  "name": "Monrovia",
  "country": {
    "idISOlower": "lr",
    "name": "Liberia"
  },
  "state": {
    "idunique": "lr-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Monrovia",
  "centre": {
    "lon": -10.79966,
    "lat": 6.314582
  },
  "airport": {
    "id": "monrovia-airport",
    "name": "Spriggs Payne Airport",
    "lon": -10.7587,
    "lat": 6.28906,
    "sourceUrl": "https://ourairports.com/airports/GLMR/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-10.80266,6.311582,-10.79666,6.317582",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -10.81466,
    6.27706,
    -10.7467,
    6.329582
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
