// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "windhoek",
  "name": "Windhoek",
  "country": {
    "idISOlower": "na",
    "name": "Namibia"
  },
  "state": {
    "idunique": "na-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Windhoek",
  "centre": {
    "lon": 17.083546,
    "lat": -22.570006
  },
  "airport": {
    "id": "windhoek-airport",
    "name": "Eros Airport",
    "lon": 17.079002,
    "lat": -22.60492,
    "sourceUrl": "https://ourairports.com/airports/FYWE/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=17.080546,-22.573006,17.086546,-22.567006",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    17.067002,
    -22.61692,
    17.098546,
    -22.555006
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
