// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "mbabane",
  "name": "Mbabane",
  "country": {
    "idISOlower": "sz",
    "name": "eSwatini"
  },
  "state": {
    "idunique": "sz-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Mbabane",
  "centre": {
    "lon": 31.133335,
    "lat": -26.316651
  },
  "airport": {
    "id": "mbabane-airport",
    "name": "King Mswati III International Airport",
    "lon": 31.716944,
    "lat": -26.358611,
    "sourceUrl": "https://ourairports.com/airports/FDSK/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=31.130335,-26.319651,31.136335,-26.313651",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    31.118335,
    -26.370611,
    31.728944,
    -26.301651
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
