// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "tunis",
  "name": "Tunis",
  "country": {
    "idISOlower": "tn",
    "name": "Tunisia"
  },
  "state": {
    "idunique": "tn-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Tunis",
  "centre": {
    "lon": 10.179678,
    "lat": 36.802778
  },
  "airport": {
    "id": "tunis-airport",
    "name": "Tunis Carthage International Airport",
    "lon": 10.2272,
    "lat": 36.851002,
    "sourceUrl": "https://ourairports.com/airports/DTTA/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=10.176678,36.799778,10.182678,36.805778",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    10.164678,
    36.787778,
    10.2392,
    36.863002
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
