// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "bujumbura",
  "name": "Bujumbura",
  "country": {
    "idISOlower": "bi",
    "name": "Burundi"
  },
  "state": {
    "idunique": "bi-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Bujumbura",
  "centre": {
    "lon": 29.360006,
    "lat": -3.376087
  },
  "airport": {
    "id": "bujumbura-airport",
    "name": "Bujumbura Melchior Ndadaye International Airport",
    "lon": 29.318501,
    "lat": -3.32402,
    "sourceUrl": "https://ourairports.com/airports/HBBA/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=29.357006,-3.379087,29.363006,-3.373087",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    29.306501,
    -3.391087,
    29.375006,
    -3.31202
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
