// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":5656,"z":-3151})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-145.66039968458335,"maxX":167.3483335516621,"minZ":-395.29421132163907,"maxZ":154.7945222984631})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"maiduguri":{"lon":13.124958945232564,"lat":11.836504429873338},"jere":{"lon":13.165934607557741,"lat":11.949477735746022}})
