// Generated by scripts/city/build-city.ts. Do not edit by hand.
import { buildFormulaRules } from '../formula/rules.ts'
import { CITY_MAP_ORIGIN } from './geography.ts'
import { CITY_SPEC } from './spec.ts'

export const CITY_RULES = buildFormulaRules(CITY_SPEC, CITY_MAP_ORIGIN)
