// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":970,"z":-1038})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-208.6024454377108,"maxX":119.05642848474076,"minZ":-103.52936084793032,"maxZ":357.88752321042125})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"jos-north":{"lon":8.905713184754456,"lat":9.938539036128374},"jos-south":{"lon":8.832968140469605,"lat":9.758750992683023}})
