import { defineCitySpec } from '../spec.ts'

export const CITY_SPEC = defineCitySpec({
  schemaVersion: 1,
  id: 'jos',
  name: 'Jos',
  state: { id: 'plateau', name: 'Plateau', sourceName: 'Plateau', unit: 'local government', sourceIds: ['geography'] },
  country: { id: 'nigeria', name: 'Nigeria' },
  timezone: 'Africa/Lagos',
  atlas: {
    lon: 8.8833333333333,
    lat: 9.9333333333333,
    teaser: 'Tin-mining heritage, Nok terracotta and a cool plateau trading city.',
    preview: ['Visit Jos Main Market and the Jos Museum.', 'Cross the city through Jos North and Jos South.'],
    coordinateSourceId: 'wikidata-selected',
    coordinateRef: { provider: 'wikidata', entity: 'Q321079' },
  },
  population: { tier: 'city', sourceIds: ['wikipedia-jos'], note: 'Wikipedia gives about 900,000 residents based on the 2006 census.' },
  localUnits: [
    { id: 'jos-north', name: 'Jos North', sourceName: 'Jos North', populationTier: 'city', description: 'The selected central local government contains the Jos Museum, the main market, the university and the teaching hospital.', sourceIds: ['geography'] },
    { id: 'jos-south', name: 'Jos South', sourceName: 'Jos South', populationTier: 'city', description: 'The selected southern local government contains the cereal and oil mill, the electoral commission office and the salon.', sourceIds: ['geography'] },
  ],
  places: [
    {
      id: 'jos-museum', name: 'Jos Museum', kind: 'museum', lon: 8.886564, lat: 9.9137199, localUnitId: 'jos-north',
      description: 'A mapped museum; Wikipedia says it was founded in 1952 and its Pottery Hall holds Nok terracotta heads and artefacts.', sourceIds: ['osm-selected', 'wikipedia-jos'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 1874729487 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['tree', 'bench'] },
    },
    {
      id: 'kyan-rikkos-village-head-palace', name: 'Village Head palace Kyan Rikkos', kind: 'heritage', lon: 8.9087457, lat: 9.9009499, localUnitId: 'jos-north',
      description: 'A mapped historic castle-type building tagged Village Head palace Kyan Rikkos in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 9772786125 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'roadside', props: ['tree'], landmark: 'gate' },
    },
    {
      id: 'rwang-pam-township-stadium', name: 'Rwang Pam Township Stadium', kind: 'stadium', lon: 8.8840016, lat: 9.9276234, localUnitId: 'jos-north',
      description: 'A mapped stadium named Rwang Pam Township Stadium in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 170165592 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'] },
    },
    {
      id: 'university-of-jos', name: 'University of Jos', kind: 'university', lon: 8.8818511, lat: 9.9717593, localUnitId: 'jos-north',
      description: 'A mapped university named University of Jos in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 180132760 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['tree'] },
    },
    {
      id: 'baptist-college-of-theology', name: 'Baptist College of Theology', kind: 'college', lon: 8.9449136, lat: 9.9073329, localUnitId: 'jos-north',
      description: 'A mapped college named Baptist College of Theology in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11109304623 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['planter'] },
    },
    {
      id: 'juth', name: 'Jos University Teaching Hospital', kind: 'hospital', lon: 8.9607561, lat: 9.9079707, localUnitId: 'jos-north',
      description: 'A mapped hospital tagged JUTH in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 195584079 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter', 'lamp'] },
    },
    {
      id: 'bingham-university-teaching-hospitals', name: 'Bingham University Teaching Hospitals', kind: 'hospital', lon: 8.8776825, lat: 9.9307653, localUnitId: 'jos-north',
      description: 'A mapped hospital named Bingham university teaching hospitals in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 9768958434 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'jos-main-market', name: 'Jos Main Market', kind: 'market', lon: 8.8931926, lat: 9.9203105, localUnitId: 'jos-north',
      description: 'A Wikidata point for Jos Main Market; Wikipedia names the Jos Main market (terminus) among the markets of Jos North and calls Jos the trading hub of Plateau State.', sourceIds: ['wikidata-selected', 'wikipedia-jos'],
      coordinateSourceId: 'wikidata-selected', coordinateRef: { provider: 'wikidata', entity: 'Q25053192' }, accuracy: 'published-point',
      scene: { roof: 'flat', sign: 'roadside', props: ['stall'] }, specialtyIds: ['jos-trade-hub'],
    },
    {
      id: 'angwan-rukuba-park', name: 'Angwan Rukuba Park', kind: 'market', lon: 8.9099534, lat: 9.9332034, localUnitId: 'jos-north',
      description: 'A mapped marketplace named Angwan Rukuba Park in Jos North; Wikipedia names the Rukuba Road satellite market in Jos North, and the name match is an inference.', sourceIds: ['osm-selected', 'wikipedia-jos'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 221862569 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['stall', 'lamp'] }, specialtyIds: ['jos-trade-hub'],
    },
    {
      id: 'kasuwan-mata', name: 'Kasuwan Mata', kind: 'market', lon: 8.9123024, lat: 9.9126116, localUnitId: 'jos-north',
      description: 'A mapped marketplace named Kasuwan Mata in Jos North.', sourceIds: ['osm-selected', 'wikipedia-jos'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11351391976 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'roadside', props: ['stall'] }, specialtyIds: ['jos-trade-hub'],
    },
    {
      id: 'terminus-motor-park', name: 'Terminus Motor Park', kind: 'road-hub', lon: 8.893104, lat: 9.9192829, localUnitId: 'jos-north',
      description: 'A mapped bus station and public-transport station named Terminus Motor Park in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 12574391840 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['bench', 'lamp'] },
    },
    {
      id: 'angwan-rukuba-polling-station', name: 'Angwan Rukuba Market polling station', kind: 'polling', lon: 8.9092849, lat: 9.9334541, localUnitId: 'jos-north',
      description: 'A mapped polling station tagged Angwan Rukuba Market in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 11581549038 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'] },
    },
    {
      id: 'gotul-peace-park', name: 'Dr. T. K. Gotul Peace Park', kind: 'park', lon: 8.8790261, lat: 9.966284, localUnitId: 'jos-north',
      description: 'A mapped park named Dr. T. K. Gotul Peace Park in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 9768938614 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'roadside', props: ['tree', 'bench'] },
    },
    {
      id: 'sculpture-garden', name: 'Sculpture Garden', kind: 'garden', lon: 8.8804641, lat: 9.9645831, localUnitId: 'jos-north',
      description: 'A mapped garden named Sculpture Garden in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1122593187 }, accuracy: 'feature-centroid',
      scene: { roof: 'hipped', sign: 'roadside', props: ['tree', 'planter'] },
    },
    {
      id: 'duke-and-duchess-executive-salon', name: 'Duke and Duchess Executive Salon', kind: 'salon', lon: 8.904045, lat: 9.8651395, localUnitId: 'jos-south',
      description: 'A mapped hairdresser named Duke and Duchess Executive Salon in Jos South.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 5379475954 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] },
    },
    {
      id: 'de-bills-food', name: "De Bill's Food", kind: 'eatery', lon: 8.8878188, lat: 9.9250944, localUnitId: 'jos-north',
      description: "A mapped restaurant whose cuisine tag says only regional; the featured dish is a Plateau State staple from the NICO cuisine list, not a menu item confirmed for this restaurant.", sourceIds: ['osm-selected', 'nico-plateau-cuisine'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1165600008 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['planter'] }, featuredIdentityId: 'plateau-acha',
    },
    {
      id: 'jos-central-mosque', name: 'Muslim Mosque', kind: 'mosque', lon: 8.8890892, lat: 9.9601145, localUnitId: 'jos-north',
      description: 'A mapped Muslim place of worship tagged Muslim Mosque in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 1905592970 }, accuracy: 'mapped-feature',
      scene: { roof: 'hipped', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'christ-methodist-cathedral', name: 'Christ Methodist cathedral', kind: 'church', lon: 8.88563, lat: 9.9258594, localUnitId: 'jos-north',
      description: 'A mapped Christian place of worship named Christ Methodist cathedral in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 9769150545 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['tree'] },
    },
    {
      id: 'st-lukes-anglican-church', name: "St Luke's Anglican church", kind: 'church', lon: 8.888205, lat: 9.9208835, localUnitId: 'jos-north',
      description: "A mapped Christian place of worship named St Luke's Anglican church in Jos North.", sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 9769286660 }, accuracy: 'mapped-feature',
      scene: { roof: 'gable', sign: 'facade', props: ['bench'] },
    },
    {
      id: 'inec-headquarters-jos', name: 'INEC headquarters', kind: 'government', lon: 8.8661912, lat: 9.8624095, localUnitId: 'jos-south',
      description: 'A mapped government office building tagged INEC headquarters in Jos South.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 1178004100 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'first-bank-jos', name: 'First Bank', kind: 'savings', lon: 8.8621072, lat: 9.9576006, localUnitId: 'jos-north',
      description: 'A mapped bank tagged First Bank in Jos North.', sourceIds: ['osm-selected'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'node', id: 1874626123 }, accuracy: 'mapped-feature',
      scene: { roof: 'flat', sign: 'facade', props: ['lamp'] },
    },
    {
      id: 'grand-cereals-and-oil-mills', name: 'Grand Cereals and Oil Mills Limited', kind: 'industry', lon: 8.8541511, lat: 9.7594243, localUnitId: 'jos-south',
      description: 'A mapped industrial land use named Grand Cereals and Oil Mills Limited; Wikipedia names it among the industries of Jos South.', sourceIds: ['osm-selected', 'wikipedia-jos'],
      coordinateSourceId: 'osm-selected', coordinateRef: { provider: 'openstreetmap', element: 'way', id: 726973779 }, accuracy: 'feature-centroid',
      scene: { roof: 'flat', sign: 'roadside', props: ['lamp'] },
    },
  ],
  identity: {
    foods: [
      { id: 'plateau-acha', name: 'Acha (hungry rice)', description: 'The NICO cuisine list names Acha (Hungry Rice), millet, tuwo shikafa, tuwo masara, yam and miyan kuka for Plateau State.', sourceIds: ['nico-plateau-cuisine'], note: 'State-level list; not specific to Jos.' },
    ],
    crafts: [
      { id: 'nok-terracotta', name: 'Nok terracotta and pottery', description: 'Wikipedia describes the Nok people as skilled artisans from around Jos, and the Jos Museum Pottery Hall as holding Nok terracotta heads and pottery from across Nigeria.', localProductId: 'clay-pot', sourceIds: ['wikipedia-jos'] },
    ],
    industries: [
      { id: 'jos-tin-mining', name: 'Tin mining', description: 'Wikipedia says Jos became an important centre for tin mining after large cassiterite deposits were found, and is still often called Tin City.', sourceIds: ['wikipedia-jos'] },
      { id: 'jos-trade-hub', name: 'Plateau trading hub', description: 'Wikipedia calls Jos the trading hub of Plateau State and names its main and satellite markets; it does not list goods for each market.', sourceIds: ['wikipedia-jos'] },
      { id: 'jos-light-industry', name: 'Food processing, soap and brewing', description: 'Wikipedia lists food processing, beer brewing and the manufacture of cosmetics, soap, rope, jute bags and furniture among local enterprises.', localProductId: 'soap', sourceIds: ['wikipedia-jos'] },
    ],
  },
  transport: {
    airports: [],
    rail: [],
    ports: [],
  },
  climate: {
    profile: 'middle-belt-wet-dry', rainyMonths: [4, 5, 6, 7, 8, 9, 10], dryMonths: [11, 12, 1, 2, 3],
    description: 'A plateau tropical savanna climate (Aw) at 1,217 m, with a rainy season from April to October, a dry season from November to March and cooler temperatures than most of Nigeria.',
    clearLabel: 'Clear plateau skies', sourceIds: ['wikipedia-jos'],
  },
  homePalette: { back: '#9aa5a8', left: '#5f6b6e', floor: ['#aab7a0', '#6c7f66'] },
  geometry: { surface: { path: 'scripts/geo/sources/formula/jos-surface.geojson', bytes: 390102, sha256: 'b2acca1fe1e4130c908f0e4e1b6f0b4ce83a9652781f5d9b7bba46ea9e2f4c6e' } },
  sourceGroups: [
    { id: 'osm-selected', title: 'Selected OpenStreetMap records for Jos', url: 'https://www.openstreetmap.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'ODbL 1.0', cache: { path: 'scripts/city/research/jos/reviewed/osm-selected.json', bytes: 5398, sha256: '16f40f1e59e1d257d5ead739a5ce11e7ce59e432f5c26504d98fc73a083af1a4' } },
    { id: 'wikidata-selected', title: 'Selected Wikidata entities for Jos', url: 'https://www.wikidata.org/', checkedOn: '2026-10-06', supports: ['coordinate', 'identity'], licence: 'CC0 1.0', cache: { path: 'scripts/city/research/jos/reviewed/wikidata-selected.json', bytes: 3369, sha256: 'e8f579b147b469209ac2097a687de056e88b2ee02bb0245bfaec1bb0f27d67cd' } },
    { id: 'geography', title: 'Pinned Nigerian administrative geography', url: 'https://www.geoboundaries.org/', checkedOn: '2026-10-06', supports: ['geography'], licence: 'CC BY 4.0', cache: { path: 'scripts/city/research/jos/reviewed/geography.json', bytes: 398, sha256: '7f2b4987df6ff3e0d9d96975ecebbbe2134ef3acf9d93053c941344993a4f137' } },
    { id: 'wikipedia-jos', title: 'Jos (Wikipedia)', url: 'https://en.wikipedia.org/wiki/Jos', checkedOn: '2026-10-06', supports: ['identity', 'population', 'climate'], licence: 'CC BY-SA 4.0', cache: { path: 'scripts/city/research/jos/reviewed/wikipedia-jos.json', bytes: 1371, sha256: '6d100bc328648f8a8f8db3a135cbccc3d5aa7d314a88599a0a1edf7e6f40df78' } },
    { id: 'nico-plateau-cuisine', title: 'Cuisines in Nigeria (NICO)', url: 'https://nico.gov.ng/cuisines-in-nigeria/', checkedOn: '2026-10-06', supports: ['identity'], cache: { path: 'scripts/city/research/jos/reviewed/nico-plateau-cuisine.json', bytes: 318, sha256: 'b357759fb59c1ebd0d757851b95d958b930d4d70a03a270ed6d68fb8f40c6dd5' } },
  ],
})
