import type { DetailConfig } from './config.ts';

/** The cairo recipe for scripts/geo/build-destination-detail.ts. Every place is chosen by its OpenStreetMap element; names and points come from the recorded answer. */
const wikidataNamed = (filters: string[]): string => filters.map((filter) => `nwr${filter};`).join('\n');

export const CONFIG: DetailConfig = {
  name: 'Cairo',
  // Greater Cairo core: the Nile valley from the Giza plateau to the airport, Shubra in the north to Maadi in the south.
  box: [29.95, 31.12, 30.14, 31.42],
  core: [30.02, 31.2, 30.08, 31.3],
  discovery: (bbox) => ({
    places: `[out:json][timeout:120][bbox:${bbox}];(
${wikidataNamed([
    '["amenity"~"^(university|hospital|marketplace)$"]["wikidata"]["name:en"]',
    '["leisure"="stadium"]["name:en"]',
    '["tourism"="museum"]["wikidata"]["name:en"]',
    '["amenity"="place_of_worship"]["wikidata"]["name:en"]',
    '["railway"="station"]["wikidata"]["name:en"]',
    '["historic"]["wikidata"]["name:en"]',
    '["tourism"~"^(attraction|zoo|theme_park)$"]["wikidata"]["name:en"]',
    '["shop"="mall"]["name:en"]',
    '["leisure"="park"]["wikidata"]["name:en"]',
    '["amenity"~"^(restaurant|cafe)$"]["wikidata"]["name:en"]',
    '["amenity"~"^(townhall|courthouse)$"]["wikidata"]["name:en"]',
    '["place"~"^(suburb|neighbourhood|quarter)$"]["name:en"]',
  ])}
);out center tags;`,
  }),
  landuse: (bbox) => `[out:json][timeout:120][bbox:${bbox}];(way["landuse"~"^(residential|commercial|industrial|retail|institutional|education|military|cemetery|religious)$"];relation["landuse"~"^(residential|commercial|industrial|retail)$"];);out center;`,
  cell: 0.004,
  grow: 2,
  split: 12,
  shore: 1,
  minHole: 40,
  minRoadKm: 0.7,
  maxRoads: 700,
  roadMarginDegrees: 0.012,
  surround: '#d9cba0',
  water: (bbox) => `[out:json][timeout:120];(relation["natural"="water"]["water"="river"](${bbox});way["natural"="water"]["water"="river"](${bbox});relation["waterway"="riverbank"](${bbox});way["waterway"="riverbank"](${bbox}););out geom;`,
  roads: (bbox, core) => `[out:json][timeout:120];way["highway"~"^(motorway|trunk|primary)$"](${bbox});out geom tags;way["highway"="secondary"]["name"](${core});out geom tags;`,
  boundaryNote: 'the built-up extent of Greater Cairo, from the mapped land use',
  terrainNote: 'the Nile as water polygons with its islands, and the motorway, trunk and primary roads of the box plus named secondary roads in the core.',
  source: 'OpenStreetMap contributors via the Overpass interpreter',
  outlineTolerance: 0.0005,
  waterTolerance: 0.0003,
  farTolerance: 0.0008,
  coreTolerance: 0.0004,
  places: [
    { slot: 'transit', ref: 'node/271864421', kind: 'hub', category: 'civic', icon: 'train', line: 'The railway station, here the road and rail hub of the game: check where you can travel from here.' },
    { slot: 'meal', ref: 'node/1262216203', kind: 'buka', category: 'food', icon: 'food', line: 'A café, here a stop for a simple meal in the game.' },
    { slot: 'community', ref: 'relation/15072032', kind: 'office', category: 'work', icon: 'school', line: 'A university; the game sets its community activities and starter work shifts here.' },
    { slot: 'clinic', ref: 'way/774871347', kind: 'hospital', category: 'care', icon: 'health', line: 'A hospital; the game clinic activities are set here.' },
    { slot: 'recreation', ref: 'way/24745061', kind: 'park', category: 'fun', icon: 'park', line: 'A public park, for a free break, a rest or a game of chess.' },
    { slot: 'market', ref: 'way/709581114', kind: 'market', category: 'work', icon: 'market', line: 'The district, mapped as a neighbourhood in OpenStreetMap, serves as the market stop of the game.' },
    { slot: 'worship', ref: 'way/24908268', kind: 'worship', category: 'fun', icon: 'worship', line: 'A mosque; a quiet place to rest and reflect in the game.' },
    { slot: 'polling', ref: 'way/30925727', kind: 'polling', category: 'civic', icon: 'poll', line: 'A public square. The voting desk here is a game activity, not an election office.' },
    { slot: 'government', ref: 'way/24942979', kind: 'statehouse', category: 'civic', icon: 'civic', line: 'A palace; the notice board here is a game activity, not a government office.' },
    { key: 'egyptian-museum', ref: 'way/10873198', kind: 'walk', category: 'fun', icon: 'museum', line: 'A museum: walk the galleries.' },
    { key: 'cairo-stadium', ref: 'way/24959847', kind: 'viewing', category: 'fun', icon: 'ball', line: 'A stadium: watch from the stands.' },
    { key: 'al-azhar-university', ref: 'way/28831942', kind: 'quad', category: 'fun', icon: 'school', line: 'A university: walk the campus.' },
    { key: 'citadel', ref: 'way/24908286', kind: 'hilltop', category: 'fun', icon: 'view', line: 'A citadel: take in the view.' },
    { key: 'cairo-tower', ref: 'way/767933342', kind: 'viewing', category: 'fun', icon: 'view', line: 'A tower: look around.' },
    { key: 'great-pyramid', ref: 'way/4420397', kind: 'walk', category: 'fun', icon: 'view', line: 'A pyramid: walk around it.' },
    { key: 'city-stars-mall', ref: 'way/284147372', kind: 'mall', category: 'fun', icon: 'market', line: 'A shopping mall: look around the shops.' },
  ],
  names: [
    { id: 'gezira', ref: 'node/13800619989', kind: 'neighbourhood' },
    { id: 'abdin', ref: 'node/315755236', kind: 'neighbourhood' },
    { id: 'azbakeya', ref: 'node/394486927', kind: 'neighbourhood' },
    { id: 'zamalek', ref: 'node/13800621826', kind: 'neighbourhood' },
    { id: 'heliopolis', ref: 'node/768591736', kind: 'neighbourhood' },
    { id: 'nasr-city', ref: 'node/768552342', kind: 'neighbourhood' },
    { id: 'dokki', ref: 'node/324279974', kind: 'neighbourhood' },
    { id: 'mohandessin', ref: 'node/768591708', kind: 'neighbourhood' },
    { id: 'agouza', ref: 'node/324282170', kind: 'neighbourhood' },
    { id: 'imbaba', ref: 'node/324279484', kind: 'neighbourhood' },
    { id: 'garden-city', ref: 'way/707036948', kind: 'neighbourhood' },
    { id: 'islamic-cairo', ref: 'node/330154299', kind: 'neighbourhood' },
    { id: 'old-cairo', ref: 'node/768552664', kind: 'neighbourhood' },
    { id: 'abbasseya', ref: 'node/384309606', kind: 'neighbourhood' },
    { id: 'boulak', ref: 'node/317193944', kind: 'neighbourhood' },
    { id: 'sayyida-zeinab', ref: 'node/324283307', kind: 'neighbourhood' },
    { id: 'ain-shams', ref: 'node/384320947', kind: 'neighbourhood' },
    { id: 'nazlet-el-batran', ref: 'node/768553302', kind: 'neighbourhood' },
    { id: 'rod-el-farag', ref: 'node/324282794', kind: 'neighbourhood' },
  ],
};
