import type { DetailConfig } from './config.ts';
import { extrasQuery, lakeWaterQuery, landuseQuery, placesQuery, roadsQuery } from './queries.ts';

/** The kampala recipe for scripts/geo/build-destination-detail.ts. Every place is chosen by its OpenStreetMap element; names and points come from the recorded answer. */
export const CONFIG: DetailConfig = {
  name: 'Kampala',
  // Kampala from Kawempe in the north to Makindye in the south, and the way south along Lake Victoria to the airport at Entebbe.
  box: [0.02, 32.42, 0.4, 32.66],
  core: [0.27, 32.52, 0.38, 32.64],
  discovery: (bbox) => ({ places: placesQuery(bbox), extras: extrasQuery(bbox) }),
  landuse: landuseQuery,
  cell: 0.004,
  grow: 2,
  split: 12,
  shore: 1,
  minHole: 40,
  minRoadKm: 0.7,
  maxRoads: 700,
  roadMarginDegrees: 0.012,
  surround: '#d3cb9f',
  water: (bbox) => lakeWaterQuery(bbox, 'Victoria'),
  sea: { kind: 'lake', bandMetres: 3000 },
  roads: roadsQuery,
  boundaryNote: 'the built-up extent of Kampala and the way to Entebbe, from the mapped land use',
  terrainNote: 'Lake Victoria as a band of water along its shore, the other lakes and river banks mapped as water, and the motorway, trunk and primary roads of the box plus named secondary roads in the core.',
  source: 'OpenStreetMap contributors via the Overpass interpreter',
  outlineTolerance: 0.0005,
  waterTolerance: 0.0003,
  farTolerance: 0.0008,
  coreTolerance: 0.0004,
  places: [
    { slot: 'transit', ref: 'node/353703378', label: 'Buganda Bus Park', kind: 'hub', category: 'civic', icon: 'bus', line: 'The old bus park, here the road hub of the game: check where you can travel from here.' },
    { slot: 'meal', ref: 'node/616311530', kind: 'buka', category: 'food', icon: 'food', line: 'A café, here a stop for a simple meal in the game.' },
    { slot: 'community', ref: 'way/317923869', label: 'Makerere University Business School', kind: 'office', category: 'work', icon: 'school', line: 'A university business school; the game sets its community activities and starter work shifts here.' },
    { slot: 'clinic', ref: 'way/331033033', kind: 'hospital', category: 'care', icon: 'health', line: 'A hospital; the game clinic activities are set here.' },
    { slot: 'recreation', ref: 'way/183107239', kind: 'park', category: 'fun', icon: 'park', line: 'Botanical gardens, for a free break, a rest or a game of chess.' },
    { slot: 'market', ref: 'way/161834654', kind: 'market', category: 'work', icon: 'market', line: 'A market, here the market stop of the game.' },
    { slot: 'worship', ref: 'way/129123588', kind: 'worship', category: 'fun', icon: 'worship', line: 'A cathedral; a quiet place to rest and reflect in the game.' },
    { slot: 'polling', ref: 'node/1737903918', kind: 'polling', category: 'civic', icon: 'poll', line: 'A public monument in the centre. The voting desk here is a game activity, not an election office.' },
    { slot: 'government', ref: 'node/3285556061', label: 'KCCA Town Hall', kind: 'statehouse', category: 'civic', icon: 'civic', line: 'The city authority town hall; the notice board here is a game activity, not a government office.' },
    { key: 'uganda-museum', ref: 'node/615341411', kind: 'walk', category: 'fun', icon: 'museum', line: 'A museum: walk the galleries.' },
    { key: 'kasubi-royal-tombs', ref: 'way/169069193', kind: 'walk', category: 'fun', icon: 'museum', line: 'Royal tombs on a hill: walk the grounds.' },
    { key: 'wankulukuku-stadium', ref: 'way/43868188', kind: 'viewing', category: 'fun', icon: 'ball', line: 'A stadium: watch from the stands.' },
    { key: 'bahai-house-of-worship', ref: 'way/44111742', kind: 'hilltop', category: 'fun', icon: 'view', line: 'A temple on a hilltop: take in the view.' },
    { key: 'victoria-university', ref: 'way/157839882', kind: 'quad', category: 'fun', icon: 'school', line: 'A university: walk the campus.' },
    { key: 'garden-city', ref: 'way/199101899', kind: 'mall', category: 'fun', icon: 'market', line: 'A shopping mall: look around the shops.' },
    { key: 'oasis-mall', ref: 'way/59529330', kind: 'mall', category: 'fun', icon: 'market', line: 'A shopping mall: look around the shops.' },
    { key: 'rubaga-cathedral', ref: 'way/207230274', kind: 'worship', category: 'fun', icon: 'worship', line: 'A cathedral; a quiet place to rest.' },
    { key: 'royal-palace-of-buganda', ref: 'way/115781989', kind: 'walk', category: 'fun', icon: 'civic', line: 'A royal palace and its grounds: walk around them.' },
    { key: 'fort-lugard', ref: 'way/263780777', kind: 'walk', category: 'fun', icon: 'view', line: 'An old fort on a hill: walk around it.' },
    { key: 'wonder-world', ref: 'way/50474010', kind: 'walk', category: 'fun', icon: 'park', line: 'An amusement park: walk around the rides.' },
    { key: 'national-library', ref: 'node/3766230238', kind: 'walk', category: 'fun', icon: 'school', line: 'The national library: walk through the reading rooms.' },
  ],
  names: [
    { id: 'nakasero', ref: 'node/294023866', kind: 'neighbourhood' },
    { id: 'kololo', ref: 'node/582695017', kind: 'neighbourhood' },
    { id: 'wandegeya', ref: 'node/582695018', kind: 'neighbourhood' },
    { id: 'mulago', ref: 'node/582695019', kind: 'neighbourhood' },
    { id: 'nakawa', ref: 'node/582809246', kind: 'neighbourhood' },
    { id: 'rubaga', ref: 'node/294016126', kind: 'neighbourhood' },
    { id: 'mengo', ref: 'node/294026632', kind: 'neighbourhood' },
    { id: 'nsambya', ref: 'node/294017965', kind: 'neighbourhood' },
    { id: 'kibuli', ref: 'node/609009114', kind: 'neighbourhood' },
    { id: 'bugolobi', ref: 'node/2229101285', kind: 'neighbourhood' },
    { id: 'makerere', ref: 'node/2316916769', kind: 'neighbourhood' },
    { id: 'kabalagala', ref: 'node/583262733', kind: 'neighbourhood' },
    { id: 'ntinda', ref: 'node/3500961529', kind: 'neighbourhood' },
    { id: 'bukoto', ref: 'node/2229101445', kind: 'neighbourhood' },
    { id: 'kawempe', ref: 'node/2229113745', kind: 'neighbourhood' },
    { id: 'katwe', ref: 'node/2321127375', kind: 'neighbourhood' },
    { id: 'makindye', ref: 'node/2321491271', kind: 'neighbourhood' },
    { id: 'namirembe', ref: 'node/2100041821', kind: 'neighbourhood' },
    { id: 'old-kampala', ref: 'node/2099377359', kind: 'neighbourhood' },
    { id: 'muyenga', ref: 'node/3500961527', kind: 'neighbourhood' },
    { id: 'port-bell', ref: 'node/2321500578', kind: 'neighbourhood' },
    { id: 'munyonyo', ref: 'node/2229120056', kind: 'neighbourhood' },
    { id: 'ggaba', ref: 'node/2229107610', kind: 'neighbourhood' },
    { id: 'luzira', ref: 'node/2229118215', kind: 'neighbourhood' },
    { id: 'katabi', ref: 'node/2229112017', kind: 'neighbourhood' },
    { id: 'nateete', ref: 'node/2099381051', kind: 'neighbourhood' },
    { id: 'kamwokya', ref: 'node/2099384695', kind: 'neighbourhood' },
    { id: 'kyambogo', ref: 'node/602638401', kind: 'neighbourhood' },
  ],
};
