import type { DetailConfig } from './config.ts';
import { extrasQuery, inlandWaterQuery, landuseQuery, placesQuery, roadsQuery } from './queries.ts';

/** The kigali recipe for scripts/geo/build-destination-detail.ts. Every place is chosen by its OpenStreetMap element; names and points come from the recorded answer. */
export const CONFIG: DetailConfig = {
  name: 'Kigali',
  // Kigali from Nyabugogo and Kimironko in the north to Kicukiro in the south, west to Nyarugenge, east to the airport at Kanombe.
  box: [-2.0, 30.02, -1.9, 30.16],
  core: [-1.99, 30.04, -1.92, 30.13],
  discovery: (bbox) => ({ places: placesQuery(bbox), extras: extrasQuery(bbox) }),
  landuse: landuseQuery,
  cell: 0.004,
  grow: 2,
  split: 12,
  shore: 1,
  minHole: 40,
  minRoadKm: 0.7,
  maxRoads: 700,
  roadMarginDegrees: 0.004,
  minWaterKm2: 0.02,
  surround: '#b4d08f',
  water: inlandWaterQuery,
  roads: roadsQuery,
  boundaryNote: 'the built-up extent of Kigali, from the mapped land use',
  terrainNote: 'the lakes, reservoirs and river banks mapped as water, and the motorway, trunk and primary roads of the box plus named secondary roads in the core.',
  source: 'OpenStreetMap contributors via the Overpass interpreter',
  outlineTolerance: 0.0005,
  waterTolerance: 0.0003,
  farTolerance: 0.0008,
  coreTolerance: 0.0004,
  places: [
    { slot: 'transit', ref: 'way/253125007', kind: 'hub', category: 'civic', icon: 'bus', line: 'The long-distance bus station, here the road hub of the game: check where you can travel from here.' },
    { slot: 'meal', ref: 'way/177861740', kind: 'buka', category: 'food', icon: 'food', line: 'A café, here a stop for a simple meal in the game.' },
    { slot: 'community', ref: 'way/400397986', kind: 'office', category: 'work', icon: 'school', line: 'A university; the game sets its community activities and starter work shifts here.' },
    { slot: 'clinic', ref: 'way/151366969', kind: 'hospital', category: 'care', icon: 'health', line: 'A hospital; the game clinic activities are set here.' },
    { slot: 'recreation', ref: 'way/1068409927', kind: 'park', category: 'fun', icon: 'park', line: 'A public park, for a free break, a rest or a game of chess.' },
    { slot: 'market', ref: 'way/106506354', kind: 'market', category: 'work', icon: 'market', line: 'A market, here the market stop of the game.' },
    { slot: 'worship', ref: 'way/106340981', kind: 'worship', category: 'fun', icon: 'worship', line: 'A church; a quiet place to rest and reflect in the game.' },
    { slot: 'polling', ref: 'way/253124794', kind: 'polling', category: 'civic', icon: 'poll', line: 'A public open space in the centre. The voting desk here is a game activity, not an election office.' },
    { slot: 'government', ref: 'way/911466828', kind: 'statehouse', category: 'civic', icon: 'civic', line: 'The city hall; the notice board here is a game activity, not a government office.' },
    { key: 'genocide-memorial', ref: 'way/25796157', kind: 'walk', category: 'fun', icon: 'museum', line: 'A memorial museum: walk the galleries quietly.' },
    { key: 'amahoro-stadium', ref: 'way/1231375013', kind: 'viewing', category: 'fun', icon: 'ball', line: 'A stadium: watch from the stands.' },
    { key: 'kandt-house-museum', ref: 'way/173293813', kind: 'walk', category: 'fun', icon: 'museum', line: 'A museum: walk the galleries.' },
    { key: 'college-of-science-and-technology', ref: 'relation/13529968', kind: 'quad', category: 'fun', icon: 'school', line: 'A university college: walk the campus.' },
    { key: 'kigali-heights', ref: 'way/472371264', kind: 'mall', category: 'fun', icon: 'market', line: 'A shopping centre: look around the shops.' },
    { key: 'parliament', ref: 'way/125898407', kind: 'walk', category: 'fun', icon: 'civic', line: 'The parliament building: walk around the grounds.' },
    { key: 'bk-arena', ref: 'way/715821982', kind: 'viewing', category: 'fun', icon: 'ball', line: 'An indoor arena: watch from the seats.' },
    { key: 'pele-stadium', ref: 'way/630835239', kind: 'viewing', category: 'fun', icon: 'ball', line: 'A stadium: watch from the stands.' },
    { key: 'campaign-against-genocide-museum', ref: 'node/6419557788', kind: 'walk', category: 'fun', icon: 'museum', line: 'A museum: walk the exhibition.' },
    { key: 'nyamirambo-womens-centre', ref: 'node/4440589892', kind: 'walk', category: 'fun', icon: 'walk', line: 'A women\'s centre known to visitors: walk the neighbourhood from here.' },
    { key: 'kigali-golf-course', ref: 'node/5886916685', kind: 'walk', category: 'fun', icon: 'park', line: 'A golf course: take a walk.' },
    { key: 'nyandungu-wetland-park', ref: 'relation/14458649', kind: 'walk', category: 'fun', icon: 'park', line: 'An urban wetland park: walk the trails.' },
    { key: 'union-trade-centre', ref: 'way/25824993', kind: 'mall', category: 'fun', icon: 'market', line: 'A shopping centre: look around the shops.' },
    { key: 'centre-culturel-islamique', ref: 'way/106460341', kind: 'worship', category: 'fun', icon: 'worship', line: 'A mosque and cultural centre; a quiet place to rest.' },
    { key: 'university-of-global-health-equity', ref: 'node/9189854986', kind: 'quad', category: 'fun', icon: 'school', line: 'A university: walk the campus.' },
    { key: 'convention-centre', ref: 'relation/13200013', kind: 'walk', category: 'fun', icon: 'civic', line: 'A convention centre: walk around the halls and the plaza.' },
  ],
  names: [
    { id: 'nyamirambo', ref: 'node/281686851', kind: 'neighbourhood' },
    { id: 'nyarugenge', ref: 'node/317754053', kind: 'neighbourhood' },
    { id: 'kiyovu', ref: 'node/317754054', kind: 'neighbourhood' },
    { id: 'kanombe', ref: 'node/317754056', kind: 'neighbourhood' },
    { id: 'kimironko', ref: 'node/317754058', kind: 'neighbourhood' },
    { id: 'kibagabaga', ref: 'node/718927083', kind: 'neighbourhood' },
    { id: 'biryogo', ref: 'node/1841621110', kind: 'neighbourhood' },
    { id: 'kacyiru', ref: 'node/3212740904', kind: 'neighbourhood' },
    { id: 'kimihurura', ref: 'node/3212740905', kind: 'neighbourhood' },
    { id: 'kabeza', ref: 'node/12478242825', kind: 'neighbourhood' },
    { id: 'rubirizi', ref: 'node/12478242824', kind: 'neighbourhood' },
  ],
};
