import type { DetailConfig } from './config.ts';
import { extrasQuery, inlandWaterQuery, landuseQuery, placesQuery, roadsQuery } from './queries.ts';

/** The lusaka recipe for scripts/geo/build-destination-detail.ts. Every place is chosen by its OpenStreetMap element; names and points come from the recorded answer. */
export const CONFIG: DetailConfig = {
  name: 'Lusaka',
  // Lusaka from Chilenje in the south to Kabulonga and Chelstone in the north east, west to Kabwata, and the way to the airport.
  box: [-15.5, 28.2, -15.3, 28.5],
  core: [-15.45, 28.25, -15.38, 28.34],
  discovery: (bbox) => ({ places: placesQuery(bbox), extras: extrasQuery(bbox) }),
  landuse: landuseQuery,
  cell: 0.004,
  grow: 2,
  split: 12,
  shore: 1,
  minHole: 40,
  minRoadKm: 0.35,
  maxRoads: 700,
  roadMarginDegrees: 0.004,
  minWaterKm2: 0.08,
  surround: '#bfd290',
  water: inlandWaterQuery,
  roads: roadsQuery,
  boundaryNote: 'the built-up extent of Lusaka, from the mapped land use',
  terrainNote: 'the dams, lakes and river banks mapped as water, and the motorway, trunk and primary roads of the box plus named secondary roads in the core.',
  source: 'OpenStreetMap contributors via the Overpass interpreter',
  outlineTolerance: 0.0005,
  waterTolerance: 0.0003,
  farTolerance: 0.0008,
  coreTolerance: 0.0004,
  places: [
    { slot: 'transit', ref: 'way/99296406', kind: 'hub', category: 'civic', icon: 'bus', line: 'The intercity bus terminal, here the road hub of the game: check where you can travel from here.' },
    { slot: 'meal', ref: 'node/444994476', kind: 'buka', category: 'food', icon: 'food', line: 'A café, here a stop for a simple meal in the game.' },
    { slot: 'community', ref: 'relation/9374733', kind: 'office', category: 'work', icon: 'school', line: 'A university; the game sets its community activities and starter work shifts here.' },
    { slot: 'clinic', ref: 'way/783202654', kind: 'hospital', category: 'care', icon: 'health', line: 'A hospital; the game clinic activities are set here.' },
    { slot: 'recreation', ref: 'way/1346006477', kind: 'park', category: 'fun', icon: 'park', line: 'A public park, for a free break, a rest or a game of chess.' },
    { slot: 'market', ref: 'way/99186160', kind: 'market', category: 'work', icon: 'market', line: 'The city market, here the market stop of the game.' },
    { slot: 'worship', ref: 'way/1422882767', kind: 'worship', category: 'fun', icon: 'worship', line: 'A cathedral; a quiet place to rest and reflect in the game.' },
    { slot: 'polling', ref: 'way/563644446', kind: 'polling', category: 'civic', icon: 'poll', line: 'A public square. The voting desk here is a game activity, not an election office.' },
    { slot: 'government', ref: 'relation/12678449', kind: 'statehouse', category: 'civic', icon: 'civic', line: 'The national assembly building; the notice board here is a game activity, not a government office.' },
    { key: 'national-museum', ref: 'way/288801150', kind: 'walk', category: 'fun', icon: 'museum', line: 'A museum: walk the galleries.' },
    { key: 'independence-stadium', ref: 'relation/5649842', kind: 'viewing', category: 'fun', icon: 'ball', line: 'A stadium: watch from the stands.' },
    { key: 'national-heroes-stadium', ref: 'relation/9099651', kind: 'viewing', category: 'fun', icon: 'ball', line: 'A stadium: watch from the stands.' },
    { key: 'evelyn-hone-college', ref: 'way/656804896', kind: 'quad', category: 'fun', icon: 'school', line: 'A college: walk the campus.' },
    { key: 'cathedral-of-the-child-jesus', ref: 'way/654342533', kind: 'worship', category: 'fun', icon: 'worship', line: 'A cathedral; a quiet place to rest.' },
    { key: 'jaame-masjid', ref: 'way/551934472', kind: 'worship', category: 'fun', icon: 'worship', line: 'A mosque; a quiet place to rest.' },
    { key: 'lusaka-playhouse', ref: 'way/676289242', kind: 'walk', category: 'fun', icon: 'music', line: 'A theatre: walk through the foyer.' },
    { key: 'oasis-mall', ref: 'node/4961581515', kind: 'mall', category: 'fun', icon: 'market', line: 'A shopping mall: look around the shops.' },
    { key: 'woodlands-mall', ref: 'way/152165978', kind: 'mall', category: 'fun', icon: 'market', line: 'A shopping mall: look around the shops.' },
    { key: 'crossroads-mall', ref: 'way/287494857', kind: 'mall', category: 'fun', icon: 'market', line: 'A shopping mall: look around the shops.' },
    { key: 'kenneth-kaunda-chilenje-house', ref: 'way/510361822', kind: 'walk', category: 'fun', icon: 'museum', line: 'A national monument: walk around the house and its grounds.' },
    { key: 'suwilanji-gardens', ref: 'node/5087935931', kind: 'walk', category: 'fun', icon: 'park', line: 'Gardens: take a walk.' },
    { key: 'embassy-park', ref: 'way/436890691', kind: 'walk', category: 'fun', icon: 'park', line: 'A park and a burial site of a president: walk quietly.' },
    { key: 'bayport', ref: 'node/4694791090', kind: 'hilltop', category: 'fun', icon: 'view', line: 'A viewpoint: take in the view.' },
    { key: 'hindu-temple', ref: 'way/1069109066', kind: 'worship', category: 'fun', icon: 'worship', line: 'A temple; a quiet place to rest.' },
  ],
  names: [
    { id: 'kabulonga', ref: 'node/917999541', kind: 'neighbourhood' },
    { id: 'chilenje', ref: 'node/1149431335', kind: 'neighbourhood' },
    { id: 'kalingalinga', ref: 'node/1149431356', kind: 'neighbourhood' },
    { id: 'ridgeway', ref: 'node/1149431320', kind: 'neighbourhood' },
    { id: 'woodlands', ref: 'node/1149431336', kind: 'neighbourhood' },
    { id: 'northmead', ref: 'node/1149341233', kind: 'neighbourhood' },
    { id: 'rhodes-park', ref: 'node/1149341269', kind: 'neighbourhood' },
    { id: 'kamwala', ref: 'node/1149431341', kind: 'neighbourhood' },
    { id: 'chawama', ref: 'node/1149431332', kind: 'neighbourhood' },
    { id: 'mandevu', ref: 'node/1168573614', kind: 'neighbourhood' },
    { id: 'chaisa', ref: 'node/1149341272', kind: 'neighbourhood' },
    { id: 'kabanana', ref: 'node/1149341219', kind: 'neighbourhood' },
    { id: 'mtendere', ref: 'node/1149431373', kind: 'neighbourhood' },
    { id: 'libala', ref: 'node/1149431362', kind: 'neighbourhood' },
    { id: 'makeni', ref: 'node/1282600548', kind: 'neighbourhood' },
    { id: 'chelston', ref: 'node/1149341214', kind: 'neighbourhood' },
    { id: 'roma', ref: 'node/1149341240', kind: 'neighbourhood' },
    { id: 'longacres', ref: 'node/1280410111', kind: 'neighbourhood' },
    { id: 'chamba-valley', ref: 'node/1149341207', kind: 'neighbourhood' },
    { id: 'ibex-hill', ref: 'node/1280410155', kind: 'neighbourhood' },
    { id: 'misisi', ref: 'node/1149431323', kind: 'neighbourhood' },
    { id: 'industrial-area', ref: 'node/1149341217', kind: 'neighbourhood' },
    { id: 'kaunda-square', ref: 'node/1149341242', kind: 'neighbourhood' },
    { id: 'cathedral-hill', ref: 'node/1149431354', kind: 'neighbourhood' },
  ],
};
