import type { DetailConfig } from './config.ts';
import { coastWaterQuery, extrasQuery, landuseQuery, placesQuery, roadsQuery } from './queries.ts';

/** The rabat recipe for scripts/geo/build-destination-detail.ts. Every place is chosen by its OpenStreetMap element; names and points come from the recorded answer. */
export const CONFIG: DetailConfig = {
  name: 'Rabat',
  // Rabat and Salé on the Atlantic and the Bou Regreg, from Temara in the south to Salé's north shore, east to the airport.
  box: [33.93, -6.95, 34.1, -6.72],
  core: [33.98, -6.88, 34.05, -6.8],
  discovery: (bbox) => ({ places: placesQuery(bbox), extras: extrasQuery(bbox) }),
  landuse: landuseQuery,
  cell: 0.004,
  grow: 2,
  split: 12,
  shore: 0,
  minHole: 40,
  minRoadKm: 0.7,
  maxRoads: 700,
  roadMarginDegrees: 0.004,
  surround: '#bcd596',
  water: coastWaterQuery,
  sea: { kind: 'coast', bandMetres: 2500 },
  roads: roadsQuery,
  boundaryNote: 'the built-up extent of Rabat and Salé, from the mapped land use',
  terrainNote: 'the Atlantic as a band of water along the coast, the Bou Regreg and the other water mapped as areas, and the motorway, trunk and primary roads of the box plus named secondary roads in the core.',
  source: 'OpenStreetMap contributors via the Overpass interpreter',
  outlineTolerance: 0.0005,
  waterTolerance: 0.0003,
  farTolerance: 0.0008,
  coreTolerance: 0.0004,
  places: [
    { slot: 'transit', ref: 'way/156426654', kind: 'hub', category: 'civic', icon: 'train', line: 'The railway station, here the road and rail hub of the game: check where you can travel from here.' },
    { slot: 'meal', ref: 'node/3116669259', kind: 'buka', category: 'food', icon: 'food', line: 'A café, here a stop for a simple meal in the game.' },
    { slot: 'community', ref: 'node/1761182094', kind: 'office', category: 'work', icon: 'school', line: 'A university; the game sets its community activities and starter work shifts here.' },
    { slot: 'clinic', ref: 'way/289025339', kind: 'hospital', category: 'care', icon: 'health', line: 'A hospital; the game clinic activities are set here.' },
    { slot: 'recreation', ref: 'way/35032391', kind: 'park', category: 'fun', icon: 'park', line: 'A public garden, for a free break, a rest or a game of chess.' },
    { slot: 'market', ref: 'way/452729966', kind: 'market', category: 'work', icon: 'market', line: 'A market, here the market stop of the game.' },
    { slot: 'worship', ref: 'way/453091664', kind: 'worship', category: 'fun', icon: 'worship', line: 'A mosque; a quiet place to rest and reflect in the game.' },
    { slot: 'polling', ref: 'way/42305066', kind: 'polling', category: 'civic', icon: 'poll', line: 'A public square. The voting desk here is a game activity, not an election office.' },
    { slot: 'government', ref: 'way/156348306', kind: 'statehouse', category: 'civic', icon: 'civic', line: 'The parliament building; the notice board here is a game activity, not a government office.' },
    { key: 'hassan-tower', ref: 'way/253426261', kind: 'viewing', category: 'fun', icon: 'view', line: 'An unfinished tower: look around.' },
    { key: 'mausoleum-of-mohammed-v', ref: 'way/278577671', kind: 'walk', category: 'fun', icon: 'museum', line: 'A mausoleum and its courtyard: walk around it.' },
    { key: 'chellah', ref: 'node/5042469923', kind: 'walk', category: 'fun', icon: 'museum', line: 'An archaeological site: walk the grounds.' },
    { key: 'oudayas-museum', ref: 'way/283167034', kind: 'walk', category: 'fun', icon: 'museum', line: 'A museum in the old fortress: walk the galleries.' },
    { key: 'archaeological-museum', ref: 'way/42354863', kind: 'walk', category: 'fun', icon: 'museum', line: 'A museum: walk the galleries.' },
    { key: 'modern-art-museum', ref: 'node/13630526273', kind: 'walk', category: 'fun', icon: 'museum', line: 'A museum of modern art: walk the galleries.' },
    { key: 'stade-moulay-el-hassan', ref: 'node/13318969885', kind: 'viewing', category: 'fun', icon: 'ball', line: 'A stadium: watch from the stands.' },
    { key: 'rabat-zoo', ref: 'way/152610832', kind: 'walk', category: 'fun', icon: 'park', line: 'A zoo: walk the paths.' },
    { key: 'saint-pierre-cathedral', ref: 'way/236725316', kind: 'worship', category: 'fun', icon: 'worship', line: 'A cathedral; a quiet place to rest.' },
    { key: 'mega-mall', ref: 'way/109711402', kind: 'mall', category: 'fun', icon: 'market', line: 'A shopping mall: look around the shops.' },
    { key: 'arribat-center', ref: 'way/96826325', kind: 'mall', category: 'fun', icon: 'market', line: 'A shopping centre: look around the shops.' },
    { key: 'national-theatre', ref: 'way/264640892', kind: 'walk', category: 'fun', icon: 'music', line: 'A national theatre: walk through the foyer.' },
    { key: 'faculty-of-law-and-economics', ref: 'way/152609311', kind: 'quad', category: 'fun', icon: 'school', line: 'A university faculty: walk the campus.' },
    { key: 'semaphore-platform', ref: 'node/2872447279', kind: 'hilltop', category: 'fun', icon: 'view', line: 'A viewing platform above the sea: take in the view.' },
    { key: 'bab-rouah', ref: 'way/280437998', kind: 'walk', category: 'fun', icon: 'walk', line: 'An old city gate: walk through it.' },
  ],
  names: [
    { id: 'agdal', ref: 'node/2184710850', kind: 'neighbourhood' },
    { id: 'souissi', ref: 'node/2184710847', kind: 'neighbourhood' },
    { id: 'yacoub-el-mansour', ref: 'node/2184710836', kind: 'neighbourhood' },
    { id: 'takaddoum', ref: 'node/21755904', kind: 'neighbourhood' },
    { id: 'aviation', ref: 'node/21098457', kind: 'neighbourhood' },
    { id: 'riad', ref: 'node/2834509152', kind: 'neighbourhood' },
    { id: 'bettana', ref: 'node/2186141148', kind: 'neighbourhood' },
    { id: 'sale-el-jadida', ref: 'node/2186141201', kind: 'neighbourhood' },
    { id: 'moulay-ismail', ref: 'node/2186141292', kind: 'neighbourhood' },
    { id: 'tabriquet', ref: 'node/2816730546', kind: 'neighbourhood' },
    { id: 'hay-el-qods', ref: 'node/2922688737', kind: 'neighbourhood' },
    { id: 'ocean', ref: 'node/3486287189', kind: 'neighbourhood' },
    { id: 'bab-lamrissa', ref: 'node/3573489093', kind: 'neighbourhood' },
    { id: 'youssoufia', ref: 'node/14094959083', kind: 'neighbourhood' },
    { id: 'akrach', ref: 'node/14094959089', kind: 'neighbourhood' },
    { id: 'madinat-al-irfane', ref: 'node/10225836569', kind: 'neighbourhood' },
    { id: 'mabella', ref: 'node/14094959081', kind: 'neighbourhood' },
    { id: 'hay-al-fath', ref: 'node/9267256549', kind: 'neighbourhood' },
    { id: 'massira', ref: 'node/14094959101', kind: 'neighbourhood' },
    { id: 'bab-al-bahr', ref: 'node/12606451042', kind: 'neighbourhood' },
    { id: 'layayda', ref: 'node/2186210621', kind: 'neighbourhood' },
  ],
};
