// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "bamako",
  "name": "Bamako",
  "country": {
    "idISOlower": "ml",
    "name": "Mali"
  },
  "state": {
    "idunique": "ml-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Bamako",
  "centre": {
    "lon": -8.001985,
    "lat": 12.65196
  },
  "airport": {
    "id": "bamako-airport",
    "name": "Modibo Keita International Airport",
    "lon": -7.94994,
    "lat": 12.5335,
    "sourceUrl": "https://ourairports.com/airports/GABS/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-8.004985,12.64896,-7.998985,12.65496",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -8.016985,
    12.5215,
    -7.93794,
    12.66696
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
