// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "praia",
  "name": "Praia",
  "country": {
    "idISOlower": "cv",
    "name": "Cabo Verde"
  },
  "state": {
    "idunique": "cv-starter",
    "name": "Starter zone"
  },
  "timezone": "Atlantic/Cape_Verde",
  "centre": {
    "lon": -23.516689,
    "lat": 14.916698
  },
  "airport": {
    "id": "praia-airport",
    "name": "Nelson Mandela International Airport",
    "lon": -23.484728,
    "lat": 14.941126,
    "sourceUrl": "https://ourairports.com/airports/GVNP/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=-23.519689,14.913698,-23.513689,14.919698",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    -23.531689,
    14.901698,
    -23.472728,
    14.953126
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
