// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "khartoum",
  "name": "Khartoum",
  "country": {
    "idISOlower": "sd",
    "name": "Sudan"
  },
  "state": {
    "idunique": "sd-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Khartoum",
  "centre": {
    "lon": 32.532233,
    "lat": 15.590024
  },
  "airport": {
    "id": "khartoum-airport",
    "name": "Khartoum International Airport",
    "lon": 32.5532,
    "lat": 15.5895,
    "sourceUrl": "https://ourairports.com/airports/HSSK/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=32.529233,15.587024,32.535233,15.593024",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    32.5152546,
    15.575024,
    32.5652,
    15.605024
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates. Published bounds include complete retained OSM feature coordinates and expand by at most 0.02 degrees beyond the initial settlement/airport bounds."
} satisfies DestinationFacts
