// Generated by scripts/world/build-playable-africa.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "addis-ababa",
  "name": "Addis Ababa",
  "country": {
    "idISOlower": "et",
    "name": "Ethiopia"
  },
  "state": {
    "idunique": "et-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Addis_Ababa",
  "centre": {
    "lon": 38.698059,
    "lat": 9.035256
  },
  "airport": {
    "id": "addis-ababa-airport",
    "name": "ADDIS ABABA / BOLE",
    "lon": 38.799399639,
    "lat": 8.975040833,
    "sourceUrl": "https://pdfcoffee.com/aip-ethiopia-2-pdf-free.html"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and cited aeronautical information sources",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=38.695059,9.032256,38.701059,9.038256",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; Airport reference points: cited aeronautical information sources",
  "bounds": [
    38.683059,
    8.963041,
    38.8114,
    9.050256
  ],
  "coverageNote": "national capital. Starter visitor area. Real city and airport points, clipped country land and a bounded central street/building sample. Visitor services and homes are fictional game content. Buildings use approximate box silhouettes; missing heights are estimates. Game prices remain in the shared Allworld economy."
} satisfies DestinationFacts
