/**
 * Client entry (foundation). Wires the client model (src/client.js), the shell and its panels
 * (src/ui), the venue scene host, the maps and the community panel together.
 * Feature owners do not edit this file: panels plug in through src/ui/panels, scenes through
 * src/scene, rules through src/game.
 *
 * FIRST LOAD. Only the shell, the eager panels and the rules needed to draw the HUD are in the
 * entry chunk. Everything heavy is fetched after the HUD is on screen and usable:
 *   - the 3D scene host with Three.js and every scene module   (loadScene, straight after start)
 *   - the city map (the 3D miniature in src/map3d, or the flat one where WebGL is missing) and
 *     the country map                                          (first time the Map opens, or a trip starts)
 *   - the community panel                                      (after the first connection; if its
 *     chunk does not arrive the status line and the community panel say so, it is retried with
 *     a bounded backoff — src/lazy-load.js — and the panel offers Try again and Reload)
 *   - the lazy panel groups                                    (src/ui/panels/index.js)
 * Until a piece arrives its callers simply skip it (`venue?.…`), and it is given the current
 * state the moment it exists, so nothing depends on load order.
 *
 * WHERE PEOPLE STAND. In a public venue the avatar's place in the scene IS the player's place in
 * the room: the scene host reports it (onMove — at most three times a second, only when it moved),
 * it goes to the community module's moveTo(x, z), the server puts it in the room's `presence`, and
 * what comes back through the module's onMembers is drawn in the scene (other players as figures
 * at their own places) AND is what proximity voice measures. One position, one source. Home is
 * private and reports nothing. Nothing here enables voice: that is the Join voice button alone.
 *
 * TRAVEL IS SHOWN ON THE MAP. Whatever started a trip (the map card, the Ride app, Go to work),
 * the moment the server reports it the Map becomes the screen in front and shows the trip; when
 * the server reports the arrival the map shows it for a moment and then the venue comes up. The
 * rules and the timer stay the server's — see accepted() and src/map3d/trip.js.
 *
 * THE FIRST MINUTE (src/quick-start/). A new device meets the landing screen (the 'quick-start'
 * panel: a name, a quick character, Play). Play arrives here as 'jaw:quick-start' { name, look }:
 * the session is opened (POST /api/session), the look is confirmed by the 'onboarding.quick-start'
 * action under an action id that is kept on the device until the server has answered — so a
 * double tap, a retry on a bad connection and a reload are all the same one start — and the
 * player is standing in a public venue. A link is then handled in ONE place (landJoin): the player it points at (/v/<id>,
 * ?join=<id>) is joined (POST /api/social/join), its share code (?ref=<code>) is attached as a referral, both are said in one
 * banner ("You’re joining Ada"), and a table it names (?table=<id>) is opened in the Tables app. The funnel
 * events ('jaw:track') are reported from the server's own state as it changes (see accepted()).
 */
import { createClient, CITIES, roomJoinNeeded } from './client.ts';
import { createLazyLoader } from './lazy-load.ts';
import { createShell } from './ui/shell.js';
import { linkWords } from './ui/link.ts';
import { PANELS, sessionGate } from './ui/panels/index.js';
import { S as social, loadPeople, onPeople, takeLinkHost, resetSocial } from './ui/panels/social-client.js';
import { crowdList, playersHere } from './scene/crowd.ts';
import { NPCS } from './game/content/npcs.ts';
import { viewLife, VENUES, isDeparting } from './life.ts';
import { venueLabel, venueDistrict } from './game/content/venues.ts';
import { funnelSnap, funnelEvents, joinBanner, linkBanner } from './quick-start/model.ts';
import { pendingPlay, keepPlay, forgetDraft, joinTarget, forgetJoin, track, play, captureLink, pendingRef, forgetRef, pendingTable, forgetTable, deviceToken } from './quick-start/entry.ts';
import { tableById } from './tables/places.ts';
import { telemetry } from './telemetry/index.ts';

const $ = (id) => document.getElementById(id);
let storage; try { storage = window.localStorage; } catch {}
let community = null, pendingRoute = null, connecting = false;
/** Where the other players in this venue room stand, as the room reports it: { [publicId]: { x, z } }. */
let positions = {};
let shell = null, venue = null, cityMap = null, world = null, mapsLoading = null;
/** The connection status line: shown in the top bar's saved indicator and in the More menu. */
let net = { text: 'Connecting…', error: false };

function status(text, error = false) { net = { text, error }; telemetry.link(client.link); if (shell) render(); }

/** The trip a state is on, as a key ('' when it is not travelling): a different key is a different trip. */
const tripKey = (state) => (isDeparting(state) ? `${state.activeAction.kind}|${state.location}|${state.activeAction.id}|${state.activeAction.duration}` : '');

const client = createClient({
  storage,
  isHidden: () => document.hidden,
  onStatus: status,
  onChange: accepted,
  // The saved life is gone: its own sheet says so ("Your city life"), not the welcome of the landing screen.
  onSessionExpired() { community?.destroy(); community = null; positions = {}; sessionChanged(null); render(); shell.open('session', { reason: 'expired' }); },
  onNeedName(problem) { telemetry.needName(); shell.open(sessionGate().id, { reason: 'new', problem: problem ?? null }); },
  onSession(session, isNew) { sessionChanged(session?.id ?? null); telemetry.session(session, isNew, client.serverNow()); },
});

/**
 * The device session is another identity now (a new life was started, or the old one is gone): whatever the browser holds
 * about people — friends, requests, threads, the growth hello, a seat at a table — belonged to the previous one and is
 * dropped before anything is drawn for the new one. A reconnection of the same session changes nothing.
 */
let sessionId;
function sessionChanged(id) {
  if (sessionId === id) return;
  const first = sessionId === undefined;
  sessionId = id;
  if (first) return; // the first session of this page: nothing was held for anyone else
  resetSocial();
  window.dispatchEvent(new CustomEvent('jaw:session', { detail: { id } }));
}

/** The player's avatar in every scene: their saved look, seeded by the session's public id (never the cookie). */
const playerLook = () => ({ look: client.state.onboarding?.look, seed: client.session?.id ?? 'you', name: client.state.name || client.identity.name });
const showPlayer = () => { venue?.setPlayer(playerLook()); cityMap?.setPlayer(playerLook()); };

/**
 * The crowd in the scene, from real data only: the server's who-is-here listing for this venue
 * room and the venue's regulars. Called when the state or the listing changes; the host compares
 * the list by value, so an unchanged crowd never draws a frame.
 */
function showCrowd() {
  const state = client.state;
  const npcs = isDeparting(state) ? [] : Object.values(NPCS).filter((npc) => npc.venue === state.location);
  venue?.setCrowd(crowdList({ players: playersHere(social.people, state, client.cityId), npcs, selfId: client.session?.id, positions }));
}
let lastPlot = null, followingCity = false;
onPeople(showCrowd);
// Friends' houses are named on the map (public ids only).
const showFriends = () => cityMap?.setFriends((social.me?.friends || []).map((friend) => friend.id));
onPeople(showFriends);

/** Tell the room where the avatar stands right now (the scene itself reports only while it moves). Public venues only. */
function reportPlace() {
  const at = venue?.position?.();
  if (!at || !community || at.location !== client.state.location || at.location === 'home' || isDeparting(client.state)) return;
  if (community.moveTo(at.x, at.z) === true) placeSent = true;
}
/**
 * Whether the room has been told where the avatar stands since it was last joined. Everywhere but the campus the room
 * says so itself (a member at the origin has not reported yet); on the campus a join starts at the main gate, which is a
 * real place, so the game remembers whether its own report went out and repeats it with the next member list if not.
 */
let placeSent = false;
/** The room's member list arrived (or emptied): draw the others where they stand, and make sure the room knows where we do. */
function onMembers({ self, members }) {
  const next = {};
  let listed = false, placed = false;
  for (const member of members) {
    if (member.id === self) { listed = true; placed = Boolean(member.position); continue; }
    if (member.position) next[member.id] = member.position;
  }
  positions = next;
  showCrowd();
  if (listed && (!placed || (client.state.location === 'unilag' && !placeSent))) reportPlace();
}

/** The 3D scene: fetched once the HUD is up. A device that cannot draw it still gets the whole game. */
async function loadScene() {
  try {
    // One scene API over two hosts: the venue host, and the UNILAG campus's own (fetched only when the player goes there).
    const { createWorldAdapter } = await import('./campus/unilag/world-adapter.js');
    venue = createWorldAdapter($('venue-scene'), { location: client.state.location, onTag: (tag) => {
      // A name tag opens that person's card: a regular (npc:<id>) or a real player (public id).
      if (tag.kind === 'goal') void goTo(client.state.location, tag.id.replace(/^goal:/, ''));
      // A game table in the venue (walked up to, or tapped): the Tables app opens on that table — sit, watch or invite.
      else if (tag.kind === 'table') shell.open('tables', { table: tag.id.replace(/^table:/, '') });
      else if (tag.kind === 'npc') shell.open('person', { npc: tag.id.replace(/^npc:/, '') });
      else if (tag.kind === 'player') shell.open('person', { player: tag.id });
    },
    // The avatar moved: that is where the player stands in the room (presence, and so proximity voice).
    onMove: (at) => { if (at.location === client.state.location && at.location !== 'home' && !isDeparting(client.state) && community?.moveTo(at.x, at.z) === true) placeSent = true; },
    // The campus: its host walks the avatar to a landmark and then asks for the game's ordinary `spot` action; its shuttle runs on server time.
    commitSpot: ({ id }) => commitSpot(id), now: () => client.serverNow(),
    onHost: () => { if (shell) { layoutScene(); reportPlace(); } } });
    $('scene-wait')?.remove();
    venue.setState(client.state);
    showPlayer();
    showCrowd();
    showGoal();
    layoutScene();
    venue.resize();
    // The first frame is in the canvas: bring it up with the same short fade as an arrival, over the calm backdrop — never a flash.
    $('venue-scene').classList.add('is-arriving');
    reportPlace();
    telemetry.sceneReady(true, $('venue-scene').querySelector('canvas'));
    // Three.js is here now, so the map's own code is a small download: fetch it ahead, so a first trip shows without a wait.
    // (Nothing is built or drawn until the Map opens.)
    void import('./map3d/index.ts').catch(() => {});
  } catch (error) {
    console.error('The scene could not be started:', error);
    telemetry.chunkFailed('scene', error); telemetry.sceneReady(false);
    const wait = $('scene-wait');
    if (wait) wait.textContent = 'The 3D scene could not be drawn on this device. Everything else still works.';
  }
}

/**
 * The two maps, fetched the first time the Map opens (or at once for a shared ?venue= link).
 * What the Map panel says to the city map before it exists is kept and replayed.
 */
const mapUi = {};
const keepMapUi = (event) => Object.assign(mapUi, event.detail || {});
window.addEventListener('jaw:map-ui', keepMapUi);
function loadMaps() {
  mapsLoading ??= Promise.all([import('./map3d/index.ts'), import('./world-map.ts')]).then(([cityModule, worldModule]) => {
    world = worldModule.createWorldMap($('map-scene'), {
      onOpenCity: () => showMapLayer('city'),
      onEnterCity: (cityId) => switchCity(cityId),
      // One character travels between cities: an ordinary game action, refused with its reason while the city is not open.
      onTravel: (to, mode) => command('estate.relocate', { to, mode }),
      routes: () => (client.state ? viewLife(client.state, { now: client.state.t, cityId: client.cityId }).estate?.links ?? null : null),
      held: heldCities,
    });
    heldShown = heldCities().join();
    cityMap = cityModule.createCityView($('city-scene'), {
      cityId: client.cityId,
      onSelectVenue: (venueId) => shell.open('map', { destination: venueId }),
      onSelectGov: () => shell.open('state-house'),
      onSelectNeighbour: (player) => shell.open('person', { player: player.id, name: player.name }),
      // The world layer: a local government opens its page, a house its owner's card; the maps fetch only what is in view.
      onSelectLga: (lga) => shell.open('lga', { lga }),
      onSelectHouse: (house) => shell.open('house-card', { house }),
      fetchJson: client.fetchJson,
      // The avatar reached the door: ask the server for the arrival now rather than at its next poll.
      onTripDue: () => { if (client.online) void client.refresh(); },
      onNotice: (text) => shell.toast(text),
    });
    window.removeEventListener('jaw:map-ui', keepMapUi);
    world.setCity(client.cityId);
    cityMap.setPlayer(playerLook());
    showFriends();
    cityMap.setState(client.state);
    // What the Map was asked for while its code was on the way (the country map, a filter) is replayed BEFORE the first
    // draw, so the layer that was asked for is the one in front.
    if (Object.keys(mapUi).length) window.dispatchEvent(new CustomEvent('jaw:map-ui', { detail: mapUi }));
    render();
    refreshScene();
  }).catch((error) => { mapsLoading = null; telemetry.chunkFailed('map', error); console.error('The map could not be loaded:', error); shell.toast('The map could not be loaded. Check your connection and open it again.', 'error'); });
  return mapsLoading;
}

/** Open the Map on the city map ('city') or the country map ('world'). The maps are told first, so the right one is in front when the shell draws. */
function showMapLayer(layer) {
  window.dispatchEvent(new CustomEvent('jaw:map-ui', { detail: { layer } }));
  shell.open('map', { layer });
}

const dialog = $('life-dialog');
shell = createShell({
  root: $('life-overlay'), dialog, dialogContent: $('life-dialog-content'), panels: PANELS,
  host: { command, fetchJson: client.fetchJson, newId: client.newId, goTo, toggleCommunity, menu, onRender: () => layoutScene(), redrawScene: () => { if (shell.mode !== 'map') venue?.update(); }, onMode(mode) {
    // A trip is watched on the map: while one is running there is no venue to stand in, so the venue screen
    // (and the shell's old full-panel travel view with it) is never what is in front.
    if (mode === 'venue' && tripKey(client.state)) { shell.setMode('map'); return; }
    telemetry.screen(mode);
    if (mode === 'map') loadMaps();
    render(); refreshScene();
  } },
});

const clockFormat = new Intl.DateTimeFormat('en-NG', { timeZone: 'Africa/Lagos', weekday: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true });
function buildView() {
  const now = client.serverNow(), cityId = client.cityId;
  return {
    ...viewLife(client.state, { now, cityId }),
    cityId, city: CITIES[cityId], connected: client.online, link: client.link, session: client.session, net, storage: client.storage,
    // The life's own name (the server keeps it equal to the session nickname), so a rename shows as soon as the next state arrives.
    name: client.state.name || client.identity.name, now,
    clock: clockFormat.format(new Date(now)).replace(',', ' ·'),
    venues: Object.values(VENUES).map((item) => ({ id: item.id, label: venueLabel(item.id, cityId), district: venueDistrict(item.id, cityId), icon: item.icon, description: item.description })),
  };
}

function render() {
  const state = client.state, mapOpen = shell.mode === 'map';
  document.body.classList.toggle('map-open', mapOpen);
  if (state.location === 'home') $('community-panel').hidden = true;
  const worldLayer = cityMap ? cityMap.ready === false : false;
  $('venue-scene').hidden = mapOpen;
  $('map-scene').hidden = !mapOpen || !worldLayer;
  $('city-scene').hidden = !mapOpen || worldLayer;
  shell.render(state, buildView());
  // The country map shows which cities this player holds: redrawn when that list changes (a session arrived, a city was entered).
  if (world && heldCities().join() !== heldShown) { heldShown = heldCities().join(); world.refresh(); }
  // A trip between cities is drawn on the world map, where the server's timer says it is.
  world?.setState?.(state);
  // Told after the shell has drawn, so the map measures the panel it shares the screen with. Hidden, it draws nothing.
  cityMap?.setShown(mapOpen && !worldLayer);
}
/** Tell the scene how much of the screen the HUD covers, so it draws itself in the free part. Measured after each shell render (host.onRender). */
function layoutScene() {
  if (!venue || !shell || shell.mode === 'map') return;
  const overlay = $('life-overlay'), box = (selector) => overlay.querySelector(selector)?.getBoundingClientRect();
  const stack = box('.life-bottom'), quick = box('.life-quick'), bar = box('.life-status'), page = overlay.getBoundingClientRect();
  const phone = page.width <= 720;
  // On a phone the rows under the top bar (needs, alerts, the goal line) are the HUD's: the scene's one-time hint sits under the last of them.
  const rows = phone ? Math.max(0, ...['.life-quick', '.life-goal'].map((selector) => { const row = box(selector); return row && row.height ? row.bottom : 0; })) : 0;
  venue.setInsets({ top: ((phone ? quick?.bottom : bar?.bottom) || bar?.bottom || page.top) - page.top, bottom: stack?.height ? page.bottom - stack.top : 0, hint: rows ? rows - page.top : 0 });
}
// A resize (or a phone being turned) moves the HUD: measure it again before the scene is re-framed, so the controls and the camera use the new free area at once.
function refreshScene() { if (shell.mode === 'map') { world?.resize(); cityMap?.resize(); } else { layoutScene(); venue?.resize(); } }

/**
 * The cities this player has a life in, so the country map can offer a "coming soon" city only to
 * someone who already lives there. The server says so in the session response (session.cities),
 * which makes it true on every device. Only a server that does not report it yet (an older host)
 * falls back to what this browser remembers.
 */
const HELD_KEY = 'joinallworld-cities';
function rememberedCities() { try { const list = JSON.parse(storage.getItem(HELD_KEY) || '[]'); return Array.isArray(list) ? list.filter((id) => typeof id === 'string') : []; } catch { return []; } }
function heldCities() { const held = client.session?.cities; return Array.isArray(held) ? held.filter((id) => typeof id === 'string') : rememberedCities(); }
function noteCity(id) { try { const list = rememberedCities(); if (!list.includes(id)) storage.setItem(HELD_KEY, JSON.stringify([...list, id])); } catch { /* remembered for this visit only */ } }
let heldShown = '';

let shownTrip = '';
function showVenue() {
  if (shell.mode === 'venue') return;
  shell.setMode('venue');
  // The venue comes up with a short fade rather than a cut.
  const scene = $('venue-scene');
  scene.classList.remove('is-arriving'); void scene.offsetWidth; scene.classList.add('is-arriving');
}

/** The current goal's place in the world: the scene flags the spot it points at (a guest's first goals; nothing once settled in). */
function showGoal() {
  const state = client.state, chip = client.online && state.onboarding?.stage === 'guest' && !state.onboarding.done ? viewLife(state, { now: client.serverNow(), cityId: client.cityId }).goals?.chip : null;
  const at = chip?.kind === 'goal' && Array.isArray(chip.go) && chip.go.length === 2 && !state.activeAction ? chip : null;
  venue?.setGoal(at ? { venue: at.go[0], spot: at.go[1], text: at.title } : null);
}

/** Called after every accepted server state. */
function accepted(state, previous) {
  telemetry.state(state, previous, client);
  const moved = previous.location !== state.location;
  // The funnel, from the server's own state: each event once, when it happens.
  const was = funnelSnap(previous), is = funnelSnap(state);
  for (const event of funnelEvents(was, is)) {
    track(event.name, event.name === 'first_activity_completed' && Number.isFinite(state.onboarding.bornAt) ? { ...event.props, server_ms: state.onboarding.firstAt - state.onboarding.bornAt } : event.props);
  }
  if (was.guest && is.done) forgetDraft();
  noteCity(client.cityId);
  // A trip started — from the map card, the Ride app, Go to work, anywhere: the map shows it. Once per trip, so a
  // player who then opens another screen (Buy, a Phone app) is not pulled back; leaving that screen returns to the map.
  const trip = tripKey(state);
  if (trip && trip !== shownTrip && shell.mode !== 'map') shell.setMode('map');
  // The trip has just set off: build the place it is going to now (once, a moment after the trip bar has appeared), so
  // arriving is a reveal and not a wait. Nothing is drawn; the map is what is on screen.
  if (trip && trip !== shownTrip && state.activeAction?.kind === 'travel') { const to = state.activeAction.id; setTimeout(() => { if (tripKey(client.state) === trip) venue?.prepare(to); }, 450); }
  shownTrip = trip;
  if (moved) {
    venue?.setLocation(state.location);
    // Arrived while watching the trip: the map shows the arrival for a moment, then the venue comes up.
    if (shell.mode === 'map' && cityMap && isDeparting(previous)) { cityMap.setState(state); cityMap.arrive(showVenue); }
    else if (shell.mode !== 'venue') shell.setMode('venue');
    if (pendingRoute && pendingRoute.venue !== state.location) pendingRoute = null; // went somewhere else instead
  }
  // Arrival, or a cancelled trip: restore room membership. Join only — voice stays off until the player asks.
  if (roomJoinNeeded(previous, state)) placeSent = false;
  if (roomJoinNeeded(previous, state)) community?.join(client.cityId, state.location);
  venue?.setState(state);
  showPlayer();
  showCrowd();
  showGoal();
  // One character: the life has arrived in another city. The server files it under that city (asked for here, so it is
  // done before the new city's life is requested), then the game follows it there.
  if (state?.estate?.city && state.estate.city !== client.cityId && !followingCity) {
    followingCity = true;
    const to = state.estate.city;
    client.fetchJson(`/api/world/me?city=${client.cityId}`).catch(() => {}).finally(() => { followingCity = false; switchCity(to); });
  }
  // The server has set a plot aside for this life (or moved it): tell the maps and, decoupled, analytics. No address, no name.
  const plotKey = state?.estate?.plot ? `${state.estate.plot.lga}/${state.estate.plot.estate}/${state.estate.plot.plot}` : '';
  if (plotKey !== lastPlot) { if (plotKey && lastPlot !== null) { window.dispatchEvent(new CustomEvent('jaw:track', { detail: { name: 'house_allocated', props: {} } })); window.dispatchEvent(new CustomEvent('jaw:world-changed')); } lastPlot = plotKey; }
  // The campus, from the server's own state: enrolment and graduation are told to analytics once each, as they happen (the programme id only).
  const studied = previous?.unilagStudent?.status, studies = state?.unilagStudent?.status;
  if (studied !== studies && studied !== undefined) {
    const event = studies === 'matriculated' && studied === 'admitted' ? { name: 'campus_enrolled', props: { programme: state.unilagStudent.programme } } : studies === 'graduated' ? { name: 'campus_graduated', props: { programme: state.unilagStudent.programme } } : null;
    if (event) window.dispatchEvent(new CustomEvent('jaw:track', { detail: event }));
  }
  cityMap?.setState(state);
  render();
  // Arrived somewhere (or a trip ended): read who is here once; later changes are pushed by the server.
  if (roomJoinNeeded(previous, state) && client.online) void loadPeople();
  if (pendingRoute && !state.activeAction) {
    const route = pendingRoute;
    if (state.location === route.venue) { pendingRoute = null; if (route.spot) { shell.setExpanded(true); void command('spot', { id: route.spot }); } }
    else if (!client.online) pendingRoute = null;
  }
}

async function sendCommand(type, payload) {
  if (type === 'cancel') pendingRoute = null;
  const measured = telemetry.action(type);
  const result = await client.command(type, payload);
  measured?.(result);
  if (!result.ok && result.reason && result.code !== 'busy') shell.toast(result.reason, 'error');
  if (!result.ok && type === 'travel') pendingRoute = null;
  return result;
}

/** The campus host calls this once the avatar has reached the landmark it was sent to: the ordinary `spot` action. */
async function commitSpot(id) {
  const result = await sendCommand('spot', { id });
  if (result.ok) shell.setExpanded(true);
  render();
  return result;
}

/** Every game action goes through here. On the campus a spot is walked to first (the host commits it on arrival); everywhere else it is sent at once. */
async function command(type, payload) {
  if (type === 'spot' && client.state.location === 'unilag' && venue?.host === 'campus' && typeof payload?.id === 'string' && payload.id !== client.state.spot) {
    const result = await venue.walkToSpot(payload.id);
    // A refusal of the walk itself (the server's own refusals were already shown by commitSpot).
    if (!result.ok && result.reason && (result.code === 'no_route' || result.code === 'invalid_spot')) shell.toast(result.reason, 'error');
    return result;
  }
  return sendCommand(type, payload);
}

/**
 * Go to a venue and stand at a spot there. Already there: select the spot. Elsewhere: open the
 * Map travel card for the venue (mode tiles, Danfo selected) — a trip is never started on the
 * player's behalf — and remember the spot for when they arrive.
 */
async function goTo(venueId, spotId) {
  if (client.state.location === venueId) {
    if (shell.mode !== 'venue') shell.setMode('venue');
    if (spotId) { shell.setExpanded(true); await command('spot', { id: spotId }); render(); }
    return;
  }
  pendingRoute = { venue: venueId, spot: spotId };
  shell.open('map', { destination: venueId });
}

/**
 * The community panel's code, fetched after the first connection. The chunk can fail to arrive (a
 * dropped connection, a deploy in between): the loader then retries by itself after 1, 2, 4, 8 and
 * 16 seconds and stops. The status line always says which of these is true — it never reads
 * "connecting" for something that is not being tried.
 */
const communityCode = createLazyLoader(() => Promise.all([import('./community.js'), import('./community.css')]).then(([module]) => module), {
  onState(state) {
    if (state.status === 'retrying') status(`Community did not load · retrying in ${Math.round(state.retryInMs / 1000)} s (attempt ${state.attempt + 1} of ${state.attempts})`, true);
    else if (state.status === 'failed') { telemetry.chunkFailed('community', state.error); status('Community is unavailable · it did not load. Open Community to retry', true); }
    // A retry that succeeded by itself: bring the panel up now, without waiting for the player.
    else if (state.status === 'ready') void startCommunity();
    showCommunityRecovery();
  },
});
/**
 * What the community panel shows while its code is not here: what happened, what happens next
 * (the same bounded retries as the status line — nothing else requests the chunk), and the two
 * things the player can do. "Reload and retry" comes first: a browser can keep a failed module
 * download for the life of the page (Chromium does — the file is reachable again and the import
 * still fails), and then no in-page retry can succeed. A reload keeps the saved identity and asks
 * for no microphone access. "Try again" asks the loader at once, for browsers that do fetch again.
 */
function showCommunityRecovery(startProblem = null) {
  if (community) return;
  const content = $('community-content'), load = communityCode.state;
  const waiting = load.status === 'loading', down = load.status === 'retrying' || load.status === 'failed' || Boolean(startProblem);
  if (!down && !(waiting && content.querySelector('[data-community-recovery]'))) return;
  const next = waiting ? 'Trying again now…'
    : load.status === 'retrying' ? `Trying again by itself in ${Math.round(load.retryInMs / 1000)} s (attempt ${load.attempt + 1} of ${load.attempts}).`
      : load.status === 'failed' ? 'It was tried several times and is no longer being retried. Reload to try again.' : 'Its code loaded but it could not start.';
  content.innerHTML = `<section data-community-recovery aria-label="Community unavailable"><h2>Community could not load</h2><p>Your saved city life is still available. Check your connection, then try community again.</p><p role="status">${next}</p><p><button type="button" class="ui-button is-primary" data-community-reload>Reload and retry</button> <button type="button" class="ui-button" data-community-retry${waiting ? ' disabled' : ''}>Try again</button></p></section>`;
  content.querySelector('[data-community-retry]').onclick = () => { if (!client.online) shell.toast(notConnected('open the community'), 'error'); else void startCommunity(); };
  content.querySelector('[data-community-reload]').onclick = () => window.location.reload();
}
/** Why something cannot be done right now, in the words of the real connection state — "offline" only when this device has no network. */
const notConnected = (what) => linkWords(client.link)?.cannot(what) || `You are not connected yet, so you cannot ${what}. Try again in a moment.`;
let startingCommunity = false;
/** Create the community panel once its code is here and the client is connected. Safe to call any number of times. */
async function startCommunity() {
  if (community || startingCommunity || !client.online) return;
  startingCommunity = true;
  try {
    const module = await communityCode.load();
    if (!module || community || !client.online) return;
    community = await module.createCommunity($('community-content'), { cityId: client.cityId, venueId: client.state.location,
      onMembers,
      venueName: (venueId, cityId) => venueLabel(venueId, cityId),
      // The panel's Walk buttons walk the avatar; its new place comes back through onMove like any other step.
      onStep: (dx, dz) => venue?.walkBy?.(dx, dz) === true,
      onStatus: (s) => { if (s.status === 'offline') status('Community disconnected · reconnect in panel', true); else if (s.connected) status('Connected · progress saved'); } });
    watchChatRefusals($('community-content'));
    render();
  } catch (error) {
    console.error('The community panel could not be started:', error);
    telemetry.captureError(error, { chunk: 'community' });
    status('Community is unavailable · it could not start. Open Community to retry', true);
    showCommunityRecovery(error);
  } finally { startingCommunity = false; }
}

function toggleCommunity(force) {
  if (client.state.location === 'home') { shell.toast('Your home is private. Visit a public venue to meet people.'); return; }
  if (!community) {
    if (!client.online) { shell.toast(notConnected('open the community'), 'error'); return; }
    // Not loaded: the panel itself says so and offers the retry (showCommunityRecovery). While the
    // first attempt is still in flight there is nothing to show yet, only to wait for.
    if (!$('community-content').querySelector('[data-community-recovery]')) {
      shell.toast('Community is still loading. Try again in a moment.');
      void startCommunity(); // starts at once, or joins the attempt already in flight
      return;
    }
  }
  $('community-panel').hidden = typeof force === 'boolean' ? !force : !$('community-panel').hidden;
}

/**
 * A venue chat line the server refused (blocked wording, or the player is muted). The community
 * panel does not pass the refusal's code to onStatus; all it exposes is its own status line
 * (`.community-feedback`), where it prints the sentence the server sent, and "Not sent" on the line
 * itself. That sentence is repeated as a toast so it is seen wherever the panel is scrolled to.
 * Event-driven (a MutationObserver on that one element): nothing runs while the game is idle.
 */
let chatWatch = null;
function watchChatRefusals(container) {
  chatWatch?.disconnect();
  const line = container.querySelector('.community-feedback');
  if (!line || typeof MutationObserver !== 'function') return;
  chatWatch = new MutationObserver(() => {
    const text = line.textContent.trim();
    const refused = [...container.querySelectorAll('.community-messages li small')].some((node) => node.textContent === 'Not sent');
    if (text && refused) shell.toast(text, 'error');
  });
  chatWatch.observe(line, { childList: true, characterData: true, subtree: true });
}

async function connect(createNew = false) {
  if (connecting) return false;
  connecting = true;
  try {
    if (createNew) { community?.destroy(); community = null; positions = {}; }
    const ok = await client.connect(createNew);
    render();
    if (ok) await firstMinute();
    // Not awaited: a slow or failing community chunk must not hold up the game or block a later Reconnect.
    if (ok) void startCommunity();
    return ok;
  } finally { connecting = false; }
}

/**
 * After every successful connection: finish a quick start whose Play was tapped (now, or before a
 * reload or a dropped connection), then handle an invite link. Safe to call any number of times.
 */
async function firstMinute() {
  const o = client.state.onboarding;
  if (o?.done || o?.stage !== 'guest') { play.sending = false; if (o?.done) forgetDraft(); await landJoin(); return; }
  const kept = pendingPlay();
  if (o.required && kept) {
    // One action id for this start, made once (it carries server time) and kept until the server has answered.
    const actionId = kept.actionId ?? client.newId();
    if (!kept.actionId) keepPlay({ ...kept, actionId });
    play.sending = true;
    // `joining` was decided when Play was tapped and is kept with the look, so every retry sends the very same request.
    const result = await client.command('onboarding.quick-start', { look: kept.look, ...(kept.joining ? { joining: true } : {}) }, { actionId });
    if (result.ok && kept.joining) owedWelcome = true;
    play.sending = false;
    if (result.ok) { keepPlay(null); shell.setExpanded(true); if (shell.isOpen(sessionGate().id)) shell.close(); }
    else if (result.code === 'invalid_look' || result.code === 'action_id_conflict' || result.code === 'action_expired') { keepPlay(null); shell.open(sessionGate().id, { problem: { reason: 'That character could not be saved. Choose again and tap Play.' } }); }
    else if (client.online) shell.open(sessionGate().id, { problem: { reason: result.reason || 'Your character could not be saved yet. Tap Play to try again — nothing is lost.' } });
    render();
  } else { play.sending = false; if (!o.required) keepPlay(null); }
  if (!client.state.onboarding.required) await landJoin();
}

/**
 * THE LANDING OF A LINK — the one place an invite, share or table link is handled, after the quick start (or at once for a
 * player who already has a life). In order:
 *   1. the share code (`ref`) is attached to the caller's life as a referral (POST /api/growth/referral/link). It pays
 *      nobody now: both gifts wait for paid work on real Lagos days (server/growth/referral.ts). A link that had no `join`
 *      names its sharer here, and that is who is joined.
 *   2. a brand-new guest is put beside the player the link points at (POST /api/social/join): in their venue, or told they
 *      are at home (Knock), out or offline. A player who has already settled in gets the Invite app on that house instead.
 *   3. ONE banner says all of it ("You’re joining Ada … Work a paid shift and you both get a gift."). There is no
 *      welcome toast beside it: the quick start said nothing because it knew a banner was coming.
 *   4. a table the link named is opened in the Tables app.
 * What is kept on the device (the id, the code, the table) is dropped as each is answered; with no answer (the connection
 * dropped) it stays and is tried again at the next connection.
 */
let joining = false, owedWelcome = false;
async function landJoin() {
  let host = joinTarget();
  const ref = pendingRef(), table = pendingTable();
  if ((!host && !ref && !table && !owedWelcome) || joining || !client.online) return;
  joining = true;
  const guest = client.state.onboarding?.stage === 'guest' && !client.state.onboarding.done;
  const kind = table ? 'table' : ref ? 'share' : 'house';
  // This landing handles the link: the address is cleaned (what it carried is kept on the device until it is answered) and
  // the Invite app is not opened for it by anyone else.
  try { if (location.pathname !== '/' || location.search) history.replaceState(null, '', '/'); } catch { /* the address stays as it was */ }
  takeLinkHost();
  if (host === client.session?.id) { forgetJoin(); host = null; }
  let banner = null, gift = false, sharer = null;
  try {
    if (ref) {
      const about = host ? null : await client.fetchJson(`/api/growth/share/${encodeURIComponent(ref)}`);
      if (about?.ok && about.by?.id && about.by.id !== client.session?.id) { host = about.by.id; sharer = about.by.name; }
      const linked = await client.fetchJson('/api/growth/referral/link', { method: 'POST', body: { cityId: client.cityId, code: ref, device: deviceToken() } });
      forgetRef();
      if (linked.ok && !linked.duplicate) { gift = true; sharer = linked.by ?? sharer; track('invite_joined', { kind }); }
    }
    if (host && guest) {
      const answer = await client.fetchJson('/api/social/join', { method: 'POST', body: { host, cityId: client.cityId } });
      forgetJoin();
      track('join_landed', { code: answer.code ?? 'refused' });
      if (answer.code === 'joined' || answer.code === 'here') track('invite_colocated', { kind });
      banner = joinBanner(answer, (id) => venueLabel(id, client.cityId), { gift });
      if (answer.code === 'joined') await client.refresh();
    } else if (host) { forgetJoin(); shell.open('invite', { host }); }
  } catch (error) {
    // No answer: what is kept is tried again at the next connection. A refusal that will not change is dropped.
    if (error.status && error.status < 500) { forgetJoin(); forgetRef(); }
    else { joining = false; return; }
  }
  joining = false;
  if (!banner && gift) banner = linkBanner(sharer || 'a friend');
  // A table the link named: the Tables app opens on it (the banner is shown over it).
  if (table) { forgetTable(); if (tableById(table)) shell.open('tables', { table }); }
  if (banner) showBanner(banner, banner.knock && !table ? { label: 'Knock', run: () => shell.open('invite', { host }) } : null);
  // Nobody could be joined after all: the welcome the quick start held back is said now, once.
  else if (owedWelcome && guest) shell.toast(`Welcome to ${venueLabel(client.state.location, client.cityId)}, ${client.state.name || client.identity.name}.`);
  owedWelcome = false;
}

/** One banner over the scene (built with textContent: a player's name is never markup). It leaves when closed or after 12 s. */
function showBanner({ tone, title, text }, action) {
  document.querySelector('.qs-banner')?.remove();
  const node = document.createElement('aside'), words = document.createElement('div'), strong = document.createElement('strong'), small = document.createElement('small');
  node.className = `qs-banner is-${tone}`; node.setAttribute('role', 'status');
  strong.textContent = title; small.textContent = text; words.append(strong, small); node.append(words);
  if (action) { const button = document.createElement('button'); button.className = 'ui-button is-primary is-small'; button.textContent = action.label; button.onclick = () => { node.remove(); action.run(); }; node.append(button); }
  const close = document.createElement('button'); close.className = 'qs-banner-close'; close.setAttribute('aria-label', 'Dismiss'); close.textContent = '×'; close.onclick = () => node.remove(); node.append(close);
  // Over an open sheet (the Tables app a table link opened) the banner goes inside the dialog, which is the top layer.
  (dialog.open ? dialog : document.body).append(node);
  setTimeout(() => node.remove(), 12000);
}

/** Play was tapped on the landing screen. A second tap while the first is on its way is the same start. */
let starting = false;
async function quickStart(detail) {
  if (starting) return;
  starting = true;
  try {
    // A life that is already there and only held for its look (its Play never reached the server, or it is a
    // life the old flow left on its first step): the session exists, so a rename and the action are all it takes.
    if (detail?.name) client.identity.name = detail.name;
    const ok = await connect(true);
    if (!ok && client.link !== 'new') {
      play.sending = false;
      const words = linkWords(client.link);
      shell.open(sessionGate().id, { reason: 'new', problem: { reason: `${words?.why || 'The game server did not answer.'} Your name and character are kept on this device — tap Play to try again.`, name: detail?.name } });
    }
  } finally { starting = false; play.sending = false; render(); }
}

async function switchCity(id) {
  const result = await client.switchCity(id);
  if (!result.ok) { if (result.reason) shell.toast(result.reason, 'error'); return; }
  noteCity(id);
  world?.setCity(id); cityMap?.setCity(id);
  placeSent = false;
  community?.join(id, client.state.location);
  venue?.setLocation(client.state.location);
  shell.setMode('venue');
  shell.open('city', { city: id });
}

/** Entries of the shell's More menu and the top bar's Reconnect. */
function menu(id) {
  if (id === 'reconnect') connect();
  // The country map: the city you are in, and the cities that are coming soon.
  else if (id === 'city') showMapLayer('world');
}

window.addEventListener('jaw:start-life', (event) => { if (event.detail?.name) client.identity.name = event.detail.name; connect(true); });
window.addEventListener('jaw:quick-start', (event) => { void quickStart(event.detail); });
window.addEventListener('jaw:reconnect', () => connect());
window.addEventListener('jaw:switch-city', (event) => switchCity(event.detail.city));
$('close-life-dialog').onclick = () => shell.close();
$('community-close').onclick = () => toggleCommunity(false);
window.addEventListener('resize', refreshScene);
// The device got its network back: try the connection once, by itself (an event, not a timer).
window.addEventListener('online', () => { if (!client.online && (client.link === 'offline' || client.link === 'unreachable')) connect(); });
window.addEventListener('pagehide', () => { community?.destroy(); client.stop(); });
document.addEventListener('visibilitychange', () => { if (document.hidden) client.stop(); else if (client.online) client.refresh(); });

if (new URLSearchParams(location.search).has('diagnostics')) {
  const panel = document.createElement('aside');
  panel.style.cssText = 'position:fixed;left:10px;bottom:90px;z-index:60;background:white;color:black;padding:8px;max-width:340px;font:12px monospace';
  const button = document.createElement('button'); button.textContent = 'Read renderer diagnostics';
  const output = document.createElement('pre'); output.id = 'render-diagnostics';
  button.onclick = () => { output.textContent = JSON.stringify({ ...(venue ? venue.diagnostics() : { renderCount: 0, scene: 'not loaded yet' }), map: cityMap ? cityMap.diagnostics() : 'not loaded yet', visibility: document.visibilityState, lazyPanelsWaiting: PANELS.filter((item) => item.pending).map((item) => item.id) }, null, 2); };
  // For the same diagnostics from a test harness: the map, the client and the shell mode.
  window.__jaw = { get map() { return cityMap; }, get client() { return client; }, get mode() { return shell.mode; }, get venue() { return venue; }, get shell() { return shell; } };
  panel.append(button, output); document.body.append(panel);
}

render();
telemetry.hudReady();
// A device without a life will meet the landing screen: its code is asked for now, in parallel with the connection, so it is
// there when the server says a name is needed. A returning player never downloads it.
if (!client.hasSavedIdentity) void sessionGate().load?.().catch(() => {});
// The link this page was opened with is read once, here, before anything rewrites the address.
{ const link = captureLink(); if (link.join || link.ref || link.table) track('invite_opened', { kind: link.table ? 'table' : link.ref ? 'share' : 'house', has_session: client.hasSavedIdentity === true }); }
connect();
// The scene (Three.js and every scene module) starts downloading only now, with the HUD already on screen and usable.
setTimeout(loadScene, 0);
if (new URLSearchParams(location.search).has('venue')) loadMaps();
