/**
 * Client entry (foundation). Wires the client model (src/client.js), the shell and its panels
 * (src/ui), the venue scene host, the world map and the community panel together.
 * Feature owners do not edit this file: panels plug in through src/ui/panels, scenes through
 * src/scene, rules through src/game.
 */
import { createVenueWorld } from './venue-world.js';
import { createWorldMap } from './world-map.js';
import { createCityMap } from './city-map.js';
import { createCommunity } from './community.js';
import { createClient, CITIES, roomJoinNeeded } from './client.js';
import { createShell } from './ui/shell.js';
import { PANELS, sessionGate } from './ui/panels/index.js';
import { S as social, loadPeople, onPeople } from './ui/panels/social-client.js';
import { crowdList, playersHere } from './scene/crowd.js';
import { NPCS } from './game/content/npcs.js';
import { viewLife, VENUES } from './life.js';
import { venueLabel, venueDistrict } from './game/content/venues.js';
import './world-map.css';
import './community.css';

const $ = (id) => document.getElementById(id);
let storage; try { storage = window.localStorage; } catch {}
let community = null, pendingRoute = null, connecting = false;

function status(text, error = false) { $('connection-status').textContent = text; $('connection-status').classList.toggle('error', error); }

const client = createClient({
  storage,
  isHidden: () => document.hidden,
  onStatus: status,
  onChange: accepted,
  onSessionExpired() { community?.destroy(); community = null; render(); shell.open(sessionGate().id, { reason: 'expired' }); },
  onNeedName() { shell.open(sessionGate().id, { reason: 'new' }); },
});

const venue = createVenueWorld($('venue-scene'), { location: client.state.location, onTag: (tag) => {
  // A name tag opens that person's card: a regular (npc:<id>) or a real player (public id).
  if (tag.kind === 'npc') shell.open('person', { npc: tag.id.replace(/^npc:/, '') });
  else if (tag.kind === 'player') shell.open('person', { player: tag.id });
} });
/** The player's avatar in every scene: their saved look, seeded by the session's public id (never the cookie). */
const showPlayer = () => venue.setPlayer({ look: client.state.onboarding?.look, seed: client.session?.id ?? 'you', name: client.state.name || client.identity.name });
const world = createWorldMap($('map-scene'), { onSelectCity: (city) => shell.open('city', { city: city.id }) });
const cityMap = createCityMap($('city-scene'), { onSelectVenue: (venueId) => shell.open('map', { destination: venueId }) });
world.setCity(client.cityId);
cityMap.setCity(client.cityId);

/**
 * The crowd in the scene, from real data only: the server's who-is-here listing for this venue
 * room and the venue's regulars. Called when the state or the listing changes; the host compares
 * the list by value, so an unchanged crowd never draws a frame.
 */
function showCrowd() {
  const state = client.state;
  const npcs = state.activeAction?.kind === 'travel' ? [] : Object.values(NPCS).filter((npc) => npc.venue === state.location);
  venue.setCrowd(crowdList({ players: playersHere(social.people, state, client.cityId), npcs, selfId: client.session?.id }));
}
onPeople(showCrowd);

const dialog = $('life-dialog');
const shell = createShell({
  root: $('life-overlay'), dialog, dialogContent: $('life-dialog-content'), panels: PANELS,
  host: { command, fetchJson: client.fetchJson, goTo, toggleCommunity, redrawScene: () => { if (shell.mode !== 'map') venue.update(); }, onMode() { render(); refreshScene(); } },
});

const clockFormat = new Intl.DateTimeFormat('en-NG', { timeZone: 'Africa/Lagos', weekday: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true });
function buildView() {
  const now = client.serverNow(), cityId = client.cityId;
  return {
    ...viewLife(client.state, { now, cityId }),
    cityId, city: CITIES[cityId], connected: client.online, session: client.session,
    // The life's own name (the server keeps it equal to the session nickname), so a rename shows as soon as the next state arrives.
    name: client.state.name || client.identity.name, now,
    clock: clockFormat.format(new Date(now)).replace(',', ' ·'),
    venues: Object.values(VENUES).map((item) => ({ id: item.id, label: venueLabel(item.id, cityId), district: venueDistrict(item.id, cityId), icon: item.icon, description: item.description })),
  };
}

function render() {
  const state = client.state, mapOpen = shell.mode === 'map';
  document.body.classList.toggle('map-open', mapOpen);
  $('community-toggle').hidden = state.location === 'home';
  if (state.location === 'home') $('community-panel').hidden = true;
  $('venue-scene').hidden = mapOpen;
  $('map-scene').hidden = !mapOpen || cityMap.ready !== false;
  $('city-scene').hidden = !mapOpen || cityMap.ready === false;
  shell.render(state, buildView());
  $('city-switch').textContent = `🌍 ${CITIES[client.cityId].name}`;
  $('retry-server').hidden = client.ready;
}
function refreshScene() { if (shell.mode === 'map') { world.resize(); cityMap.resize(); } else venue.resize(); }

/** Called after every accepted server state. */
function accepted(state, previous) {
  const moved = previous.location !== state.location;
  if (moved) {
    venue.setLocation(state.location);
    if (shell.mode !== 'venue') shell.setMode('venue');
    if (pendingRoute && pendingRoute.venue !== state.location) pendingRoute = null; // went somewhere else instead
  }
  // Arrival, or a cancelled trip: restore room membership. Join only — voice stays off until the player asks.
  if (roomJoinNeeded(previous, state)) community?.join(client.cityId, state.location);
  venue.setState(state);
  showPlayer();
  showCrowd();
  cityMap.setState(state);
  render();
  // Arrived somewhere (or a trip ended): read who is here once; later changes are pushed by the server.
  if (roomJoinNeeded(previous, state) && client.online) void loadPeople();
  if (pendingRoute && !state.activeAction) {
    const route = pendingRoute;
    if (state.location === route.venue) { pendingRoute = null; if (route.spot) { shell.setExpanded(true); void command('spot', { id: route.spot }); } }
    else if (!client.online) pendingRoute = null;
  }
}

async function command(type, payload) {
  if (type === 'cancel') pendingRoute = null;
  const result = await client.command(type, payload);
  if (!result.ok && result.reason && result.code !== 'busy') shell.toast(result.reason, 'error');
  if (!result.ok && type === 'travel') pendingRoute = null;
  return result;
}

/**
 * Go to a venue and stand at a spot there. Already there: select the spot. Elsewhere: open the
 * Map travel card for the venue (mode tiles, Danfo selected) — a trip is never started on the
 * player's behalf — and remember the spot for when they arrive.
 */
async function goTo(venueId, spotId) {
  if (client.state.location === venueId) {
    if (shell.mode !== 'venue') shell.setMode('venue');
    if (spotId) { shell.setExpanded(true); await command('spot', { id: spotId }); render(); }
    return;
  }
  pendingRoute = { venue: venueId, spot: spotId };
  shell.open('map', { destination: venueId });
}

function toggleCommunity(force) {
  if (client.state.location === 'home') { shell.toast('Your home is private. Visit a public venue to meet people.'); return; }
  $('community-panel').hidden = typeof force === 'boolean' ? !force : !$('community-panel').hidden;
}

async function connect(createNew = false) {
  if (connecting) return;
  connecting = true;
  try {
    if (createNew) { community?.destroy(); community = null; }
    const ok = await client.connect(createNew);
    if (ok && !community) {
      community = await createCommunity($('community-content'), { cityId: client.cityId, venueId: client.state.location,
        onStatus: (s) => { if (s.status === 'offline') status('Community disconnected · reconnect in panel', true); else if (s.connected) status('Connected · progress saved'); } });
    }
    render();
  } finally { connecting = false; }
}

async function switchCity(id) {
  const result = await client.switchCity(id);
  if (!result.ok) { if (result.reason) shell.toast(result.reason, 'error'); return; }
  world.setCity(id); cityMap.setCity(id);
  community?.join(id, client.state.location);
  venue.setLocation(client.state.location);
  shell.setMode('venue');
  shell.open('city', { city: id });
}

window.addEventListener('jaw:start-life', (event) => { if (event.detail?.name) client.identity.name = event.detail.name; connect(true); });
window.addEventListener('jaw:switch-city', (event) => switchCity(event.detail.city));
$('close-life-dialog').onclick = () => shell.close();
$('city-switch').onclick = () => { shell.setMode('map'); shell.open('city', { city: client.cityId }); };
$('community-toggle').onclick = () => toggleCommunity();
$('community-close').onclick = () => toggleCommunity(false);
$('retry-server').onclick = () => connect();
$('use-location').onclick = () => {
  if (!navigator.geolocation) { status('Location unavailable. Choose Lagos or Ibadan on the map.', true); return; }
  navigator.geolocation.getCurrentPosition((position) => {
    const { latitude, longitude } = position.coords;
    const lagos = Math.hypot(latitude - 6.5244, longitude - 3.3792), ibadan = Math.hypot(latitude - 7.3775, longitude - 3.947);
    shell.open('city', { city: lagos <= ibadan ? 'lagos' : 'ibadan' });
  }, () => status('Location not shared. Choose a city manually.', true), { enableHighAccuracy: false, timeout: 8000, maximumAge: 300000 });
};
window.addEventListener('resize', refreshScene);
window.addEventListener('pagehide', () => { community?.destroy(); client.stop(); });
document.addEventListener('visibilitychange', () => { if (document.hidden) client.stop(); else if (client.online) client.refresh(); });

if (new URLSearchParams(location.search).has('diagnostics')) {
  const panel = document.createElement('aside');
  panel.style.cssText = 'position:fixed;left:10px;bottom:90px;z-index:60;background:white;color:black;padding:8px;max-width:340px;font:12px monospace';
  const button = document.createElement('button'); button.textContent = 'Read renderer diagnostics';
  const output = document.createElement('pre'); output.id = 'render-diagnostics';
  button.onclick = () => { output.textContent = JSON.stringify({ ...venue.diagnostics(), visibility: document.visibilityState }, null, 2); };
  panel.append(button, output); document.body.append(panel);
}

render();
refreshScene();
connect();
