/**
 * Client entry (foundation). Wires the client model (src/client.js), the shell and its panels
 * (src/ui), the venue scene host, the maps and the community panel together.
 * Feature owners do not edit this file: panels plug in through src/ui/panels, scenes through
 * src/scene, rules through src/game.
 *
 * FIRST LOAD. Only the shell, the eager panels and the rules needed to draw the HUD are in the
 * entry chunk. Everything heavy is fetched after the HUD is on screen and usable:
 *   - the 3D scene host with Three.js and every scene module   (loadScene, straight after start)
 *   - the city map and the world map                           (first time the Map opens)
 *   - the community panel                                      (after the first connection; if its
 *     chunk does not arrive the status line says so, it is retried with a bounded backoff —
 *     src/lazy-load.js — and Community / Reconnect retry at once)
 *   - the lazy panel groups                                    (src/ui/panels/index.js)
 * Until a piece arrives its callers simply skip it (`venue?.…`), and it is given the current
 * state the moment it exists, so nothing depends on load order.
 */
import { createClient, CITIES, roomJoinNeeded } from './client.js';
import { createLazyLoader } from './lazy-load.js';
import { createShell } from './ui/shell.js';
import { PANELS, sessionGate } from './ui/panels/index.js';
import { S as social, loadPeople, onPeople } from './ui/panels/social-client.js';
import { crowdList, playersHere } from './scene/crowd.js';
import { NPCS } from './game/content/npcs.js';
import { viewLife, VENUES, isDeparting } from './life.js';
import { venueLabel, venueDistrict } from './game/content/venues.js';

const $ = (id) => document.getElementById(id);
let storage; try { storage = window.localStorage; } catch {}
let community = null, pendingRoute = null, connecting = false;
let shell = null, venue = null, cityMap = null, world = null, mapsLoading = null;
/** The connection status line: shown in the top bar's saved indicator and in the More menu. */
let net = { text: 'Connecting…', error: false };

function status(text, error = false) { net = { text, error }; if (shell) render(); }

const client = createClient({
  storage,
  isHidden: () => document.hidden,
  onStatus: status,
  onChange: accepted,
  onSessionExpired() { community?.destroy(); community = null; render(); shell.open(sessionGate().id, { reason: 'expired' }); },
  onNeedName(problem) { shell.open(sessionGate().id, { reason: 'new', problem: problem ?? null }); },
});

/** The player's avatar in every scene: their saved look, seeded by the session's public id (never the cookie). */
const showPlayer = () => venue?.setPlayer({ look: client.state.onboarding?.look, seed: client.session?.id ?? 'you', name: client.state.name || client.identity.name });

/**
 * The crowd in the scene, from real data only: the server's who-is-here listing for this venue
 * room and the venue's regulars. Called when the state or the listing changes; the host compares
 * the list by value, so an unchanged crowd never draws a frame.
 */
function showCrowd() {
  const state = client.state;
  const npcs = isDeparting(state) ? [] : Object.values(NPCS).filter((npc) => npc.venue === state.location);
  venue?.setCrowd(crowdList({ players: playersHere(social.people, state, client.cityId), npcs, selfId: client.session?.id }));
}
onPeople(showCrowd);

/** The 3D scene: fetched once the HUD is up. A device that cannot draw it still gets the whole game. */
async function loadScene() {
  try {
    const { createVenueWorld } = await import('./venue-world.js');
    venue = createVenueWorld($('venue-scene'), { location: client.state.location, onTag: (tag) => {
      // A name tag opens that person's card: a regular (npc:<id>) or a real player (public id).
      if (tag.kind === 'npc') shell.open('person', { npc: tag.id.replace(/^npc:/, '') });
      else if (tag.kind === 'player') shell.open('person', { player: tag.id });
    } });
    $('scene-wait')?.remove();
    venue.setState(client.state);
    showPlayer();
    showCrowd();
    venue.resize();
    layoutScene();
  } catch (error) {
    console.error('The scene could not be started:', error);
    const wait = $('scene-wait');
    if (wait) wait.textContent = 'The 3D scene could not be drawn on this device. Everything else still works.';
  }
}

/**
 * The two maps, fetched the first time the Map opens (or at once for a shared ?venue= link).
 * What the Map panel says to the city map before it exists is kept and replayed.
 */
const mapUi = {};
const keepMapUi = (event) => Object.assign(mapUi, event.detail || {});
window.addEventListener('jaw:map-ui', keepMapUi);
function loadMaps() {
  mapsLoading ??= Promise.all([import('./city-map.js'), import('./world-map.js'), import('./world-map.css')]).then(([cityModule, worldModule]) => {
    world = worldModule.createWorldMap($('map-scene'), { onSelectCity: (city) => shell.open('city', { city: city.id }) });
    cityMap = cityModule.createCityMap($('city-scene'), {
      onSelectVenue: (venueId) => shell.open('map', { destination: venueId }),
      onSelectGov: () => shell.open('state-house'),
      onSelectNeighbour: (player) => shell.open('person', { player: player.id, name: player.name }),
    });
    window.removeEventListener('jaw:map-ui', keepMapUi);
    world.setCity(client.cityId);
    cityMap.setCity(client.cityId);
    cityMap.setState(client.state);
    render();
    if (Object.keys(mapUi).length) window.dispatchEvent(new CustomEvent('jaw:map-ui', { detail: mapUi }));
    refreshScene();
  }).catch((error) => { mapsLoading = null; console.error('The map could not be loaded:', error); shell.toast('The map could not be loaded. Check your connection and open it again.', 'error'); });
  return mapsLoading;
}

const dialog = $('life-dialog');
shell = createShell({
  root: $('life-overlay'), dialog, dialogContent: $('life-dialog-content'), panels: PANELS,
  host: { command, fetchJson: client.fetchJson, newId: client.newId, goTo, toggleCommunity, menu, onRender: () => layoutScene(), redrawScene: () => { if (shell.mode !== 'map') venue?.update(); }, onMode(mode) { if (mode === 'map') loadMaps(); render(); refreshScene(); } },
});

const clockFormat = new Intl.DateTimeFormat('en-NG', { timeZone: 'Africa/Lagos', weekday: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true });
function buildView() {
  const now = client.serverNow(), cityId = client.cityId;
  return {
    ...viewLife(client.state, { now, cityId }),
    cityId, city: CITIES[cityId], connected: client.online, session: client.session, net, storage: client.storage,
    // The life's own name (the server keeps it equal to the session nickname), so a rename shows as soon as the next state arrives.
    name: client.state.name || client.identity.name, now,
    clock: clockFormat.format(new Date(now)).replace(',', ' ·'),
    venues: Object.values(VENUES).map((item) => ({ id: item.id, label: venueLabel(item.id, cityId), district: venueDistrict(item.id, cityId), icon: item.icon, description: item.description })),
  };
}

function render() {
  const state = client.state, mapOpen = shell.mode === 'map';
  document.body.classList.toggle('map-open', mapOpen);
  if (state.location === 'home') $('community-panel').hidden = true;
  const worldLayer = cityMap ? cityMap.ready === false : false;
  $('venue-scene').hidden = mapOpen;
  $('map-scene').hidden = !mapOpen || !worldLayer;
  $('city-scene').hidden = !mapOpen || worldLayer;
  shell.render(state, buildView());
}
/** Tell the scene how much of the screen the HUD covers, so it draws itself in the free part. Measured after each shell render (host.onRender). */
function layoutScene() {
  if (!venue || !shell || shell.mode === 'map') return;
  const overlay = $('life-overlay'), box = (selector) => overlay.querySelector(selector)?.getBoundingClientRect();
  const stack = box('.life-bottom'), quick = box('.life-quick'), bar = box('.life-status'), page = overlay.getBoundingClientRect();
  const phone = page.width <= 720;
  venue.setInsets({ top: ((phone ? quick?.bottom : bar?.bottom) || bar?.bottom || page.top) - page.top, bottom: stack?.height ? page.bottom - stack.top : 0 });
}
function refreshScene() { if (shell.mode === 'map') { world?.resize(); cityMap?.resize(); } else venue?.resize(); }

/** Called after every accepted server state. */
function accepted(state, previous) {
  const moved = previous.location !== state.location;
  if (moved) {
    venue?.setLocation(state.location);
    if (shell.mode !== 'venue') shell.setMode('venue');
    if (pendingRoute && pendingRoute.venue !== state.location) pendingRoute = null; // went somewhere else instead
  }
  // Arrival, or a cancelled trip: restore room membership. Join only — voice stays off until the player asks.
  if (roomJoinNeeded(previous, state)) community?.join(client.cityId, state.location);
  venue?.setState(state);
  showPlayer();
  showCrowd();
  cityMap?.setState(state);
  render();
  // Arrived somewhere (or a trip ended): read who is here once; later changes are pushed by the server.
  if (roomJoinNeeded(previous, state) && client.online) void loadPeople();
  if (pendingRoute && !state.activeAction) {
    const route = pendingRoute;
    if (state.location === route.venue) { pendingRoute = null; if (route.spot) { shell.setExpanded(true); void command('spot', { id: route.spot }); } }
    else if (!client.online) pendingRoute = null;
  }
}

async function command(type, payload) {
  if (type === 'cancel') pendingRoute = null;
  const result = await client.command(type, payload);
  if (!result.ok && result.reason && result.code !== 'busy') shell.toast(result.reason, 'error');
  if (!result.ok && type === 'travel') pendingRoute = null;
  return result;
}

/**
 * Go to a venue and stand at a spot there. Already there: select the spot. Elsewhere: open the
 * Map travel card for the venue (mode tiles, Danfo selected) — a trip is never started on the
 * player's behalf — and remember the spot for when they arrive.
 */
async function goTo(venueId, spotId) {
  if (client.state.location === venueId) {
    if (shell.mode !== 'venue') shell.setMode('venue');
    if (spotId) { shell.setExpanded(true); await command('spot', { id: spotId }); render(); }
    return;
  }
  pendingRoute = { venue: venueId, spot: spotId };
  shell.open('map', { destination: venueId });
}

/**
 * The community panel's code, fetched after the first connection. The chunk can fail to arrive (a
 * dropped connection, a deploy in between): the loader then retries by itself after 1, 2, 4, 8 and
 * 16 seconds and stops. The status line always says which of these is true — it never reads
 * "connecting" for something that is not being tried.
 */
const communityCode = createLazyLoader(() => Promise.all([import('./community.js'), import('./community.css')]).then(([module]) => module), {
  onState(state) {
    if (state.status === 'retrying') status(`Community did not load · retrying in ${Math.round(state.retryInMs / 1000)} s (attempt ${state.attempt + 1} of ${state.attempts})`, true);
    else if (state.status === 'failed') status('Community is unavailable · it did not load. Open Community to retry', true);
    // A retry that succeeded by itself: bring the panel up now, without waiting for the player.
    else if (state.status === 'ready') void startCommunity();
  },
});
let startingCommunity = false;
/** Create the community panel once its code is here and the client is connected. Safe to call any number of times. */
async function startCommunity() {
  if (community || startingCommunity || !client.online) return;
  startingCommunity = true;
  try {
    const module = await communityCode.load();
    if (!module || community || !client.online) return;
    community = await module.createCommunity($('community-content'), { cityId: client.cityId, venueId: client.state.location,
      onStatus: (s) => { if (s.status === 'offline') status('Community disconnected · reconnect in panel', true); else if (s.connected) status('Connected · progress saved'); } });
    watchChatRefusals($('community-content'));
    render();
  } catch (error) {
    console.error('The community panel could not be started:', error);
    status('Community is unavailable · it could not start. Open Community to retry', true);
  } finally { startingCommunity = false; }
}

function toggleCommunity(force) {
  if (client.state.location === 'home') { shell.toast('Your home is private. Visit a public venue to meet people.'); return; }
  if (!community) {
    if (!client.online) { shell.toast('You are offline. Reconnect to open the community.', 'error'); return; }
    const load = communityCode.state;
    if (load.status === 'retrying' || load.status === 'failed') shell.toast('Community did not load. Trying again now…', 'error');
    else shell.toast('Community is still loading. Try again in a moment.');
    void startCommunity(); // a manual retry: starts at once, or joins the attempt already in flight
    return;
  }
  $('community-panel').hidden = typeof force === 'boolean' ? !force : !$('community-panel').hidden;
}

/**
 * A venue chat line the server refused (blocked wording, or the player is muted). The community
 * panel does not pass the refusal's code to onStatus; all it exposes is its own status line
 * (`.community-feedback`), where it prints the sentence the server sent, and "Not sent" on the line
 * itself. That sentence is repeated as a toast so it is seen wherever the panel is scrolled to.
 * Event-driven (a MutationObserver on that one element): nothing runs while the game is idle.
 */
let chatWatch = null;
function watchChatRefusals(container) {
  chatWatch?.disconnect();
  const line = container.querySelector('.community-feedback');
  if (!line || typeof MutationObserver !== 'function') return;
  chatWatch = new MutationObserver(() => {
    const text = line.textContent.trim();
    const refused = [...container.querySelectorAll('.community-messages li small')].some((node) => node.textContent === 'Not sent');
    if (text && refused) shell.toast(text, 'error');
  });
  chatWatch.observe(line, { childList: true, characterData: true, subtree: true });
}

async function connect(createNew = false) {
  if (connecting) return;
  connecting = true;
  try {
    if (createNew) { community?.destroy(); community = null; }
    const ok = await client.connect(createNew);
    render();
    // Not awaited: a slow or failing community chunk must not hold up the game or block a later Reconnect.
    if (ok) void startCommunity();
  } finally { connecting = false; }
}

async function switchCity(id) {
  const result = await client.switchCity(id);
  if (!result.ok) { if (result.reason) shell.toast(result.reason, 'error'); return; }
  world?.setCity(id); cityMap?.setCity(id);
  community?.join(id, client.state.location);
  venue?.setLocation(client.state.location);
  shell.setMode('venue');
  shell.open('city', { city: id });
}

/** Entries of the shell's More menu and the top bar's Reconnect. */
function menu(id) {
  if (id === 'reconnect') connect();
  else if (id === 'city') { shell.setMode('map'); shell.open('city', { city: client.cityId }); }
  else if (id === 'locate') {
    if (!navigator.geolocation) { shell.toast('Location is unavailable here. Choose Lagos or Ibadan on the world map.', 'error'); return; }
    shell.toast('Asking your browser for your location…');
    navigator.geolocation.getCurrentPosition((position) => {
      const { latitude, longitude } = position.coords;
      const lagos = Math.hypot(latitude - 6.5244, longitude - 3.3792), ibadan = Math.hypot(latitude - 7.3775, longitude - 3.947);
      shell.open('city', { city: lagos <= ibadan ? 'lagos' : 'ibadan' });
    }, () => shell.toast('Location was not shared. Choose a city on the world map instead.', 'error'), { enableHighAccuracy: false, timeout: 8000, maximumAge: 300000 });
  }
}

window.addEventListener('jaw:start-life', (event) => { if (event.detail?.name) client.identity.name = event.detail.name; connect(true); });
window.addEventListener('jaw:switch-city', (event) => switchCity(event.detail.city));
$('close-life-dialog').onclick = () => shell.close();
$('community-close').onclick = () => toggleCommunity(false);
window.addEventListener('resize', refreshScene);
window.addEventListener('pagehide', () => { community?.destroy(); client.stop(); });
document.addEventListener('visibilitychange', () => { if (document.hidden) client.stop(); else if (client.online) client.refresh(); });

if (new URLSearchParams(location.search).has('diagnostics')) {
  const panel = document.createElement('aside');
  panel.style.cssText = 'position:fixed;left:10px;bottom:90px;z-index:60;background:white;color:black;padding:8px;max-width:340px;font:12px monospace';
  const button = document.createElement('button'); button.textContent = 'Read renderer diagnostics';
  const output = document.createElement('pre'); output.id = 'render-diagnostics';
  button.onclick = () => { output.textContent = JSON.stringify({ ...(venue ? venue.diagnostics() : { renderCount: 0, scene: 'not loaded yet' }), visibility: document.visibilityState, lazyPanelsWaiting: PANELS.filter((item) => item.pending).map((item) => item.id) }, null, 2); };
  panel.append(button, output); document.body.append(panel);
}

render();
connect();
// The scene (Three.js and every scene module) starts downloading only now, with the HUD already on screen and usable.
setTimeout(loadScene, 0);
if (new URLSearchParams(location.search).has('venue')) loadMaps();
