import './style.css';
import {createWorld} from './world.js';
import {interact,chooseJob,updateNeeds} from './game.js';
import {loadProgress,saveProgress} from './persistence.js';
const $=id=>document.getElementById(id);
let storage;try{storage=window.localStorage}catch{}
const progress=loadProgress(storage);
const game=progress.game;let name=progress.name;
const venues=[{id:'market',name:'🧺 Market',x:-28,z:16,description:'Collect a parcel here after accepting a delivery.'},{id:'office',name:'🏢 Office',x:0,z:23,description:'Deliver your parcel here to earn ₦1,500.'},{id:'amala',name:'🍲 Amala kitchen',x:-25,z:-15,description:'A hot meal restores your appetite and energy. ₦500.'},{id:'home',name:'🏡 Your home',x:32,z:22,description:'Buy your first home for ₦12,000, then come back to rest.'},{id:'hospital',name:'🏥 Hospital',x:30,z:-20,description:'Medical care restores health for ₦300.'},{id:'shrine',name:'🎷 Music yard',x:-30,z:-28,description:'Take in the city. The music yard is an exploration landmark in this first build.'},{id:'beach',name:'🏖️ Beach',x:42,z:31,description:'A quiet stretch of shoreline at the edge of the city.'},{id:'library',name:'📚 Library',x:12,z:17,description:'An exploration landmark. More city activities are still being built.'},{id:'canopy',name:'🌴 Canopy walk',x:28,z:13,description:'Follow the palms toward the island neighbourhood.'},{id:'club',name:'🪩 Night spot',x:6,z:32,description:'The city after dark. This venue is an exploration landmark.'},{id:'church',name:'⛪ Church',x:-43,z:12,description:'A familiar landmark on the west side of the island.'}];
let player=progress.position, selected=null, driving=false, toastTimer, last=0,saveTimer=0;
let route=[];
const keys=new Set(), touch={x:0,z:0};
const world=createWorld($('world'),{initialPosition:progress.position,onMove:p=>{player=p}});
if(game.job){selected=venues.find(v=>v.id===(game.job==='pickup'?'market':'office'));world.setDestination(selected)}
const labelNodes=venues.map(v=>{const b=document.createElement('button'); b.className='venue';b.textContent=v.name;b.addEventListener('click',()=>select(v));$('labels').appendChild(b);return b;});
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4200)}
function save(){saveProgress(storage,{game,name,position:player})}
function modal(html){$('panel-content').innerHTML=html;$('panel').showModal();keys.clear();touch.x=touch.z=0}
function select(v){route=[];selected=v;$('travel').hidden=false;world.setDestination(v);toast(v.name.replace(/^\S+ /,'')+' marked. Walk or drive to the gold marker.');render()}
function startJob(){chooseJob(game);select(venues.find(v=>v.id===(game.job==='dropoff'?'office':'market')));toast(game.message);render();save()}
function nearest(){return venues.reduce((a,v)=>Math.hypot(player.x-v.x,player.z-v.z)<Math.hypot(player.x-a.x,player.z-a.z)?v:a)}
function doInteract(){const v=nearest();if(Math.hypot(player.x-v.x,player.z-v.z)>7){toast('Move closer to a venue to interact. Click its label to mark it.');return}if(['market','office','amala','home','hospital'].includes(v.id)){interact(game,v.id);toast(game.message);if(game.job==='dropoff'){selected=venues.find(v=>v.id==='office');world.setDestination(selected)}else if(v.id==='office'&&!game.job){selected=null;world.setDestination(null)}save();render()}else{modal(`<h1>${v.name}</h1><p>${v.description}</p><button class="primary" id="return-city">Back to the city</button>`);$('return-city').onclick=()=>$('panel').close()}}
function render(){$('cash').textContent='₦'+Math.round(game.cash).toLocaleString();$('energy').value=game.energy;$('hunger').value=game.hunger;$('profile').textContent=name;$('mode').textContent=driving?'Driving • city car':'On foot';const title=game.job==='pickup'?'Collect your first parcel.':game.job==='dropoff'?'Next stop: the Office.':game.homeOwned?'A place to call your own.':'Make yourself at home.';const desc=game.job==='pickup'?'Head to the Market. Press E or Interact near the gold marker.':game.job==='dropoff'?'Bring the parcel to the Office to collect ₦1,500.':game.homeOwned?`${game.deliveries} deliveries completed. Explore, eat, and rest at home.`:'Earn ₦1,500 per delivery. Save ₦12,000 to buy your own home.';$('mission').querySelector('h2').textContent=title;$('mission').querySelector('p').textContent=desc;$('start-job').textContent=game.job?'Show destination':'Find a hustle';$('vehicle').textContent=driving?'🚶 Walk':'🚗 Drive';$('travel').textContent=driving?'Drive to marker':'Walk to marker';$('travel').hidden=!selected;}
$('travel').onclick=()=>{if(!selected)return;const opposite=(player.z>7&&selected.z< -3)||(player.z< -3&&selected.z>7);route=[];if(opposite){const bridge=[-15,20].sort((a,b)=>Math.abs(player.x-a)+Math.abs(selected.x-a)-Math.abs(player.x-b)-Math.abs(selected.x-b))[0];route.push({x:bridge,z:player.z>7?11:-7},{x:bridge,z:selected.z>7?11:-7})}route.push({x:selected.x,z:selected.z});toast('Heading to '+selected.name.replace(/^\S+ /,'')+'. Move manually to stop.');};
$('start-job').onclick=$('jobs').onclick=startJob;$('interact').onclick=doInteract;
$('vehicle').onclick=()=>{driving=!driving;world.setVehicle(driving);render();toast(driving?'You’re driving. Use the same movement controls.':'Back on foot.')};
$('home').onclick=()=>select(venues.find(v=>v.id==='home'));
$('help').onclick=()=>modal('<h1>Your city, your pace.</h1><p>Explore an original Lagos-inspired city in this early JoinAllworld build.</p><ul><li>WASD or arrow keys: move</li><li>E: interact with a nearby venue</li><li>Drive: switch to your city car</li><li>Click a place label: mark your destination</li><li>Use bridges to cross the lagoon</li><li>Deliver parcels to earn your first home</li></ul><p>Progress saves on this device. This build is single-player; online social features are not connected.</p>');
$('map').onclick=()=>{modal('<h1>Where to?</h1><p>Choose a place, then follow its gold marker.</p>'+venues.map(v=>`<div class="guide-row"><span>${v.name}</span><button data-go="${v.id}">Locate</button></div>`).join(''));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{select(venues.find(v=>v.id===b.dataset.go));$('panel').close()})};
$('profile').onclick=()=>{modal('<h1>Welcome to JoinAllworld.</h1><p>What should we call you?</p><label for="player-name">Your name</label><input id="player-name" maxlength="24" placeholder="New Lagosian"><button class="primary" id="save-name">Save name</button>');$('player-name').value=name;$('save-name').onclick=()=>{name=$('player-name').value.trim().slice(0,24)||'New Lagosian';save();$('panel').close();render()}};
$('close-panel').onclick=()=>$('panel').close();
window.addEventListener('keydown',e=>{if($('panel').open)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e'&&!e.repeat)doInteract()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();touch.x=touch.z=0});
document.querySelectorAll('#pad button').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch.x=Number(b.dataset.x||0);touch.z=Number(b.dataset.z||0)};b.onpointerup=b.onpointercancel=()=>{touch.x=touch.z=0}});
window.addEventListener('resize',()=>world.resize());
function frame(t){const dt=Math.min((t-last)/1000||0,.05);last=t;let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+touch.x;let z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+touch.z;if(x||z)route=[];if(!x&&!z&&route.length){const next=route[0],dx=next.x-player.x,dz=next.z-player.z,d=Math.hypot(dx,dz);if(d<.6){route.shift();if(!route.length)toast('You have arrived. Press Interact or E.')}else{x=dx/d;z=dz/d}}const mag=Math.hypot(x,z);if(mag>1){x/=mag;z/=mag}world.update(dt,$('panel').open?{x:0,z:0}:{x,z});if(!document.hidden&&!$('panel').open)updateNeeds(game,dt);venues.forEach((v,i)=>{const p=world.project(v.x,v.z);const b=labelNodes[i];b.style.left=p.x+'px';b.style.top=p.y+'px';b.classList.toggle('near',Math.hypot(player.x-v.x,player.z-v.z)<7);b.classList.toggle('selected',selected?.id===v.id)});saveTimer+=dt;if(saveTimer>2){saveTimer=0;render();save()}requestAnimationFrame(frame)}
render();requestAnimationFrame(frame);
