// Generated by scripts/world/build-playable-africa.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "cotonou",
  "name": "Cotonou",
  "country": {
    "idISOlower": "bj",
    "name": "Benin"
  },
  "state": {
    "idunique": "bj-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Porto-Novo",
  "centre": {
    "lon": 2.404355,
    "lat": 6.36298
  },
  "airport": {
    "id": "cotonou-airport",
    "name": "AEROPORT BERNARDIN GANTIN DE COTONOU",
    "lon": 2.383333333,
    "lat": 6.356388889,
    "sourceUrl": "https://aim.asecna.aero/html/eAIP/FR-_01AD-2.DBBB-fr-FR.html"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and cited aeronautical information sources",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=2.401355,6.35998,2.407355,6.36598",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; Airport reference points: cited aeronautical information sources",
  "bounds": [
    2.371333,
    6.344389,
    2.419355,
    6.37798
  ],
  "coverageNote": "commercial city; Porto-Novo is constitutional capital. Starter visitor area. Real city and airport points, clipped country land and a bounded central street/building sample. Visitor services and homes are fictional game content. Buildings use approximate box silhouettes; missing heights are estimates. Game prices remain in the shared Allworld economy."
} satisfies DestinationFacts
