#!/usr/bin/env -S node --experimental-strip-types
import { createHash } from 'node:crypto'
import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, renameSync, statSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, join, relative, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { CITY_CATALOGUE, CITY_LOADERS } from '../../src/game/cities/catalogue.ts'
import type { CityPersonSeed } from '../../src/game/cities/contentBuilder.ts'
import { castFor } from '../../src/game/cities/formula/cast.ts'
import { orderedPlacesOf } from '../../src/game/cities/formula/content.ts'
import { isDefinedLegacyCityRecipe } from '../../src/game/cities/formula/legacy.ts'
import type { LegacyCityRecipe } from '../../src/game/cities/formula/legacy.ts'
import { isDefinedCitySpec } from '../../src/game/cities/spec.ts'
import type { CastEntry, CitySpec, CoordinateReference, SourceGroup } from '../../src/game/cities/spec.ts'
import { validateCast } from '../../src/game/cities/specValidation.ts'
import { isRecord } from '../geo/nigeria-boundaries.ts'
import { assertNoOpenCityGeometryOverlap, buildCityGeometry } from './geometry.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const GENERATED = 'Generated by scripts/city/build-city.ts. Do not edit by hand.'
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

interface CachedSource {
  readonly source: SourceGroup
  readonly raw: Buffer
}

interface CoordinatePoint { readonly lon: number; readonly lat: number }

function usage(): never {
  throw new Error('Usage: node --experimental-strip-types scripts/city/build-city.ts <city-id> [--check] | --check-batch <city-id>...')
}

function parseArguments(): { readonly cityIds: readonly string[]; readonly check: boolean; readonly batch: boolean } {
  const args = process.argv.slice(2)
  const batch = args.includes('--check-batch')
  const check = args.includes('--check') || batch
  const unknown = args.filter(arg => arg !== '--check' && arg !== '--check-batch' && arg.startsWith('-'))
  const cityIds = args.filter(arg => !arg.startsWith('-'))
  if (unknown.length || !cityIds.length || (batch ? args.includes('--check') : cityIds.length !== 1)) return usage()
  for (const cityId of cityIds) if (!SLUG.test(cityId)) throw new Error('City id must be a lowercase slug')
  return { cityIds, check, batch }
}

async function moduleAt(path: string): Promise<Record<string, unknown>> {
  const namespace: unknown = await import(pathToFileURL(path).href)
  if (!isRecord(namespace)) throw new TypeError(`${relative(root, path)} did not export a module namespace`)
  return namespace
}

const unionText = (values: readonly string[]): string => values.map(value => JSON.stringify(value)).join(' | ')

function legacyRulesText(recipe: LegacyCityRecipe): string {
  const names = recipe.exports
  const localUnitType = `${names.typePrefix}LocalGovernmentId`
  const districtType = `${names.typePrefix}DistrictId`
  const hubType = `${names.typePrefix}HubId`
  const seeds = JSON.stringify(recipe.rules.localUnits)
  return [
    `// ${GENERATED}`,
    `import type { CityModuleRules, LgaDefinition } from '../../../types/content.ts'`,
    `import { OGUN_RULES_BASE } from '../ogun/rules.ts'`,
    `import { SAGAMU_LEGACY_RECIPE } from './recipe.ts'`,
    '',
    `export type ${localUnitType} = ${unionText(recipe.rules.localUnits.map(unit => unit.id))}`,
    `export type ${districtType} = ${unionText(recipe.rules.districts.map(district => district.id))}`,
    `export type ${hubType} = ${unionText(recipe.rules.hubs.map(hub => hub.id))}`,
    `type Seed = Omit<LgaDefinition, 'id' | 'districts' | 'beta'> & { id: ${localUnitType}; districts?: ${districtType}[] }`,
    `const seeds = ${seeds} satisfies Seed[]`,
    '',
    `export const ${names.localUnits} = Object.freeze(seeds.map(unit => Object.freeze({ beta: true as const, districts: [], ...unit })))`,
    `export const ${names.mapOrigin} = Object.freeze({ ...SAGAMU_LEGACY_RECIPE.rules.mapOrigin })`,
    `const legacy = SAGAMU_LEGACY_RECIPE.rules`,
    '',
    `export const ${names.rules} = Object.freeze({`,
    `  ...OGUN_RULES_BASE,`,
    `  id: SAGAMU_LEGACY_RECIPE.id, name: legacy.name, units: ${names.localUnits},`,
    `  hub: legacy.hub,`,
    `  rentedHomeIds: legacy.rentedHomeIds, defaultRentedHome: legacy.defaultRentedHome,`,
    `  atlas: legacy.atlas,`,
    `  mapOrigin: ${names.mapOrigin},`,
    `  districts: legacy.districts,`,
    `  hubs: legacy.hubs,`,
    `  links: legacy.links,`,
    `} satisfies CityModuleRules<'${recipe.id}', 'ogun', ${localUnitType}, ${districtType}, ${hubType}>)`,
    '',
  ].join('\n')
}

function legacyContentText(recipe: LegacyCityRecipe): string {
  return `// ${GENERATED}\nimport { buildOgunContent } from '../ogun/contentBuilder.ts'\nimport { SAGAMU_LEGACY_RECIPE } from './recipe.ts'\n\nexport const ${recipe.exports.content} = buildOgunContent(SAGAMU_LEGACY_RECIPE.content)\n`
}

function legacyMapText(recipe: LegacyCityRecipe): string {
  const names = recipe.exports
  const localUnitType = `${names.typePrefix}LocalGovernmentId`
  return `// ${GENERATED}\nimport type { CityMapPack } from '../../../types/content.ts'\nimport { OGUN_CITY_LGA_IDS } from '../../../map3d/geo/data/ogun.ts'\nimport { ${recipe.map.landmarksExport} } from '../ogun/landmarks.ts'\nimport { ogunCityGeometry, ogunStateOverview } from '../ogun/mapOverview.ts'\nimport { ogunScene } from '../ogun/scene.ts'\nimport { ${names.mapOrigin} } from './rules.ts'\nimport type { ${localUnitType} } from './rules.ts'\n\nexport const ${names.map}: CityMapPack<'${recipe.id}', ${localUnitType}> = Object.freeze({\n  cityId: '${recipe.id}', origin: ${names.mapOrigin}, projection: 'nigeria-equirectangular-v1', unitsPerKm: 10,\n  localUnitIds: OGUN_CITY_LGA_IDS['${recipe.id}'], stateFeatureId: '${recipe.map.stateFeatureId}',\n  loadScene: async () => {\n    const [{ ${names.city} }, { createModulePack }] = await Promise.all([import('./index.ts'), import('../../../map3d/cities/module.ts')])\n    return createModulePack(${names.city}, ogunScene('${recipe.id}', ${recipe.map.landmarksExport}))\n  },\n  loadGeometry: async () => ogunCityGeometry(OGUN_CITY_LGA_IDS['${recipe.id}']),\n  loadStateOverview: async () => ogunStateOverview(),\n})\n`
}

function legacyIndexText(recipe: LegacyCityRecipe): string {
  const names = recipe.exports
  const prefix = names.typePrefix
  return `// ${GENERATED}\nimport type { CityModule } from '../../../types/content.ts'\nimport { ${names.rules} } from './rules.ts'\nimport type { ${prefix}DistrictId, ${prefix}HubId, ${prefix}LocalGovernmentId } from './rules.ts'\n\nexport const ${names.city} = Object.freeze({\n  id: '${recipe.id}', rules: ${names.rules},\n  loadContent: async () => (await import('./content.ts')).${names.content},\n  loadMap: async () => (await import('#city-map/${recipe.id}')).${names.map},\n} satisfies CityModule<'${recipe.id}', 'ogun', ${prefix}LocalGovernmentId, ${prefix}DistrictId, ${prefix}HubId>)\n\nexport { ${names.localUnits}, ${names.mapOrigin}, ${names.rules} } from './rules.ts'\n`
}

export function legacyGeneratedFiles(recipe: LegacyCityRecipe): Readonly<Record<'rules.ts' | 'content.ts' | 'map.ts' | 'index.ts', string>> {
  return Object.freeze({
    'rules.ts': legacyRulesText(recipe),
    'content.ts': legacyContentText(recipe),
    'map.ts': legacyMapText(recipe),
    'index.ts': legacyIndexText(recipe),
  })
}

async function verifyLegacy(cityId: string, recipePath: string, check: boolean): Promise<boolean> {
  const namespace = await moduleAt(recipePath)
  const recipes = Object.values(namespace).filter(isDefinedLegacyCityRecipe)
  if (recipes.length !== 1) throw new Error(`${relative(root, recipePath)} must export exactly one defined legacy city recipe`)
  const recipe = recipes[0]!
  if (recipe.id !== cityId) throw new Error(`${relative(root, recipePath)} preserves ${recipe.id}, not ${cityId}`)
  const cityDirectory = dirname(recipePath)
  const outputs = Object.entries(legacyGeneratedFiles(recipe)).map(([file, output]) => [join(cityDirectory, file), output] as const)
  let stale = false
  for (const [path, output] of outputs) stale = writeGenerated(path, output, check, true) || stale
  if (check && stale) {
    process.exitCode = 1
    return false
  }
  const text = JSON.stringify(await recipe.loadSnapshot())
  const bytes = Buffer.byteLength(text)
  const sha256 = createHash('sha256').update(text).digest('hex')
  if (bytes !== recipe.baselineBytes || sha256 !== recipe.baselineSha256) {
    throw new Error(`${cityId}: legacy runtime differs from its pinned baseline; expected ${recipe.baselineBytes} bytes ${recipe.baselineSha256}, received ${bytes} bytes ${sha256}`)
  }
  console.log(`${cityId}: legacy rules, content and geometry match ${bytes} baseline bytes (${sha256}).`)
  return true
}

function cachePath(source: SourceGroup): string {
  const cache = source.cache
  const path = resolve(root, cache.path)
  const fromRoot = relative(root, path)
  if (!fromRoot || fromRoot.startsWith('..') || isAbsolute(fromRoot)) throw new Error(`${source.id}: cache path leaves the repository`)
  return path
}

function verifyCaches(spec: CitySpec): ReadonlyMap<string, CachedSource> {
  const checked = new Map<string, CachedSource>()
  for (const source of spec.sourceGroups) {
    const path = cachePath(source)
    if (!existsSync(path) || !statSync(path).isFile()) throw new Error(`${source.id}: pinned cache is missing at ${relative(root, path)}`)
    const raw = readFileSync(path)
    const sha256 = createHash('sha256').update(raw).digest('hex')
    if (raw.length !== source.cache.bytes || sha256 !== source.cache.sha256) {
      throw new Error(`${source.id}: pinned cache does not match ${source.cache.bytes} bytes and SHA-256 ${source.cache.sha256}`)
    }
    checked.set(source.id, { source, raw })
  }
  return checked
}

function finitePoint(value: unknown): CoordinatePoint | null {
  if (!isRecord(value) || typeof value.lon !== 'number' || !Number.isFinite(value.lon) || typeof value.lat !== 'number' || !Number.isFinite(value.lat)) return null
  return { lon: value.lon, lat: value.lat }
}

function osmCoordinate(value: unknown, reference: Extract<CoordinateReference, { provider: 'openstreetmap' }>): CoordinatePoint | null {
  if (!isRecord(value) || !Array.isArray(value.elements)) return null
  for (const element of value.elements) {
    if (!isRecord(element) || element.type !== reference.element || element.id !== reference.id) continue
    const direct = finitePoint(element)
    if (direct) return direct
    const centre = finitePoint(element.center)
    if (centre) return centre
  }
  return null
}

export function wikidataCoordinate(value: unknown, reference: Extract<CoordinateReference, { provider: 'wikidata' }>): CoordinatePoint | null {
  if (!isRecord(value) || !isRecord(value.entities)) return null
  const entity = value.entities[reference.entity]
  if (!isRecord(entity) || !isRecord(entity.claims) || !Array.isArray(entity.claims.P625)) return null
  for (const claim of entity.claims.P625) {
    if (!isRecord(claim) || !isRecord(claim.mainsnak) || !isRecord(claim.mainsnak.datavalue)) continue
    const coordinate = claim.mainsnak.datavalue.value
    if (!isRecord(coordinate)
      || typeof coordinate.longitude !== 'number' || !Number.isFinite(coordinate.longitude) || Math.abs(coordinate.longitude) > 180
      || typeof coordinate.latitude !== 'number' || !Number.isFinite(coordinate.latitude) || Math.abs(coordinate.latitude) > 90) continue
    return { lon: coordinate.longitude, lat: coordinate.latitude }
  }
  return null
}

function coordinateFromCache(cache: CachedSource, reference: CoordinateReference, label: string): CoordinatePoint {
  let parsed: unknown
  try {
    parsed = JSON.parse(cache.raw.toString('utf8'))
  } catch {
    throw new TypeError(`${label}: coordinate cache ${cache.source.id} is not JSON`)
  }
  const point = reference.provider === 'openstreetmap'
    ? osmCoordinate(parsed, reference)
    : wikidataCoordinate(parsed, reference)
  if (!point) {
    const identity = reference.provider === 'openstreetmap' ? `${reference.element}/${reference.id}` : reference.entity
    throw new Error(`${label}: ${identity} is absent from coordinate cache ${cache.source.id}`)
  }
  return point
}

function verifyCoordinate(
  label: string,
  expected: CoordinatePoint,
  sourceId: string,
  reference: CoordinateReference,
  caches: ReadonlyMap<string, CachedSource>,
): void {
  const cache = caches.get(sourceId)
  if (!cache) throw new Error(`${label}: coordinate source ${sourceId} has no verified cache`)
  const actual = coordinateFromCache(cache, reference, label)
  const difference = Math.max(Math.abs(actual.lon - expected.lon), Math.abs(actual.lat - expected.lat))
  if (difference > 0.000001) throw new Error(`${label}: coordinate differs from ${sourceId} by ${difference} degrees`)
}

function verifyCoordinates(spec: CitySpec, caches: ReadonlyMap<string, CachedSource>): void {
  verifyCoordinate('atlas', spec.atlas, spec.atlas.coordinateSourceId, spec.atlas.coordinateRef, caches)
  for (const place of spec.places) verifyCoordinate(place.id, place, place.coordinateSourceId, place.coordinateRef, caches)
}

export function formulaRulesText(): string {
  return `// ${GENERATED}\nimport { buildFormulaRules } from '../formula/rules.ts'\nimport { CITY_MAP_ORIGIN } from './geography.ts'\nimport { CITY_SPEC } from './spec.ts'\n\nexport const CITY_RULES = buildFormulaRules(CITY_SPEC, CITY_MAP_ORIGIN)\n`
}

export function formulaScenesText(): string {
  return `// ${GENERATED}\nimport { buildFormulaScenes } from '../formula/scenes.ts'\nimport { CITY_SPEC } from './spec.ts'\n\nexport const CITY_SCENES = buildFormulaScenes(CITY_SPEC)\n`
}

/** What the content builder reads of a regular: no place id and no list of source facts. */
export function personSeedOf(entry: CastEntry): CityPersonSeed {
  return {
    name: entry.name,
    role: entry.role,
    quotes: entry.quotes,
    ...(entry.age ? { age: entry.age } : {}),
    ...(entry.greeting ? { greeting: entry.greeting } : {}),
    ...(entry.look ? { look: entry.look } : {}),
    ...(entry.note ? { note: entry.note } : {}),
  }
}

/** Plain data written with bare keys, so the browser build can leave the `note:` fields out. */
function literalText(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(literalText).join(', ')}]`
  if (isRecord(value)) return `{ ${Object.entries(value).map(([key, item]) => `${/^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key)}: ${literalText(item)}`).join(', ')} }`
  return JSON.stringify(value)
}

export function formulaContentText(people: readonly CityPersonSeed[]): string {
  const written = people.length ? `[\n${people.map(person => `    ${literalText(person)},`).join('\n')}\n  ]` : '[]'
  return `// ${GENERATED}\nimport { buildFormulaContent } from '../formula/content.ts'\nimport { CITY_LOCAL_UNIT_ANCHORS, CITY_MAP_ORIGIN, CITY_PLAY_BOUNDS } from './geography.ts'\nimport { CITY_SCENES } from './scenes.ts'\nimport { CITY_SPEC } from './spec.ts'\n\nexport const CITY_CONTENT = buildFormulaContent({\n  spec: CITY_SPEC,\n  origin: CITY_MAP_ORIGIN,\n  bounds: CITY_PLAY_BOUNDS,\n  localUnitAnchors: CITY_LOCAL_UNIT_ANCHORS,\n  scenes: CITY_SCENES,\n  people: ${written},\n})\n`
}

export function formulaIndexText(cityId: string): string {
  return `// ${GENERATED}\nimport type { CityModule } from '../../../types/content.ts'\nimport { CITY_RULES } from './rules.ts'\nimport { CITY_SPEC } from './spec.ts'\n\nexport const city = Object.freeze({\n  id: CITY_SPEC.id,\n  rules: CITY_RULES,\n  loadContent: async () => (await import('./content.ts')).CITY_CONTENT,\n  loadMap: async () => (await import('#city-map/${cityId}')).CITY_MAP,\n} satisfies CityModule<typeof CITY_SPEC.id>)\n`
}

function writeGenerated(path: string, text: string, check: boolean, allowAuthored = false): boolean {
  if (existsSync(path) && readFileSync(path, 'utf8') === text) return false
  if (check) {
    console.error(`${relative(root, path)} is stale or missing`)
    return true
  }
  if (!allowAuthored && existsSync(path) && !readFileSync(path, 'utf8').includes(GENERATED)) {
    throw new Error(`${relative(root, path)} is hand-authored; refusing to overwrite it`)
  }
  mkdirSync(dirname(path), { recursive: true })
  const partial = `${path}.${process.pid}.part`
  writeFileSync(partial, text)
  renameSync(partial, path)
  return true
}

export const generatedTextIsCurrent = (path: string, text: string): boolean => existsSync(path) && readFileSync(path, 'utf8') === text

async function assertNoExistingCityOverlap(cityId: string, polygons: Parameters<typeof assertNoOpenCityGeometryOverlap>[0][number]['polygons']): Promise<void> {
  for (const city of CITY_CATALOGUE) {
    if (!city.open || city.id === cityId) continue
    const loader = CITY_LOADERS[city.id]
    if (!loader) throw new Error(`${city.id}: open catalogue entry has no loader`)
    const module = await loader()
    const geometry = await (await module.loadMap()).loadGeometry()
    const existingPolygons = geometry.playArea.map(polygon => polygon.map(ring => ring.map(([lon, lat]): [number, number] => [lon, lat])))
    assertNoOpenCityGeometryOverlap([
      { cityId, polygons },
      { cityId: city.id, polygons: existingPolygons },
    ])
  }
}

/** Two regulars at every place: the city's authored cast.ts where it has one, a generated pair everywhere else. */
export async function castOf(cityDirectory: string, spec: CitySpec): Promise<readonly CastEntry[]> {
  const castPath = join(cityDirectory, 'cast.ts')
  const authored: unknown = existsSync(castPath) ? (await moduleAt(castPath))['CITY_CAST'] : []
  if (!Array.isArray(authored)) throw new TypeError(`${relative(root, castPath)} must export CITY_CAST as an array`)
  const entries: readonly CastEntry[] = authored
  const errors = validateCast(spec, entries)
  if (errors.length) throw new Error(`${spec.id} cast is invalid:\n- ${errors.join('\n- ')}`)
  return castFor(spec, orderedPlacesOf(spec), entries)
}

async function buildFormula(cityId: string, specPath: string, check: boolean): Promise<boolean> {
  const namespace = await moduleAt(specPath)
  const specs = Object.values(namespace).filter(isDefinedCitySpec)
  if (specs.length !== 1) throw new Error(`${relative(root, specPath)} must export exactly one value created by defineCitySpec`)
  const spec = specs[0]!
  if (spec.id !== cityId) throw new Error(`${relative(root, specPath)} defines ${spec.id}, not ${cityId}`)
  const caches = verifyCaches(spec)
  verifyCoordinates(spec, caches)
  const geometry = await buildCityGeometry({
    cityId: spec.id,
    stateId: spec.state.id,
    stateSourceName: spec.state.sourceName,
    localUnits: spec.localUnits.map(unit => ({ id: unit.id, sourceName: unit.sourceName, name: unit.name })),
    atlas: spec.atlas,
    ...(spec.origin ? { origin: spec.origin } : {}),
    venues: spec.places.map(place => ({ id: place.id, name: place.name, lon: place.lon, lat: place.lat, localUnitId: place.localUnitId })),
    surface: { sha256: spec.geometry.surface.sha256, bytes: spec.geometry.surface.bytes },
    offline: check,
  })
  await assertNoExistingCityOverlap(cityId, geometry.playAreaPolygons)

  const cityDirectory = join(root, 'src', 'game', 'cities', cityId)
  const people = (await castOf(cityDirectory, spec)).map(personSeedOf)
  const outputs: readonly (readonly [string, string])[] = [
    [join(cityDirectory, 'rules.ts'), formulaRulesText()],
    [join(cityDirectory, 'scenes.ts'), formulaScenesText()],
    [join(cityDirectory, 'content.ts'), formulaContentText(people)],
    [join(cityDirectory, 'geography.ts'), geometry.geographyModuleText],
    [join(cityDirectory, 'map.ts'), geometry.runtimeModuleText],
    [join(cityDirectory, 'index.ts'), formulaIndexText(cityId)],
    [join(root, 'src', 'map3d', 'geo', 'data', `${cityId}.formula.ts`), geometry.dataModuleText],
  ]
  let stale = false
  for (const [path, text] of outputs) stale = writeGenerated(path, text, check) || stale
  if (check && stale) {
    process.exitCode = 1
    return false
  }
  console.log(`${cityId}: ${check ? 'generated modules match' : 'generated seven modules'}; ${spec.places.length} sourced places, ${spec.localUnits.length} local units.`)
  return true
}

function runCatalogue(check: boolean): void {
  const script = join(root, 'scripts', 'city', 'build-catalogue.ts')
  const result = spawnSync(process.execPath, ['--experimental-strip-types', script, ...(check ? ['--check'] : [])], {
    cwd: root,
    stdio: 'inherit',
  })
  if (result.error) throw result.error
  if (result.status !== 0) throw new Error(`City catalogue ${check ? 'check' : 'generation'} failed with status ${result.status ?? 'unknown'}`)
}

async function verifyCity(cityId: string, check: boolean): Promise<boolean> {
  const cityDirectory = join(root, 'src', 'game', 'cities', cityId)
  const recipePath = join(cityDirectory, 'recipe.ts')
  if (existsSync(recipePath)) return verifyLegacy(cityId, recipePath, check)
  const specPath = join(cityDirectory, 'spec.ts')
  if (!existsSync(specPath)) throw new Error(`${relative(root, specPath)} is missing`)
  return buildFormula(cityId, specPath, check)
}

async function main(): Promise<void> {
  const { cityIds, check, batch } = parseArguments()
  if (!batch) {
    if (await verifyCity(cityIds[0]!, check)) runCatalogue(check)
    return
  }

  let failed = false
  for (const cityId of cityIds) {
    try {
      if (!await verifyCity(cityId, true)) failed = true
    } catch (error) {
      console.error(`${cityId}: ${error instanceof Error ? error.message : String(error)}`)
      failed = true
    }
  }
  try {
    // The catalogue is global, so validate it once after every requested city.
    runCatalogue(true)
    console.log('Batch catalogue check passed.')
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    failed = true
  }
  if (failed) process.exitCode = 1
}

const entry = process.argv[1]
if (entry && import.meta.url === pathToFileURL(resolve(entry)).href) await main()
