import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import type { CityLink, CityModule } from '../../src/types/content.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const citiesDir = join(root, 'src/game/cities')
const cataloguePath = join(citiesDir, 'catalogue.generated.ts')
const loadersPath = join(citiesDir, 'loaders.generated.ts')
const routesPath = join(citiesDir, 'routes.generated.ts')
const check = process.argv.includes('--check')

const record = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value)
const isCityModule = (value: unknown): value is CityModule => record(value)
  && typeof value.id === 'string'
  && record(value.rules)
  && value.rules.id === value.id
  && typeof value.loadContent === 'function'
  && typeof value.loadMap === 'function'

const previousOrder = existsSync(cataloguePath)
  ? [...readFileSync(cataloguePath, 'utf8').matchAll(/^  \["([^"]+)"/gm)].flatMap((match) => typeof match[1] === 'string' ? [match[1]] : [])
  : []
const initialOrder = ['lagos', 'ibadan', 'abuja', 'port-harcourt', 'abeokuta', 'ota', 'ijebu-ode', 'sagamu', 'kano']

const folders = readdirSync(citiesDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && existsSync(join(citiesDir, entry.name, 'index.ts')))
  .map((entry) => entry.name)
const ordered = [...new Set([
  ...previousOrder.filter((id) => folders.includes(id)),
  ...initialOrder.filter((id) => folders.includes(id)),
  ...folders.filter((id) => !previousOrder.includes(id) && !initialOrder.includes(id)).sort(),
])]

interface DiscoveredCity { id: string; exportName: string; rules: CityModule['rules'] }
const cities: DiscoveredCity[] = []
for (const folder of ordered) {
  const namespace: unknown = await import(pathToFileURL(join(citiesDir, folder, 'index.ts')).href)
  if (!record(namespace)) throw new Error(`${folder}/index.ts did not export a module namespace`)
  const found = Object.entries(namespace).find((entry): entry is [string, CityModule] => isCityModule(entry[1]) && entry[1].id === folder)
  if (!found) throw new Error(`${folder}/index.ts must export one CityModule whose id matches its folder`)
  cities.push({ id: folder, exportName: found[0], rules: found[1].rules })
}

const quote = (value: string): string => JSON.stringify(value)
const catalogueLines = cities.map(({ id, rules }) => {
  const country = rules.country.id === 'ng' || rules.country.id === 'nigeria' ? '' : `,${quote(rules.country.id)},${quote(rules.country.name)}`
  return `  [${quote(id)},${quote(rules.name)},${quote(rules.state.id)},${quote(rules.state.name)},${rules.atlas.lon},${rules.atlas.lat},${rules.hubs.some((hub) => hub.mode === 'air') ? 1 : 0}${country}],`
})
const catalogueRows = catalogueLines.join('\n')
const catalogue = `// Generated by scripts/city/build-catalogue.ts. Do not add cities here by hand.\nimport type { CityCatalogueRow } from './catalogue.ts'\n\nexport const GENERATED_CITY_CATALOGUE_ROWS = Object.freeze([\n${catalogueRows}\n] satisfies readonly CityCatalogueRow[])\n`

const loaderLines = cities.map(({ id, exportName }) => `  async()=>(await import(${quote(`./${id}/index.ts`)})).${exportName},`)
const loaderRows = loaderLines.join('\n')
const loaders = `// Generated by scripts/city/build-catalogue.ts. Do not add cities here by hand.\nimport type { CityModuleLoader } from './catalogue.ts'\n\nexport const GENERATED_CITY_LOADERS = Object.freeze([\n${loaderRows}\n] satisfies readonly CityModuleLoader[])\n`

for (let index = 0; index < cities.length; index += 1) {
  const bytes = Buffer.byteLength((catalogueLines[index] ?? '').trim()) + Buffer.byteLength((loaderLines[index] ?? '').trim())
  if (bytes > 150) throw new Error(`${cities[index]?.id ?? `City ${index}`} adds ${bytes} raw catalogue bytes; keep its id, labels, or module export compact (limit 150)`)
}

const links = new Map<string, CityLink>()
for (const city of cities) for (const link of city.rules.links) {
  const key = `${[link.a, link.b].sort().join('|')}|${link.mode}`
  const existing = links.get(key)
  if (existing && JSON.stringify(existing) !== JSON.stringify(link)) throw new Error(`Conflicting city link ${key}`)
  links.set(key, link)
}
const routeJson = JSON.stringify([...links.values()], null, 2).replace(/^/gm, '  ')
const routes = `// Generated by scripts/city/build-catalogue.ts. Do not add routes here by hand.\nimport type { CityLink } from '../../types/content.ts'\n\nexport const AUTHORED_CITY_LINKS = Object.freeze(${routeJson.trimStart()} satisfies readonly CityLink[])\n`

const outputs = [[cataloguePath, catalogue], [loadersPath, loaders], [routesPath, routes]] as const
let stale = false
for (const [path, text] of outputs) {
  if (existsSync(path) && readFileSync(path, 'utf8') === text) continue
  stale = true
  if (!check) writeFileSync(path, text)
  else console.error(`${relative(root, path)} is stale; run npm run cities:catalogue`)
}
if (check && stale) process.exitCode = 1
else if (!check) console.log(`City catalogue generated for ${cities.length} open cities.`)
