// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":-615,"z":-1694})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-68.09627899355633,"maxX":52.026549816147394,"minZ":-105.81213068114198,"maxZ":98.04603532404258})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"kaduna-north":{"lon":7.445242869709071,"lat":10.555270705919371},"kaduna-south":{"lon":7.41901022456718,"lat":10.46819206620934}})
