// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "malabo",
  "name": "Malabo",
  "country": {
    "idISOlower": "gq",
    "name": "Equatorial Guinea"
  },
  "state": {
    "idunique": "gq-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Malabo",
  "centre": {
    "lon": 8.783278,
    "lat": 3.750015
  },
  "airport": {
    "id": "malabo-airport",
    "name": "Malabo International Airport",
    "lon": 8.70872,
    "lat": 3.75527,
    "sourceUrl": "https://ourairports.com/airports/FGSL/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=8.780278,3.747015,8.786278,3.753015",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    8.69672,
    3.735015,
    8.798278,
    3.76727
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
