// Generated by scripts/city/build-city.ts. Do not edit by hand.
export const CITY_MAP_ORIGIN = Object.freeze({"x":4924,"z":-222})
export const CITY_PLAY_BOUNDS = Object.freeze({"minX":-449.47050668523025,"maxX":138.134737680537,"minZ":-266.963352479686,"maxZ":173.35737856660097})
export const CITY_LOCAL_UNIT_ANCHORS = Object.freeze({"yola-north":{"lon":12.44768672722196,"lat":9.2506325494028},"yola-south":{"lon":12.421697796718524,"lat":9.218392907020597}})
