// Generated by scripts/world/build-africa-starters.py
import type { DestinationFacts } from '../africa/types.ts'
export const FACTS = {
  "id": "maseru",
  "name": "Maseru",
  "country": {
    "idISOlower": "ls",
    "name": "Lesotho"
  },
  "state": {
    "idunique": "ls-starter",
    "name": "Starter zone"
  },
  "timezone": "Africa/Maseru",
  "centre": {
    "lon": 27.483273,
    "lat": -29.316674
  },
  "airport": {
    "id": "maseru-airport",
    "name": "Moshoeshoe I International Airport",
    "lon": 27.554456,
    "lat": -29.456277,
    "sourceUrl": "https://ourairports.com/airports/FXMM/"
  },
  "sourceLabel": "Natural Earth, OpenStreetMap contributors and OurAirports dataset",
  "sourceUrl": "https://api.openstreetmap.org/api/0.6/map?bbox=27.480273,-29.319674,27.486273,-29.313674",
  "licence": "Natural Earth public domain; OpenStreetMap ODbL-1.0; OurAirports public-domain dataset",
  "bounds": [
    27.468273,
    -29.468277,
    27.566456,
    -29.301674
  ],
  "coverageNote": "Starter visitor area. Selected settlement and airport dataset points, clipped country land and a bounded central street/building sample. The settlement point is not asserted to be a current capital. OurAirports coordinates are dataset points, not official ARPs or evidence of current operations or schedules. Visitor services and homes are fictional game content; building silhouettes are approximate and missing heights are estimates."
} satisfies DestinationFacts
